force-app/main/default/objects/InstallationOrder__c/InstallationOrder__c.object-meta.xml
<CustomObject>
    <description>Object to follow up the progress of the installation service. It is the continuation of the Installation Request (InstallationRequest__c)</description>
    <label>Installation Order</label>
    <nameField>
        <label>Installation Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationOrder__c/fields/Installation_Request__c.field-meta.xml
<CustomField>
    <fullName>Installation_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Request</label>
    <referenceTo>InstallationRequest__c</referenceTo>
    <relationshipLabel>Installation Orders</relationshipLabel>
    <relationshipName>Installation_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/InstallerAccount__c.field-meta.xml
<CustomField>
    <fullName>InstallerAccount__c</fullName>
    <formula>Installation_Request__r.InstallerAccount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>InstallerAccount</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Installation_Request__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Installation_order_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/InstallationRequest__c.object-meta.xml
<CustomObject>
    <description>Class to store and follow the installation request of our products. This is a service certain showrooms offer through a list of authorised installers.</description>
    <label>Installation Request</label>
    <nameField>
        <label>Installation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationRequest__c/fields/AcceptedBy__c.field-meta.xml
<CustomField>
    <fullName>AcceptedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User accepting the installation (generally the installer himself)</description>
    <label>Accepted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Installation_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/AcceptedDate__c.field-meta.xml
<CustomField>
    <fullName>AcceptedDate__c</fullName>
    <label>Accepted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/InstallerAccount__c.field-meta.xml
<CustomField>
    <fullName>InstallerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installation Requests</relationshipLabel>
    <relationshipName>Installation_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/LastTransition__c.field-meta.xml
<CustomField>
    <fullName>LastTransition__c</fullName>
    <description>Records the date of the last state transition</description>
    <label>Last State Transition</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Opportunity this installation is for</description>
    <inlineHelpText>Please enter the opportunity this installation is for</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Installation Requests</relationshipLabel>
    <relationshipName>Installation_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/ReasonRejected__c.field-meta.xml
<CustomField>
    <fullName>ReasonRejected__c</fullName>
    <inlineHelpText>Please enter the reason for the rejection of this installation project.</inlineHelpText>
    <label>Reason Rejected</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <defaultValue>&quot;New Request&quot;</defaultValue>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InstallationStates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PENewInstallationRequest__e/PENewInstallationRequest__e.object-meta.xml
<CustomObject>
    <description>Platform Event used when a installation request is created</description>
    <label>Platform Event New Installation Request</label>
    <pluralLabel>Platform Event New Installations Request</pluralLabel>
</CustomObject>

force-app/main/default/globalValueSets/Installation_order_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Installation</fullName>
        <default>true</default>
        <label>New Installation</label>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing</fullName>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Unsatisfied</fullName>
    </customValue>
    <description>InstallationOrder states picklist</description>
    <masterLabel>Installation order State</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/InstallationStates.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Request</fullName>
        <default>true</default>
        <label>New Request</label>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>3D Design</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Estimation</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Won</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>States of Installation Requests</description>
    <masterLabel>Installation States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InstallationRequestTriggerHandler.cls
/**
* @author Ramón Prades
* @date August 2020
*
* @group Installation Request Trigger
* @group-content ../../ApexDocContent/InstallationRequest.htm
*
* @description 
*/
public class InstallationRequestTriggerHandler extends BaseTriggerHandler {
            
    /**
     * @description 			Validates the intallation request can be deleted
     * @param 		oldItems	A Map with the ids and th objects being deleted
     */    
    public override void beforeDelete(List<SObject> oldItems) {
        this.checkInstallationOrders(oldItems);
    } // beforeDelete

    /**
     * @description 			Validates the intallation request can be deleted
     * @param 		oldItems	A List/Map with the ids and th objects being deleted
     */    
    public override void beforeUpdate(List<SObject> newItems, Map<Id, SObject> oldItems) {
        for (InstallationRequest__c newRequest :(List<InstallationRequest__c>) newItems) {
            InstallationRequest__c oldRequest = (InstallationRequest__c) oldItems.get(newRequest.Id);
            this.setTransitionFields(newRequest, oldRequest.State__c);
        }        
    } // beforeUpdate

    /**
     * @description 			Validates the intallation request can be deleted
     * @param 		oldItems	A List/Map with the ids and th objects being deleted
     */    
    public override void afterUpdate(List<SObject> newItems, Map<Id, SObject> oldItems) {
        InstallationMails.changeStateInsrMail((List<InstallationRequest__c>) oldItems.values(), (List<InstallationRequest__c>) newItems);
    } // beforeUpdate 
    
    public override void beforeInsert(List<SObject> newItems) {    
		for (InstallationRequest__c newRequest :(List<InstallationRequest__c>) newItems) {
			this.setTransitionFields(newRequest, '');
        }        
    } // beforeInsert
    
    public override void afterInsert(List<SObject> newItems) {
        platformEventNew((List<InstallationRequest__c>) newItems);
        List<OpportunityTeamMember> installers = this.setOpportunityTeamMember(newItems);
        upsert installers;
    } // afterInsert
    
	/*********************************************************************************************/    
    /********************************       Private Methods      *********************************/
    /*********************************************************************************************/
    private List<OpportunityTeamMember> setOpportunityTeamMember(List<InstallationRequest__c> requests) {
        List<OpportunityTeamMember> members = new List<OpportunityTeamMember>();
        for (InstallationRequest__c request :requests){
            Id userId = UserAccountUtil.getUser(request.InstallerAccount__c, 'INSTALLER');
            if (userId != null) {
                OpportunityTeamMember member = new OpportunityTeamMember();
                member.OpportunityId = request.Opportunity__c;
                member.TeamMemberRole = 'Installer';        
                member.UserId = userId;
                members.add(member);                
            }
        }     
        return members;
    } // setOpportunityTeamMember
    
	/*
	 * Sets fields related to state transtitions
	 */
    private void setTransitionFields(InstallationRequest__c request, String oldState) {
        if ((request.State__c == oldState)) {
            return;
        } else {
            if (InstallationUtil.isRequestAccepted(request)) {
	        	this.setAcceptedFields(request);
        	} 
            if (oldState == InstallationUtil.rejectedState) {
	        	request.ReasonRejected__c = null;
			}
    	}
        request.LastTransition__c = Date.today();
    } // setTransitionFiends    
    
    /*
     * Sets fields related to the installer accepting the request
     */
    private void setAcceptedFields(InstallationRequest__c request) {
        if (InstallationUtil.isRequestAccepted(request)) {
            request.AcceptedBy__c = UserInfo.getUserId();
            request.AcceptedDate__c = Date.today();        
        }
    } // setAcceptedFields
    
    /*
     * Checks the requests do not have any installation order
     */
    private Boolean checkInstallationOrders(List<SObject> oldItems) {
        
        Boolean hasErrors = false;

        Map<Id, Integer> mapOrders = this.getMapOfOrders(oldItems);

        for(InstallationRequest__c request :(List<InstallationRequest__c>) oldItems) {
            Integer numOrders = mapOrders.get(request.Id);      
            if (numOrders > 0) {
                hasErrors = true;
                request.addError(System.Label.insr_error_delete);   
            }
        }        
        return hasErrors;
    } // checkInstallationOrders
    
    /*
     * Returns a map with the rquest Id and tyhe number of orders 
     */
    private Map<Id, Integer> getMapOfOrders(List<InstallationRequest__c> requests) {
        List<Id> ids = new List<Id>();
        for (InstallationRequest__c request :requests) {
            ids.add(request.Id);
        }        
        AggregateResult[] results = [SELECT Installation_Request__c, count(Id) theCount
                           	FROM InstallationOrder__c 
                           	WHERE Installation_Request__c in :ids
						  	GROUP BY Installation_Request__c];
        Map<Id, Integer> theMap = new Map<Id, Integer>();
        for (Integer i = 0; i < results.size(); i++) {
            theMap.put((Id)results[i].get('Installation_Request__c'), (Integer)results[i].get('theCount'));
        }
       return theMap;
    } // getMapOfOrders    

    /**
    * @description Creates Platform Events about the new installation request
    */
    private void platformEventNew(List<InstallationRequest__c> installations) {
        List<PENewInstallationRequest__e> listPlatformEvents = new List<PENewInstallationRequest__e>();
        for (InstallationRequest__c opp : installations) {
            listPlatformEvents.add( new PENewInstallationRequest__e( objectId__c = opp.Id ));
        }
        List<Database.SaveResult> results = EventBus.publish(listPlatformEvents);

        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event "New Installation Request".');
            } else {
                for(Database.Error err : sr.getErrors()) {
                    Logger.error('Error returned: ' + err.getStatusCode() + ' - ' + err.getMessage());
                    Logger.saveLog();
                }
            }
        }
    } // platformEventNew
    
}