force-app/main/default/objects/InstallationOrder__c/InstallationOrder__c.object-meta.xml
<CustomObject>
    <description>Object to follow up the progress of the installation service. It is the continuation of the Installation Request (InstallationRequest__c)</description>
    <label>Installation Order</label>
    <nameField>
        <label>Installation Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationOrder__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <inlineHelpText>Enter the date the installation works will end</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <inlineHelpText>Enter the date the installation works will begin</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Installation_order_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/InstallationRequest__c.object-meta.xml
<CustomObject>
    <description>Class to store and follow the installation request of our products. This is a service certain showrooms offer through a list of authorised installers.</description>
    <label>Installation Request</label>
    <nameField>
        <label>Installation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationRequest__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <defaultValue>&quot;New Request&quot;</defaultValue>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InstallationStates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Installation_order_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Installation</fullName>
        <default>true</default>
        <label>New Installation</label>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing</fullName>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Unsatisfied</fullName>
    </customValue>
    <description>InstallationOrder states picklist</description>
    <masterLabel>Installation order State</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/InstallationStates.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Request</fullName>
        <default>true</default>
        <label>New Request</label>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>3D Design</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Estimation</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Won</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>States of Installation Requests</description>
    <masterLabel>Installation States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CronINSOStatusUpdateTest.cls
@isTest
public with sharing class CronINSOStatusUpdateTest {
  @testSetup
  static void setup() {
    Insert TriggerConfiguration_TestDataFactory.createCustomSetting_ActivatedTriggers();

    List<InstallationRequest__c> listINSR = DatafactoryInstallation.createInstallationRequests(2);
    DatafactoryInstallation.createInstallationOrders(listINSR);
  }

  @IsTest
    static void testBatchable() {
      List<InstallationOrder__c> listINSO = [SELECT id, StartDate__c, State__c, EndDate__c FROM InstallationOrder__c];
    
      listINSO[0].endDate__c = Date.today().addDays(10);
      listINSO[0].startDate__c = Date.today().addDays(-2);
      
      update listINSO;

      Test.StartTest();
          Database.executeBatch(new CronINSOStatusUpdate());
      Test.StopTest();

      listINSO = [SELECT id, State__c, StartDate__c, EndDate__c FROM InstallationOrder__c where State__c = 'Ongoing'];
      System.assertEquals(1, listINSO.size(), 'Schedulable has not worked');       
    }

    

    @IsTest
    private static void testSchedulable() {        
        Test.startTest();
            System.schedule('Change Status INSO', '0 0 1 * * ?', new CronINSOStatusUpdate());
        Test.stopTest();
        List<AsyncApexJob> batchJobs = [SELECT Id, Status FROM AsyncApexJob WHERE ApexClass.Name = 'CronINSOStatusUpdate' AND JobType = 'BatchApex'];        
        System.assertEquals(1, batchJobs.size(), 'Unexpected number of batch jobs ran: ' + batchJobs);
        System.assertEquals('Queued', batchJobs[0].Status, 'Job planned with an unexpected status.');
    }
}