force-app/main/default/objects/InstallationOrder__c/InstallationOrder__c.object-meta.xml
<CustomObject>
    <description>Object to follow up the progress of the installation service. It is the continuation of the Installation Request (InstallationRequest__c)</description>
    <label>Installation Order</label>
    <nameField>
        <label>Installation Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationOrder__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Installation_order_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/InstallationRequest__c.object-meta.xml
<CustomObject>
    <description>Class to store and follow the installation request of our products. This is a service certain showrooms offer through a list of authorised installers.</description>
    <label>Installation Request</label>
    <nameField>
        <label>Installation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationRequest__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <defaultValue>&quot;New Request&quot;</defaultValue>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InstallationStates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Installation_order_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Installation</fullName>
        <default>true</default>
        <label>New Installation</label>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing</fullName>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Unsatisfied</fullName>
    </customValue>
    <description>InstallationOrder states picklist</description>
    <masterLabel>Installation order State</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/InstallationStates.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Request</fullName>
        <default>true</default>
        <label>New Request</label>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>3D Design</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Estimation</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Won</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>States of Installation Requests</description>
    <masterLabel>Installation States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InstallationMailsTest.cls
@isTest
public class InstallationMailsTest {
    @testSetup static void setup() {
        Insert TriggerConfiguration_TestDataFactory.createCustomSetting_ActivatedTriggers();
        List<InstallationRequest__c> requests = DataFactoryInstallation.createInstallationRequests(5);
        List<InstallationOrder__c> orders = DataFactoryInstallation.createInstallationOrders(requests);
    }

    @isTest
    static void openInstallations() {
        Test.startTest();
        InstallationMails.openInstallations();
        Integer invocations = Limits.getEmailInvocations();
        System.assert(invocations > 0, 'Mail not sent. Mails sent: ' + invocations);
        Test.stopTest();
    }

    @isTest
    static void changeStateInsrMail() {
        List<InstallationRequest__c> listInsrNew = [SELECT Id, State__c, OwnerId, Name, LastModifiedById from InstallationRequest__c];
        List<InstallationRequest__c> listInsrOld = [SELECT Id, State__c, OwnerId, Name, LastModifiedById from InstallationRequest__c];
        List<User> usrList = [SELECT Id, ProfileId from User where Id <> : listInsrNew[0].OwnerId];
        User auxAdmin = null;
        for (User aux : usrList) {
            if (UserUtils.isAdministrator(aux) == true && aux.Id != listInsrNew[0].OwnerId) {
                auxAdmin = aux;
            }
        }

        listInsrNew[0].State__c = '3D Design';
        listInsrNew[0].OwnerId = auxAdmin.Id;
        
        Test.startTest();
        InstallationMails.changeStateInsrMail(listInsrOld,listInsrNew);
        Integer invocations = Limits.getEmailInvocations();
        System.assert(invocations > 0, 'Mail not sent. Mails sent: ' + invocations);
        Test.stopTest();
    }
}