force-app/main/default/objects/InstallationOrder__c/InstallationOrder__c.object-meta.xml
<CustomObject>
    <description>Object to follow up the progress of the installation service. It is the continuation of the Installation Request (InstallationRequest__c)</description>
    <label>Installation Order</label>
    <nameField>
        <label>Installation Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationOrder__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <inlineHelpText>Enter the date the installation works will end</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <inlineHelpText>Enter the date the installation works will begin</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Installation_order_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Installation_order_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Installation</fullName>
        <default>true</default>
        <label>New Installation</label>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing</fullName>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Unsatisfied</fullName>
    </customValue>
    <description>InstallationOrder states picklist</description>
    <masterLabel>Installation order State</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CronINSOStatusUpdate.cls
global class CronINSOStatusUpdate implements Database.Batchable<sObject>, Schedulable {
  global Database.QueryLocator start(Database.BatchableContext BC){
    String query = 'SELECT Id, StartDate__c,EndDate__c FROM InstallationOrder__c WHERE StartDate__c <= TODAY AND EndDate__c >= TODAY and State__c <> \'Ongoing\'';
    return Database.getQueryLocator(query);
  }

 global void execute(Database.BatchableContext BC, List<InstallationOrder__c>scope){
    for(InstallationOrder__c a : scope){
        a.State__c = 'Ongoing';        
    }
    update scope;
  }

  global void finish(Database.BatchableContext BC){
  }

  global void execute(SchedulableContext sc) {
    try {
      CronINSOStatusUpdate b = new CronINSOStatusUpdate ();
      database.executebatch(b);
    } catch (Exception e) {
      SystemUtils.debugWarning('CRON', 'UPDATE INSO STATUS', e);
    }
  }
}