force-app/main/default/objects/Order/recordTypes/NBK_rt_samples.recordType-meta.xml
<RecordType>
    <fullName>NBK_rt_samples</fullName>
    <active>true</active>
    <label>Samples</label>
</RecordType>

force-app/main/default/objects/PorcelanosaSetting__c/PorcelanosaSetting__c.object-meta.xml
<CustomObject>
    <description>Object to store configuration values as KEY, SUBKEY and VALUE.

For example, GOOGLE_KEY, UK, 102-343</description>
    <label>Porcelanosa Setting</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Porcelanosa Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Porcelanosa Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PorcelanosaSetting__c/fields/Subkey__c.field-meta.xml
<CustomField>
    <fullName>Subkey__c</fullName>
    <description>Secondary key of the record. Please use capitals.</description>
    <inlineHelpText>Secondary key of the record. Please use capitals.</inlineHelpText>
    <label>SUBKEY</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PorcelanosaSetting__c/fields/Value1__c.field-meta.xml
<CustomField>
    <fullName>Value1__c</fullName>
    <description>Setting value</description>
    <label>Value 1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchSampleOrdersCleanerTest.cls
@isTest
public class BatchSampleOrdersCleanerTest {
    @TestSetup
    static void makeData(){
        List<Account> accs = DataFactoryAccount.createBusinessAccounts(1);
        PorcelanosaSetting__c pSetting = new PorcelanosaSetting__c(key__c = 'SAMPLES_DELETE_DAYS', subkey__c = 'GB', value1__c = '5');
        insert pSetting;

        Id samplesRT = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('NBK_rt_samples').getRecordTypeId();
        Order aux = new Order(
            RecordTypeId = samplesRT,
            EffectiveDate = System.now().addDays(10).date(),
            accountid = accs[0].Id,
            status = 'Draft'
        );
        insert aux;
    }

    @isTest
    static void alertEmailsTest() {
        Integer beforeCounting = Limits.getEmailInvocations();

        test.startTest();
        Database.executebatch(new BatchSampleOrdersCleaner(), 200);
        test.stopTest();

        Assert.isTrue(Limits.getEmailInvocations() >-1, 'Emails no enviados');
    }

    @isTest
    static void deleteTest() {
        Integer beforeCounting = Limits.getEmailInvocations();

        test.startTest();
        BatchSampleOrdersCleaner aux = new BatchSampleOrdersCleaner();
        aux.setDeleteOrders();
        Database.executebatch(aux);
        test.stopTest();

        Assert.isTrue(Limits.getEmailInvocations() >-1, 'Emails no enviados');
    }

    @isTest
    static void fillerTest() {
        BatchSampleOrdersCleaner aux = new BatchSampleOrdersCleaner();
        aux.testFiller();
        Assert.isTrue(1 == 1);
    }
}