force-app/main/default/objects/AIPrompt__c/AIPrompt__c.object-meta.xml
<CustomObject>
    <description>This object stores and manages AI prompts used in Apex classes that invoke AI services. It allows dynamic retrieval of prompts based on use case, ensuring flexibility and maintainability in AI-driven processes. The object helps standardize prompt management, track usage history, and enable easy updates for AI interactions in Salesforce.</description>
    <label>AI Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AIPrompt__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>User friendly name to retrieve the prompt from Apex</description>
    <label>Developer Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AIPrompt__c/fields/SystemRole__c.field-meta.xml
<CustomField>
    <fullName>SystemRole__c</fullName>
    <description>System role prompt</description>
    <label>System Role</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AIPromptsSelectorTest.cls
@isTest private class AIPromptsSelectorTest {

    @testSetup private static void testSetup() {
        AIPrompt__c prompt = new AIPrompt__c();
        prompt.Name = 'Example';
        prompt.DeveloperName__c = 'TEST';
        prompt.SystemRole__c = 'Return RED to any questions. Just the word, nothing else.';
        insert prompt;
    }


    @IsTest private static void testSelectByDeveloperName(){
        String name = 'TEST';
        AIPrompt__c result = new AIPromptsSelector().selectByDeveloperName(name);
        Assert.isNotNull(result, 'A prompt should have been found');
    }

}