force-app/main/default/objects/SAPRequestQueue__c/SAPRequestQueue__c.object-meta.xml
<CustomObject>
    <description>Objets to queue the requests to update objects in SAP</description>
    <label>SAP Request Queue</label>
    <nameField>
        <label>SAP Requests Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Requests Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAPRequestQueue__c/fields/ActionRequested__c.field-meta.xml
<CustomField>
    <fullName>ActionRequested__c</fullName>
    <description>Action requested from SAP</description>
    <label>Action Requested</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CREATE</fullName>
            </value>
            <value>
                <fullName>READ</fullName>
            </value>
            <value>
                <fullName>UPDATE</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/AllowDuplicates__c.field-meta.xml
<CustomField>
    <fullName>AllowDuplicates__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows same object to be sent severla times</description>
    <label>Duplicates Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/Parameter__c.field-meta.xml
<CustomField>
    <fullName>Parameter__c</fullName>
    <inlineHelpText>Optional extra information for teh API Handler</inlineHelpText>
    <label>Parameter</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/RequesterID__c.field-meta.xml
<CustomField>
    <fullName>RequesterID__c</fullName>
    <description>ID of the object requesting the service. It might be used when porcessing the repsonse to update some fields.</description>
    <label>Requester ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/Retries__c.field-meta.xml
<CustomField>
    <fullName>Retries__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of attempts to send the request</description>
    <label>Retries</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/SAPAPIHandler__c.field-meta.xml
<CustomField>
    <fullName>SAPAPIHandler__c</fullName>
    <description>Name of the class that will handle the connection to the SAP service</description>
    <label>SAP API Handler</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/SAPEndpoint__c.field-meta.xml
<CustomField>
    <fullName>SAPEndpoint__c</fullName>
    <description>Name of the requested SAP endpoint</description>
    <label>SAP Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FactoryQualityEndpoint.cls
/**
 * @author         Ramón Prades
 * @date           June 2025
 * @group          CPI
 * @description    Asynchronous integration endpoint for factory quality systems.
 * -------------------------------------------------------------------------------
 *  This class extends the base architecture built on SAPAbstractEndpoint to
 *  enqueue integration requests related to quality incidents, enabling 
 *  communication with factory-level quality systems via CPI.
 * 
 *  Specifically, it handles the registration of claims reported by our subsidiaries,
 *  preparing and inserting the required data into the SAPRequestQueue__c queue.
 *  The dispatcher will later process these entries and route them through CPI.
 * 
 *  The getRequestType() method returns 'CPI', marking these requests as part of
 *  non-SAP integrations, while still leveraging the existing infrastructure.
 * -------------------------------------------------------------------------------
 */
public class FactoryQualityEndpoint extends SAPAbstractEndpoint {

    public FactoryQualityEndpoint(Set<Id> ids) {
        super(ids);
    }

    public override String getAPIHandlerName() {
        return 'FactoryQualityAPIHandler';
    }

    public override Boolean isEnabled() {
        return PORSAIntegrationSettings.SendClaims;
    }

    protected override String getActionRequested() {
        return 'CREATE';
    }

    /**
     * Allows duplicates in the queue
     */
    protected override Boolean allowDuplicates() {
        return true; 
    }

    /**
     * Adds the requests to send the case attachments
     */
    protected override void extendRequests(List<SAPRequestQueue__c> requests) {
        SAPRequestQueue__C[] newRequests = new List<SAPRequestQueue__c>();
        for (SAPRequestQueue__c request : requests) {
            Id caseId = request.RequesterID__c;
            List<ContentVersion> lfiles = AttachmentUtils.getSObjectAttachments(caseId);
            Integer index = 0;
            for (ContentVersion cv : lfiles) {
                index++;
                SAPRequestQueue__c newRequest = new SAPRequestQueue__c();
                newRequest.ActionRequested__c = 'CREATE';
                newRequest.SAPEndpoint__c = this.getEndpointName();
                newRequest.SAPAPIHandler__c = 'FactoryQualityFileAPIHandler';
                newRequest.Retries__c = 0;
                newRequest.RequesterID__c = request.RequesterID__c;
                newRequest.Name = this.getEndpointName() + ' (CREATE)';
                newRequest.AllowDuplicates__c = true;
                newRequest.Parameter__c = cv.Id + '-' + index + '-' + lfiles.size();
                newRequests.add(newRequest);                
            }
        }
        requests.addAll(newRequests);
    }
  

} // FactoryQualityEndpoint