force-app/main/default/objects/SAPRequestQueue__c/SAPRequestQueue__c.object-meta.xml
<CustomObject>
    <description>Objets to queue the requests to update objects in SAP</description>
    <label>SAP Request Queue</label>
    <nameField>
        <label>SAP Requests Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Requests Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAPRequestQueue__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message related to the result of the last connection to the requested service</description>
    <label>Message</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/RequesterID__c.field-meta.xml
<CustomField>
    <fullName>RequesterID__c</fullName>
    <description>ID of the object requesting the service. It might be used when porcessing the repsonse to update some fields.</description>
    <label>Requester ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/SAPKey__c.field-meta.xml
<CustomField>
    <fullName>SAPKey__c</fullName>
    <description>SAP Key of the object created (if applicable). For example, the order number, the customer number, etc.</description>
    <label>SAP Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;QUEUED&quot;</defaultValue>
    <description>Status of the request</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
            </value>
            <value>
                <fullName>PROCESSED</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>EXCEPTION</fullName>
            </value>
            <value>
                <fullName>BLOCKED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClaimSAPStatusController.cls
/**
 * @author         Ramón Prades
 * @date           March 2025
 * @layer          Controller
 * @description    claimSAPStatus
*/
public class ClaimSAPStatusController {
    
    @AuraEnabled public static OrderStatusDTO getOrderStatus(Id orderId) {
        OrderStatusDTO dto = null;
        SAPRequestQueue__c[] items = [
            select Id, RequesterId__c, Message__c, Status__c, toLabel(Status__c) StatusLabel, CreatedDate, SAPKey__c  
                from SAPRequestQueue__c 
                where RequesterId__c = :orderId
                order by CreatedDate desc
            ];
        if (items.size() > 0) {
            dto = new OrderStatusDTO();
            SAPRequestQueue__c item = items[0];     
            dto.requestId = item.Id;       
            dto.orderId = item.RequesterID__c;
            dto.requestStatus = item.Status__c;
            dto.requestStatusLabel = (String) item.get('StatusLabel');
            dto.errorMessage = item.Message__c;
            dto.sapKey = item.SAPKey__c;
            dto.hasError = (dto.requestStatus == 'ERROR' || dto.requestStatus == 'EXCEPTION');
            if (!dto.hasError && dto.requestStatus == 'QUEUED') {
                // Add a warning if the order is at least 10 minutes as QUEUED
                if (Datetime.now() >= item.CreatedDate.addMinutes(10)) {
                    dto.errorMessage = System.Label.claim_label_020;
                }
            }            
        }
        return dto;
    }

    public class OrderStatusDTO {
        @AuraEnabled public Id orderId { get; set; }
        @AuraEnabled public Id requestId { get; set; }
        @AuraEnabled public String requestStatus { get; set; }
        @AuraEnabled public String requestStatusLabel { get; set; }
        @AuraEnabled public String errorMessage { get; set; }
        @AuraEnabled public String sapKey { get; set; }
        @AuraEnabled public Boolean hasError { get; set; }
    }
}