force-app/main/default/objects/SAPRequestQueue__c/SAPRequestQueue__c.object-meta.xml
<CustomObject>
    <description>Objets to queue the requests to update objects in SAP</description>
    <label>SAP Request Queue</label>
    <nameField>
        <label>SAP Requests Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Requests Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAPRequestQueue__c/fields/SAPEndpoint__c.field-meta.xml
<CustomField>
    <fullName>SAPEndpoint__c</fullName>
    <description>Name of the requested SAP endpoint</description>
    <label>SAP Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SAPSalesOrderEndpointTest.cls
@isTest public with sharing class SAPSalesOrderEndpointTest {
    @TestSetup static void makeData(){
        DataFactoryOrder.createOrders(1);
    }

    @isTest private static void testEndpoint() {
        // Retrieve 5 orders
        List<Order> allOrders = [select Id, Status from Order];

        Test.startTest();
        Set<Id> orderIds = TypeConversionCommons.listToSet(allOrders);
        SAPSalesOrderEndpoint endpoint = new SAPSalesOrderEndpoint(orderIds);
        Integer numRequests = endpoint.doRequests();
        Test.stopTest();
        
        Assert.areEqual(orderIds.size(), numRequests, 'Method should have returned ' + orderIds.size() + ' new requests');        
        List<SAPRequestQueue__c> queued = getSAPRequests();
        Assert.areEqual(numRequests, queued.size(), 'There should be ' + numRequests + ' in the SAP queue');
    
    }

    private static List<SAPRequestQueue__c> getSAPRequests() {
        return [select Id, Name, SAPEndpoint__c from SAPRequestQueue__c];
    }


}