force-app/main/default/objects/ItemGroup__c/ItemGroup__c.object-meta.xml
<CustomObject>
    <description>Lista de Grupos de Artículos de SAP (T023T__x)</description>
    <label>Item Group</label>
    <nameField>
        <label>Item Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ItemGroup__c/fields/CatalogCategory__c.field-meta.xml
<CustomField>
    <fullName>CatalogCategory__c</fullName>
    <label>Catalog Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductCatalogCategories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ItemGroup__c/fields/SAPGroup__c.field-meta.xml
<CustomField>
    <fullName>SAPGroup__c</fullName>
    <description>Item Group Code (corresponding to the SAP code)</description>
    <externalId>true</externalId>
    <label>SAP Group</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Altura__c.field-meta.xml
<CustomField>
    <fullName>Altura__c</fullName>
    <label>Altura</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Ancho__c.field-meta.xml
<CustomField>
    <fullName>Ancho__c</fullName>
    <label>Ancho</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CatalogCategory__c.field-meta.xml
<CustomField>
    <fullName>CatalogCategory__c</fullName>
    <description>Catalog Category of the product</description>
    <label>Catalog Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductCatalogCategories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/GrupoArticulos__c.field-meta.xml
<CustomField>
    <fullName>GrupoArticulos__c</fullName>
    <label>XXXGrupoArticulos</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IsSample__c.field-meta.xml
<CustomField>
    <fullName>IsSample__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set nthis checkbox when the porduct is a sample</description>
    <label>Is Sample</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Jerarquia__c.field-meta.xml
<CustomField>
    <fullName>Jerarquia__c</fullName>
    <label>Jerarquia</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Longitud__c.field-meta.xml
<CustomField>
    <fullName>Longitud__c</fullName>
    <label>Longitud</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/M2XBox__c.field-meta.xml
<CustomField>
    <fullName>M2XBox__c</fullName>
    <description>Metres in a box</description>
    <label>M2/Box</label>
    <precision>13</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Modificado__c.field-meta.xml
<CustomField>
    <fullName>Modificado__c</fullName>
    <label>Modificado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <label>XXXNombre</label>
    <length>255</length>
    <translateData>true</translateData>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Ramo__c.field-meta.xml
<CustomField>
    <fullName>Ramo__c</fullName>
    <label>Ramo</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAPItemGroup__c.field-meta.xml
<CustomField>
    <fullName>SAPItemGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to itemGroup, equivalento Grupo de Artículos SAP</description>
    <label>SAP Item Group</label>
    <referenceTo>ItemGroup__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAPMake__c.field-meta.xml
<CustomField>
    <fullName>SAPMake__c</fullName>
    <description>SAP make initial (P, B, L, etc)</description>
    <label>SAP Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SAPMakes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/StockUnit__c.field-meta.xml
<CustomField>
    <fullName>StockUnit__c</fullName>
    <description>Unit the product t is stocked in</description>
    <label>Stock Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductUnits</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Umb__c.field-meta.xml
<CustomField>
    <fullName>Umb__c</fullName>
    <label>Umb</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UmbCj__c.field-meta.xml
<CustomField>
    <fullName>UmbCj__c</fullName>
    <label>UmbCj</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UmbKg__c.field-meta.xml
<CustomField>
    <fullName>UmbKg__c</fullName>
    <label>UmbKg</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UmbMt2__c.field-meta.xml
<CustomField>
    <fullName>UmbMt2__c</fullName>
    <label>UmbMt2</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UmbPal__c.field-meta.xml
<CustomField>
    <fullName>UmbPal__c</fullName>
    <label>UmbPal</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Umv__c.field-meta.xml
<CustomField>
    <fullName>Umv__c</fullName>
    <label>Umv</label>
    <length>10</length>
    <translateData>true</translateData>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/ZSFMatBase__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>ZSFMatBaseSet</externalName>
    <label>ZSFMatBase</label>
    <pluralLabel>ZSFMatBaseSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/ZSFMatBase__x/fields/Altura__c.field-meta.xml
<CustomField>
    <fullName>Altura__c</fullName>
    <description>Altura</description>
    <externalDeveloperName>Altura</externalDeveloperName>
    <label>Altura</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/Ancho__c.field-meta.xml
<CustomField>
    <fullName>Ancho__c</fullName>
    <description>Ancho</description>
    <externalDeveloperName>Ancho</externalDeveloperName>
    <label>Ancho</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/CjPal__c.field-meta.xml
<CustomField>
    <fullName>CjPal__c</fullName>
    <description>CjPal</description>
    <externalDeveloperName>CjPal</externalDeveloperName>
    <label>CjPal</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/GrupoArticulos__c.field-meta.xml
<CustomField>
    <fullName>GrupoArticulos__c</fullName>
    <description>GrupoArticulos</description>
    <externalDeveloperName>GrupoArticulos</externalDeveloperName>
    <label>GrupoArticulos</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/IsSample__c.field-meta.xml
<CustomField>
    <fullName>IsSample__c</fullName>
    <defaultValue>false</defaultValue>
    <description>IsSample</description>
    <externalDeveloperName>IsSample</externalDeveloperName>
    <label>IsSample</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/IsSampleAccessory__c.field-meta.xml
<CustomField>
    <fullName>IsSampleAccessory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>IsSampleAccessory</description>
    <externalDeveloperName>IsSampleAccessory</externalDeveloperName>
    <label>IsSampleAccessory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/Jerarquia__c.field-meta.xml
<CustomField>
    <fullName>Jerarquia__c</fullName>
    <description>Jerarquia</description>
    <externalDeveloperName>Jerarquia</externalDeveloperName>
    <label>Jerarquia</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/Longitud__c.field-meta.xml
<CustomField>
    <fullName>Longitud__c</fullName>
    <description>Longitud</description>
    <externalDeveloperName>Longitud</externalDeveloperName>
    <label>Longitud</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Marca</description>
    <externalDeveloperName>Marca</externalDeveloperName>
    <label>Marca</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/Materia__c.field-meta.xml
<CustomField>
    <fullName>Materia__c</fullName>
    <description>Materia</description>
    <externalDeveloperName>Materia</externalDeveloperName>
    <label>Materia</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/Mt2Cj__c.field-meta.xml
<CustomField>
    <fullName>Mt2Cj__c</fullName>
    <description>Mt2Cj</description>
    <externalDeveloperName>Mt2Cj</externalDeveloperName>
    <label>Mt2Cj</label>
    <precision>13</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <description>Nombre</description>
    <externalDeveloperName>Nombre</externalDeveloperName>
    <label>Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/PzsCj__c.field-meta.xml
<CustomField>
    <fullName>PzsCj__c</fullName>
    <description>PzsCj</description>
    <externalDeveloperName>PzsCj</externalDeveloperName>
    <label>PzsCj</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/Ramo__c.field-meta.xml
<CustomField>
    <fullName>Ramo__c</fullName>
    <description>Ramo</description>
    <externalDeveloperName>Ramo</externalDeveloperName>
    <label>Ramo</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/TipoMaterial__c.field-meta.xml
<CustomField>
    <fullName>TipoMaterial__c</fullName>
    <description>TipoMaterial</description>
    <externalDeveloperName>TipoMaterial</externalDeveloperName>
    <label>TipoMaterial</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/Umb__c.field-meta.xml
<CustomField>
    <fullName>Umb__c</fullName>
    <description>Umb</description>
    <externalDeveloperName>Umb</externalDeveloperName>
    <label>Umb</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/UmbCj__c.field-meta.xml
<CustomField>
    <fullName>UmbCj__c</fullName>
    <description>UmbCj</description>
    <externalDeveloperName>UmbCj</externalDeveloperName>
    <label>UmbCj</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/UmbKg__c.field-meta.xml
<CustomField>
    <fullName>UmbKg__c</fullName>
    <description>UmbKg</description>
    <externalDeveloperName>UmbKg</externalDeveloperName>
    <label>UmbKg</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/UmbMt2__c.field-meta.xml
<CustomField>
    <fullName>UmbMt2__c</fullName>
    <description>UmbMt2</description>
    <externalDeveloperName>UmbMt2</externalDeveloperName>
    <label>UmbMt2</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZSFMatBase__x/fields/UmbPal__c.field-meta.xml
<CustomField>
    <fullName>UmbPal__c</fullName>
    <description>UmbPal</description>
    <externalDeveloperName>UmbPal</externalDeveloperName>
    <label>UmbPal</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/ProductCatalogCategories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACC</fullName>
        <label>ACCESSORIES</label>
    </customValue>
    <customValue>
        <fullName>ADH</fullName>
        <label>ADHESIVES</label>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
        <label>ALL FAMILIES</label>
    </customValue>
    <customValue>
        <fullName>BAS</fullName>
        <label>BASINS</label>
    </customValue>
    <customValue>
        <fullName>BRW</fullName>
        <label>BRASSWARE</label>
    </customValue>
    <customValue>
        <fullName>FUR</fullName>
        <label>BATHROOM FURNITURE</label>
    </customValue>
    <customValue>
        <fullName>GRO</fullName>
        <label>GROUTS</label>
    </customValue>
    <customValue>
        <fullName>HEA</fullName>
        <label>UNDERFLOOR HEATING</label>
    </customValue>
    <customValue>
        <fullName>INS</fullName>
        <label>INSTALLATION SYSTEMS</label>
    </customValue>
    <customValue>
        <fullName>MIR</fullName>
        <label>MIRRORS</label>
    </customValue>
    <customValue>
        <fullName>OTH</fullName>
        <label>OTHERS</label>
    </customValue>
    <customValue>
        <fullName>SAW</fullName>
        <label>SANITARYWARE</label>
    </customValue>
    <customValue>
        <fullName>SHC</fullName>
        <label>SHOWER COLUMNS</label>
    </customValue>
    <customValue>
        <fullName>SHE</fullName>
        <label>SHOWER ENCLOSURES</label>
    </customValue>
    <customValue>
        <fullName>SHH</fullName>
        <label>SHOWER HEADS</label>
    </customValue>
    <customValue>
        <fullName>SHT</fullName>
        <label>SHOWER TRAYS</label>
    </customValue>
    <customValue>
        <fullName>SHV</fullName>
        <label>SHOWER VALVES</label>
    </customValue>
    <customValue>
        <fullName>TIL</fullName>
        <label>TILES</label>
    </customValue>
    <customValue>
        <fullName>TOP</fullName>
        <label>WORKTOPS</label>
    </customValue>
    <customValue>
        <fullName>TOW</fullName>
        <label>TOWEL WARMERS</label>
    </customValue>
    <customValue>
        <fullName>TRI</fullName>
        <label>TRIMS</label>
    </customValue>
    <customValue>
        <fullName>TUB</fullName>
        <label>BATHTUBS</label>
    </customValue>
    <description>List of product category (related to the detail shown in the catalog)</description>
    <masterLabel>Product Catalog Categories</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProductUnits.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PZS</fullName>
        <label>PIECE</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>PALLET</label>
    </customValue>
    <customValue>
        <fullName>SAC</fullName>
        <label>BAG</label>
    </customValue>
    <customValue>
        <fullName>MT2</fullName>
        <label>SQUARE METERS</label>
    </customValue>
    <customValue>
        <fullName>BID</fullName>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>CJ</fullName>
        <label>BOX</label>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
        <label>CENTIMETER</label>
    </customValue>
    <customValue>
        <fullName>DM2</fullName>
        <label>SQUARE DECIMETER</label>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
        <label>KILOGRAM</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>LITER</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>METER</label>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
        <label>SQUARE METER</label>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
        <label>MILILITER</label>
    </customValue>
    <customValue>
        <fullName>ROL</fullName>
        <label>ROLE</label>
    </customValue>
    <customValue>
        <fullName>SQF</fullName>
        <label>SQUARE FOOT</label>
    </customValue>
    <customValue>
        <fullName>UN</fullName>
        <label>UNIT</label>
    </customValue>
    <customValue>
        <fullName>CM2</fullName>
        <label>SQUARE CENTIMETER</label>
    </customValue>
    <customValue>
        <fullName>DM</fullName>
        <label>DECIMETER</label>
    </customValue>
    <description>Values for product units</description>
    <masterLabel>Product Units</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SAPMakes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B</fullName>
        <label>BUTECH</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>EXTERNAL</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>GAMA DECOR</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>L&apos;ANTIC</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>NOKEN</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <label>PORCELANOSA</label>
    </customValue>
    <customValue>
        <fullName>S</fullName>
        <label>SYSTEM POOL</label>
    </customValue>
    <customValue>
        <fullName>-</fullName>
        <label>UNBRANDED</label>
    </customValue>
    <customValue>
        <fullName>X</fullName>
        <label>XTONE</label>
    </customValue>
    <description>List of valid SAP makes (P, L, etc)</description>
    <masterLabel>SAP Makes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MasterProductSyncJobTest.cls
@IsTest(IsParallel=false)  public class MasterProductSyncJobTest {

    private static final String GRUPO_ARTICULOS = 'PT0001';
    private static String MARCA = 'P';

    @testSetup private static void testSetup() {
        DataFactoryProduct.ignoreStandardPriceBook = true;
        Product2[] products = DataFactoryProduct.createProducts();  
        ItemGroup__c item = new ItemGroup__c();
        item.CatalogCategory__c = PicklistCommons.getKeysList(ItemGroup__c.CatalogCategory__c)[0];
        item.Name = 'Test Group';
        item.SAPGroup__c = GRUPO_ARTICULOS;
        insert item;
    }

    @IsTest
    public static void testUpdateFields() {        
        
        List<ZSFMatBase__x> sapProducts = getSAPProducts();
        Product2[] products = [select Id, SAPItemGroup__c, ProductCode from Product2];
        Assert.isNull(products[0].SAPItemGroup__c, 'Item Group should be null');

        Test.startTest();
            MasterProductSyncJob job = new MasterProductSyncJob();
            job.setUpdateMode();
            job.setMaxInfo(true);
            job.start(null);
            job.execute(null,sapProducts);
            job.finish(null);
        Test.stopTest();

        Product2 p2 = [select Id, SAPItemGroup__c, SAPMake__c from Product2 limit 1];
        Assert.isNotNull(p2.SAPItemGroup__c, 'ItemGroup should not be null');
        Assert.areEqual(MARCA, p2.SAPMake__c, 'Wrong make');           
    }


    @IsTest
    public static void testBatchProcess() {        
        
        List<ZSFMatBase__x> sapProducts = getSAPProducts();
        
        // Force this one to be set as inactive
        sapProducts[9].GrupoArticulos__c = null;
        sapProducts[9].IsSample__c = false;
        sapProducts[9].IsSampleAccessory__c = false;
        String inactiveProductCode = sapProducts[9].Material__c;

        Test.startTest();
            MasterProductSyncJob job = new MasterProductSyncJob();
            job.setStandardMode();
            job.setDeleteDuplicates(true);
            job.setMaxInfo(true);
            job.start(null);
            job.execute(null,sapProducts);
            job.finish(null);
        Test.stopTest();

        ItemGroup__c itemGroup = [select Id from ItemGroup__c limit 1];
        Product2 p2 = [select Id, SAPItemGroup__c, SAPMake__c from Product2 limit 1];
        Assert.areEqual(itemGroup.Id, p2.SAPItemGroup__c, 'ItemGroup should not be null');
        Assert.areEqual(MARCA, p2.SAPMake__c, 'Wrong make');   
        
        // Check product inactive
        Product2 p3 = [select Id, isActive from Product2 where StockKeepingUnit = :inactiveProductCode limit 1];
        Assert.isFalse(p3.isActive, 'Product should be inactive');
    }

    @isTest public static void  testMaintenance() {        
        Product2[] products = new Product2[]{};
        Test.startTest();
            MasterProductSyncJob job = new MasterProductSyncJob();
            job.setMaintenaceMode();
            job.setMaxInfo(true);
            Database.queryLocator query = job.start(null);
            Database.QueryLocatorIterator it = query.iterator();
            while (it.hasNext()) {
                Product2 p = (Product2)it.next();
                products.add(p);
            }
            System.assertNotEquals(0, products.size(), 'No products selected for test');
            job.execute(null,products);
            job.finish(null);
        Test.stopTest();          
    } 

    @isTest public static void  testActive() {        
        Product2[] products = new Product2[]{};
        Test.startTest();
            MasterProductSyncJob job = new MasterProductSyncJob();
            job.setActiveMode();
            Database.queryLocator query = job.start(null);
            Database.QueryLocatorIterator it = query.iterator();
            while (it.hasNext()) {
                Product2 p = (Product2)it.next();
                products.add(p);
            }
            System.assertNotEquals(0, products.size(), 'No products selected for test');
            job.execute(null,products);
            job.finish(null);
        Test.stopTest();  
        Product2[] actives = [select Id from Product2 where IsActive = true];
        Assert.areEqual(0, actives.size(), 'All products should be inactive becasue they are created without make and so on');        
    } 
 

 
    @isTest public static void  testConversion() {        
        Product2[] products = [select Id, ProductCode from Product2];
        
        List<ZSFMatBase__x> sapProducts = new List<ZSFMatBase__x>();
        for (Integer i = 0; i < 10; i++) {
            ZSFMatBase__x productExternalObj = new ZSFMatBase__x();
            productExternalObj.Altura__c = 1.0;
            productExternalObj.Ancho__c = 20.0;
            productExternalObj.CurrencyIsoCode = 'EUR';
            productExternalObj.DisplayUrl = 'https://desmobile.porcelanosagrupo.com:44301/sap/opu/odata/SAP/Z31SD_T_SF_INTERF_SRV/ZSFMatBaseSet(\'100000837\')';
            productExternalObj.ExternalId = products[i].ProductCode;
            productExternalObj.GrupoArticulos__c = 'PT0097';
            productExternalObj.Jerarquia__c = '000010010700000468';
            productExternalObj.Longitud__c = 10.0;
            productExternalObj.Marca__c = 'URBATEK';
            productExternalObj.Material__c = products[i].ProductCode;
            productExternalObj.Modificado__c = Date.Today();
            productExternalObj.Nombre__c = 'RETRO BLANCO 10X20(A)'+1;
            productExternalObj.Ramo__c = 'Z';
            productExternalObj.UmbCj__c = 50.0;
            productExternalObj.UmbKg__c = 3.937;
            productExternalObj.UmbMt2__c = 50.0; 
            productExternalObj.UmbPal__c = 3000.0;
            productExternalObj.Umb__c = 'PZS';
            productExternalObj.Umv__c = 'PZS';
            productExternalObj.PzsCj__c = 50;
            productExternalObj.Mt2Cj__c = 6.66;
            productExternalObj.CjPal__c = 60;
            sapProducts.add(productExternalObj);
        } // end for

        sapProducts[9].Umb__c = 'EWE';

        Test.startTest();
            MasterProductSyncJob job = new MasterProductSyncJob();
            job.setConversionMode();
            job.setMaxInfo(true);
            job.start(null);
            job.execute(null,sapProducts);
            job.finish(null);
        Test.stopTest();

        // Usamos sapProducts[0] para test
        Product2 pr2 = [select Id, ProductCode, M2XBox__c from Product2 where ProductCode = :sapProducts[0].Material__c limit 1];
        System.assertEquals(sapProducts[0].Mt2Cj__c, pr2.M2XBox__c, 'Wrong conversion field');
        
        pr2 = [select Id, ProductCode, M2XBox__c, StockUnit__c from Product2 where ProductCode = :sapProducts[9].Material__c limit 1];
        System.assertEquals('UN', pr2.StockUnit__c, 'Wrong unit');

    } 

    private static List<ZSFMatBase__x> getSAPProducts() {
        Product2[] products = [select Id, ProductCode from Product2];
        List<ZSFMatBase__x> sapProducts = new List<ZSFMatBase__x>();
        for (Integer i = 0; i < 10; i++) {
            ZSFMatBase__x productExternalObj = new ZSFMatBase__x();
            productExternalObj.Altura__c = 1.0;
            productExternalObj.Ancho__c = 20.0;
            productExternalObj.CurrencyIsoCode = 'EUR';
            productExternalObj.DisplayUrl = 'https://desmobile.porcelanosagrupo.com:44301/sap/opu/odata/SAP/Z31SD_T_SF_INTERF_SRV/ZSFMatBaseSet(\'100000837\')';
            productExternalObj.ExternalId = products[i].ProductCode;
            productExternalObj.GrupoArticulos__c = GRUPO_ARTICULOS;
            productExternalObj.Jerarquia__c = '000010010700000468';
            productExternalObj.Longitud__c = 10.0;
            productExternalObj.Marca__c = 'URBATEK';
            productExternalObj.Material__c = products[i].ProductCode;
            productExternalObj.Modificado__c = Date.Today();
            productExternalObj.Nombre__c = 'RETRO BLANCO 10X20(A)'+1;
            productExternalObj.Ramo__c = 'Z';
            productExternalObj.UmbCj__c = 50.0;
            productExternalObj.UmbKg__c = 3.937;
            productExternalObj.UmbMt2__c = 50.0;
            productExternalObj.UmbPal__c = 3000.0;
            productExternalObj.Umb__c = 'PZS';
            productExternalObj.Umv__c = 'PZS';
            productExternalObj.Materia__c = MARCA;
            productExternalObj.IsSample__c = false;
            productExternalObj.IsSampleAccessory__c = false;
            productExternalObj.TipoMaterial__c = '';
            sapProducts.add(productExternalObj);
        } // end for
        return sapProducts;
    }


} // class