force-app/main/default/objects/Case/fields/Compensation__c.field-meta.xml
<CustomField>
    <fullName>Compensation__c</fullName>
    <description>Compensation to pay to a customer</description>
    <label>Settlement Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SupplyInstallation__c.field-meta.xml
<CustomField>
    <fullName>SupplyInstallation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Supply Installation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SupplyReplacement__c.field-meta.xml
<CustomField>
    <fullName>SupplyReplacement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Supply a replacement product or part</description>
    <label>Supply Replacement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ObjectAuditTrail__c/ObjectAuditTrail__c.object-meta.xml
<CustomObject>
    <description>Generic object designed to keep a trail of significant changes at some important fields. FOr example, we use this to log all the rejected solutions to claims.</description>
    <label>Object Audit Trail</label>
    <nameField>
        <label>Object Audit Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object Audit Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectAuditTrail__c/fields/AuditTrailType__c.field-meta.xml
<CustomField>
    <fullName>AuditTrailType__c</fullName>
    <label>Audit Trail Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CLAIM_SOLUTION</fullName>
                <label>CLAIM SOLUTION</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ObjectAuditTrail__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claim Solutions Audit Trail</relationshipLabel>
    <relationshipName>Object_Audit_Trails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ObjectAuditTrail__c/fields/SettlementAmount__c.field-meta.xml
<CustomField>
    <fullName>SettlementAmount__c</fullName>
    <description>Claim Selection: Settlement Amount</description>
    <label>Settlement Amount</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ObjectAuditTrail__c/fields/SupplyInstallation__c.field-meta.xml
<CustomField>
    <fullName>SupplyInstallation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Claim Solution: Supply Installation and repair services</description>
    <label>Supply Installation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ObjectAuditTrail__c/fields/SupplyReplacement__c.field-meta.xml
<CustomField>
    <fullName>SupplyReplacement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Claim SOlution: Supply replacement</description>
    <label>Supply Replacement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ObjectAuditTrailsService.cls
/**
 * @author         Ramón Prades
 * @date           February 2024
 * @group          Object Audit Trails
 * @description    Service layer to access ObjectAuditTrail__c. This object is used to take a snapshot
 *                 of a set of up to 6 fields before they cahnge.
*/
public without sharing class ObjectAuditTrailsService {

    public static final String CLAIM_SOLUTION_TYPE = 'CLAIM_SOLUTION';

    /**
     * Inserts a new record
     */
    public static ObjectAuditTrail__c[] saveClaimSolutionTrail(Case[] claims) {
        ObjectAuditTrail__c[] trails = new List<ObjectAuditTrail__c>();
        for (Case claim : claims) {
            ObjectAuditTrail__c trail = new ObjectAuditTrail__c();
            trail.CaseId__c = claim.Id;
            trail.Name = 'CLAIM SOLUTION';
            trail.AuditTrailType__c = CLAIM_SOLUTION_TYPE;
            trail.SupplyReplacement__c = claim.SupplyReplacement__c;
            trail.SupplyInstallation__c = claim.SupplyInstallation__c;
            trail.SettlementAmount__c = claim.Compensation__c;
            trails.add(trail);
        }
        insert trails;
        return trails;
    }
    
    /**
     * Check and saves the claim solution when it has changed
     */
    public static void logClaimSolutionChanged(Case[] claims) {
        Case[] changedClaims = new List<Case>();
        for (Case claim : claims) {
            if (claimSolutionChanged(claim)) {
                changedClaims.add(claim);
            }
        }
        if (changedClaims.size() > 0) {
            saveClaimSolutionTrail(claims);
        }
    }

    public static Boolean claimSolutionChanged(Case claim) {
        ObjectAuditTrail__c lastTrail = new ObjectAuditTrailsSelector().getLastCaseTrail(claim.Id, CLAIM_SOLUTION_TYPE);
        if (lastTrail == null) {
            lastTrail = new ObjectAuditTrail__c();
            lastTrail.SupplyReplacement__c = false;
            lastTrail.SupplyInstallation__c = false;
            lastTrail.SettlementAmount__c = 0;
        }
        return (claim.SupplyReplacement__c != lastTrail.SupplyReplacement__c ||
                claim.SupplyInstallation__c != lastTrail.SupplyInstallation__c ||
                claim.Compensation__c != lastTrail.SettlementAmount__c);
    }

}