force-app/main/default/objects/Case/fields/IsClaim__c.field-meta.xml
<CustomField>
    <fullName>IsClaim__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si es un Claim</description>
    <label>Is Claim</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/IsCollection__c.field-meta.xml
<CustomField>
    <fullName>IsCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DataFactoryCaseTest.cls
@isTest public class DataFactoryCaseTest {

    @TestSetup static void makeData() {
    }

    @isTest private static void testCreateCollection() {
        DataFactoryCase.createCollections(5);        
        Case[] cases = [select Id from Case where IsCollection__c = true];
        Assert.areEqual(5, cases.size(), '5 collections expected' );
    }

    @isTest private static void testCreateClaims() {
        DataFactoryCase.createClaims(5);        
        Case[] cases = [select Id from Case where IsClaim__C = true];
        Assert.areEqual(5, cases.size(), '5 claims expected' );
    }

}