force-app/main/default/objects/Case/fields/IsCollection__c.field-meta.xml
<CustomField>
    <fullName>IsCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <formula>OrderId__r.OrderNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <description>SAP Sales Organisation</description>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_SD_Invoices__e/SAP_SD_Invoices__e.object-meta.xml
<CustomObject>
    <description>Evento para indicar que se ha hecho una factura en SAP en SAP.</description>
    <label>SAP SD Invoice</label>
    <pluralLabel>SAP SD Invoices</pluralLabel>
</CustomObject>

force-app/main/default/objects/SAP_SD_Invoices__e/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Action performed</description>
    <label>Action</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_SD_Invoices__e/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>SAP Distributino channel</description>
    <label>Distribution Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_SD_Invoices__e/fields/DeliveryNumber__c.field-meta.xml
<CustomField>
    <fullName>DeliveryNumber__c</fullName>
    <description>Delivery note number</description>
    <label>Delivery Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_SD_Invoices__e/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <description>Invoice number</description>
    <label>Invoice Number</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_SD_Invoices__e/fields/isCollection__c.field-meta.xml
<CustomField>
    <fullName>isCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if the credit note is a goods returned credit</description>
    <label>is Collection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAP_SD_Invoices__e/fields/IsCredit__c.field-meta.xml
<CustomField>
    <fullName>IsCredit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is a credit note</description>
    <label>Is Credit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAP_SD_Invoices__e/fields/IsReversal__c.field-meta.xml
<CustomField>
    <fullName>IsReversal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if the credit is the reversal of an invoice or credit</description>
    <label>Is Reversal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAP_SD_Invoices__e/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>Order number</description>
    <label>Order Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_SD_Invoices__e/fields/RefInvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>RefInvoiceNumber__c</fullName>
    <description>referred invoice (for reversals)</description>
    <label>Referred Invoice</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_SD_Invoices__e/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <description>Sales Organisation code</description>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PEVSAPInvoicesTriggerHandler.cls
/**
 * @author         Ramón Prades
 * @date           August 2023
 * @group          SAP Events
 * @description    Platform Event handler for SAP credit note events
*/
public class PEVSAPInvoicesTriggerHandler {

    public static void afterInsert(List<SAP_SD_Invoices__e> events) {
        SAPCasesService.SAPCreditNoteDTO[] collections = new List<SAPCasesService.SAPCreditNoteDTO>();
        SystemLog log = new SystemLog('SAP-EVENTS');
        log.addInfo('Processing ' + events.size() + ' events of type SAP CREDITNOTE');
        log.saveLog();
        try {
            Integer numEvent = 0;
            for (SAP_SD_Invoices__e e : events) {
                log.addSection('Event #' + ++numEvent);
                log.setInputData(JSON.serializePretty(e));
                SAPCasesService.SAPCreditNoteDTO dto = new SAPCasesService.SAPCreditNoteDTO();
                dto.invoiceNumber = e.InvoiceNumber__c;
                dto.orderNumber = e.OrderNumber__c;
                dto.deliveryNumber = e.DeliveryNumber__c;
                dto.action = e.Action__c;
                dto.isCollection = e.IsCollection__c;
                dto.isReversal = e.isReversal__c;
                dto.isCredit = e.isCredit__c;
                dto.refInvoiceNumber = e.refInvoiceNumber__c;
                dto.salesOrg = e.SalesOrg__c;
                dto.channel = e.Channel__c;
                if (dto.isCollection && dto.action != 'UNCLEAR') {  // Desactivo UNCLEAR poara no reabrir casos cerrados
                    collections.add(dto);
                }
            }              
            log.addDebug('Updating case status');            
            if (collections.size() > 0) {
                SAPCasesService.setSAPCreditNote(collections);            
            }
            log.addDebug('Case credit note updated!');
        } catch(Exception ex2){            
            log.addSection('Outer Exception');
            log.addError(ex2);
            throw ex2;
        } finally {
            log.saveLog(true);
        }
    }

} // PEVSAPCollectionTriggerHandler}