force-app/main/default/objects/Case/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G1</fullName>
                <label>Factory Liability.</label>
            </value>
            <value>
                <fullName>G2</fullName>
                <label>Region Liability.</label>
            </value>
            <value>
                <fullName>G3</fullName>
                <label>Customer Liability.</label>
            </value>
            <value>
                <fullName>Company Liability</fullName>
                <isActive>false</isActive>
                <label>Company Liability</label>
            </value>
            <value>
                <fullName>Factory Liability</fullName>
                <isActive>false</isActive>
                <label>Factory Liability</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SupplyInstallation__c.field-meta.xml
<CustomField>
    <fullName>SupplyInstallation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Supply Installation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Warranty__c.field-meta.xml
<CustomField>
    <fullName>Warranty__c</fullName>
    <label>Product Under Warranty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNoValueSet</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PORSAIntegrationSettings__c/PORSAIntegrationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>PORSA Integration Settings</label>
</CustomObject>

force-app/main/default/objects/PORSAIntegrationSettings__c/fields/SendClaims__c.field-meta.xml
<CustomField>
    <fullName>SendClaims__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Sends claims to the factory quality systems</inlineHelpText>
    <label>Send claims to factories</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/SAPRequestQueue__c.object-meta.xml
<CustomObject>
    <description>Objets to queue the requests to update objects in SAP</description>
    <label>SAP Request Queue</label>
    <nameField>
        <label>SAP Requests Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Requests Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAPRequestQueue__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message related to the result of the last connection to the requested service</description>
    <label>Message</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/Parameter__c.field-meta.xml
<CustomField>
    <fullName>Parameter__c</fullName>
    <inlineHelpText>Optional extra information for teh API Handler</inlineHelpText>
    <label>Parameter</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/RequesterID__c.field-meta.xml
<CustomField>
    <fullName>RequesterID__c</fullName>
    <description>ID of the object requesting the service. It might be used when porcessing the repsonse to update some fields.</description>
    <label>Requester ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/SAPAPIHandler__c.field-meta.xml
<CustomField>
    <fullName>SAPAPIHandler__c</fullName>
    <description>Name of the class that will handle the connection to the SAP service</description>
    <label>SAP API Handler</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAPRequestQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;QUEUED&quot;</defaultValue>
    <description>Status of the request</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
            </value>
            <value>
                <fullName>PROCESSED</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>EXCEPTION</fullName>
            </value>
            <value>
                <fullName>BLOCKED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SystemSettings__c/SystemSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Systemwide settings</description>
    <label>System Settings</label>
</CustomObject>

force-app/main/default/objects/SystemSettings__c/fields/SAPAPI__c.field-meta.xml
<CustomField>
    <fullName>SAPAPI__c</fullName>
    <description>URL del Api Manager (proxy) de SAP CPI</description>
    <label>SAP API</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/SAPCPIAPIKey__c.field-meta.xml
<CustomField>
    <fullName>SAPCPIAPIKey__c</fullName>
    <description>API key to access the salesforce API</description>
    <label>SAP CPI API Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/YesNoValueSet.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YES</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <masterLabel>YesNoValueSet</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FactoryQualityAPIHandlerTest.cls
@isTest public with sharing class FactoryQualityAPIHandlerTest {

    @TestSetup static void makeData(){
        SystemSettings__c ss = SystemSettings.getSystemSettings();
        ss.SAPAPI__c = 'https:/dummy-ai.com/';
        ss.SAPCPIAPIKey__c = '321321321321';
        Database.Upsert(ss);

        PORSAIntegrationSettings__c settings = new PORSAIntegrationSettings__c();
        settings.SendClaims__c = true;
        insert settings;

        DataFactoryCase.createClaims(1);
    }

    @isTest private static void test001() {
        Test.setMock(HttpCalloutMock.class, new FactoryQualityAPIHandlerTest.Mocker());
        Case[] claims = [select Id from Case];
        for (Case claim : claims) {
            claim.Liability__c = 'G1';
            claim.Warranty__c = 'NO';
            claim.SupplyInstallation__c = true;
            claim.Status = 'Closed';
        } 
        Test.startTest();
        update claims;
        Test.stopTest();

        SAPRequestQueue__c[] items = [select Id, Status__c, Message__c from SAPRequestQueue__c];
        Assert.areEqual(1, items.size(), 'There should be an item in the queue');
        String status = items[0].Status__c.toLowerCase();
        Assert.areEqual('processed', status, 'Status not expected ' + status);
    }

    @isTest private static void test002() {
        Test.setMock(HttpCalloutMock.class, new FactoryQualityAPIHandlerTest.Mocker());
        Case theCase = [select Id from Case limit 1];

        // Crear el archivo como ContentVersion
        ContentVersion file = new ContentVersion(
            Title = 'TestFile',
            PathOnClient = 'test.txt',
            VersionData = Blob.valueOf('Test content'),
            IsMajorVersion = true
        );
        insert file;

        // Obtener el ContentDocumentId generado automáticamente
        Id contentDocumentId = [
            SELECT ContentDocumentId 
            FROM ContentVersion 
            WHERE Id = :file.Id
        ].ContentDocumentId;

        // Crear el vínculo entre el archivo y el caso
        ContentDocumentLink link = new ContentDocumentLink(
            ContentDocumentId = contentDocumentId,
            LinkedEntityId = theCase.Id,
            ShareType = 'V', // Viewer access
            Visibility = 'AllUsers'
        );
        insert link; 

        Test.startTest();
        theCase.Liability__c = 'G1';
        theCase.Warranty__c = 'NO';
        theCase.SupplyInstallation__c = true;
        theCase.Status = 'Closed';
        update theCase;   
        Test.stopTest();

        SAPRequestQueue__c[] items = [select Id, Status__c, Message__c, SAPAPIHandler__c, RequesterId__c, Parameter__c from SAPRequestQueue__c];
        Assert.areEqual(2, items.size(), 'There should be 2 items in the queue');
        String status = items[0].Status__c.toLowerCase();
        Assert.areEqual('processed', status, 'Status not expected ' + status + ' in API handler ' + items[0].SAPAPIHandler__c);

    }

    public class Mocker implements HttpCalloutMock {
        
        public Boolean testError = false;

        public HttpResponse respond(HttpRequest request) {            
            // Set up mock HTTP response            
            request.getBody();
            HttpResponse mockResponse = new HttpResponse();
            if (this.testError) {
                String json = '{"status":"false","date":"2025-06-25 08:59:14","data":9,"message":"Dummy error","automaticChanges":false}';
                mockResponse.setStatusCode(400);
                mockResponse.setBody(json);
            } else {
                String json = '{"status":"success","date":"2025-06-25 08:59:14","data":9,"message":"Message stored successfully","automaticChanges":false}';
                mockResponse.setStatusCode(200);
                mockResponse.setBody(json);
            }
            return mockResponse;
        }
    }
    

}