force-app/main/default/objects/Case/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductUnits</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Umv__c.field-meta.xml
<CustomField>
    <fullName>Umv__c</fullName>
    <label>Umv</label>
    <length>10</length>
    <translateData>true</translateData>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/ProductListItem__c.object-meta.xml
<CustomObject>
    <description>Custom object to store list of products</description>
    <label>Product List Item</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>ItemId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product List Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductListItem__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Id of the case owning the product list</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Product List Items</relationshipLabel>
    <relationshipName>Product_List_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Product Name</description>
    <label>Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product Code</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product List Items</relationshipLabel>
    <relationshipName>Product_List_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductUnits</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ProductUnits.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PZS</fullName>
        <label>PIECE</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>PALLET</label>
    </customValue>
    <customValue>
        <fullName>SAC</fullName>
        <label>BAG</label>
    </customValue>
    <customValue>
        <fullName>MT2</fullName>
        <label>SQUARE METERS</label>
    </customValue>
    <customValue>
        <fullName>BID</fullName>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>CJ</fullName>
        <label>BOX</label>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
        <label>CENTIMETER</label>
    </customValue>
    <customValue>
        <fullName>DM2</fullName>
        <label>SQUARE DECIMETER</label>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
        <label>KILOGRAM</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>LITER</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>METER</label>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
        <label>SQUARE METER</label>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
        <label>MILILITER</label>
    </customValue>
    <customValue>
        <fullName>ROL</fullName>
        <label>ROLE</label>
    </customValue>
    <customValue>
        <fullName>SQF</fullName>
        <label>SQUARE FOOT</label>
    </customValue>
    <customValue>
        <fullName>UN</fullName>
        <label>UNIT</label>
    </customValue>
    <customValue>
        <fullName>CM2</fullName>
        <label>SQUARE CENTIMETER</label>
    </customValue>
    <customValue>
        <fullName>DM</fullName>
        <label>DECIMETER</label>
    </customValue>
    <description>Values for product units</description>
    <masterLabel>Product Units</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DataFactoryProductListItem.cls
/**
* @author 		Ramón Prades
* @date 		May 2023
* @group 		DataFactories   
* @description 	Data factory
*/
public class DataFactoryProductListItem {
    
    public static ProductListItem__c[] createCollectionCaseItems() {
        
        ProductListItem__c[] items = new List<ProductListItem__c>();
        
        if (Test.isRunningTest()) {
            Product2[] products = DataFactoryProduct.createProducts(null);
            Case c = DataFactoryCase.createCollections(1)[0];
            for (Integer i = 0; i<products.size(); i++) {
                ProductListItem__c item = new ProductListItem__c();
                item.Product__c = products[i].Id;
                item.Case__c = c.Id;
                item.Name__c = products[i].Name;
                item.ProductCode__c = products[i].ProductCode;
                item.Quantity__c = 1;
                item.Unit__c = products[i].Umv__c;
                items.add(item);
            }             
            insert items;
        }
        
        return items;                        

    }
} // class