force-app/main/default/objects/Case/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <description>SAP Sales Organisation</description>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Facturas_cabeceraSet__x/Facturas_cabeceraSet__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>Facturas_cabeceraSet</externalName>
    <label>Facturas_cabeceraSet</label>
    <pluralLabel>Facturas_cabeceraSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/Facturas_cabeceraSet__x/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Retates the sales document with the Account using the value stored in id18</description>
    <externalDeveloperName>id18</externalDeveloperName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas_cabeceraSet</relationshipLabel>
    <relationshipName>Facturas_cabeceraSet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Facturas_posicionesSet__x/Facturas_posicionesSet__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>Facturas_posicionesSet</externalName>
    <label>Facturas_posicionesSet</label>
    <pluralLabel>Facturas_posicionesSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/Order/fields/Ordernum__c.field-meta.xml
<CustomField>
    <fullName>Ordernum__c</fullName>
    <label>XXX Ordernum</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BoxXPal__c.field-meta.xml
<CustomField>
    <fullName>BoxXPal__c</fullName>
    <description>Number of boxes in a pallet</description>
    <label>Box/Pallet</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAPCasesSettings__c/SAPCasesSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuración Casos SAP</description>
    <label>PORSA SAP Cases</label>
</CustomObject>

force-app/main/default/classes/SAPDocumentsQueryController.cls
/**
 * @author         Ramón Prades
 * @date           January 2025
 * @layer          LWC Controller
 * @description    Controller class to read SAP documents for libSAPDocumentsQuery component
*/
public class SAPDocumentsQueryController {

    @AuraEnabled(cacheable=true) public static Facturas_cabeceraSet__x readInvoice(String invoiceNumber) {
        return new SAPInvoicesSelector().selectByNumber(invoiceNumber);        
    }

    @AuraEnabled(cacheable=true) public static ResultDTO readInvoiceWithDetails(String invoiceNumber) {
        ResultDTO dto = new ResultDTO();
        dto.sapInvoice = new SAPInvoicesSelector().selectByNumber(invoiceNumber);      
        if (checkPermission(dto?.sapInvoice)) {
            dto.sapItems = new SAPInvoiceLinesSelector().selectByNumber(invoiceNumber);
            dto.AccountName = AccountUtil.getName(dto.sapInvoice.Account__c );
            dto.SalesOrgName = OrganizationUtil.getSalesOrgName(dto.sapInvoice.Salesorg__c);
            //dto.productIds = searchProductIds(dto.sapItems);
            dto.productMap = buildProductMap(dto.sapItems);
            dto.settings = CasesDomain.getSAPSettings(dto.sapInvoice.Salesorg__c, dto.sapInvoice.Ordernum__c);
            dto.readyForCase = isInvoiceReadyForCase(dto.sapInvoice.Ordertype__c);
        } else {
            throw new SecurityException('Insufficient permissions to access this invoice (sales organization is ' + dto.sapInvoice.Salesorg__c + ')');
        }
        return dto;
    }

    public class ResultDTO {
        @AuraEnabled public Facturas_cabeceraSet__x sapInvoice {get; set;}
        @AUraEnabled public Facturas_posicionesSet__x[] sapItems {get; set;}
        @AuraEnabled public String accountName {get; set;}
        @AuraEnabled public String salesOrgName {get; set;}        
        @AuraEnabled public Map<String, Product2> productMap {get; set;}
        @AuraEnabled public SAPCasesSettings__c settings {get; set;}
        @AuraEnabled public Boolean readyForCase {get; set;}

    }

    //======================================================================================================

    private static Boolean checkPermission(Facturas_cabeceraSet__x invoice) {
        return UserCommons.hasAccessToSalesOrg(UserInfo.getUserId(), invoice.Salesorg__c);
    }

    private static Map<String, Product2>  buildProductMap(Facturas_posicionesSet__x[] items) {
        Map<String, Product2> productMap = new Map<String, Product2>();
        List<String> codes = TypeConversionCommons.extractFieldValues(items, 'Sku__c');
        if (codes.size() > 0) {
            List<Product2> products = [select Id, StockKeepingUnit, BoxXPal__c from Product2 where StockKeepingUnit in :codes];
            for  (Product2 product :products) {
                productMap.put(product.StockKeepingUnit, product);
            }
        }
        return productMap;
    }

    private static Boolean isInvoiceReadyForCase(String invoiceType) {
        // Only certain order types are eligible for case creation
        return (invoiceType == 'Z001' || invoiceType == 'Z004' || invoiceType == 'Z005' || invoiceType == 'Z006' || invoiceType == 'Z007');
    }

}