force-app/main/default/objects/SYS_ProcessReceipt__c/SYS_ProcessReceipt__c.object-meta.xml
<CustomObject>
    <description>Tracks unique process executions and deduplication keys to ensure idempotent behavior across system operations. Used by administrators and developers for technical maintenance, integration tracking, and duplicate prevention.</description>
    <label>SYS Process Receipt</label>
    <nameField>
        <label>Receipt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SYS Process Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_ProcessReceipt__c/fields/DedupKey__c.field-meta.xml
<CustomField>
    <fullName>DedupKey__c</fullName>
    <label>Dedup Key</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_ProcessReceipt__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Unique field (filled via trigger as Namespace + Dedupkey</description>
    <label>Key</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_ProcessReceipt__c/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SYS_ProcessReceiptsDomain.cls
/**
* @author 		Ramón Prades
* @date 		June 2022
* @group 		System Utilitiers
* @description 	Trigger for Process Receipt
*
* *TEST WITH SYS_ProcessReceiptsTest*
*
*/
public class SYS_ProcessReceiptsDomain extends zflib_TriggerDomainClass {

    public static String buildKey(String namespace, String dedupKey) {
        return namespace?.toUpperCase() + '-' + dedupKey?.toUpperCase();
    }
    
    public SYS_ProcessReceiptsDomain() {
        super();
    }

    public SYS_ProcessReceiptsDomain(List<SYS_ProcessReceipt__c> receipts) {
        super(receipts);
    }

    public override zflib_TriggerDomainClass cast() {
        return (SYS_ProcessReceiptsDomain) this;
    } 

    public override Type getSObjectType() {
        return SYS_ProcessReceiptsDomain.class;
    }

    public override void onBeforeInsert() { 
        for (SYS_ProcessReceipt__c receipt : (List<SYS_ProcessReceipt__c>)this.Records) {
            receipt.Key__c = buildKey(receipt.Namespace__c, receipt.DedupKey__c);
            receipt.Name = (receipt.Name ?? receipt.Namespace__c);
        }
    }
}