force-app/main/default/objects/SYS_ProcessReceipt__c/SYS_ProcessReceipt__c.object-meta.xml
<CustomObject>
    <description>Tracks unique process executions and deduplication keys to ensure idempotent behavior across system operations. Used by administrators and developers for technical maintenance, integration tracking, and duplicate prevention.</description>
    <label>SYS Process Receipt</label>
    <nameField>
        <label>Receipt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SYS Process Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_ProcessReceipt__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Unique field (filled via trigger as Namespace + Dedupkey</description>
    <label>Key</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SYS_ProcessReceiptsSelector.cls
/**
 * @author         Ramón Prades
 * @date           October 2025
 * @layer          System Utilities
 * @description    Access the process receipt
 * 
 * *TEST WITH SYS_ProcessReceiptsTest*
 * 
*/
public class SYS_ProcessReceiptsSelector extends zflib_SObjectSelector_v2 {
    
    public override String getTypeName() {
        return 'SYS_ProcessReceipt__c';
    }

    public SYS_ProcessReceipt__c[] selectByKey(Set<String> keys){
        zflib_QueryFactory query = newQueryFactory();
        query.setCondition('key__c in :keys');
        return  Database.query(query.toSOQL());
    }

}