force-app/main/default/objects/SYS_ProcessReceipt__c/SYS_ProcessReceipt__c.object-meta.xml
<CustomObject>
    <description>Tracks unique process executions and deduplication keys to ensure idempotent behavior across system operations. Used by administrators and developers for technical maintenance, integration tracking, and duplicate prevention.</description>
    <label>SYS Process Receipt</label>
    <nameField>
        <label>Receipt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SYS Process Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_ProcessReceipt__c/fields/DedupKey__c.field-meta.xml
<CustomField>
    <fullName>DedupKey__c</fullName>
    <label>Dedup Key</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_ProcessReceipt__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Unique field (filled via trigger as Namespace + Dedupkey</description>
    <label>Key</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_ProcessReceipt__c/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SYS_ProcessReceiptsTest.cls
@isTest public with sharing class SYS_ProcessReceiptsTest {

    @testSetup static void testSetup() {
        SYS_ProcessReceipt__c r = new SYS_ProcessReceipt__c();
        r.Namespace__c = 'MATERIAL-BANK';
        R.DedupKey__c = 'File1.TXT';
        insert r;
    }

    @isTest static void test001() {
        SYS_ProcessReceipt__c sample = [select Key__c from SYS_ProcessReceipt__c limit 1];
        Assert.areEqual('MATERIAL-BANK-FILE1.TXT', sample.Key__c);
        SYS_ProcessReceipt__c[] receipts = new SYS_ProcessReceiptsSelector().selectByKey(new Set<String>{sample.Key__c});
        Assert.areEqual(sample.Key__c, receipts[0].Key__c, 'Keys should be the same');
    }
}