force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Financial companies in the Porcelanosa Group</description>
    <label>Company</label>
    <nameField>
        <label>CompanyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/BillTo__c.field-meta.xml
<CustomField>
    <fullName>BillTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that will receive the invoice if it is different from the orde&apos;s account</description>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>BillTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>XXX Company</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ordernum__c.field-meta.xml
<CustomField>
    <fullName>Ordernum__c</fullName>
    <label>XXX Ordernum</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/Pedidos_cabeceraSet__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>Pedidos_cabeceraSet</externalName>
    <label>Pedidos_cabeceraSet</label>
    <pluralLabel>Pedidos_cabeceraSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account relation</description>
    <externalDeveloperName>id18</externalDeveloperName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos_cabeceraSet</relationshipLabel>
    <relationshipName>Pedidos_cabeceraSet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/BillTo__c.field-meta.xml
<CustomField>
    <fullName>BillTo__c</fullName>
    <description>BillTo</description>
    <externalDeveloperName>BillTo</externalDeveloperName>
    <label>BillTo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Comis2__c.field-meta.xml
<CustomField>
    <fullName>Comis2__c</fullName>
    <description>Comis2</description>
    <externalDeveloperName>Comis2</externalDeveloperName>
    <label>Comis2</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>Customer</description>
    <externalDeveloperName>Customer</externalDeveloperName>
    <label>Customer</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Dcurr__c.field-meta.xml
<CustomField>
    <fullName>Dcurr__c</fullName>
    <description>Dcurr</description>
    <externalDeveloperName>Dcurr</externalDeveloperName>
    <label>Dcurr</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Ddate__c.field-meta.xml
<CustomField>
    <fullName>Ddate__c</fullName>
    <description>Ddate</description>
    <externalDeveloperName>Ddate</externalDeveloperName>
    <label>Ddate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Doc__c.field-meta.xml
<CustomField>
    <fullName>Doc__c</fullName>
    <description>Doc</description>
    <externalDeveloperName>Doc</externalDeveloperName>
    <label>Doc</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Dtotal__c.field-meta.xml
<CustomField>
    <fullName>Dtotal__c</fullName>
    <description>Dtotal</description>
    <externalDeveloperName>Dtotal</externalDeveloperName>
    <label>Dtotal</label>
    <precision>14</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Exratet__c.field-meta.xml
<CustomField>
    <fullName>Exratet__c</fullName>
    <description>Exratet</description>
    <externalDeveloperName>Exratet</externalDeveloperName>
    <label>Exratet</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Gtax__c.field-meta.xml
<CustomField>
    <fullName>Gtax__c</fullName>
    <description>Gtax</description>
    <externalDeveloperName>Gtax</externalDeveloperName>
    <label>Gtax</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/id18__c.field-meta.xml
<CustomField>
    <fullName>id18__c</fullName>
    <description>id18</description>
    <externalDeveloperName>id18</externalDeveloperName>
    <label>id18</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Lnet__c.field-meta.xml
<CustomField>
    <fullName>Lnet__c</fullName>
    <description>Lnet</description>
    <externalDeveloperName>Lnet</externalDeveloperName>
    <label>Lnet</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Ltotal__c.field-meta.xml
<CustomField>
    <fullName>Ltotal__c</fullName>
    <description>Ltotal</description>
    <externalDeveloperName>Ltotal</externalDeveloperName>
    <label>Ltotal</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/OpenF__c.field-meta.xml
<CustomField>
    <fullName>OpenF__c</fullName>
    <description>OpenF</description>
    <externalDeveloperName>OpenF</externalDeveloperName>
    <label>OpenF</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Paid__c.field-meta.xml
<CustomField>
    <fullName>Paid__c</fullName>
    <description>Paid</description>
    <externalDeveloperName>Paid</externalDeveloperName>
    <label>Paid</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/PaisDestino__c.field-meta.xml
<CustomField>
    <fullName>PaisDestino__c</fullName>
    <description>PaisDestino</description>
    <externalDeveloperName>PaisDestino</externalDeveloperName>
    <label>PaisDestino</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Probld__c.field-meta.xml
<CustomField>
    <fullName>Probld__c</fullName>
    <description>Probld</description>
    <externalDeveloperName>Probld</externalDeveloperName>
    <label>Probld</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Repo1__c.field-meta.xml
<CustomField>
    <fullName>Repo1__c</fullName>
    <description>Repo1</description>
    <externalDeveloperName>Repo1</externalDeveloperName>
    <label>Repo1</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Salesoffic__c.field-meta.xml
<CustomField>
    <fullName>Salesoffic__c</fullName>
    <description>Salesoffic</description>
    <externalDeveloperName>Salesoffic</externalDeveloperName>
    <label>Salesoffic</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <description>status</description>
    <externalDeveloperName>status</externalDeveloperName>
    <label>status</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Trvog__c.field-meta.xml
<CustomField>
    <fullName>Trvog__c</fullName>
    <description>Trvog</description>
    <externalDeveloperName>Trvog</externalDeveloperName>
    <label>Trvog</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Vbtyp__c.field-meta.xml
<CustomField>
    <fullName>Vbtyp__c</fullName>
    <description>Vbtyp</description>
    <externalDeveloperName>Vbtyp</externalDeveloperName>
    <label>Vbtyp</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SAPOrdersSelector.cls
/**
* @author 		Ivan Losilla
* @date 		July 2022
* @group 		Sap Orders
* @description 	sap orders selector class
*/
public class SAPOrdersSelector extends zflib_SObjectSelector  {
    public Schema.SObjectType getSObjectType(){
        return Pedidos_cabeceraSet__x.sObjectType;
    }

    public List<Pedidos_cabeceraSet__x> selectById(Set<Id> recordIds){
        return (List<Pedidos_cabeceraSet__x>) selectSObjectsById(recordIds);
    }

    public Pedidos_cabeceraSet__x selectById(Id recordId){
        List<Pedidos_cabeceraSet__x> listSapOrders = (List<Pedidos_cabeceraSet__x>) selectSObjectsById(new Set<Id>{recordId});
        if (listSapOrders.size() == 1) {
            return listSapOrders[0];
        }
        return null;
    }

    public String selectSapSyncString(){
        zflib_QueryFactory query = newQueryFactory();
        query.setCondition('OrderDate__c = LAST_N_DAYS:1');
        return query.toSOQL();
    }
   
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {

            // Salesforce Data
            Pedidos_cabeceraSet__x.Id,
            Pedidos_cabeceraSet__x.Account__c,
            Pedidos_cabeceraSet__x.id18__c,
            Pedidos_cabeceraSet__x.Sfopportunity__c,
            Pedidos_cabeceraSet__x.CurrencyIsoCode,

            // Date Fields
            Pedidos_cabeceraSet__x.Orderdate__c,
            Pedidos_cabeceraSet__x.Ddate__c,
            Pedidos_cabeceraSet__x.Erdat__c,
            
            // Order Data
            Pedidos_cabeceraSet__x.ExternalId,
            Pedidos_cabeceraSet__x.BillTo__c,
            Pedidos_cabeceraSet__x.Comis2__c,
            Pedidos_cabeceraSet__x.Comis__c,
            Pedidos_cabeceraSet__x.Company__c,
            Pedidos_cabeceraSet__x.Credit__c,
            Pedidos_cabeceraSet__x.Customer__c,
            Pedidos_cabeceraSet__x.DisplayUrl,
            Pedidos_cabeceraSet__x.Distchannel__c,
            Pedidos_cabeceraSet__x.Division__c,
            Pedidos_cabeceraSet__x.Doc__c,
            Pedidos_cabeceraSet__x.Exratet__c,
            Pedidos_cabeceraSet__x.Erzet__c,
            Pedidos_cabeceraSet__x.Exrate__c,
            Pedidos_cabeceraSet__x.OpenF__c,
            Pedidos_cabeceraSet__x.Ordernum__c,
            Pedidos_cabeceraSet__x.Ordertype__c,
            Pedidos_cabeceraSet__x.Paid__c,
            Pedidos_cabeceraSet__x.PaisDestino__c,
            Pedidos_cabeceraSet__x.Probld__c,
            Pedidos_cabeceraSet__x.Refer__c,
            Pedidos_cabeceraSet__x.Repo1__c,
            Pedidos_cabeceraSet__x.Repo2__c,
            Pedidos_cabeceraSet__x.Salesoffic__c,
            Pedidos_cabeceraSet__x.Salesorg__c,
            Pedidos_cabeceraSet__x.status__c,
            Pedidos_cabeceraSet__x.Trvog__c,
            Pedidos_cabeceraSet__x.Vbtyp__c,

            // Cost fields
            Pedidos_cabeceraSet__x.Dcurr__c,
            Pedidos_cabeceraSet__x.Dnet__c,
            Pedidos_cabeceraSet__x.Dtax__c,
            Pedidos_cabeceraSet__x.Dtotal__c,
            Pedidos_cabeceraSet__x.Gcurr__c,
            Pedidos_cabeceraSet__x.Gnet__c,
            Pedidos_cabeceraSet__x.Gtax__c,
            Pedidos_cabeceraSet__x.Gtotal__c,
            Pedidos_cabeceraSet__x.Lcurr__c,
            Pedidos_cabeceraSet__x.Lnet__c,
            Pedidos_cabeceraSet__x.Ltax__c,
            Pedidos_cabeceraSet__x.Ltotal__c

        };
    }
}