force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Financial companies in the Porcelanosa Group</description>
    <label>Company</label>
    <nameField>
        <label>CompanyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <description>Código identificador de sociedad de referencia</description>
    <externalId>true</externalId>
    <label>CompanyCode</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Código de País</description>
    <inlineHelpText>Incluya el código del pais al que pertenece la compañía o sociedad de referencia</inlineHelpText>
    <label>Country</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_relations__c/Master_relations__c.object-meta.xml
<CustomObject>
    <label>Master relations</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Master relations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_relations__c/fields/DistributionChannel_code__c.field-meta.xml
<CustomField>
    <fullName>DistributionChannel_code__c</fullName>
    <label>DistributionChannel code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_relations__c/fields/DistributionChannel_name__c.field-meta.xml
<CustomField>
    <fullName>DistributionChannel_name__c</fullName>
    <label>DistributionChannel name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_relations__c/fields/SalesOffice_code__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice_code__c</fullName>
    <label>SalesOffice code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_relations__c/fields/SalesOffice_name__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice_name__c</fullName>
    <label>SalesOffice name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_relations__c/fields/SalesOrg_code__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg_code__c</fullName>
    <label>SalesOrg code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_relations__c/fields/SalesOrg_name__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg_name__c</fullName>
    <label>SalesOrg name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_relations__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/PostCodeObjects__c.object-meta.xml
<CustomObject>
    <description>Object created to set an object related to a Postal Code</description>
    <label>Post Code Object</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Serial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Code Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PostCodeObjects__c/fields/country__c.field-meta.xml
<CustomField>
    <fullName>country__c</fullName>
    <label>country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/objectId__c.field-meta.xml
<CustomField>
    <fullName>objectId__c</fullName>
    <description>Salesforce Id of the object related</description>
    <label>objectId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/objectType__c.field-meta.xml
<CustomField>
    <fullName>objectType__c</fullName>
    <label>objectType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INSTALLER</fullName>
                <default>true</default>
                <label>INSTALLER</label>
            </value>
            <value>
                <fullName>SALES_ORG</fullName>
                <label>SALES ORG</label>
            </value>
            <value>
                <fullName>SALES_OFFICE</fullName>
                <label>SALES OFFICE</label>
            </value>
            <value>
                <fullName>OWNER_USA</fullName>
                <label>OWNER USA</label>
            </value>
            <value>
                <fullName>MBK-EUR</fullName>
                <label>MATERIAL BANK (EUR)</label>
            </value>
            <value>
                <fullName>PORSAMARKET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/postCode__c.field-meta.xml
<CustomField>
    <fullName>postCode__c</fullName>
    <label>postCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/SALES_OFFICE__c.object-meta.xml
<CustomObject>
    <description>Entidad custom que contiene el maestro de relaciones para transformar el código de la oficina de ventas por el nombre.</description>
    <label>Sales Office</label>
    <nameField>
        <label>Nombre de SALES_OFFICE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_OFFICE__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Código de sociedad de referencia. Código COMPANY</description>
    <label>Company</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <description>Country ISO Code</description>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <description>Postcode</description>
    <label>Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>Código de la oficina de ventas</description>
    <externalId>true</externalId>
    <label>SalesOffice</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Org</label>
    <referenceTo>Sales_Org__c</referenceTo>
    <relationshipLabel>Sales Office</relationshipLabel>
    <relationshipName>Sales_Office</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <description>Code of the Sales Org</description>
    <externalId>true</externalId>
    <label>Sales Org</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <externalId>true</externalId>
    <label>Sap Id</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/TaxPercent__c.field-meta.xml
<CustomField>
    <fullName>TaxPercent__c</fullName>
    <label>Tax/VAT %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/DataFactoryOrganization.cls
/**
 * @author          Ramón Prades
 * @date            November 2020
 * @description     Creates organization structures for testing
 * @group           Data Factories
 */
@SuppressWarnings('PMD.ExcessiveParameterList')
public without sharing class DataFactoryOrganization {

    public static void createData() {        
        if (!Test.isRunningTest()) {
            return;
        }

        List<Company__c> cs = [select Id from Company__c];
        if (cs.size() > 0) {
            return;
        }
        List<Company__c> companies = new  List<Company__c>();
        companies.add(createCompany(OrganizationCommons.SOC_EUROCERAMIQUE, 'EUROCERAMIQUE SARL','FR'));
        companies.add(createCompany(OrganizationCommons.SOC_PIDF, 'PORCELANOSA PARIS IDF','FR'));
        companies.add(createCompany(OrganizationCommons.SOC_SOUTH_EAST, 'PORCELANOSA SOUTHEAST','GB'));
        companies.add(createCompany(OrganizationCommons.SOC_NORTH_WEST, 'PORCELANOSA NORTHWEST','GB'));
        companies.add(createCompany('610', 'PORCELANOSA USA','US'));
    
        List<Sales_Org__c> orgs = new List<Sales_Org__c>();
        orgs.add(createOrg(OrganizationCommons.ORG_AZURCERAMIQUE, 'Azurceramique', 'FR', OrganizationCommons.SOC_EUROCERAMIQUE));
        orgs.add(createOrg(OrganizationCommons.ORG_LORCERAM, 'Lorceram', 'FR', OrganizationCommons.SOC_EUROCERAMIQUE));
        orgs.add(createOrg(OrganizationCommons.ORG_EUROCERAMIQUE, 'Euroceramique', 'FR', OrganizationCommons.SOC_EUROCERAMIQUE));
        orgs.add(createOrg(OrganizationCommons.ORG_PIDF, 'Porce. Paris IDF', 'FR', OrganizationCommons.SOC_PIDF));
        orgs.add(createOrg(OrganizationCommons.ORG_SOUTH_EAST, 'Porce. South East', 'GB', OrganizationCommons.SOC_SOUTH_EAST));
        orgs.add(createOrg(OrganizationCommons.ORG_NORTH_WEST, 'Porce. North West', 'GB', OrganizationCommons.SOC_NORTH_WEST));
        orgs.add(createOrg(OrganizationCommons.ORG_NEW_YORK, 'PORCELANOSA NEW YORK', 'US', '610'));


        List<Master_relations__c> relations = new List<Master_relations__c>();
        relations.add(createRelation(OrganizationCommons.ORG_AZURCERAMIQUE, 'Azurceramique', '60', 'Retail', '3015', 'Office Azur'));
        relations.add(createRelation(OrganizationCommons.ORG_PIDF, 'Paris', '60', 'Retail', '3035', 'Office paris'));
        relations.add(createRelation(OrganizationCommons.ORG_SOUTH_EAST, 'Londres', '60', 'Retail', '2552', 'Office 2552'));
        relations.add(createRelation(OrganizationCommons.ORG_SOUTH_EAST, 'Londres', '60', 'Retail', '2558', 'Office 2558'));
        relations.add(createRelation(OrganizationCommons.ORG_NORTH_WEST, 'Warrington', '60', 'Retail', '2541', 'Office 2541'));
        relations.add(createRelation(OrganizationCommons.ORG_AZURCERAMIQUE, 'Azurceramique', '70', 'Trade', '3015', 'Office Azur'));
        relations.add(createRelation(OrganizationCommons.ORG_PIDF, 'Paris', '70', 'Trade', '3035', 'Office paris'));
        relations.add(createRelation(OrganizationCommons.ORG_SOUTH_EAST, 'Londres', '70', 'Trade', '2552', 'Office 2552'));
        relations.add(createRelation(OrganizationCommons.ORG_SOUTH_EAST, 'Londres', '70', 'Retail', '2558', 'Office 2558'));
        relations.add(createRelation(OrganizationCommons.ORG_NORTH_WEST, 'Warrington', '70', 'Trade', '2541', 'Office 2541'));
        relations.add(createRelation(OrganizationCommons.ORG_NEW_YORK, 'Ramsey', '70', 'Trade', '6001', 'Office 6001'));
        relations.add(createRelation(OrganizationCommons.ORG_NEW_YORK, 'Manhattan', '70', 'Trade', '6002', 'Office 6002'));
        relations.add(createRelation(OrganizationCommons.ORG_NEW_YORK, 'Paramus', '70', 'Trade', '6003', 'Office 6003'));

        PostCodeObjects__c pc = new PostCodeObjects__c();
        pc.objectId__c = '2558';
        pc.postCode__c = 'W';
        pc.objectType__c = 'SALES_OFFICE';
        pc.country__c = 'GB';
        insert pc;

        insert companies;
        insert orgs;
        insert relations;

        List<Sales_Org__c> salesOrgs = [Select Id, SalesOrg__c from Sales_Org__c];
        Integer i = 1;
        List<Sales_Office__c> offices = new List<Sales_Office__c>();
        for (Sales_Org__c salesOrg : salesOrgs) {
            offices.add(createSalesOffice('303' + i, 'Office Paris ' + i, 'FR', salesOrg.SalesOrg__c, salesOrg.Id));
            offices.add(createSalesOffice('503' + i, 'Office London ' + i, 'GB', salesOrg.SalesOrg__c, salesOrg.Id));
            offices.add(createSalesOffice('255' + i, 'Office New York ' + i, 'US', salesOrg.SalesOrg__c, salesOrg.Id));
            i++;
        }

        insert offices;

    } // createData


    private static Company__c createCompany(String code, String name, String country) {
        return new Company__c(CompanyCode__c = code, Name = name, Country__c = country);
    } // createCompany

    private static Sales_Org__c createOrg(String code, String name, String country, String company) {
        String curr = 'EUR';
        Decimal tax = 0;
        if (country == 'US') {
            curr = 'USD';
        } else if (country == 'GB') {
            curr = 'GBP';
            tax = 20;
        }
        return new Sales_Org__c(SalesOrg__c = code, Name = name, CountryCode__c = country, Company__c = company, SAP_Id__c = code, CurrencyIsoCode = curr, TaxPercent__c = tax);
    } // createCompany

    
    private static Sales_Office__c createSalesOffice(String code, String name, String countryCode, String company, String salesOrgId) {
        return new Sales_Office__c(SalesOffice__c = code, Name = name, CountryCode__c = countryCode, Company__c = company, SalesOrg__c = salesOrgId);
    } // createSalesOffice
    

    private static Master_relations__c createRelation(String org, String name, String channel, String channelName, String office, String officeName) {
        return new Master_relations__c(
            SalesOrg_name__c =name , SalesOrg_code__c = org, 
            DistributionChannel_name__c = channelName, DistributionChannel_code__c = channel, 
            SalesOffice_code__c = office, SalesOffice_name__c = officeName,
             Sector__c = '10');
    }

} // class