force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Financial companies in the Porcelanosa Group</description>
    <label>Company</label>
    <nameField>
        <label>CompanyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/Autopick__c.field-meta.xml
<CustomField>
    <fullName>Autopick__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use autopick by default</description>
    <label>Autopick</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/IsBlocked__c.field-meta.xml
<CustomField>
    <fullName>IsBlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The sales org has stopped business. It should not be used in new transactions</description>
    <label>Is Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <description>Code of the Sales Org</description>
    <externalId>true</externalId>
    <label>Sales Org</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/SamplesCutoff__c.field-meta.xml
<CustomField>
    <fullName>SamplesCutoff__c</fullName>
    <description>Cut-off time to deliver samples in the mini delivery days</description>
    <label>Samples Cut-off TIme</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/SamplesMinDays__c.field-meta.xml
<CustomField>
    <fullName>SamplesMinDays__c</fullName>
    <description>Minimum delivery days for samples</description>
    <label>Samples Min Delivery Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <description>Shorter option of the Sales Org Name</description>
    <label>Short Name</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/TaxPercent__c.field-meta.xml
<CustomField>
    <fullName>TaxPercent__c</fullName>
    <label>Tax/VAT %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TImeZones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TImeZones.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Africa/Abidjan</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Accra</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Addis_Ababa</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Algiers</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Asmera</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Bamako</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Bangui</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Banjul</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Bissau</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Blantyre</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Brazzaville</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Bujumbura</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Cairo</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Casablanca</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Ceuta</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Conakry</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Dakar</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Dar_es_Salaam</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Dijibouti</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Douala</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/El_Aaiun</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Freetown</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Gaborone</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Harare</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Johannesburg</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Juba</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Kampala</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Khartoum</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Kigali</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Kinshasa</fullName>
    </customValue>
    <customValue>
        <fullName>America/Los_Angeles</fullName>
    </customValue>
    <masterLabel>TIme Zones</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TaxCommonsTest.cls
@isTest
private class TaxCommonsTest {
    
    @isTest
    private static void testSelectBySAPId() {
        System.runAs(new User(Id = UserInfo.getUserId())) {
            Test.startTest();
            Sales_Org__c org = new Sales_Org__c(
                Name = 'SalesOrg',
                Company__c = '502',
                SalesOrg__c = '502',
                CountryCode__c = 'GB',
                ShortName__c = 'ShortName',
                SamplesCutoff__c = Time.newInstance(12, 0, 0, 0),
                SamplesMinDays__c = 2,
                TimeZone__c = 'America/Los_Angeles',
                Autopick__c = true,
                IsBlocked__c = false,
                TaxPercent__c = 10.0
            );
            insert org;

            Decimal taxPercent = TaxCommons.getSalesOrgTax(org.SalesOrg__c);
            Test.stopTest();

            System.assertEquals(10.0, taxPercent, 'The tax percent should be the same as the inserted SalesOrg record');
        }
    }

    @isTest
    static void testIsValidSiret() {
        // Test con un SIRET válido
        String validSiret = '34114111700083'; // Asegúrate de usar un SIRET válido para tu lógica
        Boolean isValid = TaxCommons.isValidSiret(validSiret);
        System.assert(isValid, 'El SIRET debería ser válido');

        // Test con un SIRET inválido
        String invalidSiret = '34114111700085'; // Asegúrate de usar un SIRET inválido para tu lógica
        isValid = TaxCommons.isValidSiret(invalidSiret);
        System.assert(!isValid, 'El SIRET debería ser inválido');

        // Test con un SIRET nulo
        String nullSiret = null;
        isValid = TaxCommons.isValidSiret(nullSiret);
        System.assert(!isValid, 'El SIRET nulo debería ser inválido');

        // Test con un SIRET de longitud incorrecta
        String shortSiret = '12345';
        isValid = TaxCommons.isValidSiret(shortSiret);
        System.assert(!isValid, 'El SIRET de longitud incorrecta debería ser inválido');
    }

    @isTest
    static void testGetSirenFromSiret() {
        // Test con un SIRET válido
        String validSiret = '34114111700083';
        String expectedSiren = '341141117';
        String siren = TaxCommons.getSirenFromSiret(validSiret);
        System.assertEquals(expectedSiren, siren, 'El SIREN obtenido debería ser correcto');

        // Test con un SIRET nulo
        try {
            TaxCommons.getSirenFromSiret(null);
            System.assert(false, 'Debería lanzar una excepción para SIRET nulo');
        } catch (IllegalArgumentException e) {
            System.assert(true, 'Excepción capturada correctamente para SIRET nulo');
        }

        // Test con un SIRET de longitud incorrecta
        try {
            TaxCommons.getSirenFromSiret('12345');
            System.assert(false, 'Debería lanzar una excepción para SIRET de longitud incorrecta');
        } catch (IllegalArgumentException e) {
            System.assert(true, 'Excepción capturada correctamente para SIRET de longitud incorrecta');
        }
    }

    @isTest
    static void testValidUKVAT() {
        String validVAT = '287910661';
        Boolean validated = TaxCommons.isValidUKVAT(validVAT);
        System.assertEquals(true, validated, 'El VAT debería ser correcto');
        
        validVAT = null;
        validated = TaxCommons.isValidUKVAT(validVAT);
        System.assertEquals(false, validated, 'El VAT debería ser devolver incorrecto');

        validVAT = '28791661';
        validated = TaxCommons.isValidUKVAT(validVAT);
        System.assertEquals(false, validated, 'El VAT debería ser incorrecto');

        validVAT = 'DDR';
        validated = TaxCommons.isValidUKVAT(validVAT);
        System.assertEquals(false, validated, 'El VAT debería ser incorrecto');

        validVAT = 'GB287910661';
        validated = TaxCommons.isValidUKVAT(validVAT);
        System.assertEquals(true, validated, 'El VAT debería ser correcto');
    }

    @isTest
    static void testValidCRN() {
        String crn = '11070210';
        Boolean validated = TaxCommons.isValidCRN(crn);
        System.assertEquals(true, validated, 'El CRN debería ser correcto');

        crn = null;
        validated = TaxCommons.isValidCRN(crn);
        System.assertEquals(false, validated, 'El CRN debería ser devolver incorrecto');

        crn = '110700';
        validated = TaxCommons.isValidCRN(crn);
        System.assertEquals(false, validated, 'El CRN debería ser incorrecto');

        crn = '11070210443';
        validated = TaxCommons.isValidCRN(crn);
        System.assertEquals(false, validated, 'El CRN debería ser incorrecto');

        crn = 'GB110702';
        validated = TaxCommons.isValidCRN(crn);
        System.assertEquals(true, validated, 'El CRN debería ser correcto');
    }
}