force-app/main/default/objects/PaymentRequest__c/PaymentRequest__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000000}</displayFormat>
        <label>Payment Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentRequest__c/fields/CartId__c.field-meta.xml
<CustomField>
    <fullName>CartId__c</fullName>
    <label>Cart</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Token</description>
    <label>Token</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentRequestsSelector.cls
/**
 * @author         Ramón Prades
 * @date           September 2023
 * @group          Orders
 * @description    Orders Selector 
*/
public class PaymentRequestsSelector extends zflib_SObjectSelector_v2 {
    
    public override String getTypeName() {
        return 'PaymentRequest__c';
    }

    public PaymentRequest__c selectByCartId(Id cartId){
        zflib_QueryFactory query = newQueryFactory();
        query.setCondition('CartId__c = :cartId');
        PaymentRequest__c[] results = (List<PaymentRequest__c>) Database.query(query.toSOQL());
        if (results.isEmpty()) {
            return null;
        }
        return results[0];
     }

    public PaymentRequest__c selectByToken(String token){
        zflib_QueryFactory query = newQueryFactory();
        query.setCondition('Token__c = :token');
        PaymentRequest__c[] results = (List<PaymentRequest__c>) Database.query(query.toSOQL());
        if (results.isEmpty()) {
            return null;
        }
        return results[0];
     }

}