force-app/main/default/objects/Displays_Marketing_Material__c/Displays_Marketing_Material__c.object-meta.xml
<CustomObject>
    <label>Displays &amp; Marketing Material</label>
    <nameField>
        <label>Displays &amp; Marketing Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Displays &amp; Marketing Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Displays_Marketing_Material__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Settings</fullName>
            </value>
            <value>
                <fullName>Dakkar Panel Stand</fullName>
            </value>
            <value>
                <fullName>Highker Stand</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Krion countertop</fullName>
            </value>
            <value>
                <fullName>Krion tower</fullName>
            </value>
            <value>
                <fullName>Starwood Zone</fullName>
            </value>
            <value>
                <fullName>Xlight tower</fullName>
            </value>
            <value>
                <fullName>Xtone Countertop</fullName>
            </value>
            <value>
                <fullName>Xtone tower</fullName>
            </value>
            <value>
                <fullName>Cuna parker</fullName>
            </value>
            <value>
                <fullName>Table Display Rack XTONE</fullName>
            </value>
            <value>
                <fullName>Boxtone</fullName>
                <label>BOXTONE</label>
            </value>
            <value>
                <fullName>Exp. Tower Xtone 30x60</fullName>
            </value>
            <value>
                <fullName>Ex. Tower Xtone 25x28</fullName>
            </value>
            <value>
                <fullName>Binder</fullName>
            </value>
            <value>
                <fullName>Table Display Rack Altissima</fullName>
            </value>
            <value>
                <fullName>Countertop Altissima</fullName>
            </value>
            <value>
                <fullName>Krion Box</fullName>
            </value>
            <value>
                <fullName>Xtone Setting</fullName>
            </value>
            <value>
                <fullName>Altissima Setting</fullName>
            </value>
            <value>
                <fullName>Xtone Pantonier</fullName>
            </value>
            <value>
                <fullName>Xtone Catalogue</fullName>
            </value>
            <value>
                <fullName>Sample classifier Xtone 10x20</fullName>
            </value>
            <value>
                <fullName>Xtone Packtool</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Displays_TestDataFactory.cls
@isTest
public class Displays_TestDataFactory {
    public static List<Displays_Marketing_Material__c> createDisplays(Integer numRecords, List<Map<String, Object>> fieldsToAdd){
        
        List<Displays_Marketing_Material__c> displaysList = new List<Displays_Marketing_Material__c>();
        
        for(Integer i=0; i<numRecords; i++){
            
            Displays_Marketing_Material__c display = new Displays_Marketing_Material__c(Name = 'TestDisplay' + i, Type__c = 'Kitchen');
            
            for(String fieldName: fieldsToAdd[i].keySet()){
                
                display.put(fieldName, fieldsToAdd[i].get(fieldName));
                
            }
            
            displaysList.add(display);
            
        }
        
        return displaysList;
        
    }
}