force-app/main/default/objects/OppFacade__c/OppFacade__c.object-meta.xml
<CustomObject>
    <description>Additional information for facade opportunities. Originally designed for the US but might be extended in the future.</description>
    <label>Opportunity Facade</label>
    <nameField>
        <label>Facade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Facades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppFacade__c/fields/CostEstimateMethod__c.field-meta.xml
<CustomField>
    <fullName>CostEstimateMethod__c</fullName>
    <label>Cost Estimate Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SMALL-PROJECT</fullName>
                <default>true</default>
                <label>SMALL-PROJECT</label>
            </value>
            <value>
                <fullName>PROJECT-SPECIFIC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppFacade__c/fields/DesignPhase__c.field-meta.xml
<CustomField>
    <fullName>DesignPhase__c</fullName>
    <label>Design Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRE-DESIGN</fullName>
                <default>true</default>
                <label>PRE DESIGN</label>
            </value>
            <value>
                <fullName>SCHEMATICS-DESIGN</fullName>
                <label>SCHEMATICS DESIGN</label>
            </value>
            <value>
                <fullName>DESIGN-DEVELOPMENT</fullName>
                <label>DESIGN DEVELOPMENT</label>
            </value>
            <value>
                <fullName>CONSTRUCTIONS DRAWINGS&amp;SPECIFICATION</fullName>
                <label>CONSTRUCTION DRAWINGS</label>
            </value>
            <value>
                <fullName>BID-GC-LEVEL</fullName>
                <label>BID GC LEVEL</label>
            </value>
            <value>
                <fullName>BID-INSTALLER-LEVEL</fullName>
                <label>BID INSTALLER LEVEL</label>
            </value>
            <value>
                <fullName>CONSTRUCTION-DOCUMENTS</fullName>
                <isActive>false</isActive>
                <label>CONSTRUCTION-DOCUMENTS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppFacade__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facade Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Facades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OppFacade__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Facades</relationshipLabel>
    <relationshipName>Opportunity_Facades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppFacade__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Sales Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRODUCT-REVIEW</fullName>
                <default>true</default>
                <label>1-PRODUCT REVIEW</label>
            </value>
            <value>
                <fullName>TECHNICAL-ASSISTANCE</fullName>
                <label>2-TECHNICAL ASSISTANCE</label>
            </value>
            <value>
                <fullName>DESIGN-ASSIST</fullName>
                <label>3-DESIGN ASSIST / COST ESTIMATE</label>
            </value>
            <value>
                <fullName>WON (WORK IN PROGRESS)</fullName>
                <label>4-WON (WORK IN PROGRESS)</label>
            </value>
            <value>
                <fullName>CLOSED</fullName>
                <label>5-CLOSED (FULLY INVOICED)</label>
            </value>
            <value>
                <fullName>LOST</fullName>
                <label>6-LOST</label>
            </value>
            <value>
                <fullName>CLOSED-WON</fullName>
                <isActive>false</isActive>
                <label>CLOSED-WON</label>
            </value>
            <value>
                <fullName>INSTALLATION</fullName>
                <isActive>false</isActive>
                <label>INSTALLATION</label>
            </value>
            <value>
                <fullName>MATERIAL-QUOTE</fullName>
                <isActive>false</isActive>
                <label>MATERIAL QUOTE</label>
            </value>
            <value>
                <fullName>SOLD/SHIPPING</fullName>
                <isActive>false</isActive>
                <label>SOLD/SHIPPING</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataFactoryOppFacade.cls
/**
* @author 		Ramón Prades
* @date 		February 2022
* @group 		Data factories
* @description 	Opp Facade
*/
public  class DataFactoryOppFacade {

    public static Boolean CreateAttachment = true;

    public static OppFacade__c createFacade() {
        if (!Test.isRunningTest()) {
            return null;
        }

        // Opportunity
        testUtils.enableTriggers();
        Opportunity opp = DataFactoryOpportunity.createRetailOpportunities(1, 1)[0];
    
        // Facade
        OppFacade__c k = new OppFacade__c();
        k.Opportunity__c = opp.Id;
        k.Stage__c = TestUtils.getPicklistOption(OppFacade__c.Stage__c);
        k.DesignPhase__c = TestUtils.getPicklistOption(OppFacade__c.DesignPhase__c);
        k.Manager__c = UserInfo.getUserId();
        k.CostEstimateMethod__c = TestUtils.getPicklistOption(OppFacade__c.CostEstimateMethod__c);
        insert k;
    
        // Attachment
        if (DataFactoryOppFacade.CreateAttachment) {
            ContentVersion contentVersion = new ContentVersion(
                Title          = 'a picture',
                PathOnClient   = 'Pic.jpg',
                VersionData    = Blob.valueOf('Test Content'),
                IsMajorVersion = true);
            insert contentVersion;
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.LinkedEntityId = k.Id;
            cdl.ContentDocumentId = documents[0].Id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers';
            insert cdl;    
        }

        return k;
    } // createFacade
}