force-app/main/default/objects/OppFacade__c/OppFacade__c.object-meta.xml
<CustomObject>
    <description>Additional information for facade opportunities. Originally designed for the US but might be extended in the future.</description>
    <label>Opportunity Facade</label>
    <nameField>
        <label>Facade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Facades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppFacade__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Facades</relationshipLabel>
    <relationshipName>Opportunity_Facades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OppFacadeService.cls
/**
* @author 		Ramón Prades
* @date 		February 2022
* @group 		Opportunities
* @description 	Service class for OppFacade
*/
public class OppFacadeService {

    /**
     * Deletes a facade is no files have been attached
     */
    public static Boolean deleteFacade(Id id) {
        Boolean success = false;
        ContentVersion[] attachments = AttachmentUtils.getSObjectAttachments(id);        
        if (attachments.size() == 0) {
            OppFacade__c facade = [select Id, Opportunity__c from OppFacade__c where Id = :id limit 1];
            Opportunity opp = [select Id from Opportunity where Id = :facade.Opportunity__c limit 1];
            if (SystemSettings.CPNotificationsEnabled) {
                OppFacadeMailer mailer = new OppFacadeMailer(id);
                mailer.sendDeletedFacadeMail();
            }
            delete opp;   
            Logger.setScenario('OPP.FACADE');
            Logger.info('La fachada con id ' + id + ' ha sido borrada por no tener ficheros adjuntos');
            Logger.saveLog();
            success = true;
        } 
        return success;
    } // deleteFacade
} // class