force-app/main/default/objects/InstallationRequest__c/InstallationRequest__c.object-meta.xml
<CustomObject>
    <description>Class to store and follow the installation request of our products. This is a service certain showrooms offer through a list of authorised installers.</description>
    <label>Installation Request</label>
    <nameField>
        <label>Installation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationRequest__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CurrencyCodes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/Installation_Cost__c.field-meta.xml
<CustomField>
    <fullName>Installation_Cost__c</fullName>
    <label>Installation Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/InstallerAccount__c.field-meta.xml
<CustomField>
    <fullName>InstallerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installation Requests</relationshipLabel>
    <relationshipName>Installation_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Opportunity this installation is for</description>
    <inlineHelpText>Please enter the opportunity this installation is for</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Installation Requests</relationshipLabel>
    <relationshipName>Installation_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <defaultValue>&quot;New Request&quot;</defaultValue>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InstallationStates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/SurveyDate__c.field-meta.xml
<CustomField>
    <fullName>SurveyDate__c</fullName>
    <inlineHelpText>Please enter the date agreed with the customer to visit the installation location</inlineHelpText>
    <label>Site Survey Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/CurrencyCodes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>DKK</fullName>
    </customValue>
    <customValue>
        <fullName>ZAR</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>SEK</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <masterLabel>Currency Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/InstallationStates.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Request</fullName>
        <default>true</default>
        <label>New Request</label>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>3D Design</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Estimation</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Won</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>States of Installation Requests</description>
    <masterLabel>Installation States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FlashCardInsRequestController.cls
/**
* @author 	Ramón Prades
* @date 	August 2020
*
* @group 	Installations
* @group-content ../../ApexDocContent/Installations.htm
*
* @description Controller for the Installation Request Flash Card component
*/
public class FlashCardInsRequestController {
     
    @AuraEnabled 
    public static List<sObject> getRequest(Id opportunityId) {
        if (!InstallationUtil.hasInstallations()) {
            throw new NotEnabledException('Installations not enabled');
        }
        List<sObject> result = new List<sObject>();
        String fields = 'Id, State__c, Name, Description__c, Installation_Cost__c, Currency__c, SurveyDate__c, Opportunity__c, InstallerAccount__c';
        String sql = 'select ' + fields + ' from InstallationRequest__c where Opportunity__c = :opportunityId';
        List<InstallationRequest__c> requests = Database.query(sql);
        if (requests.size() > 0) {
            result.add(requests[0]);            
            Account installer = [select Id, Name from Account where Id = :requests[0].InstallerAccount__c][0];
            result.add(installer);
        }                   
        return result;        
    } // getRequest    
    
} // class