force-app/main/default/objects/RegionalSettings__mdt/RegionalSettings__mdt.object-meta.xml
<CustomObject>
    <description>Region configuration</description>
    <label>Regional Settings</label>
    <pluralLabel>Regional Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/RegionalSettings__mdt/fields/InstallationsEnabled__c.field-meta.xml
<CustomField>
    <fullName>InstallationsEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enables intallation requests for the region</description>
    <label>Installations Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegionalSettings__mdt/fields/SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganization__c</fullName>
    <description>Sales organization code</description>
    <label>Sales Organization</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RegionalSettingsTest.cls
/**
  @author Ramón Prades
 * @date August 2020
 *
 * @group Settings
 * @group-content ../../ApexDocContent/Settings.htm
 *
 * @description Test class for the App configuration per region
 */

@isTest public class RegionalSettingsTest {
    	    
    @isTest private static void testProperties() {
        String region = getInstallationRegion();
        if (region != null) {
            RegionalSettings settings = new RegionalSettings(region);
            System.assertEquals(true, settings.installationsEnabled);
        }

        RegionalSettings settings2 = new RegionalSettings('333');
        System.assertEquals(false, settings2.installationsEnabled);        
    }
    
    private static String getInstallationRegion() {
        List<RegionalSettings__mdt> theList = [select SalesOrganization__c, InstallationsEnabled__c from RegionalSettings__mdt];
        for (RegionalSettings__mdt item :theList) {
            if (item.InstallationsEnabled__c) {
                return item.SalesOrganization__c;
            }
        }
        return null;
    }
    
}