force-app/main/default/objects/ZSFMatOrgv__x/ZSFMatOrgv__x.object-meta.xml
<CustomObject>
    <description>ZSFMatOrgvSet</description>
    <externalDataSource>SAP</externalDataSource>
    <externalName>ZSFMatOrgvSet</externalName>
    <label>ZSFMatOrgv</label>
    <pluralLabel>ZSFMatOrgvSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/ZSFMatOrgv__x/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <description>Matnr</description>
    <externalDeveloperName>Matnr</externalDeveloperName>
    <label>Material</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZSFMatOrgv__x/fields/Stkprog__c.field-meta.xml
<CustomField>
    <fullName>Stkprog__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Stkprog</description>
    <externalDeveloperName>Stkprog</externalDeveloperName>
    <label>Stkprog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProductCommons.cls
/**
 * @author         Ramón Prades
 * @date           December 2024
 * @layer          Commons
 * @description    Utility methods to handle product related properties
*/
public class ProductCommons {
    
    /**
     * Normalizes a make by removing the "SIN MARCA" and converting it to upper case
     */
    public static String normalizeMake(String make) {
        String result = make;
        if (result == null || result?.toLowerCase() == 'sin marca') {
            result = '';
        }  
        return result?.toUpperCase();
    }

    /**
     * Gets the one-char make code from a make name (i.e. P from PORCELANOSA)
     */
    public static String makeCodeFromName(String makeName) {
        String result = normalizeMake(makeName);
        if (String.isNotBlank(result)) {
            if (result == 'KRION') {
                result = 'S';
            } else if (result?.toLowerCase() == 'URBATEK') {
                result = 'C';
            } else {
                result = result.substring(0,1);
            }
        }
        return result;
    }

    /**
     * Returns true if all the products are in the stock program
     */
    public static Boolean checkStockProgram(String salesOrg, Set<String> materialsSet) {
        Boolean result = true; 
        ZSFMatOrgv__x[] mats = [select Material__c, Stkprog__c from ZSFMatOrgv__x where Vkorg__c = :salesOrg and Material__c in :materialsSet];
        for (ZSFMatOrgv__x mat : mats) {
            result = result && mat.Stkprog__c;
        } 
        return result;
    }

}