force-app/main/default/objects/Facturas_cabeceraSet__x/Facturas_cabeceraSet__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>Facturas_cabeceraSet</externalName>
    <label>Facturas_cabeceraSet</label>
    <pluralLabel>Facturas_cabeceraSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/Facturas_posicionesSet__x/Facturas_posicionesSet__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>Facturas_posicionesSet</externalName>
    <label>Facturas_posicionesSet</label>
    <pluralLabel>Facturas_posicionesSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product2/fields/SalesUnit__c.field-meta.xml
<CustomField>
    <fullName>SalesUnit__c</fullName>
    <description>Minimum unit this product can be sold in</description>
    <label>Sales Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductUnits</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ProductUnits.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PZS</fullName>
        <label>PIECE</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>PALLET</label>
    </customValue>
    <customValue>
        <fullName>SAC</fullName>
        <label>BAG</label>
    </customValue>
    <customValue>
        <fullName>MT2</fullName>
        <label>SQUARE METERS</label>
    </customValue>
    <customValue>
        <fullName>BID</fullName>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>CJ</fullName>
        <label>BOX</label>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
        <label>CENTIMETER</label>
    </customValue>
    <customValue>
        <fullName>DM2</fullName>
        <label>SQUARE DECIMETER</label>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
        <label>KILOGRAM</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>LITER</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>METER</label>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
        <label>SQUARE METER</label>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
        <label>MILILITER</label>
    </customValue>
    <customValue>
        <fullName>ROL</fullName>
        <label>ROLE</label>
    </customValue>
    <customValue>
        <fullName>SQF</fullName>
        <label>SQUARE FOOT</label>
    </customValue>
    <customValue>
        <fullName>UN</fullName>
        <label>UNIT</label>
    </customValue>
    <customValue>
        <fullName>CM2</fullName>
        <label>SQUARE CENTIMETER</label>
    </customValue>
    <customValue>
        <fullName>DM</fullName>
        <label>DECIMETER</label>
    </customValue>
    <description>Values for product units</description>
    <masterLabel>Product Units</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SAPInvoiceSearchController.cls
/**
 * @author         Ramón Prades
 * @date           January 2025
 * @layer          LWC Controllers
 * @description    description
*/
public class SAPInvoiceSearchController {

    @AuraEnabled public static SearchResultsDTO readInvoices(SearchDTO searchCriteria) {   
        SAPInvoicesFinderService finder = new SAPInvoicesFinderService();
        finder.setSalesOrg(searchCriteria.salesOrg);
        finder.setAccountId(searchCriteria.accountId);
        finder.setProductId(searchCriteria.productId);
        finder.setOrderNumber(searchCriteria.orderNumber);
        finder.setTimeframe(searchCriteria.timeframe);
        finder.setAmountFilter(SAPInvoicesFinderService.AmountOptions.GREATER_THAN_ZERO);        
        finder.setOrderBy(SAPInvoicesFinderService.OrderByField.INV_DATE, SAPInvoicesFinderService.OrderByDirection.DESCENDING);
        //finder.setMaxLines(5);

        SearchResultsDTO resultsDTO = new SearchResultsDTO();
        resultsDTO.invoices = finder.find();
        resultsDTO.invoiceLines = finder.readItems();
        resultsDTO.unitsMap = PicklistCommons.getValues(Product2.SalesUnit__c);
        return resultsDTO;
    }

    public class SearchDTO {
        @AuraEnabled public String salesOrg {get;set;}
        @AuraEnabled public String accountId {get;set;}
        @AuraEnabled public String productId {get;set;}
        @AuraEnabled public String orderNumber {get;set;}
        @AuraEnabled public String timeframe {get;set;}
    }
    
    public class SearchResultsDTO {
        @AuraEnabled public List<Facturas_cabeceraSet__x> invoices;
        @AuraEnabled public Map<String, List<Facturas_posicionesSet__x>> invoiceLines;
        @AuraEnabled public Map<String, String> unitsMap;
    }

}