force-app/main/default/objects/CartItem/fields/SalesPriceUnit__c.field-meta.xml
<CustomField>
    <fullName>SalesPriceUnit__c</fullName>
    <description>Unit of the sales price</description>
    <label>Sales Price Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductUnits</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PorcelanosaAddress__c/PorcelanosaAddress__c.object-meta.xml
<CustomObject>
    <label>Porcelanosa Address</label>
    <nameField>
        <label>Porcelanosa Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porcelanosa Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PorcelanosaAddress__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeZone_IANA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PORSAStoreSettings__c/PORSAStoreSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Definición de comportamiento de stores B2B</description>
    <label>PORSA Store Settings</label>
</CustomObject>

force-app/main/default/objects/PORSAStoreSettings__c/fields/CaptureURL__c.field-meta.xml
<CustomField>
    <fullName>CaptureURL__c</fullName>
    <label>XXXCapture URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PORSAStoreSettings__c/fields/ErrorURL__c.field-meta.xml
<CustomField>
    <fullName>ErrorURL__c</fullName>
    <label>XXXError URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PORSAStoreSettings__c/fields/MerchantID__c.field-meta.xml
<CustomField>
    <fullName>MerchantID__c</fullName>
    <label>XXXMerchant ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PORSAStoreSettings__c/fields/PaymentGatewayURL__c.field-meta.xml
<CustomField>
    <fullName>PaymentGatewayURL__c</fullName>
    <label>XXXPayment Gateway URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PORSAStoreSettings__c/fields/ResponseURL__c.field-meta.xml
<CustomField>
    <fullName>ResponseURL__c</fullName>
    <label>XXXResponse URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PORSAStoreSettings__c/fields/Secret__c.field-meta.xml
<CustomField>
    <fullName>Secret__c</fullName>
    <label>XXXSecret</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/SALES_OFFICE__c.object-meta.xml
<CustomObject>
    <description>Entidad custom que contiene el maestro de relaciones para transformar el código de la oficina de ventas por el nombre.</description>
    <label>Sales Office</label>
    <nameField>
        <label>Nombre de SALES_OFFICE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Default_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Organization__c</fullName>
    <description>La organización de ventas por defecto para el comercial</description>
    <inlineHelpText>The default sales organization for sales and distribution</inlineHelpText>
    <label>Default Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Distribution_channel_default__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel_default__c</fullName>
    <label>Distribution channel default</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Sales Office from Sales Org default</description>
    <inlineHelpText>Sales Office from Sales Org default</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Default_Sales_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ProductUnits.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PZS</fullName>
        <label>PIECE</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>PALLET</label>
    </customValue>
    <customValue>
        <fullName>SAC</fullName>
        <label>BAG</label>
    </customValue>
    <customValue>
        <fullName>MT2</fullName>
        <label>SQUARE METERS</label>
    </customValue>
    <customValue>
        <fullName>BID</fullName>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>CJ</fullName>
        <label>BOX</label>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
        <label>CENTIMETER</label>
    </customValue>
    <customValue>
        <fullName>DM2</fullName>
        <label>SQUARE DECIMETER</label>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
        <label>KILOGRAM</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>LITER</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>METER</label>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
        <label>SQUARE METER</label>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
        <label>MILILITER</label>
    </customValue>
    <customValue>
        <fullName>ROL</fullName>
        <label>ROLE</label>
    </customValue>
    <customValue>
        <fullName>SQF</fullName>
        <label>SQUARE FOOT</label>
    </customValue>
    <customValue>
        <fullName>UN</fullName>
        <label>UNIT</label>
    </customValue>
    <customValue>
        <fullName>CM2</fullName>
        <label>SQUARE CENTIMETER</label>
    </customValue>
    <customValue>
        <fullName>DM</fullName>
        <label>DECIMETER</label>
    </customValue>
    <description>Values for product units</description>
    <masterLabel>Product Units</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/B2B_PaymentGatewayRedirectHelper.cls
public without sharing class B2B_PaymentGatewayRedirectHelper {

    private static final String STORE_SETTING_KEY = 'US_DEALERS';

    public ConnectApi.CartSummary cart {get; private set;}
    public List<ConnectApi.CartItem> cartItems {get; private set;}
    public String token {get; private set;}

    private PORSAStoreSettings__c storeSettings;
    private String uniqueId;
    private String salesOrg;
    private String poNumber;
    private PorcelanosaAddress__c warehouse;
    private Decimal cartTotal = 0;
    private Decimal cardSurcharge = 0;    
    private Map<String, String> unitsMap;

    public B2B_PaymentGatewayRedirectHelper(B2B_CommerceCartAdapter.CommerceCartData cartData) {
        PORSAStoreSettings__c cfg = PORSAStoreSettings__c.getInstance(STORE_SETTING_KEY);
        if (cfg == null || String.isBlank(cfg.PaymentGatewayURL__c) 
            || String.isBlank(cfg.MerchantID__c) || String.isBlank(cfg.Secret__c)
            || String.isBlank(cfg.CaptureURL__c)) {
            throw new ContextException('Missing gateway configuration in store settings ' + STORE_SETTING_KEY);
        }
        this.storeSettings = cfg;

        // Validate the cart details and validate status
        if (cartData == null || cartData.cart == null) {
            throw new ObjectNotFoundException('Cart not found or empty.');
        }
        if (cartData.cart.status != ConnectApi.CartStatus.CHECKOUT) {
            throw new ContextException('Cart is not in checkout status. Current status: ' + cartData.cart.status);
        }
        this.cart = cartData.cart;
        this.cartItems = cartData.cartItems;

        User currentUser = [SELECT Id, Default_Sales_Organization__c, Distribution_channel_default__c, Sales_Office__c from User WHERE Id = :UserInfo.getUserId() limit 1];
        this.salesOrg = currentUser.Default_Sales_Organization__c;
        this.warehouse = new B2B_CommerceUtils().getB2BWarehouse(this.salesOrg); 
        this.unitsMap =  PicklistCommons.getValues(CartItem.SalesPriceUnit__c);
    }

    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    public void setCardSurcharge(Decimal cardSurcharge) {
        this.cardSurcharge = cardSurcharge;
    }

    public void setCartTotal(Decimal cartTotal) {
        this.cartTotal = cartTotal;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public void setPoNumber(String poNumber) {
        this.poNumber = poNumber;
    }

    public Map<String, String> getFieldsPayload() {
        Map<String, String> fields = new Map<String, String>();
        this.buildConfigFields(fields);
        this.buildCustomerFields(fields);
        this.buildCartFields(fields);
        this.addSignature(fields);
        return fields;
    }

    public String getRedirectURL() {
        return this.storeSettings.PaymentGatewayURL__c;
    }


    /* ==================================================================== */

    @SuppressWarnings('PMD.UnusedLocalVariable')

    private void buildConfigFields( Map<String, String> fields) {
        String company = OrganizationUtil.getSalesOrgCompany(this.salesOrg);
        String tstamp = '';
        try {
            tstamp = DateTime.now().format('yyyyMMddHHmmss', this.warehouse.TimeZone__c);
        } catch (Exception e) {
            tstamp = DateTime.now().format('yyyyMMddHHmmss');
        }
        
        fields.put('MERCHANT', this.storeSettings.MerchantID__c);
        fields.put('B2B', '1');
        fields.put('TYPE', 'redirect_form');
        fields.put('LANG', 'en-us');
        fields.put('CAPTURE_URL_OVERRIDE', this.storeSettings.CaptureURL__c);
        fields.put('SALES_ORGANIZATION', this.salesOrg);
        fields.put('SOCIETY', company); 
        fields.put('TIMESTAMP', tstamp);
        fields.put('CUSTOM_FIELD1', this.token);

        if (String.isNotBlank(this.storeSettings.ResponseURL__c)) {
            fields.put('RESPONSE_URL_OVERRIDE', this.storeSettings.ResponseURL__c);
        }

        if (String.isNotBlank(this.storeSettings.ErrorURL__c)) {
            fields.put('ERROR_URL_OVERRIDE', this.storeSettings.ErrorURL__c);
        }

    }        
    
    private void buildCustomerFields(Map<String, String> fields) {
        Account acc = new AccountsSelector().selectById(this.cart.accountId);
        if (String.isBlank(acc.BillingStreet) || String.isBlank(acc.BillingCity) || String.isBlank(acc.BillingState)
            || String.isBlank(acc.BillingPostalCode) || String.isBlank(acc.BillingCountry)) {
            throw new AuraHandledException('Account billing address is incomplete.');
        }
        
        fields.put('CUSTOMER_ID', acc.Id);
        fields.put('CUSTOMER_NAME', UserInfo.getName());
        fields.put('CUSTOMER_SURNAME', acc.Name);
        fields.put('CUSTOMER_MAIL', UserInfo.getUserEmail());
        fields.put('CUSTOMER_PHONENUMBER_MOBILE', acc.Phone);
        fields.put('BILLING_STREET', acc.BillingStreet);
        fields.put('BILLING_CITY', acc.BillingCity);
        fields.put('BILLING_STATE', acc.BillingStateCode);
        fields.put('BILLING_POSTALCODE', acc.BillingPostalCode);
        fields.put('BILLING_COUNTRY', acc.BillingCountryCode);
    }

    public void buildCartFields(Map<String, String> fields) { 
        String quoteId = this.uniqueId ?? this.cart.cartId;       
        fields.put('CURRENCY', this.cart.currencyIsoCode);
        fields.put('AMOUNT', String.valueOf(Integer.valueOf(this.getCartTotal() * 100))); // Convert to minor units
        fields.put('QUOTE_ID', quoteId);
        fields.put('ITEM_LINE_COUNT', String.valueOf(this.cartItems.size()));
        Integer lineNum = 1;
        for (ConnectApi.CartItem item : this.cartItems) {
            String unit = 'UN'; // Default unit
            if (item.customFields != null && item.customFields.size() > 0) {
                CartItem custom = (CartItem) item.customFields[0];                
                unit = custom?.SalesPriceUnit__c ?? 'UN';
                if (unitsMap.containsKey(unit)) {
                    unit = unitsMap.get(unit);
                }   
            }
            fields.put('ITEM_' + lineNum + '_POSITION', String.valueOf(lineNum));
            fields.put('ITEM_' + lineNum + '_SKU', item.productDetails.sku);
            fields.put('ITEM_' + lineNum + '_DESCRIPTION', item.name);
            fields.put('ITEM_' + lineNum + '_QUANTITY', String.valueOf(item.quantity)); 
            fields.put('ITEM_' + lineNum + '_UNIT', unit);
            lineNum++;   
        }
    }

    /**
     * Add signature field to the payload based on the specified signed field names and the secret from store settings.
     * (HMAC SHA256 Base64)
     */
    private void addSignature(Map<String, String> fields) {

        List<String> signed = new List<String>(fields.keySet());

        if (!signed.contains('SIGNED_FIELD_NAMES')) {
            signed.add('SIGNED_FIELD_NAMES');
        }

        String signedFieldNamesValue = String.join(signed, ',');
        fields.put('SIGNED_FIELD_NAMES', signedFieldNamesValue);

        // Build data-to-sign in the exact order: key=value,key=value,...
        List<String> parts = new List<String>();
        for (String key : signed) {
            parts.add(key + '=' + (fields.containsKey(key) && fields.get(key) != null ? fields.get(key) : ''));
        }
        String dataToSign = String.join(parts, ',');

        // HMAC-SHA256 + Base64
        Blob mac = Crypto.generateMac('HmacSHA256', Blob.valueOf(dataToSign), Blob.valueOf(this.storeSettings.Secret__c));
        fields.put('SIGNATURE', EncodingUtil.base64Encode(mac));
    }

    private Decimal getCartTotal() {
        Decimal amount = 0;
        if (this.cartTotal != null && this.cartTotal > 0) {
            amount = this.cartTotal;
        } else {
            amount = Decimal.valueOf(this.cart.grandTotalAmount) + this.cardSurcharge;
        }
        return amount;
    }

    private List<String> addItemSignedFields(List<String> signed, Integer itemLineCount) {
        // OJO: índice empieza en 1
        for (Integer i = 1; i <= itemLineCount; i++) {
            signed.add('ITEM_' + i + '_POSITION');
            signed.add('ITEM_' + i + '_SKU');
            signed.add('ITEM_' + i + '_QUANTITY');
        }
        return signed;
    }

}