force-app/main/default/objects/Pricebook2/fields/Bzirk__c.field-meta.xml
<CustomField>
    <fullName>Bzirk__c</fullName>
    <description>SAP price list code or multiple SAP price list codes separated by semicolon. Ignored when SAP Customer is informed.</description>
    <label>SAP Price Lists</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/IsRetailReferencePricebook__c.field-meta.xml
<CustomField>
    <fullName>IsRetailReferencePricebook__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If check, it&apos;s the Reference Pricebook for the context</description>
    <label>Is Retail Reference Pricebook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Relationship__c/Sales_Relationship__c.object-meta.xml
<CustomObject>
    <label>SAP Accounting Info</label>
    <nameField>
        <label>Nombre Organizaciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Accounting Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Relationship__c/fields/Bzirk__c.field-meta.xml
<CustomField>
    <fullName>Bzirk__c</fullName>
    <description>Sales area of the customer in SAP (BZIRK). In France is related to the price list applied.</description>
    <label>Sales Area</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Default_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Organization__c</fullName>
    <description>La organización de ventas por defecto para el comercial</description>
    <inlineHelpText>The default sales organization for sales and distribution</inlineHelpText>
    <label>Default Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Execution_Context__c.field-meta.xml
<CustomField>
    <fullName>Execution_Context__c</fullName>
    <description>User&apos;s execution context</description>
    <label>Execution Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <label>DEUTSCHLAND</label>
            </value>
            <value>
                <fullName>ZA</fullName>
                <label>SOUTH AFRICA</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>DENMARK</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>UNITED STATES</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>FRANCE</label>
            </value>
            <value>
                <fullName>GB</fullName>
                <label>UNITED KINGDOM</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>SPAIN</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>POLAND</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>SWITZERLAND</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>ITALY</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>CANADA</label>
            </value>
            <value>
                <fullName>JP</fullName>
                <label>JAPAN</label>
            </value>
            <value>
                <fullName>VO</fullName>
                <label>VOID</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>BELGIUM</label>
            </value>
            <value>
                <fullName>PEXP</fullName>
                <label>PORCELANOSA EXPORT</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>AUSTRALIA</label>
            </value>
            <value>
                <fullName>SE</fullName>
                <label>SCANDINAVIA</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>ISRAEL</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>CHILE</label>
            </value>
            <value>
                <fullName>RD</fullName>
                <label>REPUBLICA DOMINICANA</label>
            </value>
            <value>
                <fullName>DEFAULT</fullName>
                <isActive>false</isActive>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>FLOWTESTUK</fullName>
                <isActive>false</isActive>
                <label>FLOWTESTUK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesZoneTariffAssignator.cls
/**
    * @description Given a user and an Account, returns the Pricebook should be used. The implementation works like this:
    *
    *                               The User Has Pricebooks, besides of the Standard?
    *                                                           |
    *                                       ------------------------------------------------------------------
    *                                        |                                                                |
    *                                       YES                                                               NO
    *                                        |                                                                |
    *                                        |                                                                |
    *                ------------------ Account has Pricebooks ----------                     Returns the Standard Pricebook
    *                |                                                  |
    *                NO                                                YES
    *                |                                                  |
    *   User Has a Reference Pricebook? <-----|           Account has a Pricebook on the User
    *                |                       ||                  default Sales Org and can
    *                |                       ||                     the user use it?
    *         ------------------             ||                         |
    *         |                 |            ||             -----------------------------
    *        YES                NO           ||             |                           |
    *         |                 |            ||            YES                          NO
    *   return Reference    return Standard  ||             |                           |
    *       Pricebook           Pricebook    ||     return Sales Relation   ------ Account has more Sales Rel ------
    *                                        ||          Pricebook          |      with Pricebook apart  of the    |
    *                                        ||                             NO          Users default?             |
    *                                        | -----------------------------|                                      |
    *                                        |                                                                    YES
    *                                        |                                                                     |
    *                                        |                                                       --- Can the user use any of them? ---
    *                                        |                                                       |                                   |
    *                                        |                                                      YES                                  NO
    *                                        |                                                       |                                   |
    *                                        |                                                  Returns the first one                    |
    *                                        |                                                  of the other Sales Rel                   |
    *                                        |                                                                                           |
    *                                        --------------------------------------------------------------------------------------------|
    *                                                                                          
    *                                                                                          
    * @param User Id
    * @param Account Id
    * @return Pricebook to assign, or null 
    */
    public class SalesZoneTariffAssignator extends AbstractPricebookAssignator
    {
        protected List<Sales_Relationship__c> accountSalesRel;
        protected User user;
    
        public override void setAccount(Id accId) {
          this.accountSalesRel = new SalesRelationshipsSelector().selectByAccountId(new Set<Id>{accId});
        }
      
        public override void setUser(Id usrId) {
          this.user = new UsersSelector().selectById(usrId);
        }
    
        public override Pricebook2 getPricebook() {
    
            Map<Id, Pricebook2> mapUserPricebooks = new Map<Id, Pricebook2>();
            Map<Id, Pricebook2> mapAccountPricebooks = new Map<Id, Pricebook2>();
    
            if (this.user != null) {
                List<Pricebook2> listuserPricebooks = getUserPricebooks();
                Map<String, Pricebook2> mapAccountPricebooksSalesOrg = getAccountPricebooksMap();
    
                for (Pricebook2 pb : listUserPricebooks) {
                    mapUserPricebooks.put(pb.Id, pb);
                }
                
                for (Pricebook2 pb : mapAccountPricebooksSalesOrg.values()) {
                    mapAccountPricebooks.put(pb.Id, pb);
                }
                
                // El Account no tiene Pricebooks por Sales Relationships.
                if (mapAccountPricebooksSalesOrg.size() == 0) {
                    for (Pricebook2 pb : listuserPricebooks) {
                        
                        // De los que el User puede acceder, cogemos el que sea Retail Standard
                        if (pb.IsRetailReferencePricebook__c == true) {
                            return pb;
                        }
                    }
                } else {
                    // Se mira si el Account tiene Pricebook configurado en la Sales Rel que el usuario tiene seteado como default. Si lo tiene y
                    // el usuario tiene acceso, cogemos el pricebook
                    if (mapAccountPricebooksSalesOrg.containsKey(this.user.Default_Sales_Organization__c) == true) {
                        if (mapUserPricebooks.containsKey(mapAccountPricebooksSalesOrg.get(this.user.Default_Sales_Organization__c).Id) == true) {
                            return mapAccountPricebooksSalesOrg.get(this.user.Default_Sales_Organization__c);
                        }
                    } else {
                        // No hay Pricebook en la Sales rel del Account, que es la misma que la del user, pero hay mas Pricebooks por Sales relationship
                        for (String salesOrg : mapAccountPricebooksSalesOrg.keySet()){
                            // Cogemos el primer Pricebook de Sales Relationship que el usuario tenga acceso
                            if (mapUserPricebooks.containsKey(mapAccountPricebooksSalesOrg.get(salesOrg).Id) == true) {
                                return mapAccountPricebooksSalesOrg.get(salesOrg);
                            }
                        }

                    }
                    
                    for (Pricebook2 pb : listuserPricebooks) {
                        // De los que el User puede acceder, cogemos el que sea Retail Standard
                        if (pb.IsRetailReferencePricebook__c == true) {
                            return pb;
                        }
                    }
                }
            }
    
            List<Pricebook2> standardPricebook = new PricebooksSelector().selectStandardPricebook();
            if (standardPricebook.size() == 1) {
                return standardPricebook[0];
            }
    
            return null;
    
        } // getOwner
    
        /*************************************************/
        /************* PRIVATE METHODS *******************/
        /*************************************************/
    
        /**
        * @description Gets the Pricebooks an Account works with, defined by the field Bzirk__c field on the
        * different Sales Relations of the Account, wich contains the tariff code.
        * @param accountId
        * @return Map of Pricebooks with the format SalesOrg => Pricebook
        */
        private Map<String, Pricebook2> getAccountPricebooksMap() {
            Map<String, Pricebook2> result = new Map<String, Pricebook2>();
            Set<String> listTariffs = new Set<String>();
            Map<String, Pricebook2> tariffPricebookMap = new Map<String, Pricebook2>();
            Map<String, String> tariffSalesRelMap = new Map<String, String>();
            
            if (this.accountSalesRel.size() > 0) {
                for (Sales_Relationship__c obj :this.accountSalesRel) {
                    if (String.isEmpty(obj.Bzirk__c) == false) {
                        tariffSalesRelMap.put(obj.Sales_org__c, obj.Bzirk__c);
                        listTariffs.add(obj.Bzirk__c);
                    }
                }
                
                for (Pricebook2 obj : new PricebooksSelector().selectByTariffs(listTariffs)) {
                    tariffPricebookMap.put(obj.Bzirk__c, obj);
                }
                
                for (String salesOrg : tariffSalesRelMap.keySet()) {
                    if (tariffPricebookMap.containsKey(tariffSalesRelMap.get(salesOrg))) {
                        result.put(salesOrg, tariffPricebookMap.get(tariffSalesRelMap.get(salesOrg)));
                    }
                }
            }
    
            return result;
        }
        
        /**
        * @description Gets the Pricebooks an User can work with. These are related through the Execution Context
        * @param userId
        * @return List of Pricebooks
        */
        private List<Pricebook2> getUserPricebooks() {
            List<Pricebook2> result = new List<Pricebook2>();
            if (this.user != null) {
                result = new PricebooksSelector().selectByExecutionContext(this.user.Execution_Context__c);
            }
            
            return result;
        }
        
        /**
        * @description Gets the Pricebooks an User can work with, but filtered by the ones related to a tariff. 
        * These are related through the Execution Context and the field Bzirk__c is not empty
        * @param userId
        * @return List of Pricebooks
        */
        private List<Pricebook2> getUserPricebooksWithTariff(Id userId) {
            List<Pricebook2> result = new List<Pricebook2>();
            List<Pricebook2> pbooks = getUserPricebooks();
            if (pbooks.size() > 0) {
                for (Pricebook2 obj : pbooks) {
                    if (obj.isActive == true && String.isBlank(obj.Bzirk__c) == false) {
                        result.add(obj);
                    }
                }
            }
            
            return result;
        }
    } // class