force-app/main/default/objects/Pricebook2/fields/Bzirk__c.field-meta.xml
<CustomField>
    <fullName>Bzirk__c</fullName>
    <description>SAP price list code or multiple SAP price list codes separated by semicolon. Ignored when SAP Customer is informed.</description>
    <label>SAP Price Lists</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/IsRetailReferencePricebook__c.field-meta.xml
<CustomField>
    <fullName>IsRetailReferencePricebook__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If check, it&apos;s the Reference Pricebook for the context</description>
    <label>Is Retail Reference Pricebook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Execution_Context__c.field-meta.xml
<CustomField>
    <fullName>Execution_Context__c</fullName>
    <description>User&apos;s execution context</description>
    <label>Execution Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <label>DEUTSCHLAND</label>
            </value>
            <value>
                <fullName>ZA</fullName>
                <label>SOUTH AFRICA</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>DENMARK</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>UNITED STATES</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>FRANCE</label>
            </value>
            <value>
                <fullName>GB</fullName>
                <label>UNITED KINGDOM</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>SPAIN</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>POLAND</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>SWITZERLAND</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>ITALY</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>CANADA</label>
            </value>
            <value>
                <fullName>JP</fullName>
                <label>JAPAN</label>
            </value>
            <value>
                <fullName>VO</fullName>
                <label>VOID</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>BELGIUM</label>
            </value>
            <value>
                <fullName>PEXP</fullName>
                <label>PORCELANOSA EXPORT</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>AUSTRALIA</label>
            </value>
            <value>
                <fullName>SE</fullName>
                <label>SCANDINAVIA</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>ISRAEL</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>CHILE</label>
            </value>
            <value>
                <fullName>RD</fullName>
                <label>REPUBLICA DOMINICANA</label>
            </value>
            <value>
                <fullName>DEFAULT</fullName>
                <isActive>false</isActive>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>FLOWTESTUK</fullName>
                <isActive>false</isActive>
                <label>FLOWTESTUK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReferenceTariffAssignator.cls
/**
* @description Given a user and an Account, returns the Pricebook should be used. The implementation works like this:
*
*                               The User Has Pricebooks, besides of the Standard?
*                                                           |
*                                       ------------------------------------------------------------------
*                                        |                                                                |
*                                       YES                                                               NO                     
*                                        |                                                                |                         
*                           User Has a Reference Pricebook?                                 Returns the Standard Pricebook  
*                                        |                     
*                                        |                      
*                               -------------------                
*                               |                 |          
*                              YES                NO          
*                               |                 |           
*                       return Reference    return Standard 
*                           Pricebook           Pricebook   
*                                                                                                                                              
*/
    public class ReferenceTariffAssignator extends AbstractPricebookAssignator
    {
        protected User user;
    
        public override void setUser(Id usrId) {
          this.user = new UsersSelector().selectById(usrId);
        }
        
        public override void setAccount(Id accId) {
        }
    
        public override Pricebook2 getPricebook() {
    
            Map<Id, Pricebook2> mapUserPricebooks = new Map<Id, Pricebook2>();
    
            if (this.user != null) {
                List<Pricebook2> listuserPricebooks = getUserPricebooksWithTariff();

                for (Pricebook2 pb : listuserPricebooks) {
                    if (pb.IsRetailReferencePricebook__c == true) {
                        return pb;
                    }
                }
            }
    
            List<Pricebook2> standardPricebook = new PricebooksSelector().selectStandardPricebook();
            if (standardPricebook.size() == 1) {
                return standardPricebook[0];
            }
    
            return null;
    
        } // getOwner
    
        /*************************************************/
        /************* PRIVATE METHODS *******************/
        /*************************************************/
        
        /**
        * @description Gets the Pricebooks an User can work with. These are related through the Execution Context
        * @param userId
        * @return List of Pricebooks
        */
        private List<Pricebook2> getUserPricebooks() {
            List<Pricebook2> result = new List<Pricebook2>();
            if (this.user != null) {
                result = new PricebooksSelector().selectByExecutionContext(this.user.Execution_Context__c);
            }
            
            return result;
        }
        
        /**
        * @description Gets the Pricebooks an User can work with, but filtered by the ones related to a tariff. 
        * These are related through the Execution Context and the field Bzirk__c is not empty
        * @param userId
        * @return List of Pricebooks
        */
        private List<Pricebook2> getUserPricebooksWithTariff() {
            List<Pricebook2> result = new List<Pricebook2>();
            List<Pricebook2> pbooks = getUserPricebooks();
            if (pbooks.size() > 0) {
                for (Pricebook2 obj : pbooks) {
                    if (obj.isActive == true && String.isBlank(obj.Bzirk__c) == false) {
                        result.add(obj);
                    }
                }
            }
            
            return result;
        }
    } // class