force-app/main/default/objects/Pricebook2/fields/SAPCustomer__c.field-meta.xml
<CustomField>
    <fullName>SAPCustomer__c</fullName>
    <description>SAP customer code to get the special prices from (read from ZB2B_PRICE2__x)</description>
    <inlineHelpText>SAP customer code to get the special prices from (read from ZB2B_PRICE2__x)</inlineHelpText>
    <label>SAP Customer</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Umv__c.field-meta.xml
<CustomField>
    <fullName>Umv__c</fullName>
    <label>Umv</label>
    <length>10</length>
    <translateData>true</translateData>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZB2B_PRICE2__x/ZB2B_PRICE2__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>ZB2B_PRICE2Set</externalName>
    <label>ZB2B_PRICE2</label>
    <pluralLabel>ZB2B_PRICE2Set</pluralLabel>
</CustomObject>

force-app/main/default/objects/ZB2B_PRICE2__x/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <description>Cantidad</description>
    <externalDeveloperName>Cantidad</externalDeveloperName>
    <label>Cantidad</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZB2B_PRICE2__x/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <description>Material</description>
    <externalDeveloperName>Material</externalDeveloperName>
    <label>Material</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZB2B_PRICE2__x/fields/Prneto__c.field-meta.xml
<CustomField>
    <fullName>Prneto__c</fullName>
    <description>Prneto</description>
    <externalDeveloperName>Prneto</externalDeveloperName>
    <label>Prneto</label>
    <precision>12</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MasterPricesSpecialSyncJobTest.cls
@isTest public class MasterPricesSpecialSyncJobTest {
    @testSetup private static void testSetup() {
        Product2[] products = DataFactoryProduct.createProducts();        
    }

    @isTest
    public static void testBatchProcess() {        
        String SAPCustomer = '1000000';
        Product2[] products = [select Id, ProductCode from Product2];
        
        List<ZB2B_PRICE2__x> sapPrices = new List<ZB2B_PRICE2__x>();
        //for (Integer i = 0; i < 10; i++) {
            ZB2B_PRICE2__x price = new ZB2B_PRICE2__x();
            price.Cliente__c = SAPCustomer;
            price.Cantidad__c = 1;
            price.Material__c = products[0].ProductCode;
            price.Moneda__c = 'USD';
            price.Prneto__c = 99.99;
            price.Uprecio__c = 'PZS';
            price.PrecioUMV__c = 99.99;
            price.UMV__c = 'PZS';
            sapPrices.add(price);
        //} // end for
        
        PricebookEntry pbe = [select Id, Pricebook2Id, UnitPrice from PricebookEntry where Product2Id = :products[0].Id and currencyIsoCode = 'USD' limit 1];
        System.assertNotEquals(null, pbe, 'No pricebook found - Cannot run the test');

        Pricebook2 pb = [select Id from Pricebook2 where Id = :pbe.Pricebook2Id limit 1];
        pb.SAPCustomer__c = Decimal.valueOf(SAPCUstomer);
        update pb;

        Test.startTest();
            MasterPricesSpecialSyncJob job = new MasterPricesSpecialSyncJob(pbe.Pricebook2Id);
            job.setNumberOfItems(10);
            job.setFullUpdate(false);
            job.start(null);
            job.execute(null,sapPrices);
            job.finish(null);
        Test.stopTest();

        PricebookEntry pbeAfter = [select Id, Pricebook2Id, UnitPrice from PricebookEntry where Id = :pbe.Id limit 1];
        System.assertNotEquals(null, pbeAfter, 'No pricebook entry found - Cannot run the test');
        //System.assertEquals(99.99, pbeAfter.UnitPrice, 'New price should be 99.99');
        
    }
} // class