force-app/main/default/objects/OppCustomProject__c/OppCustomProject__c.object-meta.xml
<CustomObject>
    <description>Object to store opportunity&apos;s additional information on US custom project (Krion and similar products transformed by a fabricator).</description>
    <label>Opportunity Custom Project</label>
    <nameField>
        <label>Custom Project Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Custom Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppCustomProject__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Related opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Project Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUALIFICATION</fullName>
                <default>true</default>
                <label>QUALIFICATION</label>
            </value>
            <value>
                <fullName>PR-RECEIVED</fullName>
            </value>
            <value>
                <fullName>PROPOSAL</fullName>
            </value>
            <value>
                <fullName>DEPOSIT</fullName>
            </value>
            <value>
                <fullName>TEMPLATE-APP</fullName>
            </value>
            <value>
                <fullName>DRAWING-SIGNED</fullName>
            </value>
            <value>
                <fullName>CHANGE-ORDER</fullName>
            </value>
            <value>
                <fullName>PAYMENT-RECEIVED</fullName>
            </value>
            <value>
                <fullName>IN-PRODUCTION</fullName>
            </value>
            <value>
                <fullName>INSTALLATION</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>LOST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InfoType__c.field-meta.xml
<CustomField>
    <fullName>InfoType__c</fullName>
    <description>Type of record of the additional info related to the opportunity (if any). Can be &apos;CUSTOM PROJECT&apos;, &apos;FACADE&apos; or &apos;KITCHEN&apos; (or blank)</description>
    <label>Opportunity Info Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PROJECT</fullName>
                <label>Custom Project</label>
            </value>
            <value>
                <fullName>KITCHEN</fullName>
                <label>Kitchen</label>
            </value>
            <value>
                <fullName>FACADE</fullName>
                <label>Facade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OppCustomProjectTriggerHandlerTest.cls
@isTest private class OppCustomProjectTriggerHandlerTest {

    @TestSetup static void makeData(){
        TestUtils.enableTriggers();
        SystemSettings.CPDeletionTime = 0;
        SystemSettings.CPNotificationsEnabled = true;
        //SystemSettings.CPDeletionTime = 15;
        DataFactoryOppCustomProjects.createRecords(2);
    }

    @isTest static void testInfoTypeUpdated() {
        Opportunity[] opps = [select Id, InfoType__c from Opportunity];
        for (Opportunity opp : opps) {
            System.assertEquals(OpportunitiesInfoCommons.PROJECT_TYPE, opp.InfoType__c, 'InfoType__c should be ' + OpportunitiesInfoCommons.PROJECT_TYPE);
        }
    }

    @isTest static void testInfoTypeCleared() {
        List<OppCustomProject__c> cps = [select Id, Opportunity__c from OppCustomProject__c];
        delete cps;
        Opportunity[] opps2 = [select Id, InfoType__c from Opportunity];
        for (Opportunity opp : opps2) {
            System.assertEquals(true, String.IsBlank(opp.InfoType__c), 'InfoType__c should have been cleared');
        }
    }

    @isTest static void testAfterUpdate() {
        OppCustomProject__c cp = [select Id, Opportunity__c from OppCustomProject__c limit 1];
        cp.Stage__c = 'INSTALLATION';
        update cp;
        System.assertEquals(true, true, 'Code coverage');
    }

}