force-app/main/default/objects/OppCustomProject__c/OppCustomProject__c.object-meta.xml
<CustomObject>
    <description>Object to store opportunity&apos;s additional information on US custom project (Krion and similar products transformed by a fabricator).</description>
    <label>Opportunity Custom Project</label>
    <nameField>
        <label>Custom Project Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Custom Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppCustomProject__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>Delivery Needed By</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Related opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/fields/ProductManager__c.field-meta.xml
<CustomField>
    <fullName>ProductManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <description>Type of custom project</description>
    <label>Project Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALTISSIMA</fullName>
            </value>
            <value>
                <fullName>KRION</fullName>
            </value>
            <value>
                <fullName>KRION &amp; XTONE</fullName>
            </value>
            <value>
                <fullName>XTONE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppCustomProjectRequest__c/OppCustomProjectRequest__c.object-meta.xml
<CustomObject>
    <label>Opportunity Custom Project Request</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Custom Project Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppCustomProjectRequest__c/fields/OppCustomProject__c.field-meta.xml
<CustomField>
    <fullName>OppCustomProject__c</fullName>
    <label>Custom Project</label>
    <referenceTo>OppCustomProject__c</referenceTo>
    <relationshipName>CustomProjectRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppCustomProjectRequest__c/fields/ProductDescription__c.field-meta.xml
<CustomField>
    <fullName>ProductDescription__c</fullName>
    <label>Product Description</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kitchen_Countertop</fullName>
                <label>Kitchen Countertop</label>
            </value>
            <value>
                <fullName>Kitchen_Island</fullName>
                <label>Kitchen Island</label>
            </value>
            <value>
                <fullName>Vanity_Top</fullName>
                <label>Vanity Top</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Other (Explain in Notes)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <label>ProjectType</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/OpportunityCustomProjectControllerTest.cls
@isTest public with sharing class OpportunityCustomProjectControllerTest {

    @testSetup private static void testSetup() {
        TestUtils.enableTriggers();
        Opportunity opp = DataFactoryOpportunity.createRetailOpportunities(1, 1)[0];
    }

    @isTest private static void readCustomProjectData_1()  {
        Opportunity opp = [select id from Opportunity limit 1];
        OpportunityCustomProjectController.ProjectDTO dto = OpportunityCustomProjectController.readCustomProjectData(opp.Id, null);
        System.assertNotEquals(null, dto, 'No result returned');
    }

    @isTest private static void saveCustomProject() {
        Opportunity opp = [select id from Opportunity limit 1];
        OppCustomProject__c cp = new OppCustomProject__c();
        cp.Opportunity__c = opp.Id;
        cp.ProjectType__c = 'KRION';
        cp.ProductManager__c = UserInfo.getUserId();
        cp.DeliveryDate__c = System.today();
        
        // test saveCustomProject
        OpportunityCustomProjectController.ResultDTO dto = OpportunityCustomProjectController.saveCustomProject(cp);
        System.assertEquals(true, dto.success);
        cp.Id = dto.arg;
        
        // readCustomProjectData
        OpportunityCustomProjectController.ProjectDTO dto2 = OpportunityCustomProjectController.readCustomProjectData(opp.Id, dto.arg);
        System.assertNotEquals(null, dto2, 'No result returned');

        // test saveRequestLines
        OppCustomProjectRequest__c[] reqs = new List<OppCustomProjectRequest__c>();
        reqs.add(new OppCustomProjectRequest__c(ProductDescription__c = 'Other'));
        reqs.add(new OppCustomProjectRequest__c(ProductDescription__c = 'Other'));        

        OpportunityCustomProjectController.saveRequestLines(cp.Id, reqs, new List<OppCustomProjectRequest__c>());
        OppCustomProjectRequest__c[] result1 = [select Id, OppCustomProject__c from OppCustomProjectRequest__c where OppCustomProject__c = :cp.Id];
        System.assertEquals(2, result1.size());

        OppCustomProjectRequest__c[] listI = new List<OppCustomProjectRequest__c>();
        listI.add(result1[0]);

        OppCustomProjectRequest__c[] listD = new List<OppCustomProjectRequest__c>();
        listD.add(result1[1]);

        OpportunityCustomProjectController.saveRequestLines(cp.Id, listI, listD);

        OppCustomProjectRequest__c[] result2 = [select Id, OppCustomProject__c from OppCustomProjectRequest__c where OppCustomProject__c = :cp.Id];
        System.assertEquals(1, result2.size());

    }

}