force-app/main/default/objects/OppCustomProject__c/OppCustomProject__c.object-meta.xml
<CustomObject>
    <description>Object to store opportunity&apos;s additional information on US custom project (Krion and similar products transformed by a fabricator).</description>
    <label>Opportunity Custom Project</label>
    <nameField>
        <label>Custom Project Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Custom Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppCustomProject__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>Delivery Needed By</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Related opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/fields/ProductManager__c.field-meta.xml
<CustomField>
    <fullName>ProductManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <description>Type of custom project</description>
    <label>Project Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALTISSIMA</fullName>
            </value>
            <value>
                <fullName>KRION</fullName>
            </value>
            <value>
                <fullName>KRION &amp; XTONE</fullName>
            </value>
            <value>
                <fullName>XTONE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <label>ProjectType</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/DataFactoryOppCustomProjects.cls
/**
* @author 		Ramón Prades
* @date 		July 2022
* @group 		Data Factotries
* @description 	Creates opportunities with Custom Projects attached
*/
public without sharing class DataFactoryOppCustomProjects {

    public static Boolean autoInsert = true;

    public static List<OppCustomProject__c> createRecords(Integer numRecords) {
        List<OppCustomProject__c> projects = new List<OppCustomProject__c>();
        Opportunity[] opps = DataFactoryOpportunity.createRetailOpportunities(1, numRecords);
        for  (Opportunity opp: opps ) {
            projects.add(createCustomProject(opp));
        }
        if (autoInsert && Test.isRunningTest()) {
            insert projects;
        }
        return projects;
    }

    private static OppCustomProject__c createCustomProject(Opportunity opp) {

        OppCustomProject__c cp = new OppCustomProject__c();
        cp.Opportunity__c = opp.Id;
        cp.ProjectType__c = 'KRION';
        cp.ProductManager__c = UserInfo.getUserId();
        cp.DeliveryDate__c = System.today();
        
        return cp;
        
    }

}