force-app/main/default/objects/Order/fields/Ordernum__c.field-meta.xml
<CustomField>
    <fullName>Ordernum__c</fullName>
    <label>XXX Ordernum</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/Pedidos_cabeceraSet__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>Pedidos_cabeceraSet</externalName>
    <label>Pedidos_cabeceraSet</label>
    <pluralLabel>Pedidos_cabeceraSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>Customer</description>
    <externalDeveloperName>Customer</externalDeveloperName>
    <label>Customer</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Dcurr__c.field-meta.xml
<CustomField>
    <fullName>Dcurr__c</fullName>
    <description>Dcurr</description>
    <externalDeveloperName>Dcurr</externalDeveloperName>
    <label>Dcurr</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Ddate__c.field-meta.xml
<CustomField>
    <fullName>Ddate__c</fullName>
    <description>Ddate</description>
    <externalDeveloperName>Ddate</externalDeveloperName>
    <label>Ddate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/DestinoMerc__c.field-meta.xml
<CustomField>
    <fullName>DestinoMerc__c</fullName>
    <description>DestinoMerc</description>
    <externalDeveloperName>DestinoMerc</externalDeveloperName>
    <label>DestinoMerc</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Dtotal__c.field-meta.xml
<CustomField>
    <fullName>Dtotal__c</fullName>
    <description>Dtotal</description>
    <externalDeveloperName>Dtotal</externalDeveloperName>
    <label>Dtotal</label>
    <precision>14</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/OpenF__c.field-meta.xml
<CustomField>
    <fullName>OpenF__c</fullName>
    <description>OpenF</description>
    <externalDeveloperName>OpenF</externalDeveloperName>
    <label>OpenF</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Salesoffic__c.field-meta.xml
<CustomField>
    <fullName>Salesoffic__c</fullName>
    <description>Salesoffic</description>
    <externalDeveloperName>Salesoffic</externalDeveloperName>
    <label>Salesoffic</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <description>status</description>
    <externalDeveloperName>status</externalDeveloperName>
    <label>status</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_posicionesSet__x/Pedidos_posicionesSet__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>Pedidos_posicionesSet</externalName>
    <label>Pedidos_posicionesSet</label>
    <pluralLabel>Pedidos_posicionesSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pedidos_posicionesSet__x/fields/kmein__c.field-meta.xml
<CustomField>
    <fullName>kmein__c</fullName>
    <description>kmein</description>
    <externalDeveloperName>kmein</externalDeveloperName>
    <label>Kmein</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_posicionesSet__x/fields/Netpr__c.field-meta.xml
<CustomField>
    <fullName>Netpr__c</fullName>
    <description>Netpr</description>
    <externalDeveloperName>Netpr</externalDeveloperName>
    <label>Netpr</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pedidos_posicionesSet__x/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity</description>
    <externalDeveloperName>Quantity</externalDeveloperName>
    <label>Quantity</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pedidos_posicionesSet__x/fields/Sqmetres__c.field-meta.xml
<CustomField>
    <fullName>Sqmetres__c</fullName>
    <description>Sqmetres</description>
    <externalDeveloperName>Sqmetres</externalDeveloperName>
    <label>Sqmetres</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pedidos_posicionesSet__x/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <externalDeveloperName>Status</externalDeveloperName>
    <label>Status</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_posicionesSet__x/fields/Vrkme__c.field-meta.xml
<CustomField>
    <fullName>Vrkme__c</fullName>
    <description>Vrkme</description>
    <externalDeveloperName>Vrkme</externalDeveloperName>
    <label>Vrkme</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SAPOrderReader.cls
/**
 * Clase para encapsular el acceso a pedidos SAP
 * Ramón Prades - February 2026
 *
 * Lee cabecera y líneas de SAP y devuelve los fresultados en un DTO consolidado
 * - 
 *
 * Design notes
 * - Los datos de SAP se leen de las tablas externas
 * - La idea es que esta clase devuelva el DTO con datos en vocabulario de negocio apra no tener que 
 *   lidiar con la estructura de las tablas externas en el resto del sistema
 */
public without sharing class SAPOrderReader {

    /* =========================================================
     * PUBLIC METHODS (API)
     * ========================================================= */

    public static B2BSalesDocContracts.OrderHeaderDTO readOrder(String sapId) {
        B2BSalesDocContracts.OrderHeaderDTO dto = SAPOrderReader.readHeader(sapId);
        if (dto != null) {
            dto.items = SAPOrderReader.readItems(sapId);
        }
        return dto;
    }

    public static B2BSalesDocContracts.OrderHeaderDTO  readHeader(String sapNumber) {
        B2BSalesDocContracts.OrderHeaderDTO header = null;
        Pedidos_cabeceraSet__x[] headers = [
            SELECT 
                Ordernum__c, Orderdate__c, Ddate__c, Status__c, Refer__c, Dnet__c, Dtax__c, Dtotal__c, Dcurr__c,
                Customer__c, Salesorg__c, Distchannel__c, Salesoffic__c, DestinoMerc__c
            FROM Pedidos_cabeceraSet__x
            WHERE Ordernum__c = :sapNumber            
        ];
        if (!headers.isEmpty()) {
            header = SAPOrderReader.mapHeader(headers[0]);
        }
        return header;
    }

    public static B2BSalesDocContracts.OrderItemDTO[] readItems(String sapNumber) {
        List<B2BSalesDocContracts.OrderItemDTO> lines = new List<B2BSalesDocContracts.OrderItemDTO>();
        Pedidos_posicionesSet__x[] items = [
            SELECT 
                Ordernum__c, Orderlin__c, Sku__c, Name__c, Quantity__c, Vrkme__c,
                Netpr__c, Kmein__c, Dcurr__c, Dnet__c, Dtax__c, Dtotal__c,
                Sqmetres__c, Status__c, OpenF__c
            FROM Pedidos_posicionesSet__x
            WHERE Ordernum__c = :sapNumber
            ORDER BY Orderlin__c
        ];
        for (Pedidos_posicionesSet__x item : items) {
            lines.add(SAPOrderReader.mapItem(item));
        }
        return lines;
    }

    /* =========================================================
     * PRIVATE METHODS
     * ========================================================= */

     @testVisible private static B2BSalesDocContracts.OrderHeaderDTO mapHeader(Pedidos_cabeceraSet__x header) {        
        B2BSalesDocContracts.OrderHeaderDTO  dto = new B2BSalesDocContracts.OrderHeaderDTO ();
        dto.orderNumber = header.Ordernum__c;
        dto.orderDate = header.Orderdate__c?.date();
        dto.deliveryDate = header.Ddate__c?.date();
        dto.status = header.Status__c;
        dto.poNumber = header.Refer__c;
        dto.net = header.Dnet__c;
        dto.tax = header.Dtax__c;
        dto.total = header.Dtotal__c;
        dto.currencyCode = header.Dcurr__c;
        dto.sapCustomerCode = header.Customer__c;
        dto.SalesOrg = header.Salesorg__c;
        dto.Channel = header.Distchannel__c;
        dto.SalesOffice = header.Salesoffic__c;
        dto.sapShipToCode = header.DestinoMerc__c;
        return dto;
    }

    @TestVisible private static B2BSalesDocContracts.OrderItemDTO  mapItem(Pedidos_posicionesSet__x item) {
        B2BSalesDocContracts.OrderItemDTO  dto = new B2BSalesDocContracts.OrderItemDTO ();
        dto.orderNumber = item.Ordernum__c;
        dto.lineNumber = Integer.valueOf(item.Orderlin__c ?? '0');
        dto.sku = item.Sku__c;
        dto.name = item.Name__c;
        dto.quantity = item.Quantity__c;
        dto.salesUnit = item.Vrkme__c;
        dto.netUnitPrice = item.Netpr__c;
        dto.netPriceUnit = item.Kmein__c;
        dto.currencyCode = item.Dcurr__c;
        dto.netAmount = item.Dnet__c;
        dto.taxAmount = item.Dtax__c;
        dto.totalAmount = item.Dtotal__c;
        dto.squareMetres = item.Sqmetres__c;
        dto.statusCode = item.Status__c;
        dto.openFlag = item.OpenF__c;
        return dto;
    }
}