force-app/main/default/objects/Order/fields/Ordernum__c.field-meta.xml
<CustomField>
    <fullName>Ordernum__c</fullName>
    <label>XXX Ordernum</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <description>Sap code of the order is coming from</description>
    <label>Sap Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_posicionesSet__x/Pedidos_posicionesSet__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>Pedidos_posicionesSet</externalName>
    <label>Pedidos_posicionesSet</label>
    <pluralLabel>Pedidos_posicionesSet</pluralLabel>
</CustomObject>

force-app/main/default/classes/NB2B_OrderSelector_Test.cls
@IsTest
public with sharing class NB2B_OrderSelector_Test {
    @TestSetup
	public static void setupData(){
		NB2B_SetupClassTest.setupAllData();
	}

	public static void testAll(){
		Test.startTest();
		orderSelector_Test();
		Test.stopTest();
	}

	@IsTest
	public static void orderSelector_Test(){
		Test.startTest();
		orderSelectorTest();
		Test.stopTest();
	}

	private static void orderSelectorTest() {
        Order order1 = NB2B_SetupClassTest.getOrder();

        Set<Id> setId = new set<id>();
        setId.add(order1.Id);
		List<Order> orderById = NB2B_OrderSelector.getOrderById(setId);

		List<Order> orderItemById = NB2B_OrderSelector.getOrderAndOrderItemById(order1.Id);

        List<String> stringList = new List<String>();
        stringList.add(order1.Sap_Id__c);
		List<Order> orderItemBySap = NB2B_OrderSelector.getOrderAndOrderItemFromSap(stringList);

        List<String> orderNumList = new List<String>();
        orderNumList.add(order1.Ordernum__c);
		List<Order> orderByOrderNum = NB2B_OrderSelector.getOrderByOrderNum(orderNumList);

        List<Pedidos_posicionesSet__x> pedidosByOrderNum = NB2B_OrderSelector.getPedidosPosicionesById(orderNumList);
	}

}