force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <description>Coutry of application of this price book. Required for the retail reference PB</description>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/IsForClaims__c.field-meta.xml
<CustomField>
    <fullName>IsForClaims__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True when the price book is the one used in claims</description>
    <label>Is For Claims</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/IsRetailReferencePricebook__c.field-meta.xml
<CustomField>
    <fullName>IsRetailReferencePricebook__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If check, it&apos;s the Reference Pricebook for the context</description>
    <label>Is Retail Reference Pricebook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/PriceType__c.field-meta.xml
<CustomField>
    <fullName>PriceType__c</fullName>
    <description>Indica qué precios se graban en los price book entries. Si &quot;PRICE UNIT&quot;, se usa el precio de SAP (por MT2 en bases). Si &quot;SALES UNIT&quot; se usa el precio calculado por unidad de venta.</description>
    <inlineHelpText>Indica qué precios se graban en los price book entries. Si &quot;PRICE UNIT&quot;, se usa el precio de SAP (por MT2 en bases). Si &quot;SALES UNIT&quot; se usa el precio calculado por unidad de venta.</inlineHelpText>
    <label>Price Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPR</fullName>
                <default>true</default>
                <label>Use Price Unit</label>
            </value>
            <value>
                <fullName>UMV</fullName>
                <label>Use Sales Unit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/SAPSync__c.field-meta.xml
<CustomField>
    <fullName>SAPSync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SI marcado, significa que se actualizan los entries según SAP</description>
    <label>SAP Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <description>Code of the Sales Org</description>
    <externalId>true</externalId>
    <label>Sales Org</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesPricebooksServiceTest.cls
/**
 * @author         Ramón Prades
 * @date           June 2024
 * @layer          Services
 * @description    Test class
*/
@isTest public class SalesPricebooksServiceTest {

    @testSetup public static void testSetup() {   
        Sales_Org__c sorg = new Sales_Org__c();     
        sorg.Name = 'Test SORG';
        sorg.CountryCode__c = 'US';
        sorg.SalesOrg__c = '610';
        insert sorg;

        Pricebook2 pb = new Pricebook2();
        pb.Name = 'Test Pricebook';
        pb.isActive = true;
        pb.SapSync__c = true;
        pb.CurrencyIsoCode = 'USD';
        pb.PriceType__c = 'UPR';
        pb.IsRetailReferencePricebook__c = true;
        pb.CountryCode__c = 'US';

        if (Test.isRunningTest()) {
            insert pb;
        }
    } // testSetup

    @isTest private static void testStandardOrder() {
        Order o = new Order();
        o.Type = SalesPricebooksService.ORDER_STANDARD_TYPE;
        o.SalesOrg__c = '610';
         
        Pricebook2 dbBook = [select Id from Pricebook2 limit 1];
        Pricebook2[] result = SalesPricebooksService.getOrderPricebooks(o);
        Assert.areEqual(1, result.size(), 'A result is expected');
        Assert.areEqual(dbBook.Id, result[0].Id, 'Wrong pricebook');
   }

   @isTest private static void testClaimsOrder() {
        Order o = new Order();
        o.Type = SalesPricebooksService.ORDER_REPLACEMENT_TYPE;
        o.CurrencyIsoCode = 'USD';
        o.SalesOrg__c = '610';

        Pricebook2 dbBook = [select Id from Pricebook2 limit 1];
        dbBook.IsForClaims__c = true;
        dbBook.CurrencyIsoCode = 'USD';
        update dbBook;

        Pricebook2[] result = SalesPricebooksService.getOrderPricebooks(o);
        Assert.areEqual(1, result.size(), 'A result is expected');
        Assert.areEqual(dbBook.Id, result[0].Id, 'Wrong pricebook');
    }

    @isTest private static void testWrongCurrency() {
        Order o = new Order();
        o.Type = SalesPricebooksService.ORDER_REPLACEMENT_TYPE;
        o.CurrencyIsoCode = 'GBP';
        o.SalesOrg__c = '610';

        Pricebook2 dbBook = [select Id from Pricebook2 limit 1];
        dbBook.IsForClaims__c = true;
        dbBook.CurrencyIsoCode = 'USD';
        update dbBook;

        Pricebook2[] result = SalesPricebooksService.getOrderPricebooks(o);
        Assert.areEqual(0, result.size(), 'No results expected');
    }

}