force-app/main/default/objects/SALES_OFFICE__c/SALES_OFFICE__c.object-meta.xml
<CustomObject>
    <description>Entidad custom que contiene el maestro de relaciones para transformar el código de la oficina de ventas por el nombre.</description>
    <label>Sales Office</label>
    <nameField>
        <label>Nombre de SALES_OFFICE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_OFFICE__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone</description>
    <label>Phone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>Código de la oficina de ventas</description>
    <externalId>true</externalId>
    <label>SalesOffice</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/WaitingList__c.field-meta.xml
<CustomField>
    <fullName>WaitingList__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the Sales Office Waiting List?</description>
    <label>Waiting List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/WaitingList__c.object-meta.xml
<CustomObject>
    <description>Manages waiting lists</description>
    <label>Waiting List</label>
    <nameField>
        <displayFormat>WL-{0000000}</displayFormat>
        <label>Waiting List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waiting Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WaitingList__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Office</label>
    <referenceTo>SALES_OFFICE__c</referenceTo>
    <relationshipLabel>Waiting Lists</relationshipLabel>
    <relationshipName>Waiting_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RESTWaitingList.cls
/**
* @author 			Ivan Losilla
* @date 			May 2021
* @group 			REST
* @description 	    REST service to create Waiting List persons
*/
@RestResource(urlMapping='/custom/waitinglist/*')
global class RESTWaitingList {

    @HttpGet
    global static void ping () {
        RestResponse response = RestContext.response;        
        response.statusCode = 200;
        response.responseBody = Blob.valueOf('{"hola":"mundo"}');
    }
    
    @HttpPost
    global static void create (String FirstName, String LastName, String Phone, String Email, String SalesOffice) {
        RestResponse response = RestContext.response;
        WaitingList__c wlPerson = null;
        try {
            if (String.isBlank(FirstName) || String.isBlank(LastName) || String.isBlank(Phone) || String.isBlank(SalesOffice)) {
                response.statusCode = 404;
                response.responseBody = Blob.valueOf('{"Message": "All fields are required!"}');
            } else {
                List<Sales_Office__c> salesOfficeDMLBase = [Select Id, SalesOffice__c from Sales_Office__c];
                List<Sales_Office__c> salesOfficeDML = [Select Id, SalesOffice__c from Sales_Office__c where SalesOffice__c =: SalesOffice];
                if (salesOfficeDML.size() == 0) {
                    response.statusCode = 404;
                    response.responseBody = Blob.valueOf('{"Message":"Sales Office not valid"}');
                } else {
                    wlPerson = new WaitingList__c(FirstName__c = FirstName,
                                                                LastName__c = LastName,
                                                                Phone__c = Phone,
                                                                Email__c = Email,
                                                                SalesOffice__c = salesOfficeDML[0].Id);
                    insert wlPerson;
                    WaitingList newWL = new WaitingList(wlPerson.Id);
                    newWL.sendNotificationNewWLItem();
                    response.statusCode = 204;
                    response.responseBody = Blob.valueOf('Object created!');
                }
            }

        } catch (ObjectExistsException ex) {
            response.statusCode = 404;
            response.responseBody = Blob.valueOf('{"Message": "Waiting List person failed!"}');
        }
    } // create
        
} // class