force-app/main/default/objects/Follow__c/Follow__c.object-meta.xml
<CustomObject>
    <description>Objeto que registra la suscripción de un usuario con un Account, Opportunity, etc</description>
    <label>Follow</label>
    <nameField>
        <displayFormat>FW-{00000000}</displayFormat>
        <label>Follow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cuenta a la que se ha suscrito el usuario</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Follows</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow__c/fields/ActivityId__c.field-meta.xml
<CustomField>
    <fullName>ActivityId__c</fullName>
    <description>Id of the Activity. Can be a Task or an Event</description>
    <label>Activity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Follow__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oportunidad a la que el usuario se ha suscrito</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Follows</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PorcelanosaSetting__c/PorcelanosaSetting__c.object-meta.xml
<CustomObject>
    <description>Object to store configuration values as KEY, SUBKEY and VALUE.

For example, GOOGLE_KEY, UK, 102-343</description>
    <label>Porcelanosa Setting</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Porcelanosa Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Porcelanosa Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PorcelanosaSetting__c/fields/Subkey__c.field-meta.xml
<CustomField>
    <fullName>Subkey__c</fullName>
    <description>Secondary key of the record. Please use capitals.</description>
    <inlineHelpText>Secondary key of the record. Please use capitals.</inlineHelpText>
    <label>SUBKEY</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PorcelanosaSetting__c/fields/Value1__c.field-meta.xml
<CustomField>
    <fullName>Value1__c</fullName>
    <description>Setting value</description>
    <label>Value 1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScriptSyncFollowRecordsCleaner.cls
/**
* @author Ivan Losilla
* @date April 2024
* @group Scripts
* @test ScriptSyncFollowsTest
* @description Gets from Follow all the registers of the last week, and check if the user still follows that register. If not, it gets deleted.
*/
global class ScriptSyncFollowRecordsCleaner implements Schedulable,Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
    private PorcelanosaSetting__c setting;

    public void execute(SchedulableContext sc) {
        System.debug('START SYNC CLEANER FOLLOWS');
        Database.executeBatch(this,10);
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        this.setting = [SELECT Id, Value1__c, IsActive__c FROM PorcelanosaSetting__c WHERE Key__c = 'SYNCFOLLOWS' and Subkey__c = 'ALL'];
        if (setting == null || setting.IsActive__c == false) {
            System.debug('SYNC FOLLOWS CLEANER NO ACTIVO');
            System.abortJob(bc.getJobId());
        }

        String query = 'select id,Account__c, Opportunity__c,ActivityId__c, OwnerId from Follow__c';
        System.debug('QUERY CLEANER: ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Follow__c> scope) {
        List<Follow__c> deleteFollowsList = new List<Follow__c>();

        System.debug('Follow Records: ' + scope.size());
        for (Follow__c follow : scope) {
            if (follow.ActivityId__c == null) {
                if (follow.Account__c != null) {
                    List<EntitySubscription> aux = [SELECT id FROM EntitySubscription WHERE SubscriberId =: follow.OwnerId AND ParentId =: follow.Account__c LIMIT 1];
                    if (aux.size() == 0) {
                        deleteFollowsList.add(follow);
                    }
                }
                if (follow.Opportunity__c != null) {
                    List<EntitySubscription> aux = [SELECT id FROM EntitySubscription WHERE SubscriberId =: follow.OwnerId AND ParentId =: follow.Opportunity__c LIMIT 1];
                    if (aux.size() == 0) {
                        deleteFollowsList.add(follow);
                    }
                }
            } /*else {
                List<EntitySubscription> aux = [SELECT id FROM EntitySubscription WHERE SubscriberId =: follow.OwnerId AND ParentId =: follow.ActivityId__c LIMIT 1];
                if (aux.size() == 0) {
                    deleteFollowsList.add(follow);
                }
            }*/
        }

        System.debug('List of elements to delete:');
        System.debug(deleteFollowsList);
        delete deleteFollowsList;
    }
    
    global void finish(Database.BatchableContext bc){
        System.debug('Finished');
    }

    @testVisible public String testFiller() {
        String s = 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        return s;
    }
}