force-app/main/default/objects/ContentVersion/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <description>Type of the document uploaded (for example, price proposal or shop drawing). Free text because can be used in multiple contexts.</description>
    <label>DocumentType</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/OppCustomProject__c.object-meta.xml
<CustomObject>
    <description>Object to store opportunity&apos;s additional information on US custom project (Krion and similar products transformed by a fabricator).</description>
    <label>Opportunity Custom Project</label>
    <nameField>
        <label>Custom Project Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Custom Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppCustomProject__c/fields/ShopDrawings__c.field-meta.xml
<CustomField>
    <fullName>ShopDrawings__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shop Drawings Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OppCustomProjectRequest__c/OppCustomProjectRequest__c.object-meta.xml
<CustomObject>
    <label>Opportunity Custom Project Request</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Custom Project Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppCustomProjectRequest__c/fields/BacksplashDetail__c.field-meta.xml
<CustomField>
    <fullName>BacksplashDetail__c</fullName>
    <label>Backsplash Detail</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loose/Standard</fullName>
                <label>Loose/Standard (KRION)</label>
            </value>
            <value>
                <fullName>1/2Standard</fullName>
                <label>½ Standard Continuous Flow (XTONE)</label>
            </value>
            <value>
                <fullName>1/2Random</fullName>
                <label>½ Random Pattern (XTONE)</label>
            </value>
            <value>
                <fullName>3/8 Random</fullName>
                <label>3/8 Random Pattern (XTONE)</label>
            </value>
            <value>
                <fullName>1/4Random</fullName>
                <label>¼ Random Pattern (XTONE)</label>
            </value>
            <value>
                <fullName>3/8  Bookmatched</fullName>
                <label>3/8  Bookmatched (XTONE)</label>
            </value>
            <value>
                <fullName>1/4Bookmatched</fullName>
                <label>¼ Bookmatched (XTONE)</label>
            </value>
            <value>
                <fullName>Coved/Moulded</fullName>
                <label>Coved/Moulded (KRION)</label>
            </value>
            <value>
                <fullName>Other option 1</fullName>
                <isActive>false</isActive>
                <label>Other option 1</label>
            </value>
            <value>
                <fullName>Other option 2</fullName>
                <isActive>false</isActive>
                <label>Other option 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppCustomProjectRequest__c/fields/BacksplashHeight__c.field-meta.xml
<CustomField>
    <fullName>BacksplashHeight__c</fullName>
    <label>Backsplash Height</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OppCustomProjectRequest__c/fields/ColorName__c.field-meta.xml
<CustomField>
    <fullName>ColorName__c</fullName>
    <label>Color Name/No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OppCustomProjectRequest__c/fields/Edge__c.field-meta.xml
<CustomField>
    <fullName>Edge__c</fullName>
    <label>Edge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XTONE Square Mitered Edge</fullName>
            </value>
            <value>
                <fullName>XTONE Eased (Only for ½ in)</fullName>
            </value>
            <value>
                <fullName>KRION Eased Edge</fullName>
            </value>
            <value>
                <fullName>KRION ¼ Beveled</fullName>
            </value>
            <value>
                <fullName>KRION Demi-Bullnosed</fullName>
            </value>
            <value>
                <fullName>Other (Explain in Notes)</fullName>
            </value>
            <value>
                <fullName>ALTISSIMA ¼ Bevel</fullName>
            </value>
            <value>
                <fullName>ALTISSIMA Demi-Bullnose</fullName>
            </value>
            <value>
                <fullName>ALTISSIMA Eased Edge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppCustomProjectRequest__c/fields/EdgeThickness__c.field-meta.xml
<CustomField>
    <fullName>EdgeThickness__c</fullName>
    <label>Edge Thickness</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OppCustomProjectRequest__c/fields/Finish__c.field-meta.xml
<CustomField>
    <fullName>Finish__c</fullName>
    <label>Finish</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALTISSIMA Honed</fullName>
            </value>
            <value>
                <fullName>ALTISSIMA Polished</fullName>
            </value>
            <value>
                <fullName>KRION Matte</fullName>
            </value>
            <value>
                <fullName>KRION Satin</fullName>
            </value>
            <value>
                <fullName>XTONE Nature</fullName>
            </value>
            <value>
                <fullName>XTONE Polished</fullName>
            </value>
            <value>
                <fullName>XTONE Silk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppCustomProjectRequest__c/fields/OppCustomProject__c.field-meta.xml
<CustomField>
    <fullName>OppCustomProject__c</fullName>
    <label>Custom Project</label>
    <referenceTo>OppCustomProject__c</referenceTo>
    <relationshipName>CustomProjectRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppCustomProjectRequest__c/fields/ProductDescription__c.field-meta.xml
<CustomField>
    <fullName>ProductDescription__c</fullName>
    <label>Product Description</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kitchen_Countertop</fullName>
                <label>Kitchen Countertop</label>
            </value>
            <value>
                <fullName>Kitchen_Island</fullName>
                <label>Kitchen Island</label>
            </value>
            <value>
                <fullName>Vanity_Top</fullName>
                <label>Vanity Top</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Other (Explain in Notes)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppCustomProjectRequest__c/fields/Underlayment__c.field-meta.xml
<CustomField>
    <fullName>Underlayment__c</fullName>
    <label>Underlayment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard to match KRION/XTONE</fullName>
            </value>
            <value>
                <fullName>Plywood/MDF with Melamine</fullName>
            </value>
            <value>
                <fullName>Canada - Plywood MDF/Painted</fullName>
            </value>
            <value>
                <fullName>Outdoor Use - Marine Grade Plywood</fullName>
            </value>
            <value>
                <fullName>Plywood/MDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityCustomProjectController.cls
/**
* @author 		Ramón Prades
* @date 		May 2021
* @group 		Opportunities
* @description 	Opportunity Custom Project controller
*/
public class OpportunityCustomProjectController {
    /**
     * Sets the custom project default values 
     */
    @AUraEnabled public static ProjectDTO readCustomProjectData(String opportunityId, String customProjectId) {
        ProjectDTO dto = new ProjectDTO();
        dto.isNew = (customProjectId == null);
        dto.hasQuote = false;
        dto.hasDrawing = false;
        dto.opportunity = [select Id, Name, OwnerId, Owner.Name, StageName, CurrencyIsoCode from Opportunity where Id = :opportunityId limit 1];
        dto.productManagers = UserUtils.getProductManagers('US');
        dto.requestLines = readRequestLines(customProjectId);
        dto.attachments = readAttachments(customProjectId);
        dto.location = InternationalAddress.fromOpportunity(opportunityId).format();
        dto.userName = UserInfo.getName();
        dto.currencyCode = dto.opportunity.CurrencyIsoCode;
        setAttachmentFlags(dto);
        setUserProperties(dto);
        return dto;
    } // readCustomProjectData

    /**
     * Validates & saves the custom project
     * OBSOLETE: No se usa de momento para validar nada en servidor
     */
    @AuraEnabled public static ResultDTO saveCustomProject(OppCustomProject__c customProject) {
        ResultDTO dto = new ResultDTO();
        dto.success = false;
        if (validateCustomProject(customProject)) {
            if (customProject.Id == null) {
                insert customProject;
                dto.success = true;
                dto.command = 'INSERT';
                dto.arg = customProject.Id;
            } else {
                update customProject;
                dto.success = true;
                dto.command = 'MODIFY';
                dto.arg = customProject.Id;
            }
            return dto;
        }
        return dto;
    } // saveCustomProject

    /**
     * Saves the request lines
     */
    @AuraEnabled public static  OppCustomProjectRequest__c[] saveRequestLines(String projectId, OppCustomProjectRequest__c[] requestLines,  OppCustomProjectRequest__c[] deleteLines) {
        for (OppCustomProjectRequest__c req :requestLines) {
            if (req.OppCustomProject__c == null) {
                req.OppCustomProject__c = projectId;
            }
        }
        upsert requestLines;
        delete deleteLines;

        return requestLines;
    } // saveRequestLines

    /**
     * Actions after uploading a file
     */
    @AuraEnabled public static void afterUploadFile(String projectId, List<String> contentIds, String contentType) {
        if (String.isNotEmpty(contentType)) {
            ContentVersion[] versions = [select Id, contentDocumentId, CreatedDate, CreatedById, DocumentType__c from ContentVersion where Id in :contentIds];
            for (ContentVersion version :versions) {
                version.DocumentType__c = contentType;
            }            
            update versions;
            if (contentType == 'DRAWING'||contentType == 'QUOTE') {                
                OppCustomProject__c cp = [select Id, ShopDrawings__c from OppCustomProject__c where id = :projectId limit 1];
                if (!cp.ShopDrawings__c) {
                    cp.ShopDrawings__c = true;
                    update cp;
                }
                if (SystemSettings.CPNotificationsEnabled) {
                    CustomProjectMailer mailer = new CustomProjectMailer(projectId, contentType);
                    mailer.setMailAttachments(contentIds);
                    ID jobId = System.enqueueJob(mailer);
                }
            }
        }
    } // contentIds

    /**
     * Deletes a list of attachments
     */
    @AuraEnabled public static void deleteAttachments(String projectId, List<String> documentIds) {
        ContentDocument[] documents = [select Id from ContentDocument where Id in :documentIds];
        if (documents.size() > 0) {
            delete documents;
            setDrawingFlag(projectId);
        }
    } // deleteAttachments

    /*********************************************************/    
    /********************* INNER CLASSES *********************/
    /*********************************************************/
    /**
     * Inner class to return a set of data to the component
     */
    public class ProjectDTO {
        @AUraEnabled public Boolean isNew;
        @AuraEnabled public String currencyCode;
        @AuraEnabled public Opportunity opportunity;
        @AuraEnabled public User[] productManagers;
        @AuraEnabled public Boolean hasQuote;
        @AuraEnabled public Boolean hasDrawing;
        @AuraEnabled public List<OppCustomProjectRequest__c> requestLines;
        @AuraEnabled public String location;
        @AuraEnabled public String userName;
        @AuraEnabled public List<AttachmentDTO> attachments;
        @AuraEnabled public Boolean isProductManager = false;
        @AuraEnabled public Boolean isProjectsStaff = false;
        @AuraEnabled public Boolean isAdmin = false;
    } // inner class

    public class AttachmentDTO {
        @AuraEnabled public String id;        
        @AuraEnabled public String fileName;        
        @AuraEnabled public DateTime createdDate;        
        @AuraEnabled public String createdBy;        
        @AuraEnabled public String documentType; 
        @AuraEnabled public String contentDescription; 
        @AuraEnabled public String contentVersionId;
    }

    /**
     * Inner class to return the result of the save operation
     */
    public class ResultDTO {
        @AuraEnabled public Boolean success = false;     
        @AuraEnabled public String command;     
        @AuraEnabled public String arg;     
    }

    /*********************************************************/
    /******************** PRIVATE METHODS ********************/
    /*********************************************************/
    private static Boolean validateCustomProject(OppCustomProject__c projectId) {
        return true;
    } // validateCustomProject

    private static List<OppCustomProjectRequest__c> readRequestLines(Id projectId) {
        List<OppCustomProjectRequest__c> lines = new List<OppCustomProjectRequest__c>();
        if (projectId != null) {
            lines = [
                select 
                    Id, isDeleted, BacksplashDetail__c, BacksplashHeight__c, ColorName__c,
                    OppCustomProject__c, Edge__c, EdgeThickness__c,Finish__c,
                    ProductDescription__c, Name, Underlayment__c                
                from OppCustomProjectRequest__c
                where OppCustomProject__c = :projectId
                and isDeleted = false
                order by Name
            ];            
        }
        return lines;
    } // readRequestLines

    private static void setDrawingFlag(Id projectId) {
        List<ContentDocumentLink> links = [select contentDocumentId from ContentDocumentLink where LinkedEntityId  = :projectId];
        List<Id> ids = new List<Id>();
        for (ContentDocumentLink link :links) {
            ids.add(link.contentDocumentId);
        }
        // prepares a map of versions (a document can have several versions)
        Map<String, ContentVersion> versions = new Map<String, ContentVersion>();
        for (ContentVersion cv : [select Id, contentDocumentId, CreatedDate, CreatedById, DocumentType__c from ContentVersion where contentDocumentId in :ids order by createdDate desc]) {
            if (!versions.containsKey(cv.contentDocumentId)) {
                versions.put(cv.contentDocumentId, cv);
            }
        }
    } // setDrawingFlag

    private static List<AttachmentDTO> readAttachments(Id projectId) {        
        if (projectId == null ) {
            return new List<AttachmentDTO>();
        }

        List<ContentDocumentLink> links = [select contentDocumentId from ContentDocumentLink where LinkedEntityId  = :projectId];
        List<Id> ids = new List<Id>();
        for (ContentDocumentLink link :links) {
            ids.add(link.contentDocumentId);
        }
        // prepares a map of versions (a document can have several versions)
        Map<String, ContentVersion> versions = new Map<String, ContentVersion>();
        for (ContentVersion cv : [select Id, contentDocumentId, CreatedDate, CreatedById, DocumentType__c from ContentVersion where contentDocumentId in :ids order by createdDate desc]) {
            if (!versions.containsKey(cv.contentDocumentId)) {
                versions.put(cv.contentDocumentId, cv);
            }
        }
        List<ContentDocument> docs = [select Id, Title, Description, CreatedDate, FileExtension, OwnerId, Owner.Name from ContentDocument where id in :ids order by createdDate];
        AttachmentDTO[] atts = new List<AttachmentDTO>();
        for (ContentDocument doc :docs) {
            AttachmentDTO att = new AttachmentDTO();            
            att.id = doc.Id;            
            att.fileName = doc.Title + '.' + doc.FileExtension;
            att.createdDate = doc.createdDate;
            att.createdBy = doc.Owner.Name;
            att.documentType = '';
            ContentVersion version = versions.get(doc.Id);
            if (version != null) {
                att.documentType = version.documentType__c;
                att.contentVersionId = version.Id;
            }            
            atts.add(att);
        }
        return atts;
    } // readAttachments

    private static void setAttachmentFlags(ProjectDTO dto) {
        dto.hasQuote = false;
        dto.hasDrawing = false;
        for (AttachmentDTO att :dto.attachments) {
            switch on att.documentType {
                when 'QUOTE'    { dto.hasQuote = true;   }
                when 'DRAWING'  { dto.hasDrawing = true; }
            }
        }
    } // setFlagAttachments

    private static void setUserProperties(ProjectDTO dto) {
        dto.isAdmin = UserUtils.isAdministrator();
        dto.isProductManager = false;
        for (User manager : dto.productManagers) {
            if (manager.Id == UserInfo.getUserId()) {
                dto.isProductManager = true;
            }
        }
        dto.isProjectsStaff = false;
        for (User staff : UserUtils.getProjectsStaff('US')) {
            if (staff.Id == UserInfo.getUserId()) {
                dto.isProjectsStaff = true;
            }
        }
    } // setUserProperties    

} // class