force-app/main/default/objects/Distribution_Channel__c/Distribution_Channel__c.object-meta.xml
<CustomObject>
    <label>Distribution Channel</label>
    <nameField>
        <label>Distribution Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_OFFICE__c/SALES_OFFICE__c.object-meta.xml
<CustomObject>
    <description>Entidad custom que contiene el maestro de relaciones para transformar el código de la oficina de ventas por el nombre.</description>
    <label>Sales Office</label>
    <nameField>
        <label>Nombre de SALES_OFFICE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>User accepts in store appointments</description>
    <inlineHelpText>Please tick this box if the user accepts store appointments</inlineHelpText>
    <label>Store Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/countries__c.field-meta.xml
<CustomField>
    <fullName>countries__c</fullName>
    <description>List of countries where the user can work</description>
    <label>Countries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Default_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Organization__c</fullName>
    <description>La organización de ventas por defecto para el comercial</description>
    <inlineHelpText>The default sales organization for sales and distribution</inlineHelpText>
    <label>Default Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Distribution_channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel__c</fullName>
    <label>Distribution channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Distribution_channel_default__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel_default__c</fullName>
    <label>Distribution channel default</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Sales Office from Sales Org default</description>
    <inlineHelpText>Sales Office from Sales Org default</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Default_Sales_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Team_Manager__c.field-meta.xml
<CustomField>
    <fullName>Team_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si un Comercial es o no el Responsable de la Tienda. Puede haber varios responsables en la misma Tienda</description>
    <inlineHelpText>Indicates whether or not a commercial is the store manager. There can be several people in charge in the same store</inlineHelpText>
    <label>Team Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DataFactoryUser.cls
/**
* @author 			Ramón Prades
* @date 			November-2020
* @group 			Data Factories
* @description 	    User Data Factories. Should replace User_TestDataFactory
*/
public class DataFactoryUser {

    public static Boolean autoInsert = true;

    /**
     * Creates a UK administrator
     */
    public static User createUKAdmin() {
        DataFactoryOrganization.createData();
        String email = 'ukadmin@ukuser.cxm';        
        User user = new User(Alias = 'tstuka', 
            Email = email,
            EmailEncodingKey ='ISO-8859-1', 
            LastName ='Johnson', 
            CountryCode = 'GB',
            Country = 'United Kingdom',
            ProfileId = getAdminProfile(), 
            UserName = email,
            Sales_Office__c = '2552',
            Sales_Org__c = OrganizationCommons.ORG_SOUTH_EAST + ';' + OrganizationCommons.ORG_NORTH_WEST,
            Default_Sales_Organization__c =OrganizationCommons.ORG_SOUTH_EAST,
            Distribution_Channel__c = '60;70', 
            Distribution_channel_default__c = '70',
            TimeZoneSidKey = 'GMT',
            LocaleSidKey = 'en_GB',
            LanguageLocaleKey = 'en_US',
            Team_Manager__c = TRUE);
        if (autoInsert) {
            insert user;
        }
        return user;
    } // createUKAdmin

    /**
     * Creates a UK user
     */    
    public static User createUKUser() { 
        return createUKUsers(1)[0];
    } // createUKUser

    /**
     * Creates a UK user
     */    
    public static List<User> createUKUsers(Integer numUsers) { 
        
        DataFactoryOrganization.createData();
        List<User> users = new List<User>();
        Profile profile = [Select Id From Profile Where Name='Standard Retail' LIMIT 1][0];

        Map<String, String> currentOrgsMap = PicklistCommons.getValuesSwaped(User.Sales_Org__c);
        
        for (Integer i = 0; i<numUsers; i++) {
            String email = 'ukuser@ukuser' + i + '.cxm';        
            User user = new User(Alias = 'USER' + i, 
                Email = email,
                EmailEncodingKey ='ISO-8859-1', 
                LastName ='Johnson ' + i, 
                CountryCode = 'GB',
                countries__c = 'GB',
                Country = 'United Kingdom',
                ProfileId = profile.Id, 
                UserName = email,
                Sales_Office__c = '2552',
                Sales_Org__c = OrganizationCommons.ORG_SOUTH_EAST + ';' + OrganizationCommons.ORG_NORTH_WEST,
                Default_Sales_Organization__c =OrganizationCommons.ORG_SOUTH_EAST,
                Distribution_Channel__c = '60;70', 
                Distribution_channel_default__c = '70',
                TimeZoneSidKey = 'GMT',
                LocaleSidKey = 'en_GB',
                LanguageLocaleKey = 'en_US',
                Appointment__c = true,
                Team_Manager__c = TRUE);
            users.add(user);
        }
        if (autoInsert) {
            insert users;
        }
        return users;
    } // createUKUser
  
  

    private static Id getNonAdminProfile() {
        Id profile = null;
        String admins = SystemSettings.adminProfiles;
        if ( admins <> null ) {
            List<String> lista = admins.split(';');
            for (String profileId : lista ) {
                try {
                    Profile p = [select Id from Profile where id != :profileId limit 1][0];                                
                    profile = p.Id;
                    break;
                } catch (ListException lex) {}
            } // for
        }
        return profile;
    } // getAdminProfile

    private static Id getAdminProfile() {
        Id profile = null;
        String admins = SystemSettings.adminProfiles;
        if ( admins <> null ) {
            List<String> lista = admins.split(';');
            for (String profileId : lista ) {
                try {
                    Profile p = [select Id from Profile where id = :profileId limit 1][0];                                
                    profile = p.Id;
                    break;
                } catch (ListException lex) {}
            } // for
        }
        return profile;
    } // getAdminProfile

}