force-app/main/default/objects/Distribution_Channel__c/Distribution_Channel__c.object-meta.xml
<CustomObject>
    <label>Distribution Channel</label>
    <nameField>
        <label>Distribution Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_OFFICE__c/SALES_OFFICE__c.object-meta.xml
<CustomObject>
    <description>Entidad custom que contiene el maestro de relaciones para transformar el código de la oficina de ventas por el nombre.</description>
    <label>Sales Office</label>
    <nameField>
        <label>Nombre de SALES_OFFICE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>User accepts in store appointments</description>
    <inlineHelpText>Please tick this box if the user accepts store appointments</inlineHelpText>
    <label>Store Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Commercial_Type__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Type__c</fullName>
    <label>Commercial Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/countries__c.field-meta.xml
<CustomField>
    <fullName>countries__c</fullName>
    <description>List of countries where the user can work</description>
    <label>Countries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Default_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Organization__c</fullName>
    <description>La organización de ventas por defecto para el comercial</description>
    <inlineHelpText>The default sales organization for sales and distribution</inlineHelpText>
    <label>Default Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Distribution_channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel__c</fullName>
    <label>Distribution channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Distribution_channel_default__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel_default__c</fullName>
    <label>Distribution channel default</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Does_this_position_have_a_sales_budget__c.field-meta.xml
<CustomField>
    <fullName>Does_this_position_have_a_sales_budget__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <label>Does this position have a sales budget?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Es_Comisionista__c.field-meta.xml
<CustomField>
    <fullName>Es_Comisionista__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Comisionista?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Execution_Context__c.field-meta.xml
<CustomField>
    <fullName>Execution_Context__c</fullName>
    <description>User&apos;s execution context</description>
    <label>Execution Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <label>DEUTSCHLAND</label>
            </value>
            <value>
                <fullName>ZA</fullName>
                <label>SOUTH AFRICA</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>DENMARK</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>UNITED STATES</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>FRANCE</label>
            </value>
            <value>
                <fullName>GB</fullName>
                <label>UNITED KINGDOM</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>SPAIN</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>POLAND</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>SWITZERLAND</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>ITALY</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>CANADA</label>
            </value>
            <value>
                <fullName>JP</fullName>
                <label>JAPAN</label>
            </value>
            <value>
                <fullName>VO</fullName>
                <label>VOID</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>BELGIUM</label>
            </value>
            <value>
                <fullName>PEXP</fullName>
                <label>PORCELANOSA EXPORT</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>AUSTRALIA</label>
            </value>
            <value>
                <fullName>SE</fullName>
                <label>SCANDINAVIA</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>ISRAEL</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>CHILE</label>
            </value>
            <value>
                <fullName>RD</fullName>
                <label>REPUBLICA DOMINICANA</label>
            </value>
            <value>
                <fullName>DEFAULT</fullName>
                <isActive>false</isActive>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>FLOWTESTUK</fullName>
                <isActive>false</isActive>
                <label>FLOWTESTUK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/kunnr__c.field-meta.xml
<CustomField>
    <fullName>kunnr__c</fullName>
    <label>User&apos;s rep code in SAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Sales Office from Sales Org default</description>
    <inlineHelpText>Sales Office from Sales Org default</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Default_Sales_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/SAP_Pass__c.field-meta.xml
<CustomField>
    <fullName>SAP_Pass__c</fullName>
    <label>SAP Pass</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SAP_User__c.field-meta.xml
<CustomField>
    <fullName>SAP_User__c</fullName>
    <label>SAP User</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UsersSelector.cls
/**
* @author 		Ivan Losilla
* @date 		June 2022
* @group 		Users
* @description 	users selector class
*/
public class UsersSelector extends zflib_SObjectSelector  {
    public Schema.SObjectType getSObjectType(){
        return User.sObjectType;
    }

    public List<User> selectById(Set<Id> recordIds){
        return (List<User>) selectSObjectsById(recordIds);
    }

    public User selectById(Id recordId){
        List<User> listUsers = (List<User>) selectSObjectsById(new Set<Id>{recordId});
        if (listUsers.size() == 1) {
            return listUsers[0];
        }
        return null;
    }

    public List<User> selectByRepCode(Set<String> repCodes) {
        return Database.query(newQueryFactory().setCondition('kunnr__c in :repCodes').toSOQL());
    } // selectByRepCode
   
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            
            // Main info fields
            User.Id,
            User.Username,
            User.FirstName,
            User.LastName,
            User.Name,
            User.LanguageLocaleKey,
            User.TimeZoneSidKey,
            User.Phone,
            User.MobilePhone,
            User.Email,
            
            //Classification fields
            User.UserRoleId,
            User.UserType,
            User.ProfileId,
            User.Commercial_Type__c,
            User.Es_Comisionista__c,
            User.Does_this_position_have_a_sales_budget__c,
            
            // Other info fields
            User.Default_Sales_Organization__c,
            User.Distribution_channel_default__c,
            User.Distribution_channel__c,
            User.Sales_Office__c,
            User.Sales_Org__c,
            User.Appointment__c,
            User.kunnr__c,
            User.Countries__c,
            User.SAP_Pass__c,
            User.SAP_User__c,
            
            // Address fields
            User.CountryCode,

            // Admin fields
            User.CreatedById,
            User.CreatedDate,
            User.IsActive,
            User.Execution_Context__c,
            User.LastLoginDate
        };
    }
}