force-app/main/default/objects/Distribution_Channel__c/Distribution_Channel__c.object-meta.xml
<CustomObject>
    <label>Distribution Channel</label>
    <nameField>
        <label>Distribution Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationOrder__c/InstallationOrder__c.object-meta.xml
<CustomObject>
    <description>Object to follow up the progress of the installation service. It is the continuation of the Installation Request (InstallationRequest__c)</description>
    <label>Installation Order</label>
    <nameField>
        <label>Installation Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationOrder__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <inlineHelpText>Enter the date the installation works will end</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/Installation_Request__c.field-meta.xml
<CustomField>
    <fullName>Installation_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Request</label>
    <referenceTo>InstallationRequest__c</referenceTo>
    <relationshipLabel>Installation Orders</relationshipLabel>
    <relationshipName>Installation_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Installation_Request__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <inlineHelpText>Enter the date the installation works will begin</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Installation_order_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/InstallationRequest__c.object-meta.xml
<CustomObject>
    <description>Class to store and follow the installation request of our products. This is a service certain showrooms offer through a list of authorised installers.</description>
    <label>Installation Request</label>
    <nameField>
        <label>Installation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationRequest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Opportunity this installation is for</description>
    <inlineHelpText>Please enter the opportunity this installation is for</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Installation Requests</relationshipLabel>
    <relationshipName>Installation_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please select the sales organization that will invoice this installation</inlineHelpText>
    <label>Sales Organization</label>
    <referenceTo>Sales_Org__c</referenceTo>
    <relationshipLabel>Installation Requests</relationshipLabel>
    <relationshipName>Installation_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <defaultValue>&quot;New Request&quot;</defaultValue>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InstallationStates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installer__c/Installer__c.object-meta.xml
<CustomObject>
    <description>Define accounts that can act as installers in a sales organisation</description>
    <label>Installer</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Installer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Installer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installers</relationshipLabel>
    <relationshipName>Installers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installer__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/countryCode__c.field-meta.xml
<CustomField>
    <fullName>countryCode__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distribution Channel</label>
    <referenceTo>Distribution_Channel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Default Sales Org of the User who created the Opportunity</description>
    <label>Sales Org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State / Province</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Distribution_channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel__c</fullName>
    <label>Distribution channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <description>Code of the Sales Org</description>
    <externalId>true</externalId>
    <label>Sales Org</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Distribution_channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel__c</fullName>
    <label>Distribution channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Installation_order_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Installation</fullName>
        <default>true</default>
        <label>New Installation</label>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing</fullName>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Unsatisfied</fullName>
    </customValue>
    <description>InstallationOrder states picklist</description>
    <masterLabel>Installation order State</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/InstallationStates.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Request</fullName>
        <default>true</default>
        <label>New Request</label>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>3D Design</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Estimation</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Won</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>States of Installation Requests</description>
    <masterLabel>Installation States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InstallationUtil.cls
/**
* @author 	Ramón Prades
* @date 	July 2020
*
* @group 	Opportunities
* @group-content ../../ApexDocContent/Opportunities.htm
*
* @description Utility meethods for Installation Requests and Installation orders
*/
public class InstallationUtil {
    
    public static String newState = 'New Request';				// New state
    public static String acceptedState = 'Site Survey';			// Installer accepted the request
    public static String rejectedState = 'Rejected';			// Installer rejected the request
    public static List<String> closedStateRequest = new List<String>{'Closed Won', 'Closed Lost', 'Rejected'};
    public static List<String> closedStateOrder = new List<String>{'Customer Satisfied', 'Customer Unsatisfied'};

    /**
    * @description Searches installation orders related to an installation request
 	* @param Installation request id 
 	* @return The list of installation orders
 	*/    
    public static List<InstallationOrder__c> getInstallationOrders(String requestId) {
    	return [select Id from InstallationOrder__c where Installation_Request__c = :requestId ];
    } // getInstallationOrders
    
    public static Boolean hasInstallationRequest(String oppId) {
        List<InstallationRequest__c> results = [select Id from InstallationRequest__c where Opportunity__c = :oppId];
        return (results.size() > 0);
    } // hasInstallationRequest

    /**
     * @description	Checks if the installation is in Accepted state
     * @param 		The request
     * @return		true if in accepted state
     */
    public static Boolean isRequestAccepted(InstallationRequest__c request) {
       return (request.State__c == InstallationUtil.acceptedState);
    } // isRequestAccepted

    /**
     * @description	Checks if the installation is in New state
     * @param 		The request
     * @return		true if in new state
     */
    public static Boolean isRequestNew(InstallationRequest__c request) {
       return (request.State__c == InstallationUtil.newState || request.State__c == null);
    } // isRequestNew
    
    /**
     * @description	Checks if the installation is in Rejected state
     * @param 		The request
     * @return		true if in new state
     */
    public static Boolean isRequestRejected(InstallationRequest__c request) {
       return (request.State__c == InstallationUtil.rejectedState);
    } // isRequestNew

    /**
     * @description	Checks if the installation Request is closed
     * @param 		The request
     * @return		true if not closed
     */
    public static Boolean isRequestClosed(InstallationRequest__c request) {
        return InstallationUtil.closedStateRequest.contains(request.State__c);
     } // isRequestNew
 
     /**
      * @description	Checks if the installation Order is closed
      * @param 		The request
      * @return		true if not closed
      */
     public static Boolean isOrderClosed(InstallationOrder__c inso) {
        return InstallationUtil.closedStateOrder.contains(inso.State__c);
     } // isRequestNew
 
     public static String requestNextActionLabel(InstallationRequest__c request) {
         if (request.State__c == 'New Request') {
             return Label.insr_next_newrequest;
         }
         if (request.State__c == 'Site Survey') {
             return Label.insr_next_sitesurvey;
         }
         if (request.State__c == '3D Design') {
             return Label.insr_next_3ddesign;
         }
         if (request.State__c == 'Cost Estimation') {
             return Label.insr_next_costestimation;
         }
         if (request.State__c == 'Quote Preparation') {
             return Label.insr_next_quotepreparation;
         }
         if (request.State__c == 'Quote Sent') {
             return Label.insr_next_quotesent;
         }
         return '';        
     }
 
     public static String orderNextActionLabel(InstallationOrder__c inso) {
         if (inso.State__c == 'New Installation') {
             return Label.inso_next_newinstallation;
         }
         if (inso.State__c == 'Ongoing') {
             if (inso.EndDate__c == null) {
                 return Label.inso_next_ongoing;
             }
             return Label.inso_next_ongoing + ' ' + inso.EndDate__c;
         }
         if (inso.State__c == 'Scheduled') {
             if (inso.StartDate__c == null) {
                 return Label.inso_next_scheduled;
             }
             return Label.inso_next_scheduled + ' ' + inso.StartDate__c;
         }
         if (inso.State__c == 'Finished') {
             return Label.inso_next_finished;
         }
         return '';        
     }
    
	/**
	 * Returns the installer assigned to a post code
     *  Old version per Post Code
	 *
    public static List<Id> getInstallers(String country, String postCode) {
        PostCodeObjectFinder objFinder = new PostCodeObjectFinder('INSTALLER');        
        objFinder.countryCode = country;
        objFinder.postCode = postCode;
        return new List<String>(objFinder.find());
    } // getInstallers
    */
    public static List<Id> getInstallers(String salesOrgs) {
        List<Id> result = new List<Id>();
        List<String> orgs = salesOrgs.split(';');
        List<Installer__c> installers = [select SalesOrg__c, Account__c from Installer__c where SalesOrg__c in :orgs];
        for (Installer__c ins :installers) {
            if (!result.contains(ins.Account__c)) {
                result.add(ins.Account__c);
            }
        }
        return result;
    } // getInstallers

    
    /**
     * Returns the installer for an opportunity
     */
    public static List<Id> getOpportunityInstallers(Id idOpportunity) {
        // Opportunity opp = [select Id, countryCode__c, Postcode__c from Opportunity where id = :idOpportunity][0];
        // return InstallationUtil.getInstallers(opp.countryCode__c, opp.Postcode__c);
        Opportunity opp = [select Id, countryCode__c, Postcode__c, OwnerId, Owner.Sales_Org__c from Opportunity where id = :idOpportunity limit 1];
        List<Id> installers = new List<Id>();
        if (String.isNotBlank(opp.Owner.Sales_Org__c)) {
            installers =InstallationUtil.getInstallers(opp.Owner.Sales_Org__c);
        }
        return installers;
    } // getOpportunityInstaller
    
    /**
     * Checks if the current user has access to the installations
     */
    public static Boolean hasInstallations() {
        return (checkChannel() && checkSalesOrgs());
	} // hasInstallations
    
    private static Boolean checkChannel() {
    	String channels = [select Distribution_Channel__c from User where id = :UserInfo.getUserId() limit 1].Distribution_Channel__c;
        return (channels.contains('60'));
    } // checkChannel
    
    private static Boolean checkSalesOrgs() {
		List<String> salesOrgs = UserUtils.getSalesOrgs();
        for (String salesOrg :salesOrgs) {
            RegionalSettings settings = new RegionalSettings(salesOrg);
            if (settings.installationsEnabled) {
                return true;
            }
        }
        return false;
    } // checkSalesOrgs
    
} // class