force-app/main/default/objects/OppPriceRequestHeader__c/OppPriceRequestHeader__c.object-meta.xml
<CustomObject>
    <label>Price Request Header</label>
    <nameField>
        <displayFormat>OPRH-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Request Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppPriceRequestHeader__c/fields/NeededBy__c.field-meta.xml
<CustomField>
    <fullName>NeededBy__c</fullName>
    <label>Products Needed By</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OppPriceRequestHeader__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Price Request</relationshipLabel>
    <relationshipName>OppPriceRequestHeaders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppPriceRequestHeader__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>FINISHED</fullName>
            </value>
            <value>
                <fullName>NEW</fullName>
                <default>true</default>
                <label>NEW</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppPriceRequestItem__c/OppPriceRequestItem__c.object-meta.xml
<CustomObject>
    <label>Price Request Item</label>
    <nameField>
        <displayFormat>OPRI-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppPriceRequestItem__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Pricebook Price per unit</description>
    <label>Customer Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OppPriceRequestItem__c/fields/PriceRequestHeader__c.field-meta.xml
<CustomField>
    <fullName>PriceRequestHeader__c</fullName>
    <label>Price Request Header</label>
    <referenceTo>OppPriceRequestHeader__c</referenceTo>
    <relationshipLabel>Price Request Items</relationshipLabel>
    <relationshipName>OppPriceRequestItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/OppPriceRequestItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Price Request Items</relationshipLabel>
    <relationshipName>Price_Request_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OppPriceRequestItem__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Code</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OppPriceRequestItem__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OppPriceRequestItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>NOTSENT</fullName>
                <default>true</default>
                <label>NOT SENT</label>
            </value>
            <value>
                <fullName>APPROVEDPARTIALLY</fullName>
                <label>PARTIALLY APPROVED</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OppPriceRequestMailerTest.cls
@isTest
public class OppPriceRequestMailerTest {
    @TestSetup
    static void makeData(){
        TestUtils.enableTriggers();
        DataFactoryOrganization.createData();
        List<Product2> listProducts = DataFactoryProduct.createProducts();
        List<Opportunity> opps = DataFactoryOpportunity.createRetailOpportunities(2, 1);

        OppPriceRequestHeader__c priceRequestHeader = new OppPriceRequestHeader__c(Neededby__c = Date.newInstance(2021, 8, 17), currencyIsoCode = 'USD', Opportunity__c = opps[0].Id);
        insert priceRequestHeader;
        OppPriceRequestItem__c item = new OppPriceRequestItem__c(ProductCode__c='111111',ProductName__c='Test product',Product__c = listProducts[0].Id, Price__c = 34.45, currencyIsoCode = 'GBP', priceRequestHeader__c = priceRequestHeader.Id);
        insert item;
    }

    @isTest
    static void sendToApprovalMail() {
        OppPriceRequestHeader__c header = [select Id, NeededBy__c from OppPriceRequestHeader__c limit 1];
        OppPriceRequestItem__c item = [select Id, status__c from OppPriceRequestItem__c];
        item.Status__c = 'PENDING';
        update item;
        
        OppPriceRequestMailer aux =  new OppPriceRequestMailer();
        aux.sendToApprovalMail(header.Id, new Set<Id>{item.Id});
        aux.sendToFactoryApprovalMail(header.Id, new Set<Id>{item.Id});
        
        Integer invocations = Limits.getEmailInvocations();
        System.assert(invocations > 0, 'Mail not sent. Mails sent: ' + invocations);
    }
    
    @isTest
    static void sendReviewedMail() {
        OppPriceRequestHeader__c header = [select Id, NeededBy__c from OppPriceRequestHeader__c limit 1];
        OppPriceRequestItem__c item = [select Id, status__c from OppPriceRequestItem__c];
        item.Status__c = 'APPROVED';
        update item;

        OppPriceRequestMailer aux =  new OppPriceRequestMailer();
        aux.sendReviewedMail(header.Id, new Set<Id>{item.Id});
        aux.sendFactoryReviewedMail(header.Id, new Set<Id>{item.Id});

        Integer invocations = Limits.getEmailInvocations();
        System.assert(invocations > 0, 'Mail not sent. Mails sent: ' + invocations);
    }
}