force-app/main/default/objects/PostCodeObjects__c/PostCodeObjects__c.object-meta.xml
<CustomObject>
    <description>Object created to set an object related to a Postal Code</description>
    <label>Post Code Object</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Serial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Code Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PostCodeObjects__c/fields/country__c.field-meta.xml
<CustomField>
    <fullName>country__c</fullName>
    <label>country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/objectId__c.field-meta.xml
<CustomField>
    <fullName>objectId__c</fullName>
    <description>Salesforce Id of the object related</description>
    <label>objectId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/objectType__c.field-meta.xml
<CustomField>
    <fullName>objectType__c</fullName>
    <label>objectType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INSTALLER</fullName>
                <default>true</default>
                <label>INSTALLER</label>
            </value>
            <value>
                <fullName>SALES_ORG</fullName>
                <label>SALES ORG</label>
            </value>
            <value>
                <fullName>SALES_OFFICE</fullName>
                <label>SALES OFFICE</label>
            </value>
            <value>
                <fullName>OWNER_USA</fullName>
                <label>OWNER USA</label>
            </value>
            <value>
                <fullName>MBK-EUR</fullName>
                <label>MATERIAL BANK (EUR)</label>
            </value>
            <value>
                <fullName>PORSAMARKET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/postCode__c.field-meta.xml
<CustomField>
    <fullName>postCode__c</fullName>
    <label>postCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/ProductLine__c.field-meta.xml
<CustomField>
    <fullName>ProductLine__c</fullName>
    <description>Para USA: se almacenan gamas de productos.</description>
    <inlineHelpText>Opciones aceptadas:
KRION
FAÇADE
KITCHEN</inlineHelpText>
    <label>Product Line</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/SALES_OFFICE__c.object-meta.xml
<CustomObject>
    <description>Entidad custom que contiene el maestro de relaciones para transformar el código de la oficina de ventas por el nombre.</description>
    <label>Sales Office</label>
    <nameField>
        <label>Nombre de SALES_OFFICE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_OFFICE__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <description>Postcode</description>
    <label>Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>User accepts in store appointments</description>
    <inlineHelpText>Please tick this box if the user accepts store appointments</inlineHelpText>
    <label>Store Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Sales Office from Sales Org default</description>
    <inlineHelpText>Sales Office from Sales Org default</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Default_Sales_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesOfficeAssignatorTest.cls
@isTest
public class SalesOfficeAssignatorTest {
  @testSetup static void setup() {
    Insert TriggerConfiguration_TestDataFactory.createCustomSetting_ActivatedTriggers();
    List<PostCodeObjects__c> pcoList = new List<PostCodeObjects__c>();

    List<User> userList = User_TestDataFactory.createUsersNoAdmin(8, new List<String>{'fr_FR', 'es_ES', 'es_ES', 'en_US', 'fr_FR', 'fr_FR', 'en_US', 'en_US'});
    userList[0].Appointment__c = true;
    insert userList;

    pcoList.add(new PostCodeObjects__c(objectType__c = 'SALES_OFFICE', country__c = 'GB', postCode__c = 'LA22', objectId__c = userList[0].Sales_Office__c));
    pcoList.add(new PostCodeObjects__c(objectType__c = 'OWNER_USA', country__c = 'GB', state__c = 'UT', profile__c = 'SELLER', productLine__c = 'KRION', objectId__c = userList[7].id));

    insert pcoList;
  }

  @isTest
  public static void findOwner() {
    SalesOfficeAssignator aux = new SalesOfficeAssignator();
    aux.setCountry('GB');
    aux.setPostCode('LA22 9NZ');
    
    User result = aux.getOwner();
    System.assert(result != null, 'Debería haber encontrado uno');
    aux.setPostCode('LA45 9NZ');
    result = aux.getOwner();
    System.assert(result == null, 'No debería haber encontrado uno');
  }
}