force-app/main/default/objects/PostCodeObjects__c/PostCodeObjects__c.object-meta.xml
<CustomObject>
    <description>Object created to set an object related to a Postal Code</description>
    <label>Post Code Object</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Serial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Code Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PostCodeObjects__c/fields/country__c.field-meta.xml
<CustomField>
    <fullName>country__c</fullName>
    <label>country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/objectId__c.field-meta.xml
<CustomField>
    <fullName>objectId__c</fullName>
    <description>Salesforce Id of the object related</description>
    <label>objectId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/objectType__c.field-meta.xml
<CustomField>
    <fullName>objectType__c</fullName>
    <label>objectType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INSTALLER</fullName>
                <default>true</default>
                <label>INSTALLER</label>
            </value>
            <value>
                <fullName>SALES_ORG</fullName>
                <label>SALES ORG</label>
            </value>
            <value>
                <fullName>SALES_OFFICE</fullName>
                <label>SALES OFFICE</label>
            </value>
            <value>
                <fullName>OWNER_USA</fullName>
                <label>OWNER USA</label>
            </value>
            <value>
                <fullName>MBK-EUR</fullName>
                <label>MATERIAL BANK (EUR)</label>
            </value>
            <value>
                <fullName>PORSAMARKET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/postCode__c.field-meta.xml
<CustomField>
    <fullName>postCode__c</fullName>
    <label>postCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/ProductLine__c.field-meta.xml
<CustomField>
    <fullName>ProductLine__c</fullName>
    <description>Para USA: se almacenan gamas de productos.</description>
    <inlineHelpText>Opciones aceptadas:
KRION
FAÇADE
KITCHEN</inlineHelpText>
    <label>Product Line</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/USAAssignatorTest.cls
@isTest
public class USAAssignatorTest 
{
    @testSetup static void setup() {
        TestUtils.EnableTriggers();
        DataFactoryUser.autoInsert = false;
        List<User> users = DataFactoryUser.createUKUsers(5);
        users[0].LastName = 'NJ-KC';
        users[1].LastName = 'NJ-K@';
        users[2].LastName = 'NJ-@C';
        users[3].LastName = 'US-@C';
        users[4].LastName = 'UNLISTED';
        insert users;
        
        List<PostCodeObjects__c> pcoList = new List<PostCodeObjects__c>();
        pcoList.add(buildObject('NJ', 'KRION', 'CONSUMER', users[0].Id));
        pcoList.add(buildObject('NJ', 'KRION', '', users[1].Id));
        pcoList.add(buildObject('NJ', '', 'CONSUMER', users[2].Id));
        pcoList.add(buildObject('', '', 'CONSUMER', users[3].Id));

        PostCodeObjects__c unlistedRow = buildObject('', '', '', users[4].Id);
        unlistedRow.country__c = '**';
        pcoList.add(unlistedRow);
        insert pcoList;
  	}

    @isTest
    public static void findOwner_01() {      
        // Full match
        USAAssignator aux = new USAAssignator();
        aux.setCountry('US');
        aux.setState('NJ');
        aux.setPostCode('07250');
        aux.setProfile('CONSUMER');
        aux.setProductLine('KRION FACADE');
        User user = aux.getOwner();
        System.assertEquals('NJ-KC', user.LastName, 'Should have been assigned the KRION CONSUMER MANAGER IN NJ');    
    }

    @isTest public static void findOwner_02() {      
        // Full match
        USAAssignator aux = new USAAssignator();
        aux.setCountry('US');
        aux.setState('NJ');
        aux.setPostCode('07250');
        aux.setProfile('ARCHITECT');
        aux.setProductLine('KRION FACADE');
        User user = aux.getOwner();
        System.assertEquals('NJ-K@', user.LastName, 'Should have been assigned the KRION MANAGER IN NJ');    
    }

    @isTest public static void findOwner_03() {      
        // Full match
        USAAssignator aux = new USAAssignator();
        aux.setCountry('US');
        aux.setState('NJ');
        aux.setPostCode('07250');
        aux.setProfile('CONSUMER');
        aux.setProductLine('KITCHENS');
        User user = aux.getOwner();
        System.assertEquals('NJ-@C', user.LastName, 'Should have been assigned the CONSUMER MANAGER IN NJ');    
    }

    @isTest public static void findOwner_04() {      
        // Full match
        USAAssignator aux = new USAAssignator();
        aux.setCountry('US');
        aux.setState('FL');
        aux.setPostCode('07250');
        aux.setProfile('CONSUMER');
        aux.setProductLine('KITCHENS');
        User user = aux.getOwner();
        System.assertEquals('US-@C', user.LastName, 'Should have been assigned the CONSUMER MANAGER IN US');    
    }

    @isTest public static void findOwner_05() {      
        // Full match
        USAAssignator aux = new USAAssignator();
        aux.setCountry('US');
        aux.setState('FL');
        aux.setPostCode('07300');
        aux.setProfile('FIXER');
        aux.setProductLine('KITCHENS');
        User user = aux.getOwner();
        System.assertEquals(null, user, 'User should be null');    
    }

    @isTest public static void findOwner_06() {      
        // Unlisted country
        USAAssignator aux = new USAAssignator();
        aux.setCountry('IT');
        aux.setState('');
        aux.setPostCode('07300');
        aux.setProfile('FIXER');
        aux.setProductLine('KITCHENS');
        User user = aux.getOwner();
        System.assertNotEquals(null, user, 'A user should have been assigned as owner');    
        System.assertEquals('UNLISTED', user.lastName, 'User should be the unlisted');    
    }


    /******************************************************/
    /***************** PRIVATE METHODS ********************/
    /******************************************************/

    private static PostCodeObjects__c buildObject(String state, String product, String profile, String objectId) {
        return new PostCodeObjects__c(
        objectType__c = 'OWNER_USA', 
        country__c = 'US', 
        state__c = state, 
        postCode__c = '', 
        productline__c = product, 
        profile__c = profile, 
        objectId__c = objectId);
    } // buildObject
} // class