force-app/main/default/objects/Queue_metadata__mdt/Queue_metadata__mdt.object-meta.xml
<CustomObject>
    <label>Queue metadata</label>
    <pluralLabel>Queues metadata</pluralLabel>
</CustomObject>

force-app/main/default/objects/Queue_metadata__mdt/fields/Queue__c.field-meta.xml
<CustomField>
    <fullName>Queue__c</fullName>
    <label>Queue</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TEST_EmailMessageUtil.cls
/**
* @service Hecho por NTS
*/
@isTest (SeeAllData = false)
public class TEST_EmailMessageUtil {}
// public class TEST_EmailMessageUtil 
// {
//     static Integer QUANT = 10;
//     static Integer QUANT_BULK = 200;

// 	@isTest 
//     /** 
//      *  @description: Creates an email for the administrator, who allready has a case and is in the metadata list - OK case owner assigned to the admins queue.
//      **
//      *  @Autor: jurretabizkaia (17/07/2018)
//      **
//      *  @Modificacion: 
//      **
//      */ 
// 	static void test_1_caseAssignedToAdminUser() 
//     { 
//         System.assertEquals('dummy', 'dummy', 'apex pmd dummy');
//         /*
//         //Generate/get values
//         Queue_metadata__mdt metadata        =   Test_DataFactory.getQueueMetadata(Test_DataFactory.getAdminUser().id); 
//         List<Case> caseList                 =   Test_DataFactory.gen_Cases(QUANT, 0);
//         List<EmailMessage> testEmailMessage =   Test_DataFactory.gen_Emails(QUANT, caseList, true);

// 		Test.startTest();
// 		    insert(testEmailMessage);
// 		Test.stopTest(); 

//         for (Case c: [Select id, OwnerId from Case] )
//         {
//             System.assertEquals(c.OwnerId, metadata.Queue__c);
//         }
//         */
//     }


// }