force-app/main/default/objects/Account/fields/Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Account_Classification__c</fullName>
    <label>Account Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agence immobiliÃ¨re</fullName>
                <isActive>false</isActive>
                <label>Agence immobiliÃ¨re</label>
            </value>
            <value>
                <fullName>Agencia de Representación de Porcelanosa</fullName>
            </value>
            <value>
                <fullName>Architectural firm</fullName>
                <label>Architectural Firm</label>
            </value>
            <value>
                <fullName>Architectural Firms</fullName>
                <isActive>false</isActive>
                <label>Architectural Firms</label>
            </value>
            <value>
                <fullName>Brand/Chain/Franchise</fullName>
                <label>Brand/Franchise</label>
            </value>
            <value>
                <fullName>Brands and Franchises</fullName>
                <isActive>false</isActive>
                <label>Brands and Franchises</label>
            </value>
            <value>
                <fullName>Building company</fullName>
                <isActive>false</isActive>
                <label>Building company</label>
            </value>
            <value>
                <fullName>Construction company</fullName>
                <label>Construction Company</label>
            </value>
            <value>
                <fullName>Custom home builder</fullName>
                <label>Custom Home Builder</label>
            </value>
            <value>
                <fullName>Custom home designer</fullName>
                <isActive>false</isActive>
                <label>Custom home designer</label>
            </value>
            <value>
                <fullName>Design-Build company</fullName>
                <label>Design-Build Company</label>
            </value>
            <value>
                <fullName>Developer</fullName>
                <label>Developer/Investor</label>
            </value>
            <value>
                <fullName>Distributor</fullName>
                <isActive>false</isActive>
                <label>Distributor</label>
            </value>
            <value>
                <fullName>Distributor / 3rd party retailer/dealer</fullName>
                <label>Distributor / Dealer</label>
            </value>
            <value>
                <fullName>Engineering consultant</fullName>
                <label>Engineering Consultant</label>
            </value>
            <value>
                <fullName>Fabricator</fullName>
                <label>Fabricator/Stonemason</label>
            </value>
            <value>
                <fullName>Fabricators</fullName>
                <isActive>false</isActive>
                <label>Fabricators</label>
            </value>
            <value>
                <fullName>Facade consultant</fullName>
                <label>Facade Consultant</label>
            </value>
            <value>
                <fullName>Facade Contractor</fullName>
                <isActive>false</isActive>
                <label>Facade Contractor</label>
            </value>
            <value>
                <fullName>Facade Installer</fullName>
            </value>
            <value>
                <fullName>Fit-out</fullName>
                <isActive>false</isActive>
                <label>Fit-out</label>
            </value>
            <value>
                <fullName>Fit-out company (commercial contract)</fullName>
                <label>Fit-Out Company (Commercial Contract)</label>
            </value>
            <value>
                <fullName>Franchisee</fullName>
            </value>
            <value>
                <fullName>Furniture Company</fullName>
            </value>
            <value>
                <fullName>Interior Design</fullName>
                <isActive>false</isActive>
                <label>Interior Design</label>
            </value>
            <value>
                <fullName>Interior design firm</fullName>
                <label>Interior Design Firm</label>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath store</fullName>
                <label>Kitchen &amp; Bath Store (XTONE only)</label>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath Store XTONE</fullName>
                <isActive>false</isActive>
                <label>Kitchen &amp; Bath Store XTONE</label>
            </value>
            <value>
                <fullName>Kitchen instalation company</fullName>
                <label>Kitchen Installation Company</label>
            </value>
            <value>
                <fullName>National House Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Subclassification__c.field-meta.xml
<CustomField>
    <fullName>Account_Subclassification__c</fullName>
    <label>Account Subclassification</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Account_Classification__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Big-Box</fullName>
            </value>
            <value>
                <fullName>Consumer Goods</fullName>
            </value>
            <value>
                <fullName>Cruises</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hospitality/ Hotel</fullName>
            </value>
            <value>
                <fullName>Landscape Architect</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Multi-Unit</fullName>
            </value>
            <value>
                <fullName>Offices</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Retail Chain</fullName>
            </value>
            <value>
                <fullName>Senior Living</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Email__c.field-meta.xml
<CustomField>
    <fullName>Business_Email__c</fullName>
    <description>Email del Business</description>
    <inlineHelpText>Business Email</inlineHelpText>
    <label>Business Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/DVSAcceptedBy__c.field-meta.xml
<CustomField>
    <fullName>DVSAcceptedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quien ha aceptado o descartado los cambios del DVS</description>
    <label>DVS Accepted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DVSAcceptedDate__c.field-meta.xml
<CustomField>
    <fullName>DVSAcceptedDate__c</fullName>
    <description>Fecha de cuando se han aceptado o descartado los cambios</description>
    <label>DVS Accepted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/DVSAction__c.field-meta.xml
<CustomField>
    <fullName>DVSAction__c</fullName>
    <description>Discarded: Se quedan con los datos de Salesforce
Accepted: Se quedan con los datos del DVS
Unknown: No ha habido resultados al buscar por el dvs.
Confirmed: Contabilidad ha aceptado la validación.</description>
    <label>DVS Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACCEPTED</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>DISCARDED</fullName>
                <label>Discarded</label>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
                <label>Unknown</label>
            </value>
            <value>
                <fullName>CONFIRMED</fullName>
                <label>Confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>External ID to match the Lead Account of origin</description>
    <label>External ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SynchronizedWithDvs__c.field-meta.xml
<CustomField>
    <fullName>SynchronizedWithDvs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Data validated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number_2__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number_2__c</fullName>
    <label>VAT Number 2</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <description>Código de Identificación Fiscal</description>
    <label>VAT Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Trade_and_Specificators.recordType-meta.xml
<RecordType>
    <fullName>Trade_and_Specificators</fullName>
    <active>true</active>
    <description>Form used for trade specifications and other professionals involved in projects (B2B)</description>
    <label>Trade and Specificators</label>
</RecordType>

force-app/main/default/classes/PorsaMarketAccount.cls
/**
 * @author       Ivan Losilla
 * @since        April 2025
 * @group        Porsamarket
 * @description  PorsaMarket Account figure class
 * @test PorsaMarketAccountTest
 */
public class PorsaMarketAccount {
    public class PorsamarketAccountException extends Exception {}

    public String accountId;        // Porsamarket Id. SIret on France
    public String pmService;      // Servie of Poramarket. GB, US, HH, etc
    public String sfId = null;      // if exists on Salesforce, the Id
    public String sfOwnerId;        // if exists on Salesforce, the Id of the Owner
    public String vat;              // Siret of the account, on france
    public String type;             // ACCOUNT or LOT, depending on the type.
    public Boolean sendEmail = true;             // ACCOUNT or LOT, depending on the type.
    public PMPAccountWrapper data;  // Data taken from porsamarket

    public PorsaMarketAccount() {}

    public void getData() {
        HttpRequest req = new HttpRequest();

        if (this.type == 'ACCOUNT') {
            req.setEndpoint('https://porsamarket.porcelanosagrupo.com/' + this.pmService + '/Accounts');
        }

        if (this.type == 'LOT') {
            req.setEndpoint('https://porsamarket.porcelanosagrupo.com/' + this.pmService + '/Lots');
        }

        req.setMethod('POST');
        req.setHeader('Accept', 'application/json;odata=verbose');

        String user = 'sf_to_porsamarket_FR';
        String pass = 'Ry5s7y5WzCcVmmz75MaPAeCdANjUgs4Wejt6nJAMmV7QTn8qv976GxcuqjY8yAJQ2597ZvJrGCNZAaRAVTm9BebanQt3suunKcSdQwLA8XRneTyg8MyMmuufAN2UeGnNgtasEVYr5b5MtqdwPQP2uKtCdwfjgvs8A9sbjQBmUEsPmSrk7qGhSAJEaUy4fMgx2C2DpWcdMj7acmRx2gNAS8SueFWJGRV4RfVddwr2QPtZVRqmChMLKFY8qr3BsxSv';
        String body = '{' +
            '"User": "' + user + '", ' +
            '"Pwd": "' + pass + '",' +
            '"Project": "",' +
            '"Account": "' + this.accountId + '"' +
        '}';

        req.setBody(body);

        Http http = new Http();
        HttpResponse res = http.send(req);

        if (res.getStatusCode() == 200) {
            if (Test.isRunningTest()) {
                PMPAccountWrapper testData = new PMPAccountWrapper();
                testData.Name = 'test account';
                testData.Street = 'test street';
                testData.Street2 = 'test street 2';
                testData.City = 'test city';

                this.data = testData;
            } else {
                List<PMPAccountWrapper> results = (List<PMPAccountWrapper>) JSON.deserialize(res.getBody(), List<PMPAccountWrapper>.class);
                if (results.size() > 0) {
                    this.data = results[0];
                }
            }
        } else {
            throw new PorsamarketAccountException('Error al recabar datos de porsamarket');
        }
    }

    public Account toAccount() {
        if (this.data == null) {
            return null;
        }
        Account result = new Account();
        Id rTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Trade_and_Specificators').getRecordTypeId();

        result.recordTypeId = rTypeId;
        result.Name = this.data.Name;
        result.BillingStreet = this.data.Street + (this.data.Street2 != null ? ' ' + this.data.Street2 : '');
        result.BillingCountryCode =  this.data.countryCode;

        if (this.data.countryCode == 'CAN') {
            result.BillingCountryCode = 'CA';
        }

        result.BillingStateCode = this.data.State;
        result.BillingCity = this.data.City;
        result.BillingPostalCode = this.data.PostCode;
        result.vat_number__c = this.data.VAT;
        result.vat_number_2__c = this.data.VAT2;
        result.Business_Email__c = this.data.Email;
        result.Phone = this.data.Phone;
        result.Account_Classification__c = this.data.Classification;
        result.Account_Subclassification__c = this.data.Subclassification;
        result.DVSAction__c = 'ACCEPTED';
        result.SynchronizedWithDvs__c = true;
        result.DVSAcceptedDate__c = System.now();
        result.DVSAcceptedBy__c = UserInfo.getUserId();
        result.AccountSource = 'Porsamarket';
        if (this.pmService == 'HZ') {
            result.AccountSource = 'Houzz';
        }
        result.External_ID__c = this.pmService + this.data.Id;

        return result;
    }

    public static PorsaMarketAccount readLot(List<string> csvLine) {
        String pmService = csvLine[0];
        String obj = csvLine[1];
        String registerId = csvLine[5];
        String user = csvLine[7];
        String dateParam = csvLine[8];
        Boolean sendEmail = true;
        if (csvLine.size() > 9) {
            sendEmail = (String.isBlank(csvLine[9]) == false && csvLine[9].toUpperCase().contains('NOMAIL') ? false : true);
        }        String sfId = null;
        if (csvLine[6].startsWith('001')) {
            sfId = csvLine[6];
        }

        PorsaMarketAccount elemLot = new PorsaMarketAccount();
        elemLot.accountId = registerId;
        elemLot.pmService = pmService;
        elemLot.sfId = sfId;
        elemLot.vat = registerId;
        elemLot.type = 'LOT';
        elemLot.sendEmail = sendEmail;
        elemLot.getData();

        return elemLot;
    }

    public static PorsaMarketAccount readAccount(List<string> csvLine) {
        String pmService = csvLine[0];
        String obj = csvLine[1];
        String registerId = csvLine[5];
        String user = csvLine[7];
        String dateParam = csvLine[8];
        Boolean sendEmail = true;
        if (csvLine.size() > 9) {
            sendEmail = (String.isBlank(csvLine[9]) == false && csvLine[9].toUpperCase().contains('NOMAIL') ? false : true);
        }
        String sfId = null;
        if (csvLine[6].startsWith('001')) {
            sfId = csvLine[6];
        }

        PorsaMarketAccount elemAccount = new PorsaMarketAccount();
        elemAccount.accountId = registerId;
        elemAccount.pmService = pmService;
        elemAccount.sfId = sfId;
        elemAccount.vat = registerId;
        elemAccount.type = 'ACCOUNT';
        elemAccount.sendEmail = sendEmail;
        elemAccount.getData();

        return elemAccount;
    }

    public class PMPAccountWrapper {
        public String Id;
        public String Name;
        public String Street;
        public String Street2;
        public String State;
        public String PostCode;
        public String CountryCode;
        public String City;
        public String Phone;
        public String Email;
        public String VAT;
        public String VAT2;
        public String Classification;
        public String Subclassification;
    }
}