force-app/main/default/objects/Account/fields/Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Account_Classification__c</fullName>
    <label>Account Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agence immobiliÃ¨re</fullName>
                <isActive>false</isActive>
                <label>Agence immobiliÃ¨re</label>
            </value>
            <value>
                <fullName>Agencia de Representación de Porcelanosa</fullName>
            </value>
            <value>
                <fullName>Architectural firm</fullName>
                <label>Architectural Firm</label>
            </value>
            <value>
                <fullName>Architectural Firms</fullName>
                <isActive>false</isActive>
                <label>Architectural Firms</label>
            </value>
            <value>
                <fullName>Brand/Chain/Franchise</fullName>
                <label>Brand/Franchise</label>
            </value>
            <value>
                <fullName>Brands and Franchises</fullName>
                <isActive>false</isActive>
                <label>Brands and Franchises</label>
            </value>
            <value>
                <fullName>Building company</fullName>
                <isActive>false</isActive>
                <label>Building company</label>
            </value>
            <value>
                <fullName>Construction company</fullName>
                <label>Construction Company</label>
            </value>
            <value>
                <fullName>Custom home builder</fullName>
                <label>Custom Home Builder</label>
            </value>
            <value>
                <fullName>Custom home designer</fullName>
                <isActive>false</isActive>
                <label>Custom home designer</label>
            </value>
            <value>
                <fullName>Design-Build company</fullName>
                <label>Design-Build Company</label>
            </value>
            <value>
                <fullName>Developer</fullName>
                <label>Developer/Investor</label>
            </value>
            <value>
                <fullName>Distributor</fullName>
                <isActive>false</isActive>
                <label>Distributor</label>
            </value>
            <value>
                <fullName>Distributor / 3rd party retailer/dealer</fullName>
                <label>Distributor / Dealer</label>
            </value>
            <value>
                <fullName>Engineering consultant</fullName>
                <label>Engineering Consultant</label>
            </value>
            <value>
                <fullName>Fabricator</fullName>
                <label>Fabricator/Stonemason</label>
            </value>
            <value>
                <fullName>Fabricators</fullName>
                <isActive>false</isActive>
                <label>Fabricators</label>
            </value>
            <value>
                <fullName>Facade consultant</fullName>
                <label>Facade Consultant</label>
            </value>
            <value>
                <fullName>Facade Contractor</fullName>
                <isActive>false</isActive>
                <label>Facade Contractor</label>
            </value>
            <value>
                <fullName>Facade Installer</fullName>
            </value>
            <value>
                <fullName>Fit-out</fullName>
                <isActive>false</isActive>
                <label>Fit-out</label>
            </value>
            <value>
                <fullName>Fit-out company (commercial contract)</fullName>
                <label>Fit-Out Company (Commercial Contract)</label>
            </value>
            <value>
                <fullName>Franchisee</fullName>
            </value>
            <value>
                <fullName>Furniture Company</fullName>
            </value>
            <value>
                <fullName>Interior Design</fullName>
                <isActive>false</isActive>
                <label>Interior Design</label>
            </value>
            <value>
                <fullName>Interior design firm</fullName>
                <label>Interior Design Firm</label>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath store</fullName>
                <label>Kitchen &amp; Bath Store (XTONE only)</label>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath Store XTONE</fullName>
                <isActive>false</isActive>
                <label>Kitchen &amp; Bath Store XTONE</label>
            </value>
            <value>
                <fullName>Kitchen instalation company</fullName>
                <label>Kitchen Installation Company</label>
            </value>
            <value>
                <fullName>National House Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country code ISO-3166-1</description>
    <label>Country_old</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Trade_and_Specificators.recordType-meta.xml
<RecordType>
    <fullName>Trade_and_Specificators</fullName>
    <active>true</active>
    <description>Form used for trade specifications and other professionals involved in projects (B2B)</description>
    <label>Trade and Specificators</label>
</RecordType>

force-app/main/default/objects/AccountSettings__c/AccountSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for features related to the Accounts, by country</description>
    <label>PORSA Account Settings</label>
</CustomObject>

force-app/main/default/objects/AccountSettings__c/fields/novalidcreation_mailto__c.field-meta.xml
<CustomField>
    <fullName>novalidcreation_mailto__c</fullName>
    <description>List of Id, of the Managers that are going to receive the email of AccountMail.alertNotValidCreation</description>
    <label>No Valid Account Creation Mail To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/PostCodeObjects__c.object-meta.xml
<CustomObject>
    <description>Object created to set an object related to a Postal Code</description>
    <label>Post Code Object</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Serial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Code Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PostCodeObjects__c/fields/country__c.field-meta.xml
<CustomField>
    <fullName>country__c</fullName>
    <label>country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/objectId__c.field-meta.xml
<CustomField>
    <fullName>objectId__c</fullName>
    <description>Salesforce Id of the object related</description>
    <label>objectId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/objectType__c.field-meta.xml
<CustomField>
    <fullName>objectType__c</fullName>
    <label>objectType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INSTALLER</fullName>
                <default>true</default>
                <label>INSTALLER</label>
            </value>
            <value>
                <fullName>SALES_ORG</fullName>
                <label>SALES ORG</label>
            </value>
            <value>
                <fullName>SALES_OFFICE</fullName>
                <label>SALES OFFICE</label>
            </value>
            <value>
                <fullName>OWNER_USA</fullName>
                <label>OWNER USA</label>
            </value>
            <value>
                <fullName>MBK-EUR</fullName>
                <label>MATERIAL BANK (EUR)</label>
            </value>
            <value>
                <fullName>PORSAMARKET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/postCode__c.field-meta.xml
<CustomField>
    <fullName>postCode__c</fullName>
    <label>postCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/SALES_OFFICE__c.object-meta.xml
<CustomObject>
    <description>Entidad custom que contiene el maestro de relaciones para transformar el código de la oficina de ventas por el nombre.</description>
    <label>Sales Office</label>
    <nameField>
        <label>Nombre de SALES_OFFICE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_OFFICE__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <description>Postcode</description>
    <label>Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Default_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Organization__c</fullName>
    <description>La organización de ventas por defecto para el comercial</description>
    <inlineHelpText>The default sales organization for sales and distribution</inlineHelpText>
    <label>Default Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Distribution_channel_default__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel_default__c</fullName>
    <label>Distribution channel default</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Sales Office from Sales Org default</description>
    <inlineHelpText>Sales Office from Sales Org default</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Default_Sales_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountMailsTest.cls
@isTest
public class AccountMailsTest {
    @testSetup static void setup() {
        Insert TriggerConfiguration_TestDataFactory.createCustomSetting_ActivatedTriggers();
        AccountSettings__c newAccSetting = new AccountSettings__c(Name = 'UK', Country__c = 'GB', novalidcreation_mailto__c = 'ivan.losilla@porcelanosagrupo.com');
        PostCodeObjects__c aux = new PostCodeObjects__c(postCode__c = 'BB', objectId__c = '500', objectType__c = 'SALES_ORG', country__c = 'GB');

        insert aux;
        insert newAccSetting;
    }

    @isTest
    static void alertNotValidCreation() {
        Map<String,Schema.RecordTypeInfo> recTypeMap = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        String tradeRecTypeId = recTypeMap.get('Trade_and_Specificators').getRecordTypeId();

        User u = [SELECT Id, CountryCode, Sales_org__c, Default_Sales_Organization__c, Distribution_channel_default__c, Sales_Office__c, ProfileId from User where Sales_Org__c =: OrganizationCommons.ORG_PIDF and IsActive = true LIMIT 1][0];
        Account acc = new Account();
        System.runAs(u) {
            acc = new Account(Name = 'Test Trade Account',
                                        BillingPostalCode = 'BB5 7OH',
                                        BillingCountryCode = 'GB',
                                        Phone = '23423423423',
                                        RecordTypeId = tradeRecTypeId,
                                        BillingCity = 'LLOYD',
                                        Account_Classification__c = 'Architectural firm');
            insert acc;
        }

        List<Account> listAcc = AccountUtil.getData(new Set<Id>{acc.Id});
        AccountMails.alertNotValidCreation(listAcc);
        Integer invocations = Limits.getEmailInvocations();
        System.assert(invocations > 0, 'Mail not sent. Mails sent: ' + invocations);
    }
}