force-app/main/default/objects/Account/fields/Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Account_Classification__c</fullName>
    <label>Account Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agence immobiliÃ¨re</fullName>
                <isActive>false</isActive>
                <label>Agence immobiliÃ¨re</label>
            </value>
            <value>
                <fullName>Agencia de Representación de Porcelanosa</fullName>
            </value>
            <value>
                <fullName>Architectural firm</fullName>
                <label>Architectural Firm</label>
            </value>
            <value>
                <fullName>Architectural Firms</fullName>
                <isActive>false</isActive>
                <label>Architectural Firms</label>
            </value>
            <value>
                <fullName>Brand/Chain/Franchise</fullName>
                <label>Brand/Franchise</label>
            </value>
            <value>
                <fullName>Brands and Franchises</fullName>
                <isActive>false</isActive>
                <label>Brands and Franchises</label>
            </value>
            <value>
                <fullName>Building company</fullName>
                <isActive>false</isActive>
                <label>Building company</label>
            </value>
            <value>
                <fullName>Construction company</fullName>
                <label>Construction Company</label>
            </value>
            <value>
                <fullName>Custom home builder</fullName>
                <label>Custom Home Builder</label>
            </value>
            <value>
                <fullName>Custom home designer</fullName>
                <isActive>false</isActive>
                <label>Custom home designer</label>
            </value>
            <value>
                <fullName>Design-Build company</fullName>
                <label>Design-Build Company</label>
            </value>
            <value>
                <fullName>Developer</fullName>
                <label>Developer/Investor</label>
            </value>
            <value>
                <fullName>Distributor</fullName>
                <isActive>false</isActive>
                <label>Distributor</label>
            </value>
            <value>
                <fullName>Distributor / 3rd party retailer/dealer</fullName>
                <label>Distributor / Dealer</label>
            </value>
            <value>
                <fullName>Engineering consultant</fullName>
                <label>Engineering Consultant</label>
            </value>
            <value>
                <fullName>Fabricator</fullName>
                <label>Fabricator/Stonemason</label>
            </value>
            <value>
                <fullName>Fabricators</fullName>
                <isActive>false</isActive>
                <label>Fabricators</label>
            </value>
            <value>
                <fullName>Facade consultant</fullName>
                <label>Facade Consultant</label>
            </value>
            <value>
                <fullName>Facade Contractor</fullName>
                <isActive>false</isActive>
                <label>Facade Contractor</label>
            </value>
            <value>
                <fullName>Facade Installer</fullName>
            </value>
            <value>
                <fullName>Fit-out</fullName>
                <isActive>false</isActive>
                <label>Fit-out</label>
            </value>
            <value>
                <fullName>Fit-out company (commercial contract)</fullName>
                <label>Fit-Out Company (Commercial Contract)</label>
            </value>
            <value>
                <fullName>Franchisee</fullName>
            </value>
            <value>
                <fullName>Furniture Company</fullName>
            </value>
            <value>
                <fullName>Interior Design</fullName>
                <isActive>false</isActive>
                <label>Interior Design</label>
            </value>
            <value>
                <fullName>Interior design firm</fullName>
                <label>Interior Design Firm</label>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath store</fullName>
                <label>Kitchen &amp; Bath Store (XTONE only)</label>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath Store XTONE</fullName>
                <isActive>false</isActive>
                <label>Kitchen &amp; Bath Store XTONE</label>
            </value>
            <value>
                <fullName>Kitchen instalation company</fullName>
                <label>Kitchen Installation Company</label>
            </value>
            <value>
                <fullName>National House Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Cuentas Activas o Inactivas</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Inactive: Cessation of Activity</fullName>
            </value>
            <value>
                <fullName>Inactive: Duplicated</fullName>
            </value>
            <value>
                <fullName>Inactive: Wrong Classification, not a business client</fullName>
            </value>
            <value>
                <fullName>Inactive: Private customer purchasing through a trade client</fullName>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Email__c.field-meta.xml
<CustomField>
    <fullName>Business_Email__c</fullName>
    <description>Email del Business</description>
    <inlineHelpText>Business Email</inlineHelpText>
    <label>Business Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <defaultValue>$Label.CurrentLanguage</defaultValue>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Potential__c.field-meta.xml
<CustomField>
    <fullName>Potential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Potential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <externalId>true</externalId>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>en_US</fullName>
        <label>US English</label>
    </customValue>
    <customValue>
        <fullName>en_GB</fullName>
        <label>GB English</label>
    </customValue>
    <customValue>
        <fullName>fr_FR</fullName>
        <label>French</label>
    </customValue>
    <customValue>
        <fullName>es_ES</fullName>
        <label>Spanish</label>
    </customValue>
    <customValue>
        <fullName>pt_PT</fullName>
        <label>Portuguese</label>
    </customValue>
    <customValue>
        <fullName>de_DE</fullName>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>nl_FL</fullName>
        <label>Flemish</label>
    </customValue>
    <customValue>
        <fullName>it_IT</fullName>
        <label>Italian</label>
    </customValue>
    <customValue>
        <fullName>nl_BE</fullName>
        <label>Dutch</label>
    </customValue>
    <customValue>
        <fullName>en_UK</fullName>
        <isActive>false</isActive>
        <label>en_UK</label>
    </customValue>
    <masterLabel>language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountProxy.cls
/**
* @author 		Ramón Prades
* @date 		April 2021
* @group 		Accounts
* @description 	Proxy class to provide a common interface to account and person account
*/
public class AccountProxy {

    @AuraEnabled public Account account { get; private set; }
    @AuraEnabled public Id id { get; private set; }
    @AuraEnabled public Boolean isPersonAccount { get; private set; }
    @AuraEnabled public String name;
    @AuraEnabled public String street;
    @AuraEnabled public String city;
    @AuraEnabled public string stateCode;
    @AuraEnabled public string state;
    @AuraEnabled public string countryCode;    
    @AuraEnabled public String country;
    @AuraEnabled public string postalCode;
    @AuraEnabled public string email;
    @AuraEnabled public string phone;

    public AccountProxy(String Id) {
        this.read(Id);
    }

    private void read(String Id) {
        this.account = [select
            Account_Classification__c, Account_Status__c, BillingCity, BillingCountry, BillingCountryCode, BillingPostalCode,
            BillingState, BillingStateCode, BillingStreet, Business_Email__c, CreatedDate, Id, IsDeleted, IsPersonAccount,
            Language__c, Name, OwnerId, Potential__c, PersonEmail, PersonMailingStreet, PersonMailingCity, PersonMailingCountryCode,
            PersonMailingCountry,  PersonMailingPostalCode, PersonMobilePhone, PersonMailingStateCode, PersonMailingState, Phone,  Salutation, FirstName, LastName,
            RecordTypeId, SAP_Id__c
        from Account where Id = :Id limit 1];
        if (this.account.isPersonAccount) {
            assignPersonAccount();
        } else {
            assignAccount();
        }
    } // read

    private void assignAccount() {
        this.id = this.account.Id;
        this.city = this.account.BillingCity;
        this.country = this.account.BillingCountry;
        this.countryCode = this.account.BillingCountryCode;
        this.postalCode = this.account.BillingPostalCode;
        this.state = this.account.BillingState;
        this.stateCode = this.account.BillingStateCode;
        this.street = this.account.BillingStreet;
        this.email = this.account.Business_Email__c;
        this.isPersonAccount = this.account.IsPersonAccount;
        this.name = this.account.Name;
        this.phone = this.account.Phone;
    } // assignAccount

    private void assignPersonAccount() {
        this.id = this.account.Id;
        this.city = this.account.PersonMailingCity;
        this.country = this.account.PersonMailingCountry;
        this.countryCode = this.account.PersonMailingCountryCode;
        this.postalCode = this.account.PersonMailingPostalCode;
        this.state = this.account.PersonMailingState;
        this.stateCode = this.account.PersonMailingStateCode;
        this.street = this.account.PersonMailingStreet;
        this.email = this.account.PersonEmail;
        this.isPersonAccount = this.account.IsPersonAccount;
        this.name = this.account.Name;
        this.phone = this.account.PersonMobilePhone;
    } // assignAccount

}