force-app/main/default/objects/Account/fields/Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Account_Classification__c</fullName>
    <label>Account Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agence immobiliÃ¨re</fullName>
                <isActive>false</isActive>
                <label>Agence immobiliÃ¨re</label>
            </value>
            <value>
                <fullName>Agencia de Representación de Porcelanosa</fullName>
            </value>
            <value>
                <fullName>Architectural firm</fullName>
                <label>Architectural Firm</label>
            </value>
            <value>
                <fullName>Architectural Firms</fullName>
                <isActive>false</isActive>
                <label>Architectural Firms</label>
            </value>
            <value>
                <fullName>Brand/Chain/Franchise</fullName>
                <label>Brand/Franchise</label>
            </value>
            <value>
                <fullName>Brands and Franchises</fullName>
                <isActive>false</isActive>
                <label>Brands and Franchises</label>
            </value>
            <value>
                <fullName>Building company</fullName>
                <isActive>false</isActive>
                <label>Building company</label>
            </value>
            <value>
                <fullName>Construction company</fullName>
                <label>Construction Company</label>
            </value>
            <value>
                <fullName>Custom home builder</fullName>
                <label>Custom Home Builder</label>
            </value>
            <value>
                <fullName>Custom home designer</fullName>
                <isActive>false</isActive>
                <label>Custom home designer</label>
            </value>
            <value>
                <fullName>Design-Build company</fullName>
                <label>Design-Build Company</label>
            </value>
            <value>
                <fullName>Developer</fullName>
                <label>Developer/Investor</label>
            </value>
            <value>
                <fullName>Distributor</fullName>
                <isActive>false</isActive>
                <label>Distributor</label>
            </value>
            <value>
                <fullName>Distributor / 3rd party retailer/dealer</fullName>
                <label>Distributor / Dealer</label>
            </value>
            <value>
                <fullName>Engineering consultant</fullName>
                <label>Engineering Consultant</label>
            </value>
            <value>
                <fullName>Fabricator</fullName>
                <label>Fabricator/Stonemason</label>
            </value>
            <value>
                <fullName>Fabricators</fullName>
                <isActive>false</isActive>
                <label>Fabricators</label>
            </value>
            <value>
                <fullName>Facade consultant</fullName>
                <label>Facade Consultant</label>
            </value>
            <value>
                <fullName>Facade Contractor</fullName>
                <isActive>false</isActive>
                <label>Facade Contractor</label>
            </value>
            <value>
                <fullName>Facade Installer</fullName>
            </value>
            <value>
                <fullName>Fit-out</fullName>
                <isActive>false</isActive>
                <label>Fit-out</label>
            </value>
            <value>
                <fullName>Fit-out company (commercial contract)</fullName>
                <label>Fit-Out Company (Commercial Contract)</label>
            </value>
            <value>
                <fullName>Franchisee</fullName>
            </value>
            <value>
                <fullName>Furniture Company</fullName>
            </value>
            <value>
                <fullName>Interior Design</fullName>
                <isActive>false</isActive>
                <label>Interior Design</label>
            </value>
            <value>
                <fullName>Interior design firm</fullName>
                <label>Interior Design Firm</label>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath store</fullName>
                <label>Kitchen &amp; Bath Store (XTONE only)</label>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath Store XTONE</fullName>
                <isActive>false</isActive>
                <label>Kitchen &amp; Bath Store XTONE</label>
            </value>
            <value>
                <fullName>Kitchen instalation company</fullName>
                <label>Kitchen Installation Company</label>
            </value>
            <value>
                <fullName>National House Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Cuentas Activas o Inactivas</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Inactive: Cessation of Activity</fullName>
            </value>
            <value>
                <fullName>Inactive: Duplicated</fullName>
            </value>
            <value>
                <fullName>Inactive: Wrong Classification, not a business client</fullName>
            </value>
            <value>
                <fullName>Inactive: Private customer purchasing through a trade client</fullName>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Activity_Level__c.field-meta.xml
<CustomField>
    <fullName>Activity_Level__c</fullName>
    <formula>IF(RT_Name_ANA_Form__c=&apos;Private Customer&apos;, NULL, IF(NOW() - Last_Activity_Date__c &gt; 90, Image(&quot;/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0681r00000KOIne&amp;operationContext=CHATTER&amp;contentId=05T1r000017F3XJ&quot;,&quot;Dormant&quot;),
	IF(AND(NOW() - Last_Activity_Date__c &gt; 60,NOW() - Last_Activity_Date__c &lt;= 90),Image(&quot;/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0681r00000KOInt&amp;operationContext=CHATTER&amp;contentId=05T1r000017F3Xd&quot;,&quot;Medium&quot;),
		IF(ISBLANK(Last_Activity_Date__c), Image(&quot;/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0681q000000Fzm0&amp;operationContext=CHATTER&amp;contentId=05T1q000006hJN9&quot;,&quot;NoActivity&quot;), Image(&quot;/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0681r00000KOIno&amp;operationContext=CHATTER&amp;contentId=05T1r000017F3XY&quot;,&quot;High&quot;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activity Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DVSAcceptedBy__c.field-meta.xml
<CustomField>
    <fullName>DVSAcceptedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quien ha aceptado o descartado los cambios del DVS</description>
    <label>DVS Accepted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DVSAction__c.field-meta.xml
<CustomField>
    <fullName>DVSAction__c</fullName>
    <description>Discarded: Se quedan con los datos de Salesforce
Accepted: Se quedan con los datos del DVS
Unknown: No ha habido resultados al buscar por el dvs.
Confirmed: Contabilidad ha aceptado la validación.</description>
    <label>DVS Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACCEPTED</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>DISCARDED</fullName>
                <label>Discarded</label>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
                <label>Unknown</label>
            </value>
            <value>
                <fullName>CONFIRMED</fullName>
                <label>Confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DvsHasError__c.field-meta.xml
<CustomField>
    <fullName>DvsHasError__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tell whether a DVS Error has been reported</inlineHelpText>
    <label>Has Dvs Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DvsLongError__c.field-meta.xml
<CustomField>
    <fullName>DvsLongError__c</fullName>
    <label>DVS Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Account</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <externalId>true</externalId>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number_2__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number_2__c</fullName>
    <label>VAT Number 2</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <description>Código de Identificación Fiscal</description>
    <label>VAT Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fabricator.recordType-meta.xml
<RecordType>
    <fullName>Fabricator</fullName>
    <active>true</active>
    <description>Form used for fabricators, stonemasons and craftsmen involved in product manufacturing</description>
    <label>Fabricator</label>
</RecordType>

force-app/main/default/objects/Order/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <description>Sap code of the order is coming from</description>
    <label>Sap Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PopupActionsService.cls
/**
* @author Ivan Losilla
* @date November 2024
*
* @group Others 
* @description Class to manage everything about PopupActions LWC.
*/
public class PopupActionsService {
    @AuraEnabled (cacheable=true)
    public static User currentUserData() {
        return new UsersSelector().selectById(UserInfo.getUserId());
    }

    @AuraEnabled (cacheable=false)
    public static List<Account> getNoManagedAccounts(Integer numOfRecords) {
        List<RecordType> rcTypes = [SELECT Id FROM RecordType WHERE (Name = 'Fabricator' OR Name = 'Third party Retailer / Reseller' OR Name = 'Trade and Specificators')];
        List<Id> rcTypesIds = new List<Id>{rcTypes[0].Id, rcTypes[1].Id, rcTypes[2].Id};

        List<Account> listAccounts = [SELECT ID, Name, VAT_Number__c, VAT_Number_2__c, BillingStreet, BillingPostalCode, BillingCity, BillingCountry, BillingCountryCode,
                                    DvsLongError__c, DvsHasError__c, Last_Activity_Date__c,Activity_Level__c,Sap_id__c,
                                    DvsAcceptedBy__c, DvsAction__c, Account_Classification__c
        FROM Account
        WHERE DvsAction__c = null
        AND BillingCountryCode = 'FR'
        AND Account_Status__c = 'Active'
        AND RecordTypeId IN :rcTypesIds
        AND createddate < LAST_N_DAYS:1
        AND OwnerId =: Userinfo.getUserId()
        ORDER BY Activity_Level__c DESC
        LIMIT : numOfRecords];

        return listAccounts;
    }
}