force-app/main/default/objects/Account/fields/Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Account_Classification__c</fullName>
    <label>Account Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agence immobiliÃ¨re</fullName>
                <isActive>false</isActive>
                <label>Agence immobiliÃ¨re</label>
            </value>
            <value>
                <fullName>Agencia de Representación de Porcelanosa</fullName>
            </value>
            <value>
                <fullName>Architectural firm</fullName>
                <label>Architectural Firm</label>
            </value>
            <value>
                <fullName>Architectural Firms</fullName>
                <isActive>false</isActive>
                <label>Architectural Firms</label>
            </value>
            <value>
                <fullName>Brand/Chain/Franchise</fullName>
                <label>Brand/Franchise</label>
            </value>
            <value>
                <fullName>Brands and Franchises</fullName>
                <isActive>false</isActive>
                <label>Brands and Franchises</label>
            </value>
            <value>
                <fullName>Building company</fullName>
                <isActive>false</isActive>
                <label>Building company</label>
            </value>
            <value>
                <fullName>Construction company</fullName>
                <label>Construction Company</label>
            </value>
            <value>
                <fullName>Custom home builder</fullName>
                <label>Custom Home Builder</label>
            </value>
            <value>
                <fullName>Custom home designer</fullName>
                <isActive>false</isActive>
                <label>Custom home designer</label>
            </value>
            <value>
                <fullName>Design-Build company</fullName>
                <label>Design-Build Company</label>
            </value>
            <value>
                <fullName>Developer</fullName>
                <label>Developer/Investor</label>
            </value>
            <value>
                <fullName>Distributor</fullName>
                <isActive>false</isActive>
                <label>Distributor</label>
            </value>
            <value>
                <fullName>Distributor / 3rd party retailer/dealer</fullName>
                <label>Distributor / Dealer</label>
            </value>
            <value>
                <fullName>Engineering consultant</fullName>
                <label>Engineering Consultant</label>
            </value>
            <value>
                <fullName>Fabricator</fullName>
                <label>Fabricator/Stonemason</label>
            </value>
            <value>
                <fullName>Fabricators</fullName>
                <isActive>false</isActive>
                <label>Fabricators</label>
            </value>
            <value>
                <fullName>Facade consultant</fullName>
                <label>Facade Consultant</label>
            </value>
            <value>
                <fullName>Facade Contractor</fullName>
                <isActive>false</isActive>
                <label>Facade Contractor</label>
            </value>
            <value>
                <fullName>Facade Installer</fullName>
            </value>
            <value>
                <fullName>Fit-out</fullName>
                <isActive>false</isActive>
                <label>Fit-out</label>
            </value>
            <value>
                <fullName>Fit-out company (commercial contract)</fullName>
                <label>Fit-Out Company (Commercial Contract)</label>
            </value>
            <value>
                <fullName>Franchisee</fullName>
            </value>
            <value>
                <fullName>Furniture Company</fullName>
            </value>
            <value>
                <fullName>Interior Design</fullName>
                <isActive>false</isActive>
                <label>Interior Design</label>
            </value>
            <value>
                <fullName>Interior design firm</fullName>
                <label>Interior Design Firm</label>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath store</fullName>
                <label>Kitchen &amp; Bath Store (XTONE only)</label>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath Store XTONE</fullName>
                <isActive>false</isActive>
                <label>Kitchen &amp; Bath Store XTONE</label>
            </value>
            <value>
                <fullName>Kitchen instalation company</fullName>
                <label>Kitchen Installation Company</label>
            </value>
            <value>
                <fullName>National House Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dirty__c.field-meta.xml
<CustomField>
    <fullName>Dirty__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If check, the account hasn&apos;t been synced with SAP and has been updated any of the Sync SAP fields</description>
    <label>Dirty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/F_Domain__c.field-meta.xml
<CustomField>
    <fullName>F_Domain__c</fullName>
    <formula>IF(
  NOT(IsPersonAccount),
  RIGHT(Business_Email__c, LEN(Business_Email__c) - FIND(&quot;@&quot;, Business_Email__c)),
  RIGHT(PersonEmail, LEN(PersonEmail) - FIND(&quot;@&quot;, PersonEmail))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Account</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/RegisterUniqueId__c.field-meta.xml
<CustomField>
    <fullName>RegisterUniqueId__c</fullName>
    <description>Código único del registro, calculado por apex en el trigger, y que puede variar el formato dependiendo el país o lo que se decida. Actualmente es domain+postcode</description>
    <label>Register Unique Id</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <externalId>true</externalId>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number_2__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number_2__c</fullName>
    <label>VAT Number 2</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <description>Código de Identificación Fiscal</description>
    <label>VAT Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distribution_Channel__c/Distribution_Channel__c.object-meta.xml
<CustomObject>
    <label>Distribution Channel</label>
    <nameField>
        <label>Distribution Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Channel__c/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <label>Sap Id / Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Opportunity</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Default Sales Org of the User who created the Opportunity</description>
    <label>Sales Org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <externalId>true</externalId>
    <label>Sap Id</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/Sales_Relationship__c.object-meta.xml
<CustomObject>
    <label>SAP Accounting Info</label>
    <nameField>
        <label>Nombre Organizaciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Accounting Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Relationship__c/fields/Account_Org__c.field-meta.xml
<CustomField>
    <fullName>Account_Org__c</fullName>
    <label>Account Org</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Organizaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Custom_Id__c.field-meta.xml
<CustomField>
    <fullName>Custom_Id__c</fullName>
    <description>id_de_sap del account + org. ventas + canal (revisar)</description>
    <externalId>true</externalId>
    <inlineHelpText>SAP ID, PK of 3 grouped values: Customer Sap ID + Sales Organization + Distribution Channel</inlineHelpText>
    <label>Custom Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Tienda</description>
    <inlineHelpText>Sales Office</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <formula>Account_Org__r.SAP_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Default_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Organization__c</fullName>
    <description>La organización de ventas por defecto para el comercial</description>
    <inlineHelpText>The default sales organization for sales and distribution</inlineHelpText>
    <label>Default Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Distribution_channel_default__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel_default__c</fullName>
    <label>Distribution channel default</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Sales Office from Sales Org default</description>
    <inlineHelpText>Sales Office from Sales Org default</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Default_Sales_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
/**
* @author Ivan Losilla
* @date November 2020
* @group Triggers
*/
public class AccountTriggerHandler extends BaseTriggerHandler {
 
    public override void beforeDelete(List<SObject> oldItems) {
        for (Account acc : (List<Account>) oldItems) {
            if (acc.SAP_Id__c != null) {
                acc.addError(Label.Account_Cant_delete);
            }
        }
    }

    public override void beforeUpdate(List<SObject> newItems, Map<Id, SObject> oldItems) {
        Boolean userHasSap = UserCommons.hasSAPConnection();
        PorcelanosaSetting setting;
        try {
            setting = new PorcelanosaSetting('REQUIRED_VAT', 'ALL');
        } catch (Exception ex) {
            setting = null;
        }

        for (Account acc : (List<Account>) newItems) {
            changesBefore(acc);
            checkVAT(acc, setting);
            setRegisterUniqueId(acc);

            // If any of the Synced SAP fields change, set Dirty to True if the Account is on SAP
            if (String.isNotBlank(acc.Sap_Id__c) && AccountSyncEvaluator.syncToSAP(acc, (Account)oldItems.get(acc.Id)) == true) {
                acc.Dirty__c = true;
            }

            if (String.isNotBlank(acc.Sap_Id__c) && userHasSap == false && test.isrunningtest() == false ) {
                acc.addError(Label.Account_no_editable_context);
            }
        }
    }

    public override void beforeInsert(List<SObject> newItems) {
        Boolean isAdmin = UserUtils.isAdministrator();
        PorcelanosaSetting setting;
        try {
            setting = new PorcelanosaSetting('REQUIRED_VAT', 'ALL');
        } catch (Exception ex) {
            setting = null;
        }

        for (Account acc : (List<Account>) newItems) {
            changesBefore(acc);
            checkVAT(acc, setting);
            setRegisterUniqueId(acc);
        }
    }

    public override void afterUpdate(List<SObject> newItems, Map<Id, SObject> oldItems) {
        ExecutionContext context = ExecutionContext.getUserExecutionContext();
        List<Sales_Relationship__c> listSalesRel = new List<Sales_Relationship__c>();
        Set<Id> contactIds = new Set<Id>();

        if (UserCommons.hasSAPConnection()) {
            listSalesRel = createDefaultSalesRelations((List<Account>) newItems, (Map<Id, Account>)oldItems);
            sendSalesRelToSap(listSalesRel);
        }

        for (Account acc : (List<Account>) newItems) {
            if (acc.IsPersonAccount == true) {
                contactIds.add(acc.PersonContactId);
            }
        }
    }
    
    public override void afterInsert(List<SObject> newItems) {
        Boolean isAdmin = UserUtils.isAdministrator();
        List<Sales_Relationship__c> listSalesRel = new List<Sales_Relationship__c>();
        Set<Id> accIds = new Set<Id>();
        Set<Id> contactIds = new Set<Id>();

        for (Account acc : (List<Account>) newItems) {
            accIds.add(acc.Id);
        }
        
        if (isAdmin == false && UserCommons.hasSAPConnection()) {
            listSalesRel = createDefaultSalesRelations((List<Account>) newItems, new Map<Id,Account>());
            sendSalesRelToSap(listSalesRel);
        }
        createAutomaticOpps((List<Account>) newItems);
        sendInvalidAccountsMail(accIds);
    }
    
    /********************************       Private Methods      *********************************/
    @future
    private static void sendInvalidAccountsMail(Set<Id> accIds) {
        List<Account> newItemsData = new List<Account>();

        newItemsData = AccountUtil.getData(accIds);
        AccountMails.alertNotValidCreation(newItemsData);
    }

    private static void setRegisterUniqueId(Account acc) {
        String domain = acc.F_Domain__c;
        String postal;

        try {
            if (acc.IsPersonAccount) {
                postal = acc.PersonMailingPostalCode;
            } else {
                postal = acc.BillingPostalCode;
            }
    
            if (!String.isBlank(domain) && !String.isBlank(postal)) {
                String cleanDomain = domain.trim().replaceAll('\\s+', '').toUpperCase();
                String cleanPostal = postal.trim().replaceAll('\\s+', '').toUpperCase();
                String postal3 = cleanPostal.length() > 3 ? cleanPostal.substring(0, 3) : cleanPostal;

                // Obtener el país para decidir la lógica
                String country = acc.BillingCountryCode; // O PersonMailingCountry si es PersonAccount
                if (acc.IsPersonAccount) {
                    country = acc.PersonMailingCountryCode;
                }

                if (country == 'US' || country == 'CA') {
                    acc.RegisterUniqueId__c = cleanDomain + ':' + postal3;
                } else {
                    // Lógica normal (todo el código postal)
                    acc.RegisterUniqueId__c = cleanDomain + ':' + cleanPostal;
                }
            } else {
                acc.RegisterUniqueId__c = null;
            }
        } catch (Exception ex) {
            acc.RegisterUniqueId__c = null;
        }
    }

    // Chequea que el vat sea correcto, si no es vacío
    private void checkVAT(Account acc, PorcelanosaSetting settingsRequiredVat) {
        Boolean validVat = true;
        Boolean validate = false;

        if (settingsRequiredVat == null) {
            return;
        }

        List<String> requiredVatCountries = settingsRequiredVat.value1.split(';');

        if (acc.IsPersonAccount == false && requiredVatCountries.contains(acc.BillingCountryCode)) {
            // France
            if (acc.BillingCountryCode == 'FR') {
                if (String.isNotBlank(acc.Vat_number__c)){
                    validate = true;
                }

                if (validate) {
                    validVat = TaxCommons.isValidSiret(acc.VAT_Number__c);
                    if (validVat == true) {
                        acc.VAT_Number_2__c = TaxCommons.getSirenFromSiret(acc.VAT_Number__c);
                    } else {
                        acc.addError(Label.Not_valid_vat);
                    }
                }
            }

            if (acc.BillingCountryCode == 'GB') {
                if (String.isNotBlank(acc.Vat_number__c)) {
                    validVat = TaxCommons.isValidCRN(acc.VAT_Number__c);
                    if (validVat == false && test.isRunningTest() == false) {
                        acc.addError(Label.Not_valid_vat);
                    }
                }

                if (String.isNotBlank(acc.Vat_number_2__c)){
                    validVat = TaxCommons.isValidUKVAT(acc.Vat_number_2__c);
                    if (validVat == false && test.isRunningTest() == false) {
                        acc.addError(Label.Not_valid_vat_2);
                    }
                }
            }
        }
    }

    private void createAutomaticOpps(List<Account> newItems) {
        Id tradeRecTypeId = RecordTypeLibrary.Account_TradeCustomer;
        List<Opportunity> listAutomaticOpps = new List<Opportunity>();

        for (Account acc : newItems) {
            if(acc.RecordTypeId == tradeRecTypeId && acc.Account_Classification__c == 'National House Builders') {
                listAutomaticOpps.add( SalesRelationshipUtils.createAutomaticOpportunity(acc) );
            }
        }
        upsert listAutomaticOpps;
    }

    private void sendSalesRelToSap(List<Sales_Relationship__c> listSalesRel) {
        List<Id> salesRelIdList = new List<Id>();
        if (listSalesRel.isEmpty() == false) {
            for( Sales_Relationship__c salesRel : listSalesRel ){
                salesRelIdList.add(salesRel.Id);
            }

            Automatic_AccountSendToSAP.ManageSendToSap(salesRelIdList);
        }
    }

    private void changesBefore(Account acc) {
        if (Trigger.isInsert) {
            acc.Last_Activity_Date__c = System.now(); 
        }

        if(acc.IsPersonAccount){
            acc.PersonMailingPostalCode = StringUtils.toUpperCase(acc.PersonMailingPostalCode);
            acc.Salutation = AccountUtil.mapSalutation(acc.Salutation);
            acc.Firstname = StringUtils.toUpperCase(acc.Firstname);
            acc.Lastname = StringUtils.toUpperCase(acc.Lastname);
        } else {
            acc.BillingPostalCode = StringUtils.toUpperCase(acc.BillingPostalCode);
            acc.name = StringUtils.toUpperCase(acc.name);
        }
    }

    private List<Sales_Relationship__c> createDefaultSalesRelations(List<Account> newAccounts, Map<Id, Account> oldAccounts) {
        Boolean isAdmin = UserUtils.isAdministrator();
        Id privateRecTypeId = RecordTypeLibrary.Account_PrivateCustomer;
        List<Sales_Relationship__c> salesRelsToInsert = new List<Sales_Relationship__c>();
        Set<Id> accOwnerIds = new Set<Id>();
        Set<Id> newAccIds = new Set<Id>();
        Map<Id,User> accOwnerMap = new Map<Id, User>();
        List<Sales_Relationship__c> salesRelList = new List<Sales_Relationship__c>();
        User triggerUser = [SELECT Id, ProfileId, CountryCode, Default_Sales_Organization__c, Distribution_channel_default__c, Sales_Office__c
                            FROM User WHERE Id =: UserInfo.getUserId()];
        
        // Si la organización tiene restricción, no se crea por defecto la Sales Relationship
        Boolean isRestrictedOrg = SalesRelationshipsDomain.isRestrictedOrg(triggerUser.Default_Sales_Organization__c);
        if (isRestrictedOrg) {
            return salesRelList;
        }

        for(Account acc : newAccounts ){
            accOwnerIds.add( acc.OwnerId );
            newAccIds.add( acc.Id );
        }
        
        salesRelList = [SELECT Id, Account_Org__c, Name, Custom_Id__c, Sales_Org__c, Distribution_Channel__c, CreatedBy.CountryCode
        FROM Sales_Relationship__c WHERE Account_Org__c IN: newAccIds];
        accOwnerMap = new Map<Id, User>([SELECT Id, CountryCode, Default_Sales_Organization__c, Distribution_channel_default__c,
        Sales_Office__c, ProfileId FROM User WHERE Id IN :accOwnerIds]);
                            
        for (Account acc : newAccounts) {
            User newAccOwner = accOwnerMap.get(acc.OwnerId);
            Boolean salesRelAlreadyExist = false;
            if (Trigger.isInsert && acc.RecordTypeId == privateRecTypeId && isAdmin == false) {
                    salesRelsToInsert.add(SalesRelationshipUtils.createDefaultSalesRelations(acc, triggerUser, 'New Account'));
            }

            // Changed owner
            if (Trigger.isUpdate && acc.RecordTypeId ==  privateRecTypeId && acc.SAP_Id__c != null && acc.OwnerId != oldAccounts.get(acc.Id).OwnerId && isAdmin == false && newAccOwner != null){
                for(Sales_Relationship__c salesRel : salesRelList){
                    if(salesRel.Account_Org__c == acc.Id && salesRel.Distribution_Channel__c == newAccOwner.Distribution_channel_default__c && salesRel.Sales_Org__c == newAccOwner.Default_Sales_Organization__c){
                        salesRelAlreadyExist = true;
                        break;
                    }
                }

                // The default Sales Relation doesn't exist
                if( salesRelAlreadyExist == false ){
                    salesRelsToInsert.add(SalesRelationshipUtils.createDefaultSalesRelations(acc, newAccOwner, 'Change Account Owner'));
                }
            }
        }

        upsert salesRelsToInsert;

        return salesRelsToInsert;
    }
}