force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country code ISO-3166-1</description>
    <label>Country_old</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Account</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastOpportunityDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastOpportunityDateTime__c</fullName>
    <description>We set here the time of the last Opportunity related created</description>
    <label>Last Opportunity DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <formula>Owner.Sales_Office_Text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Amount_custom__c.field-meta.xml
<CustomField>
    <fullName>Amount_custom__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount of the opportunity without currency</description>
    <inlineHelpText>Amount of the opportunity without currency</inlineHelpText>
    <label>Quantity of the opportunity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <defaultValue>&apos;GBP&apos;</defaultValue>
    <description>IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;203&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;206&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;207&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;208&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;210&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;218&quot;),&quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;602&quot;), &quot;USD&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;603&quot;), &quot;USD&quot;,  IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;604&quot;), &quot;USD&quot;, IF(ISPICKVAL($User.Default_Sales_Organization__c,&quot;605&quot;), &quot;USD&quot;, IF(ISPICKVAL($User.Default_Sales_Organization__c,&quot;606&quot;), &quot;USD&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;608&quot;), &quot;USD&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;615&quot;), &quot;USD&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;650&quot;), &quot;CAD&quot;, &quot;GBP&quot;))))))</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>ILS</fullName>
            </value>
            <value>
                <fullName>CLP</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>DOP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dist_Channel__c.field-meta.xml
<CustomField>
    <fullName>Dist_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Have_we_won_specification__c.field-meta.xml
<CustomField>
    <fullName>Have_we_won_specification__c</fullName>
    <label>Is PORCELANOSA included in the Spec?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>--</fullName>
                <isActive>false</isActive>
                <label>--</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Opportunity</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Classification__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Classification__c</fullName>
    <label>Opportunity Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
                <isActive>false</isActive>
                <label>Education</label>
            </value>
            <value>
                <fullName>Health care</fullName>
                <label>Healthcare</label>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Institutional</fullName>
            </value>
            <value>
                <fullName>Mixed Use Development</fullName>
                <isActive>false</isActive>
                <label>Mixed Use Development</label>
            </value>
            <value>
                <fullName>Office</fullName>
                <label>Office/Corporate</label>
            </value>
            <value>
                <fullName>Other (indicate)</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>Transport stations</fullName>
                <label>Other Transport stations</label>
            </value>
            <value>
                <fullName>Public building</fullName>
                <isActive>false</isActive>
                <label>Public building</label>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Residential (Retail)</fullName>
            </value>
            <value>
                <fullName>Retail Store</fullName>
            </value>
            <value>
                <fullName>Samples Ecommerce</fullName>
            </value>
            <value>
                <fullName>Senior living</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Default Sales Org of the User who created the Opportunity</description>
    <label>Sales Org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesOrglookup__c.field-meta.xml
<CustomField>
    <fullName>SalesOrglookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Org</label>
    <referenceTo>Sales_Org__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityContactRole/fields/SapStatus__c.field-meta.xml
<CustomField>
    <fullName>SapStatus__c</fullName>
    <label>Sap Status</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/SALES_OFFICE__c.object-meta.xml
<CustomObject>
    <description>Entidad custom que contiene el maestro de relaciones para transformar el código de la oficina de ventas por el nombre.</description>
    <label>Sales Office</label>
    <nameField>
        <label>Nombre de SALES_OFFICE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Default_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Organization__c</fullName>
    <description>La organización de ventas por defecto para el comercial</description>
    <inlineHelpText>The default sales organization for sales and distribution</inlineHelpText>
    <label>Default Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Does_this_position_have_a_sales_budget__c.field-meta.xml
<CustomField>
    <fullName>Does_this_position_have_a_sales_budget__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <label>Does this position have a sales budget?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Sales Office from Sales Org default</description>
    <inlineHelpText>Sales Office from Sales Org default</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Default_Sales_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandlerTest.cls
@isTest
public class OpportunityTriggerHandlerTest {
    private static Map<String, Sales_Org__c> salesOrgMap;
    
	@testSetup
    static void setup() {
        TestUtils.enableTriggers();
        User testUser = User_TestDataFactory.createUsers(1, new List<String>{'en_US'})[0];
        testUser.Sales_Org__c = OrganizationCommons.ORG_AZURCERAMIQUE + ';' + OrganizationCommons.ORG_PIDF;
        testUser.Does_this_position_have_a_sales_budget__c = 'Si';
        testUser.Default_Sales_Organization__c = OrganizationCommons.ORG_AZURCERAMIQUE;
        testUser.sales_office__c = '3015';
        Insert testUser;
        
        List<Account> accList = new List<Account>();
        accList.add(Account_TestDataFactory.createBusinessAccount());
        accList.add(Account_TestDataFactory.createFabricator());
        Insert accList;

        List<Contact> contList = Contact_TestDataFactory.createContacts(2, new List<Map<String, Object>>{
            new Map<String, Object>{'AccountId' => accList[0].Id},
            new Map<String, Object>{'AccountId' => accList[1].Id}
        });
        Insert contList;

        DatafactoryOrganization.createData();  
    }

    @isTest static void testAfterInsert(){
        // Busca el usuario recien creado
        User testUser = [SELECT Id FROM User WHERE UserName LIKE '%@testOrg0.com' LIMIT 1];
        
        Account accbefore = [SELECT Id, LastOpportunityDateTime__c FROM Account WHERE Name = 'TestAcctBusinessAccount1'];
        accbefore.Last_Activity_Date__c = System.today().addDays(-3);
        update accbefore;
        System.runAs(testUser) {
            Test.startTest();        
            Opportunity newOpp = Opportunity_TestDataFactory.createTrade(accbefore);
            Insert newOpp;
            Test.stopTest();
        }
        Account accafter = [SELECT Id, LastOpportunityDateTime__c FROM Account WHERE Name = 'TestAcctBusinessAccount1'];
        System.assert(accbefore.LastOpportunityDateTime__c != accafter.LastOpportunityDateTime__c, 'Last Activity of the Account hasn\'t changed');
        
    }
    
    @isTest static void testBeforeInsert(){
        User testUser = [SELECT Name, Id FROM User WHERE UserName LIKE '%@testOrg0.com'][0];
        
        System.runAs(testUser){
            
            // Test 1: Success. Project Trade Record Type + Country de Account que no esta en la picklist Country__c
            List<Account> accList = [SELECT Id FROM Account WHERE Name = 'TestAcctBusinessAccount1' OR Name = 'TestAcctFabricatorAccount1'];
            
            List<Opportunity> oppList = new List<Opportunity>();
            oppList.add(Opportunity_TestDataFactory.createTrade(accList[0]));
            oppList.add(Opportunity_TestDataFactory.createTrade(accList[1]));
            
            List<Database.SaveResult> result_test_1;
            
            Test.setMock(HttpCalloutMock.class, new OpportunityMockHttpResponseGenerator());
            Test.startTest();
            	result_test_1 = Database.insert(oppList, false);
            Test.stopTest();
            
            System.assert( result_test_1[0].isSuccess() );
            System.assert( result_test_1[1].isSuccess() );
            
            // Actualizar la referencia para ver el campbio
            oppList = [SELECT Sales_Org__c, Dist_Channel__c FROM Opportunity WHERE Id IN: oppList];
            
            System.assertEquals(OrganizationCommons.ORG_AZURCERAMIQUE, oppList[0].Sales_Org__c);
            System.assertEquals('70', oppList[0].Dist_Channel__c);
            
            System.assertEquals(OrganizationCommons.ORG_AZURCERAMIQUE, oppList[1].Sales_Org__c);
            System.assertEquals('70', oppList[1].Dist_Channel__c);
            
            
       }
    }
    
    @isTest static void testBeforeUpdate(){
        Map<String, Sales_Org__c> salesOrgMap = OrganizationUtil.getSalesOrgsMap();
        User testUser = [SELECT Id FROM User WHERE UserName LIKE '%@testOrg0.com' LIMIT 1];
        
        System.runAs(testUser) {
            // Test 1: Success. Una Opportunity con Actores Validos
            // Cuando se pasa al estado Cotizacion entonces debera ejecutarse la comprobacion validateAcount
            // Si pasa entonces debera enviarse a sap
            Account acc = [SELECT Id FROM Account WHERE Name = 'TestAcctBusinessAccount1'];
            Contact cont = [SELECT Id FROM Contact WHERE AccountId =: acc.Id];
            
            List<Opportunity> oppListToInsert = new List<Opportunity>();
            // Opportunity valida.
            Opportunity newOpp = Opportunity_TestDataFactory.createTrade(acc);
            newOpp.Opportunity_Classification__c = 'Residential';
            newOpp.SalesOrglookup__c = salesOrgMap.get(OrganizationCommons.ORG_AZURCERAMIQUE).Id;
            oppListToInsert.add(newOpp);
            
            // Opportunity sin actores.
            Opportunity oppWithoutActors = Opportunity_TestDataFactory.createTrade(acc);
            oppWithoutActors.SalesOrglookup__c = salesOrgMap.get(OrganizationCommons.ORG_AZURCERAMIQUE).Id;
            oppWithoutActors.Opportunity_Classification__c = 'Residential';
            oppListToInsert.add(oppWithoutActors);
            
            // Opportunity con una salesOrg que no coincide con la relacion de ventas de la cuenta.
            Opportunity oppInvalidAcc = Opportunity_TestDataFactory.createTrade(acc);
            oppInvalidAcc.Opportunity_Classification__c = 'Residential';
            oppInvalidAcc.SalesOrglookup__c = salesOrgMap.get(OrganizationCommons.ORG_PIDF).Id;
            oppListToInsert.add(oppInvalidAcc);
            
            Insert oppListToInsert;
            
            // Actor para newOpp
            OpportunityContactRole oppActor_newOpp = new OpportunityContactRole(OpportunityId = newOpp.Id, ContactId = cont.Id, isPrimary = true);
            insert oppActor_newOpp;
            
            // Actor para oppInvalidAcc
            OpportunityContactRole oppActor_Invalid = new OpportunityContactRole(OpportunityId = oppInvalidAcc.Id, ContactId = cont.Id, isPrimary = false);
            insert oppActor_Invalid;
            
            // Have_we_won_specification__c es necesario para poder pasar la regla de validacion y pasar a la etapa "Cotizacion"
            newOpp.StageName = 'Cotización';
            newOpp.Amount_custom__c = 1000;
            newOpp.Have_we_won_specification__c = 'Yes';
            newOpp.Currency__c = 'CAD';
            // oppWithoutActors.StageName = 'Cotización';
            // oppWithoutActors.Amount_custom__c = 1000;
            // oppWithoutActors.Have_we_won_specification__c = 'Yes';
            
            Test.setMock(HttpCalloutMock.class, new OpportunityMockHttpResponseGenerator());
            Test.startTest();
            	update oppListToInsert;
            	// Se prueba actualizar la misma oportunidad devuelva, si el StageName no cambia entonces no se debe enviar a sap.
            	update newOpp;
            Test.stopTest();
            
            // Cherckeando que el Opportunity Actor se haya enviado a SAP exitosamente.
            List<OpportunityContactRole> oppListUpdated = [SELECT Id, SAPStatus__c FROM OpportunityContactRole 
                                                         WHERE Id =: oppActor_newOpp.Id OR OpportunityId =: oppWithoutActors.Id
                                                         OR OpportunityId =: oppInvalidAcc.Id];
            System.assertEquals('Success', oppListUpdated[0].SAPStatus__c); // oppActor_newOpp
            System.assertEquals('Success', oppListUpdated[1].SAPStatus__c); // oppInvalidAcc
        }
    }
}