force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country code ISO-3166-1</description>
    <label>Country_old</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/InstallationOrder__c.object-meta.xml
<CustomObject>
    <description>Object to follow up the progress of the installation service. It is the continuation of the Installation Request (InstallationRequest__c)</description>
    <label>Installation Order</label>
    <nameField>
        <label>Installation Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationOrder__c/fields/Installation_Request__c.field-meta.xml
<CustomField>
    <fullName>Installation_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Request</label>
    <referenceTo>InstallationRequest__c</referenceTo>
    <relationshipLabel>Installation Orders</relationshipLabel>
    <relationshipName>Installation_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Installation_Request__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InstallationOrder__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Installation_order_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/InstallationRequest__c.object-meta.xml
<CustomObject>
    <description>Class to store and follow the installation request of our products. This is a service certain showrooms offer through a list of authorised installers.</description>
    <label>Installation Request</label>
    <nameField>
        <label>Installation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationRequest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Opportunity this installation is for</description>
    <inlineHelpText>Please enter the opportunity this installation is for</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Installation Requests</relationshipLabel>
    <relationshipName>Installation_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/ReasonRejected__c.field-meta.xml
<CustomField>
    <fullName>ReasonRejected__c</fullName>
    <inlineHelpText>Please enter the reason for the rejection of this installation project.</inlineHelpText>
    <label>Reason Rejected</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <defaultValue>&quot;New Request&quot;</defaultValue>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InstallationStates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installer__c/Installer__c.object-meta.xml
<CustomObject>
    <description>Define accounts that can act as installers in a sales organisation</description>
    <label>Installer</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Installer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Installer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installers</relationshipLabel>
    <relationshipName>Installers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installer__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State / Province</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/PostCodeObjects__c.object-meta.xml
<CustomObject>
    <description>Object created to set an object related to a Postal Code</description>
    <label>Post Code Object</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Serial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Code Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PostCodeObjects__c/fields/country__c.field-meta.xml
<CustomField>
    <fullName>country__c</fullName>
    <label>country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/objectId__c.field-meta.xml
<CustomField>
    <fullName>objectId__c</fullName>
    <description>Salesforce Id of the object related</description>
    <label>objectId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/objectType__c.field-meta.xml
<CustomField>
    <fullName>objectType__c</fullName>
    <label>objectType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INSTALLER</fullName>
                <default>true</default>
                <label>INSTALLER</label>
            </value>
            <value>
                <fullName>SALES_ORG</fullName>
                <label>SALES ORG</label>
            </value>
            <value>
                <fullName>SALES_OFFICE</fullName>
                <label>SALES OFFICE</label>
            </value>
            <value>
                <fullName>OWNER_USA</fullName>
                <label>OWNER USA</label>
            </value>
            <value>
                <fullName>MBK-EUR</fullName>
                <label>MATERIAL BANK (EUR)</label>
            </value>
            <value>
                <fullName>PORSAMARKET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PostCodeObjects__c/fields/postCode__c.field-meta.xml
<CustomField>
    <fullName>postCode__c</fullName>
    <label>postCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Installation_order_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Installation</fullName>
        <default>true</default>
        <label>New Installation</label>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing</fullName>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Satisfied</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Unsatisfied</fullName>
    </customValue>
    <description>InstallationOrder states picklist</description>
    <masterLabel>Installation order State</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/InstallationStates.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Request</fullName>
        <default>true</default>
        <label>New Request</label>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>3D Design</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Estimation</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Won</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>States of Installation Requests</description>
    <masterLabel>Installation States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InstallationUtilTest.cls
@isTest
public class InstallationUtilTest {

    @testSetup static void setup() {
 		Insert TriggerConfiguration_TestDataFactory.createCustomSetting_ActivatedTriggers();
    } // setup
    
    /* */
    @isTest static void getInstallationOrders() {
        List<InstallationRequest__c> requests = DataFactoryInstallation.createInstallationRequests(1);
        List<InstallationOrder__c> orders = DataFactoryInstallation.createInstallationOrders(requests);
        
        String requestId = requests[0].Id;        
    	InstallationOrder__c order = [select Id from InstallationOrder__c where Installation_Request__c = :requestId ][0];
        
        System.assertEquals(order.Id, orders[0].Id, 'Orders ID do not match!');
    } // getInstallationOrders
    
    @isTest static void hasInstallationRequest() {
        List<InstallationRequest__c> requests = DataFactoryInstallation.createInstallationRequests(1);        
        String oppId = requests[0].Opportunity__c;        
        Boolean result = InstallationUtil.hasInstallationRequest(oppId);
        System.assertEquals(true, result); 
        
        delete requests[0];
		result = InstallationUtil.hasInstallationRequest(oppId);
        System.assertEquals(false, result); 
                
    }
    
    /* */    
    @isTest static void isRequestNew() {
		InstallationRequest__c request = DataFactoryInstallation.createInstallationRequests(1)[0];
        Boolean result = InstallationUtil.isRequestNew(request);
        System.assertEquals(true, result);
    } // isRequestNew
    
    /* */    
    @isTest static void isRequestAccepted() {
		InstallationRequest__c request = DataFactoryInstallation.createInstallationRequests(1)[0];
        request.State__c = InstallationUtil.acceptedState;
  		Boolean result = InstallationUtil.isRequestAccepted(request);
        System.assertEquals(result, true);
    } // isRequestNew

    /* */    
    @isTest static void isRequestRejected() {
		InstallationRequest__c request = DataFactoryInstallation.createInstallationRequests(1)[0];
        request.State__c = InstallationUtil.rejectedState;
    	request.ReasonRejected__c = 'test comments';
  		Boolean result = InstallationUtil.isRequestRejected(request);
        System.assertEquals(result, true);
    } // isRequestNew  
    
    /*
    @isTest static void getInstallers() {
        List<PostCodeObjects__c> pco = new List<PostCodeObjects__c>();
        pco.add(new PostCodeObjects__c(objectType__c = 'INSTALLER', country__c = 'GB', postCode__c = '', objectId__c = 'a2U1x0000003LO6EAM'));
        pco.add(new PostCodeObjects__c(objectType__c = 'INSTALLER', country__c = 'GB', postCode__c = '', objectId__c = 'a2U1x0000003LO6EAR'));           
        pco.add(new PostCodeObjects__c(objectType__c = 'INSTALLER', country__c = 'FR', postCode__c = '', objectId__c = 'a2U1x0000003LO6EAR'));           
        insert pco;
        List<Id> installers = InstallationUtil.getInstallers('GB', 'LA22 9NZ');
        System.assertEquals(2, installers.size(), 'Two installers should have been returned');        
    }
    */

    @isTest static void getInstallers() {
        List<Installer__c> ins = new List<Installer__c>();
        Account[] accs = DataFactoryAccount.createAccounts(2);
        Account acc1 = accs[0];
        Account acc2 = accs[1];
        ins.add(new Installer__c(SalesOrg__c = OrganizationCommons.ORG_SOUTH_EAST, Account__c = acc1.Id));
        ins.add(new Installer__c(SalesOrg__c = OrganizationCommons.ORG_NORTH_WEST, Account__c = acc1.Id));
        ins.add(new Installer__c(SalesOrg__c = OrganizationCommons.ORG_NORTH_WEST, Account__c = acc2.Id));
        ins.add(new Installer__c(SalesOrg__c = OrganizationCommons.ORG_YORKSHIRE, Account__c = acc2.Id));
        insert ins;

        List<Id> installers = InstallationUtil.getInstallers(OrganizationCommons.ORG_SOUTH_EAST + ';' + OrganizationCommons.ORG_NORTH_WEST + ';' + OrganizationCommons.ORG_YORKSHIRE);
        System.assertEquals(2, installers.size(), '2 installers should have been returned');        

        installers = InstallationUtil.getInstallers(OrganizationCommons.ORG_SOUTH_EAST);
        System.assertEquals(1, installers.size(), '1 installer should have been returned');        

        installers = InstallationUtil.getInstallers(OrganizationCommons.ORG_SCOTLAND);
        System.assertEquals(0, installers.size(), 'No installer should have been returned');        
    }
    
    @isTest static void getOpportunityInstallers() {
        List<Account> accounts = DataFactoryAccount.createPersonAccounts(1);
        List<Opportunity> opportunities = DataFactoryOpportunity.createRetailOpportunities(accounts, 1);
        Opportunity opp = opportunities[0];        
        List<id> installers = InstallationUtil.getOpportunityInstallers(opp.Id);
        System.assertEquals(0, installers.size(), 'No installer should have been found');
    }
    
    @isTest static void hasInstallations() {
        // Just tests if there's a result
        Boolean access = InstallationUtil.hasInstallations();
        System.assert(access == true || access == false);
    }

    @isTest static void isRequestClosed() {
        InstallationRequest__c request = DataFactoryInstallation.createInstallationRequests(1)[0];
        request.State__c = InstallationUtil.closedStateRequest[0];
    	request.ReasonRejected__c = 'test comments';
        Boolean result = InstallationUtil.isRequestClosed(request);
        System.assertEquals(result, true);
    } // isRequestClosed  
    
    @isTest static void isOrderClosed() {
        List<InstallationRequest__c> requests = DataFactoryInstallation.createInstallationRequests(1);
        List<InstallationOrder__c> orders = DataFactoryInstallation.createInstallationOrders(requests);
        orders[0].State__c = InstallationUtil.closedStateOrder[0];
        Boolean result = InstallationUtil.isOrderClosed(orders[0]);
        System.assertEquals(result, true);
    } // isRequestClosed  
    
    @isTest static void requestNextActionLabel() {
        InstallationRequest__c request = DataFactoryInstallation.createInstallationRequests(1)[0];
        request = [select id, State__c from InstallationRequest__c where Id =: request.Id];
        String aux = '';
        request.State__c = InstallationUtil.newState;
        aux = InstallationUtil.requestNextActionLabel(request);
        System.assert(aux == Label.insr_next_newrequest, 'Label doesn\'t match');
     }
}