force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country code ISO-3166-1</description>
    <label>Country_old</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountrySettings__c/CountrySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings at country level</description>
    <label>Country Settings</label>
</CustomObject>

force-app/main/default/objects/CountrySettings__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country code</description>
    <inlineHelpText>Country code</inlineHelpText>
    <label>Country</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CountrySettings__c/fields/EnableREVIEWSMS__c.field-meta.xml
<CustomField>
    <fullName>EnableREVIEWSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enables the button to send a SMS to an account asking for a good review in Google</description>
    <inlineHelpText>Enables the button to send a SMS to an account asking for a good review in Google</inlineHelpText>
    <label>Enable REVIEW SMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MarketingActions__c/MarketingActions__c.object-meta.xml
<CustomObject>
    <description>Keeps data used by Marketing to send emails, SMS, etc.</description>
    <label>Marketing Action</label>
    <nameField>
        <displayFormat>MA-{00000000}</displayFormat>
        <label>Marketing Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MarketingActions__c/fields/ActionId__c.field-meta.xml
<CustomField>
    <fullName>ActionId__c</fullName>
    <description>Identifies the type of action</description>
    <label>Action ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MarketingActions__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MarketingActions__c/fields/DateRequested__c.field-meta.xml
<CustomField>
    <fullName>DateRequested__c</fullName>
    <description>Stores the date requested</description>
    <label>Date Requested</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MarketingActions__c/fields/RelatedId__c.field-meta.xml
<CustomField>
    <fullName>RelatedId__c</fullName>
    <description>Stores the Id of the related object</description>
    <label>Related Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MarketingActions__c/fields/SendTo__c.field-meta.xml
<CustomField>
    <fullName>SendTo__c</fullName>
    <description>Stores the information about where is gonna be sent (SMS, Email, etc.)</description>
    <label>Send To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MarketingActions__c/fields/TimeRequested__c.field-meta.xml
<CustomField>
    <fullName>TimeRequested__c</fullName>
    <description>Stores the time requested</description>
    <label>Time Requested</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReviewSmsComponentControllerTest.cls
@isTest
public class ReviewSmsComponentControllerTest {
  @testSetup
  static void setup() {
    TestUtils.enableTriggers();
    List<Account> listAcc = new List<Account>();

    listAcc.addAll(DataFactoryAccount.createPersonAccounts(1));
    MarketingActions.createReviewSMS(listAcc[0].Id, '+61411111111', 'US');
    MarketingActions.createReviewSMS(listAcc[0].Id, '+3499999999', 'ES');

  }

  @isTest
  public static void getLastReviewSMS(){
    List<Account> accs = [Select Id from Account];
    List<MarketingActions__c> listActions = [SELECT Id,
                                              ActionId__c,
                                              Country__c,
                                              DateRequested__c,
                                              RelatedId__c,
                                              SendTo__c,
                                              TimeRequested__c,
                                              CreatedById
                                              from MarketingActions__c];
    String idNewest = listActions[1].Id;
    listActions[0].DateRequested__c = '2020-01-01';
    update listActions;

    MarketingActions__c action = ReviewSmsComponentController.getLastReviewSMS(accs[0].Id);

    System.assert(action.Id == idNewest, 'No se ha encontrado el último Review');
  }

  @isTest
  public static void createReviewSMS(){
    List<Account> listAcc = new List<Account>();
    listAcc.addAll(DataFactoryAccount.createBusinessAccounts(1));
    ReviewSmsComponentController.createReviewSMS(listAcc[0].Id, listAcc[0].Phone, listAcc[0].PersonMailingCountryCode);
    List<Account> accs = [Select Id from Account];
    ReviewSmsComponentController.createReviewSMS(accs[0].Id, '+3499999999', 'GB');
    List<MarketingActions__c> actions = [Select Id from MarketingActions__c];

    System.assertEquals(4, actions.size(), 'No se ha creado un review SMS');
  }

  @isTest
  public static void canReviewSMS(){
      List<Account> accs = [Select Id, Owner.CountryCode from Account];
    User usr = DataFactoryUser.createUKUser();

    System.assertEquals(false, ReviewSmsComponentController.canReviewSMS(accs[0].Id), 'no ha de poder crear Review SMS');
    

    CountrySettings__c newCountrySetting = new CountrySettings__c(Name = 'United Kingdom', Country__c = accs[0].Owner.CountryCode, enableREVIEWSMS__c = true);
    insert newCountrySetting;

    System.assertEquals(true, ReviewSmsComponentController.canReviewSMS(accs[0].Id), 'Ha de poder crear Review SMS');

  }

  @isTest
  public static void checkValidPhone(){
      String phone = '123-123123-123 .55';
      System.assertEquals(true, ReviewSmsComponentController.checkValidPhone(phone), 'Debería ser un teléfono válido');
      phone = '2864 HTG (56)';
      System.assertEquals(false, ReviewSmsComponentController.checkValidPhone(phone), 'Debería ser un teléfono válido');
  }
}