force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country code ISO-3166-1</description>
    <label>Country_old</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Trade_and_Specificators.recordType-meta.xml
<RecordType>
    <fullName>Trade_and_Specificators</fullName>
    <active>true</active>
    <description>Form used for trade specifications and other professionals involved in projects (B2B)</description>
    <label>Trade and Specificators</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/countryCode__c.field-meta.xml
<CustomField>
    <fullName>countryCode__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Default Sales Org of the User who created the Opportunity</description>
    <label>Sales Org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Project_retail.recordType-meta.xml
<RecordType>
    <fullName>Project_retail</fullName>
    <active>true</active>
    <businessProcess>Sales process retail</businessProcess>
    <label>Project retail</label>
</RecordType>

force-app/main/default/objects/OpportunitySettings__c/OpportunitySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for features related to the Opportunities, by Country</description>
    <label>PORSA Opportunity Settings</label>
</CustomObject>

force-app/main/default/objects/OpportunitySettings__c/fields/novalidcreation_mailto__c.field-meta.xml
<CustomField>
    <fullName>novalidcreation_mailto__c</fullName>
    <description>List of Id, of the Managers that are going to receive the email of OpportunitytMail.alertNotValidCreation</description>
    <label>No Valid Opportunity Creation Mail To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/SALES_OFFICE__c.object-meta.xml
<CustomObject>
    <description>Entidad custom que contiene el maestro de relaciones para transformar el código de la oficina de ventas por el nombre.</description>
    <label>Sales Office</label>
    <nameField>
        <label>Nombre de SALES_OFFICE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_OFFICE__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <description>Country ISO Code</description>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/countries__c.field-meta.xml
<CustomField>
    <fullName>countries__c</fullName>
    <description>List of countries where the user can work</description>
    <label>Countries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Default_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Organization__c</fullName>
    <description>La organización de ventas por defecto para el comercial</description>
    <inlineHelpText>The default sales organization for sales and distribution</inlineHelpText>
    <label>Default Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Distribution_channel_default__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel_default__c</fullName>
    <label>Distribution channel default</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Sales Office from Sales Org default</description>
    <inlineHelpText>Sales Office from Sales Org default</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Default_Sales_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityMailsTest.cls
@isTest
public with sharing class OpportunityMailsTest {
  @testSetup static void setup() {
    Insert TriggerConfiguration_TestDataFactory.createCustomSetting_ActivatedTriggers();
    OpportunitySettings__c newOppSetting = new OpportunitySettings__c(Name = 'GB', Country__c = 'GB', novalidcreation_mailto__c = 'ivan.losilla@porcelanosagrupo.com');
    insert newOppSetting;
  }

  @isTest
  static void alertNotValidCreation() {
    User auxUser = DataFactoryUser.createUKUser();
      Map<String,Schema.RecordTypeInfo> recTypeMap = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName();
      Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Trade_and_Specificators').getRecordTypeId();	
      String retailRecTypeId = recTypeMap.get('Project_retail').getRecordTypeId();

      User u = [SELECT Id, CountryCode, Sales_org__c, countries__c, Default_Sales_Organization__c, Distribution_channel_default__c, Sales_Office__c, ProfileId from User where Id =: auxUser.Id LIMIT 1][0];
      Opportunity opp = new Opportunity();
      System.runAs(u) {
        Account acc = new Account(Name = 'Test Account #2', RecordTypeId=rtId, 
                          BillingCountryCode = 'GB',
                          BillingCity = 'London',
                          BillingPostalCode = 'BS1 3ND');
        insert acc;
        opp = new Opportunity(Name = 'Test Retail Opportunity',
                          AccountId = acc.Id,
                          countryCode__c = 'ES',
                          RecordTypeId = retailRecTypeId,
                          StageName = 'Qualification',
                          roomTypeBathroom__c = 1,
                          CloseDate = System.today());
        insert opp;
      }

      OpportunityMails.alertNotValidCreation(new Set<Id>{opp.Id});
      Integer invocations = Limits.getEmailInvocations();
      System.assert(invocations > 0, 'Mail not sent. Mails sent: ' + invocations);
  }
}