force-app/main/default/objects/Account/fields/DVSAcceptedBy__c.field-meta.xml
<CustomField>
    <fullName>DVSAcceptedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quien ha aceptado o descartado los cambios del DVS</description>
    <label>DVS Accepted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DVSAcceptedDate__c.field-meta.xml
<CustomField>
    <fullName>DVSAcceptedDate__c</fullName>
    <description>Fecha de cuando se han aceptado o descartado los cambios</description>
    <label>DVS Accepted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/DVSAction__c.field-meta.xml
<CustomField>
    <fullName>DVSAction__c</fullName>
    <description>Discarded: Se quedan con los datos de Salesforce
Accepted: Se quedan con los datos del DVS
Unknown: No ha habido resultados al buscar por el dvs.
Confirmed: Contabilidad ha aceptado la validación.</description>
    <label>DVS Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACCEPTED</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>DISCARDED</fullName>
                <label>Discarded</label>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
                <label>Unknown</label>
            </value>
            <value>
                <fullName>CONFIRMED</fullName>
                <label>Confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DvsError__c.field-meta.xml
<CustomField>
    <fullName>DvsError__c</fullName>
    <label>DVS Error (Deprecated)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/DvsHasError__c.field-meta.xml
<CustomField>
    <fullName>DvsHasError__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tell whether a DVS Error has been reported</inlineHelpText>
    <label>Has Dvs Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DvsLongError__c.field-meta.xml
<CustomField>
    <fullName>DvsLongError__c</fullName>
    <label>DVS Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/SynchronizedWithDvs__c.field-meta.xml
<CustomField>
    <fullName>SynchronizedWithDvs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Data validated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number_2__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number_2__c</fullName>
    <label>VAT Number 2</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <description>Código de Identificación Fiscal</description>
    <label>VAT Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DvsAccountInfo__c/DvsAccountInfo__c.object-meta.xml
<CustomObject>
    <label>Dvs Account Info</label>
    <nameField>
        <label>Dvs Account Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dvs Account Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DvsAccountInfo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DVS Account Info</relationshipLabel>
    <relationshipName>DVSAccountInfo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DvsAccountInfo__c/fields/PreviousCity__c.field-meta.xml
<CustomField>
    <fullName>PreviousCity__c</fullName>
    <label>Previous City</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DvsAccountInfo__c/fields/PreviousId1__c.field-meta.xml
<CustomField>
    <fullName>PreviousId1__c</fullName>
    <label>Previous Id1</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DvsAccountInfo__c/fields/PreviousId2__c.field-meta.xml
<CustomField>
    <fullName>PreviousId2__c</fullName>
    <label>Previous Id2</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DvsAccountInfo__c/fields/PreviousName__c.field-meta.xml
<CustomField>
    <fullName>PreviousName__c</fullName>
    <label>Previous Name</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DvsAccountInfo__c/fields/PreviousPostalCode__c.field-meta.xml
<CustomField>
    <fullName>PreviousPostalCode__c</fullName>
    <label>Previous PostalCode</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DvsAccountInfo__c/fields/PreviousStreet__c.field-meta.xml
<CustomField>
    <fullName>PreviousStreet__c</fullName>
    <label>Previous Street</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DvsAccountInfo__c/fields/ProcessedTime__c.field-meta.xml
<CustomField>
    <fullName>ProcessedTime__c</fullName>
    <label>Processed Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DvsDiscrepancy__c/DvsDiscrepancy__c.object-meta.xml
<CustomObject>
    <description>Company&apos;s discrepancies between Salesforce&apos;s and official national&apos;s information</description>
    <label>DVS Discrepancy</label>
    <nameField>
        <label>DVS Discrepancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DVS Discrepancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DvsDiscrepancy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DVS Discrepancies</relationshipLabel>
    <relationshipName>Dvs_Discrepancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DvsDiscrepancy__c/fields/DvsCity__c.field-meta.xml
<CustomField>
    <fullName>DvsCity__c</fullName>
    <label>DVS City</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DvsDiscrepancy__c/fields/DvsId2__c.field-meta.xml
<CustomField>
    <fullName>DvsId2__c</fullName>
    <label>DVS Id 2</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DvsDiscrepancy__c/fields/DvsId__c.field-meta.xml
<CustomField>
    <fullName>DvsId__c</fullName>
    <label>DVS Id</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DvsDiscrepancy__c/fields/DvsName__c.field-meta.xml
<CustomField>
    <fullName>DvsName__c</fullName>
    <label>DVS Name</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DvsDiscrepancy__c/fields/DvsPostalCode__c.field-meta.xml
<CustomField>
    <fullName>DvsPostalCode__c</fullName>
    <label>DVS PostalCode</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DvsDiscrepancy__c/fields/DvsStreet__c.field-meta.xml
<CustomField>
    <fullName>DvsStreet__c</fullName>
    <label>DVS Street</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DvsHelper.cls
/**
* @author Ivan Losilla
* @date April 2025
* @group Dvs
* @test DvsHelperTest
*/
public class DvsHelper {
    public static Map<String, DvsPorsaService> searchDiscrepancies(List<Account> accounts, Boolean fuzzySearch) {
        Map<String, DvsPorsaService> result = new Map<String, DvsPorsaService>();

        for (Account acc : accounts) {
            DvsPorsaService elem = new DvsPorsaService(acc);
            elem.doFullSearch();
            result.put(acc.Id, elem);
        }

        return result;
    }

    /**
     * Applies discrepancies to the account fields
     */
    public static List<Account> correctDiscrepancies(List<DvsDiscrepancy__c> discrepancies, List<Account> accounts) {
        SavePoint sp = Database.setSavepoint();

        try {
            Map<Id, DvsDiscrepancy__c> discrepanciesByAccountId = new Map<Id, DvsDiscrepancy__c>();
            for (DvsDiscrepancy__c discrepancy : discrepancies) {
                if (discrepancy.DvsId__c != null) {
                    discrepanciesByAccountId.put(discrepancy.Account__c, discrepancy);
                }
            }

            if (discrepanciesByAccountId.size() > 0) {
                List<DvsAccountInfo__c> oldInfo = new List<DvsAccountInfo__c>();

                for (Account account : accounts) {
                    oldInfo.add(createOldData(account));

                    DvsDiscrepancy__c discrepancy = discrepanciesByAccountId.get(account.Id);
                    account.Name = discrepancy.DvsName__c;
                    account.BillingStreet = discrepancy.DvsStreet__c;
                    account.BillingPostalCode = discrepancy.DvsPostalCode__c;
                    account.BillingCity = discrepancy.DvsCity__c;
                    account.VAT_Number__c = discrepancy.DvsId__c;
                    account.VAT_Number_2__c = discrepancy.DvsId2__c;
                    account.SynchronizedWithDvs__c = true;
                    account.DvsLongError__c = '';
                    account.DvsError__c = '';
                    account.DvsHasError__c = false;

                    account.DVSAcceptedBy__c = UserInfo.getUserId();
                    account.DVSAcceptedDate__c = Datetime.now();
                    account.DVSAction__c = 'ACCEPTED';
                }

                insert oldInfo;
            }
        } catch (Exception ex) {
            Database.rollback(sp);
        }

        return accounts;
    }

    private static DvsAccountInfo__c createOldData(Account acc){
        DvsAccountInfo__c result = new DvsAccountInfo__c();
        result.Account__c = acc.Id;
        result.PreviousCity__c = acc.BillingCity;
        result.PreviousId1__c = acc.VAT_Number__c;
        result.PreviousId2__c = acc.VAT_Number_2__c;
        result.PreviousName__c = acc.Name;
        result.PreviousPostalCode__c = acc.BillingPostalCode;
        result.PreviousStreet__c = acc.BillingStreet;
        result.ProcessedTime__c = Datetime.now();

        return result;
    }

    @testVisible public static String testFiller() {
        String s = 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        return s;
    }
}