force-app/main/default/objects/Account/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Información sobre si al cuenta se encuentra bloqueada</description>
    <inlineHelpText>Information on whether the account is locked</inlineHelpText>
    <label>Is Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAP_Account_Lock__e/SAP_Account_Lock__e.object-meta.xml
<CustomObject>
    <description>Platform event to lock or unlock accounts when they are lcoked or unlocked in SAP</description>
    <label>SAP Account Lock</label>
    <pluralLabel>SAP Account Locks</pluralLabel>
</CustomObject>

force-app/main/default/objects/SAP_Account_Lock__e/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Salesforce ID of the account to lock or unlock</description>
    <label>Account ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Account_Lock__e/fields/IsLocked__c.field-meta.xml
<CustomField>
    <fullName>IsLocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag specifying whether the account is locked.</description>
    <label>Is Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAP_Account_Lock__e/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <description>Customer ID in SAP</description>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PEVSAPAccountLockTriggerHandler.cls
/**
 * @author         Ramón Prades
 * @date           March 2025
 * @layer          Platform Events
 * @description    Manages the PE sent by SAP when a customer is locked or unlocked
*/
public class PEVSAPAccountLockTriggerHandler {
    
    public static void afterInsert(List<SAP_Account_Lock__e> events) {
        SystemLog log = new SystemLog('SAP-EVENTS');
        log.setTag('SAP_Account_Lock');
        log.setInputObject(events);
        log.addInfo('Processing ' + events.size() + ' events of type SAP Account Lock');
        Boolean hasErrors = false;

        Account[] accounts = new List<Account>();
        for (SAP_Account_Lock__e e : events) {
            try {
                log.addInfo('==> Account ' + e.AccountId__c + ' - ' + e.SAPId__c + ': ' + e.IsLocked__c);
                Account acc = new Account();
                acc.Id = e.AccountId__c;
                acc.Is_Locked__c = e.IsLocked__c;
                accounts.add(acc);
            } catch (Exception ex) {
                hasErrors = true;
                log.addError('Inner Exception: ' + ex);
                e.addError('Error processing event: ' + ex.getMessage());
            }
        }
        
        Database.SaveResult[] results = Database.update(accounts, false);        
        for (Database.SaveResult res : results) {
            if (!res.isSuccess()) {
                hasErrors = true;
                log.addError('Error updating ' + res.getId());
                for (Database.Error err : res.getErrors()) {
                    log.addError('Error: ' + err.getMessage());
                }
            }
        }

        if (!hasErrors) {
            log.setSummary(events.size() +' account(s) updated successfully');
        } else {
            log.setSummary(events.size() +' account(s) updated with errors');
        }
        log.saveLog(true);
    }
}