force-app/main/default/objects/Account/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Account</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Amount_custom__c.field-meta.xml
<CustomField>
    <fullName>Amount_custom__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount of the opportunity without currency</description>
    <inlineHelpText>Amount of the opportunity without currency</inlineHelpText>
    <label>Quantity of the opportunity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Opportunity</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reason_Lost__c.field-meta.xml
<CustomField>
    <fullName>Reason_Lost__c</fullName>
    <label>Reason Lost</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AUTOMATICCLOSURE</fullName>
                <label>Automatic closure</label>
            </value>
            <value>
                <fullName>Customer not Ready</fullName>
            </value>
            <value>
                <fullName>Duplicated Ecommerce Opportunity</fullName>
            </value>
            <value>
                <fullName>Lack of product availability</fullName>
            </value>
            <value>
                <fullName>Lack of product</fullName>
                <label>Lack of product range</label>
            </value>
            <value>
                <fullName>Late in the process</fullName>
            </value>
            <value>
                <fullName>No Decision / Non-Responsive</fullName>
            </value>
            <value>
                <fullName>Ordered through Trade Account</fullName>
            </value>
            <value>
                <fullName>Ordered Via Online</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchOpportunityAutoCloseTest.cls
@isTest
public class BatchOpportunityAutoCloseTest {
    @TestSetup
    static void makeData(){
        DataFactoryOpportunity.createRetailOpportunities(1, 2);
    }

    @isTest
    static void testBatch() {
        Opportunity opp = [SELECT Id, Reason_Lost__c, Amount_custom__c, StageName,Name,Account.Name,OwnerId,AccountId, Last_Activity_Date__c, CloseDate
                            FROM Opportunity LIMIT 1];
        
        opp.Last_Activity_Date__c = System.today().addYears(-2);
        opp.CloseDate = System.today().addDays(-6);
        update opp;

        Integer before = Limits.getEmailInvocations();
        test.startTest();
            BatchOpportunityAutoClose aux = new BatchOpportunityAutoClose();
            Database.executebatch(aux);
        test.stopTest();

        Assert.isTrue(before == Limits.getEmailInvocations(), 'Emails no enviados');
    }

    @isTest
    static void testBatchTest() {
        Opportunity opp = [SELECT Id, Reason_Lost__c, Amount_custom__c, StageName,Name,Account.Name,OwnerId,AccountId, Last_Activity_Date__c, CloseDate
                            FROM Opportunity LIMIT 1];
        
        opp.Last_Activity_Date__c = System.today().addYears(-2);
        opp.CloseDate = System.today().addDays(-6);
        update opp;

        Integer before = Limits.getEmailInvocations();
        test.startTest();
            BatchOpportunityAutoClose aux = new BatchOpportunityAutoClose();
            aux.setTest();
            Database.executebatch(aux);
        test.stopTest();

        Assert.isTrue(before == Limits.getEmailInvocations(), 'Emails no enviados');
    }

    @isTest
    static void fillerTest() {
        BatchOpportunityAutoClose aux = new BatchOpportunityAutoClose();
        aux.testFiller();
        Assert.isTrue(1 == 1);
    }
    
}