force-app/main/default/objects/Account/fields/LastOrderDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastOrderDateTime__c</fullName>
    <description>We set here the time of the last SAP Order related created</description>
    <label>Last Order DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/OppCustomProject__c.object-meta.xml
<CustomObject>
    <description>Object to store opportunity&apos;s additional information on US custom project (Krion and similar products transformed by a fabricator).</description>
    <label>Opportunity Custom Project</label>
    <nameField>
        <label>Custom Project Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Custom Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppCustomProject__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Related opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Project Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUALIFICATION</fullName>
                <default>true</default>
                <label>QUALIFICATION</label>
            </value>
            <value>
                <fullName>PR-RECEIVED</fullName>
            </value>
            <value>
                <fullName>PROPOSAL</fullName>
            </value>
            <value>
                <fullName>DEPOSIT</fullName>
            </value>
            <value>
                <fullName>TEMPLATE-APP</fullName>
            </value>
            <value>
                <fullName>DRAWING-SIGNED</fullName>
            </value>
            <value>
                <fullName>CHANGE-ORDER</fullName>
            </value>
            <value>
                <fullName>PAYMENT-RECEIVED</fullName>
            </value>
            <value>
                <fullName>IN-PRODUCTION</fullName>
            </value>
            <value>
                <fullName>INSTALLATION</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>LOST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppFacade__c/OppFacade__c.object-meta.xml
<CustomObject>
    <description>Additional information for facade opportunities. Originally designed for the US but might be extended in the future.</description>
    <label>Opportunity Facade</label>
    <nameField>
        <label>Facade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Facades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppFacade__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Facades</relationshipLabel>
    <relationshipName>Opportunity_Facades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppFacade__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Sales Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRODUCT-REVIEW</fullName>
                <default>true</default>
                <label>1-PRODUCT REVIEW</label>
            </value>
            <value>
                <fullName>TECHNICAL-ASSISTANCE</fullName>
                <label>2-TECHNICAL ASSISTANCE</label>
            </value>
            <value>
                <fullName>DESIGN-ASSIST</fullName>
                <label>3-DESIGN ASSIST / COST ESTIMATE</label>
            </value>
            <value>
                <fullName>WON (WORK IN PROGRESS)</fullName>
                <label>4-WON (WORK IN PROGRESS)</label>
            </value>
            <value>
                <fullName>CLOSED</fullName>
                <label>5-CLOSED (FULLY INVOICED)</label>
            </value>
            <value>
                <fullName>LOST</fullName>
                <label>6-LOST</label>
            </value>
            <value>
                <fullName>CLOSED-WON</fullName>
                <isActive>false</isActive>
                <label>CLOSED-WON</label>
            </value>
            <value>
                <fullName>INSTALLATION</fullName>
                <isActive>false</isActive>
                <label>INSTALLATION</label>
            </value>
            <value>
                <fullName>MATERIAL-QUOTE</fullName>
                <isActive>false</isActive>
                <label>MATERIAL QUOTE</label>
            </value>
            <value>
                <fullName>SOLD/SHIPPING</fullName>
                <isActive>false</isActive>
                <label>SOLD/SHIPPING</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppKitchen__c/OppKitchen__c.object-meta.xml
<CustomObject>
    <description>Additional information for kitchen opportunities. Originally designed for the US, but can (and will) be extended.</description>
    <label>Opportunity Kitchen</label>
    <nameField>
        <label>Kitchen Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Kitchens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppKitchen__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CurrencyCodes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppKitchen__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Kitchens</relationshipLabel>
    <relationshipName>OpportunityKitchens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppKitchen__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUALIFICATION</fullName>
                <default>true</default>
                <label>QUALIFICATION</label>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>RETAINER-RECEIVED</fullName>
            </value>
            <value>
                <fullName>DESIGN-PROPOSAL</fullName>
            </value>
            <value>
                <fullName>DEPOSIT-RECEIVED</fullName>
            </value>
            <value>
                <fullName>SHOP DRAWINGS</fullName>
            </value>
            <value>
                <fullName>DRAWINGS-SIGNED</fullName>
            </value>
            <value>
                <fullName>IN-PRODUCTION</fullName>
            </value>
            <value>
                <fullName>IN-TRANSIT</fullName>
            </value>
            <value>
                <fullName>ARRIVED</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>INSTALLATION</fullName>
            </value>
            <value>
                <fullName>PUNCH-LIST</fullName>
            </value>
            <value>
                <fullName>LOST</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/countryCode__c.field-meta.xml
<CustomField>
    <fullName>countryCode__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <defaultValue>&apos;GBP&apos;</defaultValue>
    <description>IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;203&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;206&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;207&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;208&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;210&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;218&quot;),&quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;602&quot;), &quot;USD&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;603&quot;), &quot;USD&quot;,  IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;604&quot;), &quot;USD&quot;, IF(ISPICKVAL($User.Default_Sales_Organization__c,&quot;605&quot;), &quot;USD&quot;, IF(ISPICKVAL($User.Default_Sales_Organization__c,&quot;606&quot;), &quot;USD&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;608&quot;), &quot;USD&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;615&quot;), &quot;USD&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;650&quot;), &quot;CAD&quot;, &quot;GBP&quot;))))))</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>ILS</fullName>
            </value>
            <value>
                <fullName>CLP</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>DOP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InfoType__c.field-meta.xml
<CustomField>
    <fullName>InfoType__c</fullName>
    <description>Type of record of the additional info related to the opportunity (if any). Can be &apos;CUSTOM PROJECT&apos;, &apos;FACADE&apos; or &apos;KITCHEN&apos; (or blank)</description>
    <label>Opportunity Info Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PROJECT</fullName>
                <label>Custom Project</label>
            </value>
            <value>
                <fullName>KITCHEN</fullName>
                <label>Kitchen</label>
            </value>
            <value>
                <fullName>FACADE</fullName>
                <label>Facade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LastOrderDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastOrderDateTime__c</fullName>
    <description>We set here the time of the last Order related created</description>
    <label>Last Order DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/numberOfProducts__c.field-meta.xml
<CustomField>
    <fullName>numberOfProducts__c</fullName>
    <description>Count of Opportunity Line Items</description>
    <label># of Products</label>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reason_Lost__c.field-meta.xml
<CustomField>
    <fullName>Reason_Lost__c</fullName>
    <label>Reason Lost</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AUTOMATICCLOSURE</fullName>
                <label>Automatic closure</label>
            </value>
            <value>
                <fullName>Customer not Ready</fullName>
            </value>
            <value>
                <fullName>Duplicated Ecommerce Opportunity</fullName>
            </value>
            <value>
                <fullName>Lack of product availability</fullName>
            </value>
            <value>
                <fullName>Lack of product</fullName>
                <label>Lack of product range</label>
            </value>
            <value>
                <fullName>Late in the process</fullName>
            </value>
            <value>
                <fullName>No Decision / Non-Responsive</fullName>
            </value>
            <value>
                <fullName>Ordered through Trade Account</fullName>
            </value>
            <value>
                <fullName>Ordered Via Online</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Project_trade.recordType-meta.xml
<RecordType>
    <fullName>Project_trade</fullName>
    <active>true</active>
    <businessProcess>Sales process trade</businessProcess>
    <label>Project trade</label>
</RecordType>

force-app/main/default/objects/OpportunityContactRole/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>CASESAFEID(Contact.AccountId)</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CurrencyCodes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>DKK</fullName>
    </customValue>
    <customValue>
        <fullName>ZAR</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>SEK</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <masterLabel>Currency Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunitiesDomain.cls
/**
* @author 		Ramón Prades
* @date 		July 2022
* @group 		Opportunities   
* @description 	First version of a domain class to start adding content here instead of to the trigger
*/
public without sharing class OpportunitiesDomain extends zflib_DomainClass {

    public static final String INFO_LOST_STAGE = 'LOST';
    public static final String PROJECT_DEPOSIT_STAGE = 'DEPOSIT';

    public OpportunitiesDomain(List<Opportunity> opportunities) {
        super(opportunities);
    }

    /**
     * Applies automatic actions depending on the opportunity stage
     */
    public void runStageActions(Map<Id, Opportunity> existingRecords) {
        this.ExistingRecords = existingRecords;
        this.setInfoObjectStage();
    } 

    /**
     * Same with no pre-existing records
     */
    public void runStageActions() {
        this.runStageActions(new Map<Id, Opportunity>());
    }

    /*********************************************************/
    /******************** PRIVATE METHODS ********************/
    /*********************************************************/

    /*
     * Change the info object stage when opportunity stage changes
     */
    private void setInfoObjectStage() {
        List<String> wonStages = OpportunityCOmmons.getClosedWonStages();
        List<String> lostStages = OpportunityCOmmons.getClosedLostStages();

        List<SObject> infoObjects = new List<SObject>();
        for (Opportunity opp: (List<Opportunity>) this.Records) {
            Boolean selected = false;            
            Opportunity oldOpp = (Opportunity) this.ExistingRecords.get(opp.Id);
            selected = (oldOpp == null || oldOpp.StageName != opp.stageName);
            selected = (selected && String.IsNotBlank(opp.infoType__c));
            if (!selected) {
                continue;
            }
            if (wonStages.contains(opp.StageName) && opp.infoType__c == OpportunitiesInfoCommons.PROJECT_TYPE) {
                Sobject infoObject = this.getInfoObject(opp.Id, opp.InfoType__c);
                ((OppCustomProject__c) infoObject).Stage__c = PROJECT_DEPOSIT_STAGE;
                infoObjects.add(infoObject);                
            } else if (lostStages.contains(opp.StageName)) {

                SObject infoObject2 = this.getInfoObject(opp.Id, opp.InfoType__c);
                infoObjects.add(infoObject2);
            }
        }
        update infoObjects;
    }

    private SObject getInfoObject(Id oppId, String objectType) {
        SObject infoObject = null;
        try {
            if (objectType == OpportunitiesInfoCommons.PROJECT_TYPE) {
                infoObject = [select Id, Opportunity__c from OppCustomProject__c where Opportunity__c = :oppId limit 1];
                ((OppCustomProject__c)infoObject).Stage__c = INFO_LOST_STAGE;
            } else if (objectType == OpportunitiesInfoCommons.FACADE_TYPE) {
                infoObject = [select Id, Opportunity__c from OppFacade__c where Opportunity__c = :oppId limit 1];
                ((Oppfacade__c)infoObject).Stage__c = INFO_LOST_STAGE;

            } else if (objectType == OpportunitiesInfoCommons.KITCHEN_TYPE) {             
                infoObject = [select Id, Opportunity__c from OppKitchen__c where Opportunity__c = :oppId limit 1];
                ((OppKitchen__c)infoObject).Stage__c = INFO_LOST_STAGE;
            }
        } catch (Exception ex) {}
        return infoObject;
    }

    /**
     * @description Set the default currency, depending on the country of the Opportunity
     */
    public static void setOpportunityCurrency(List<Opportunity> newOpportunities) {
        for (Opportunity opp : newOpportunities) {
            switch on opp.CountryCode__c {
                when 'US' {
                    opp.Currency__c = 'USD';
                }
                when 'CA' {
                    opp.Currency__c = 'CAD';
                }
                when 'GB' {
                    opp.Currency__c = 'GBP';
                }
                when 'CH' {
                    opp.Currency__c = 'CHF';
                }
                when 'SE' {
                    opp.Currency__c = 'SEK';
                }
                when 'IL' {
                    opp.Currency__c = 'ILS';
                }
                when 'AU' {
                    opp.Currency__c = 'AUD';
                }
                when 'CL' {
                    opp.Currency__c = 'CLP';
                }
                when 'DK' {
                    opp.Currency__c = 'DKK';
                }
                when 'RD' {
                    opp.Currency__c = 'DOP';
                }
                when else {
                    opp.Currency__c = 'EUR';
                }
            }
        }
    }

    /**
     * @description Changes the stage of the Opp depending on the values on some fields
     * TODO Cambiarlo a formato FFLIB Cuando el Domain se esté usando para el Trigger, ya que debería de usar "this.Records" 
     */
    public static void setOpportunityStage(List<Opportunity> newOpportunities) {
        setOpportunityStage(newOpportunities, new Map<Id, Opportunity>());
    }

    public static void setOpportunityStage(List<Opportunity> newOpportunities, Map<Id, Opportunity> oldOpportunities) {
        Id RecordTypeTradeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Project_trade').getRecordTypeId();
        
        for (Opportunity opp : newOpportunities) {
            
            // LOST : when a reason lost has been set
            if (String.isNotBlank(opp.Reason_Lost__c) && opp.LastOrderDateTime__c == null) {
                opp.StageName = INFO_LOST_STAGE;
            }
            /* Balma al final no quiere ponerlo hasta que los productos de SAP puedan pasar a SF
             if there is one or more product items, changes the stage to SPECIFICATION, if on QUALIFICATION*/
            if (opp.RecordTypeId == RecordTypeTradeId && opp.numberOfProducts__c >= 1 && opp.stageName.toUpperCase() == 'QUALIFICATION') {
                opp.stageName = 'ESPECIFICACIÓN';
            }
            // If all products are removed and the stage is SPECIFICATION, it changes to QUALIFICATION
            if (opp.RecordTypeId == RecordTypeTradeId &&
                opp.stageName.toUpperCase() == 'ESPECIFICACIÓN' &&
                oldOpportunities.size() > 0 &&
                opp.numberOfProducts__c == 0 &&
                oldOpportunities.get(opp.Id).numberOfProducts__c != opp.numberOfProducts__c) {
                opp.stageName = 'QUALIFICATION';
            }
        }
    }

    /**
     * @description Set the default currency, depending on the country of the Opportunity
     */
    public static void setOpportunitySalesProgram(Set<Id> oppids) {
        try {
            Map<String, Opportunity> mapOpps= new Map<String, Opportunity>();
            Set<String> oppIdsTandem = new Set<String>();

            List<Opportunity> opps = new OpportunitiesSelector().selectById(oppids);

            List<OpportunityContactRole> allContactRolesFullData = [SELECT id, opportunityId, Account__c, Contact.Account.Id, Opportunity.Account.Id, Contact.Account.Account_Classification__c, Contact.Account.TypeCustomer__c FROM OpportunityContactRole WHERE opportunityId IN : oppids];

            System.debug('ENTER OPP SALES PROGRAM');
            for (OpportunityContactRole contactRole : allContactRolesFullData) {
                if (contactRole.Contact.Account.Id != contactRole.Opportunity.Account.Id ) {
                    // TANDEM PROGRAM - Si el cliente de un contact tiene como TypeCustomer TANDEM, la oportunidad es Tándem
                    System.debug('Type Customer: ' + contactRole.Contact.Account.TypeCustomer__c);
                    if (contactRole.Contact.Account.TypeCustomer__c == 'TANDEM') {
                        oppIdsTandem.add(contactRole.opportunityId);
                    }
                }
            }

            for (Opportunity opp : opps) {
                opp.SalesProgram__c = null;
                 // TANDEM PROGRAM
                if (oppIdsTandem.contains(opp.Id)) {
                    opp.SalesProgram__c = 'TANDEM';
                }
                mapOpps.put(opp.Id, opp);
            }

            update mapOpps.values();
        } catch (Exception ex) {
            System.debug(ex.getMessage());
        }
    }
}