force-app/main/default/objects/Account/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Account</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Follow__c/Follow__c.object-meta.xml
<CustomObject>
    <description>Objeto que registra la suscripción de un usuario con un Account, Opportunity, etc</description>
    <label>Follow</label>
    <nameField>
        <displayFormat>FW-{00000000}</displayFormat>
        <label>Follow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oportunidad a la que el usuario se ha suscrito</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Follows</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>RecordType para Follow de Account</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Follow__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <description>Recordtype para Follow de Opportunity</description>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Moodboard__c/Moodboard__c.object-meta.xml
<CustomObject>
    <description>Object created to have Moodboard Info</description>
    <label>Moodboard</label>
    <nameField>
        <label>Moodboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moodboards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Moodboard__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Moodboards</relationshipLabel>
    <relationshipName>Moodboards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Moodboard__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <description>Url to the moodboard website</description>
    <label>Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Opportunity</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/MoodboardsDomainTest.cls
@isTest
public class MoodboardsDomainTest {
    @testSetup
  static void setup() {
    TestUtils.enableTriggers();

    Account acc = Account_TestDataFactory.createBusinessAccount();
    Insert acc;

    Opportunity newOpp = Opportunity_TestDataFactory.createTrade(acc);
    Insert newOpp;

    Moodboard__c mood = new Moodboard__c(Opportunity__c = newOpp.id, Name = 'Test Moodboard');
    insert mood;

  }

  @IsTest
  static void urlMoodboard() {
    List<Moodboard__c> moodb = [SELECT Url__c, Opportunity__r.Owner.LanguageLocaleKey from Moodboard__c LIMIT 1];
    System.assert(moodb[0].Url__c == 'https://moodboard.porcelanosagrupo.com/#/templates/' + moodb[0].Opportunity__r.Owner.LanguageLocaleKey + '/SFORCE_' + moodb[0].Id, 'No se ha seteado la Url del moodboard');
  }

  @IsTest
  static void activityDate() {
    Test.startTest();
    Account acc = [SELECT Id FROM Account LIMIT 1];
    Opportunity newOpp = Opportunity_TestDataFactory.createTrade(acc);
    insert newOpp;
    Moodboard__c aux = new Moodboard__c(Opportunity__c = newOpp.id, Name = 'Test Moodboard');
    acc.Last_Activity_Date__c = System.now().addDays(-8);
    update acc;
    insert aux;
    Test.stopTest();
    acc = [SELECT Id, Last_Activity_Date__c FROM Account WHERE Id =: acc.Id];
    System.assert(acc.Last_Activity_Date__c != null, 'No se ha seteado el Last Activity');
    System.assert(acc.Last_Activity_Date__c.date() == System.now().date(), 'No se ha actualizado el Last Activity');
  }
}