force-app/main/default/objects/Account/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Account</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Distribution_Channel__c/Distribution_Channel__c.object-meta.xml
<CustomObject>
    <label>Distribution Channel</label>
    <nameField>
        <label>Distribution Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distribution Channel</label>
    <referenceTo>Distribution_Channel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Opportunity</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Default Sales Org of the User who created the Opportunity</description>
    <label>Sales Org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegionalSettings__mdt/RegionalSettings__mdt.object-meta.xml
<CustomObject>
    <description>Region configuration</description>
    <label>Regional Settings</label>
    <pluralLabel>Regional Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/RegionalSettings__mdt/fields/reassignOwner__c.field-meta.xml
<CustomField>
    <fullName>reassignOwner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>indica si se debe reasignar el owner en la ampliacion de Accounts si es generico</description>
    <label>reassign owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegionalSettings__mdt/fields/SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganization__c</fullName>
    <description>Sales organization code</description>
    <label>Sales Organization</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/SALES_OFFICE__c.object-meta.xml
<CustomObject>
    <description>Entidad custom que contiene el maestro de relaciones para transformar el código de la oficina de ventas por el nombre.</description>
    <label>Sales Office</label>
    <nameField>
        <label>Nombre de SALES_OFFICE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Relationship__c/Sales_Relationship__c.object-meta.xml
<CustomObject>
    <label>SAP Accounting Info</label>
    <nameField>
        <label>Nombre Organizaciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Accounting Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Relationship__c/fields/Account_Org__c.field-meta.xml
<CustomField>
    <fullName>Account_Org__c</fullName>
    <label>Account Org</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Organizaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>Distribution Channel</description>
    <inlineHelpText>Distribution Channel</inlineHelpText>
    <label>Distribution Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Tienda</description>
    <inlineHelpText>Sales Office</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Default_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Organization__c</fullName>
    <description>La organización de ventas por defecto para el comercial</description>
    <inlineHelpText>The default sales organization for sales and distribution</inlineHelpText>
    <label>Default Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Distribution_channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel__c</fullName>
    <label>Distribution channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Sales Office from Sales Org default</description>
    <inlineHelpText>Sales Office from Sales Org default</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Default_Sales_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesRelationshipTriggerHandlerTest.cls
@isTest
public class SalesRelationshipTriggerHandlerTest {
    // Crea un usuario de prueba para darle permisos.
    @testSetup static void setup() {
        TestUtils.enableTriggers();
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        Map<String, Object> fieldsToAdd = new Map<String, Object> {'ProfileId' => p.Id, 'LocaleSidKey' => 'en_GB', 
            'Sales_Org__c' => OrganizationCommons.ORG_AZURCERAMIQUE + ';' + OrganizationCommons.ORG_PIDF, 'Default_Sales_Organization__c' => OrganizationCommons.ORG_AZURCERAMIQUE, 'Distribution_Channel__c' => '10;15;30;50;60;65;70', 'Sales_office__c' => '3015'};
		User testUser = User_TestDataFactory.createUsers(1, fieldsToAdd)[0];
       	Insert testUser;
        
        List<Account> accList = new List<Account>();
        accList.add(Account_TestDataFactory.createBusinessAccount());
        accList.add(Account_TestDataFactory.createRetailer());
        accList.add(Account_TestDataFactory.createRetailer());
        
        accList[1].Name = 'Acc Many Sales Rel';
        accList[2].Name = 'Acc One Sales Rel';
        
        Account_TestDataFactory.insertAccounts(accList);
        
    }
    
    @isTest public static void insertOpportunity() {
        // Busca el usuario recien creado
        User u = [SELECT Id FROM User WHERE UserName LIKE '%@testOrg.com' LIMIT 1];
        
        // Corremos el caso de prueba como el usuario recien creado.
        
        // Test 1: 
        // Cuando se inserta una "Sales Relationship" con un Account de record Type Third party Retailer / Reseller
        // Se debera activar el trigger y este inserta una Oportunity y un Opportunity Actor
        // Y los envia a sap
        System.debug('Test 1');
        
        Account accManySalesRel = [SELECT Id FROM Account WHERE Name = 'Acc Many Sales Rel'];
        Account accOneSalesRel = [SELECT Id FROM Account WHERE Name = 'Acc One Sales Rel'];
        System.debug('accManySalesRel: ' + accManySalesRel.Id);
        
        List<Sales_RelationShip__c> salesRelList = new List<Sales_RelationShip__c>();
        salesRelList.add(Sales_RelationShip_TestDataFactory.createSalesRelationship(accOneSalesRel));
        salesRelList.add(Sales_RelationShip_TestDataFactory.createSalesRelationship(accManySalesRel));
        salesRelList.add(Sales_RelationShip_TestDataFactory.createSalesRelWithPicklist(accManySalesRel, OrganizationCommons.ORG_EUROCERAMIQUE, '3035', '10'));
        System.debug('salesRelList: ' + salesRelList);
        
        Database.SaveResult[] result_test_1;
        
        Test.setMock(HttpCalloutMock.class, new OpportunityMockHttpResponseGenerator());
        Test.startTest();
        System.runAs(u) {
            result_test_1 = Database.insert(salesRelList, false);
        }
        Test.stopTest();
        
        for(Database.SaveResult sv : result_test_1){
            System.assert( sv.isSuccess() );
        }
        
        // Verificando que se haya creado solamente una Opportunity para ambas cuentas
        Opportunity opp2 = [SELECT Id, Name, CloseDate, StageName, RecordTypeId FROM Opportunity WHERE accountId =: accManySalesRel.Id];
        
        // Test 3: Se crea otra sales rol con la misma cuenta que test 1 pero con diferente sales org y dist channel
        // Luego verifia que no se inserte otra opportunity comparando que dos queries sean iguales.
        Sales_RelationShip__c salesRel3 = Sales_RelationShip_TestDataFactory.createSalesRelWithPicklist(accManySalesRel, OrganizationCommons.ORG_PIDF, '3035', '10');
        System.debug('salesRel: ' + salesRel3);
        
        Database.SaveResult result_test_3 = Database.insert(salesRel3, false);
        System.assert( result_test_3.isSuccess() );
        
        Opportunity oppAfter = [SELECT Id, Name, CloseDate, StageName, RecordTypeId FROM Opportunity WHERE accountId =: salesRel3.Account_Org__c];
        System.assertEquals(opp2, oppAfter);
        
        // Test 2: 
        // Account con record Type Trade.
        // Se debe dejar pasar sin crear objetos relacionados.
        Account acc2 = [SELECT Id FROM Account WHERE NAME = 'TestAcctBusinessAccount1'];
        System.debug('acc2: ' + acc2);
        
        Sales_RelationShip__c salesRel2 = Sales_RelationShip_TestDataFactory.createSalesRelationship(acc2);
        System.debug('salesRel2: ' + salesRel2);
        
        Database.SaveResult result_test_2 = Database.insert(salesRel2, false);
        System.assert( result_test_2.isSuccess() );
        
        // Verificando que no se hayan insertado Opportunities relacionadas al Account de la Sales Relationship
        String error_test_2 = '';
        Opportunity newOpp = new Opportunity();
        try {
            newOpp = [SELECT Id FROM Opportunity WHERE AccountId =: salesRel2.Account_Org__c];
        } catch (QueryException ex){
            error_test_2 = ex.getMessage();
        }
        System.assert(error_test_2.contains('List has no rows for assignment to SObject') );
    }

    @isTest static void updateActivity(){
        // Busca el usuario recien creado
        User testUser = [SELECT Name, Id FROM User WHERE UserName LIKE '%@testOrg.com'];
        
        System.runAs(testUser) {
            Account acc = [SELECT Id, Last_Activity_Date__c FROM Account WHERE Name = 'TestAcctBusinessAccount1'];
            Test.startTest();
            acc.Last_Activity_Date__c = System.now().addDays(-8);
            update acc;
            //Check the beforeInsert Trigger
            Sales_Relationship__c newSalesRel = Sales_RelationShip_TestDataFactory.createSalesRelationship(acc);
            Insert newSalesRel;
            Test.stopTest();
            
            acc = [SELECT Id, Last_Activity_Date__c FROM Account WHERE Id =: acc.Id];
            // Check the update of the Last_Activity_Date on Account
            System.assert(acc.Last_Activity_Date__c.date() == System.now().date());
        }
    }

    @isTest static void updateOwnerTest() {
        // Busca el usuario recien creado
        User user = DatafactoryUser.createUKAdmin();

        RegionalSettings__mdt soutMetadata = [SELECT Id, MasterLabel, SalesOrganization__c, ReassignOwner__c 
            FROM RegionalSettings__mdt 
            WHERE SalesOrganization__c = :OrganizationCommons.ORG_FLORIDA LIMIT 1];
        soutMetadata.ReassignOwner__c = true;

        Account acc = [SELECT Id,OwnerId,Owner.Name FROM Account WHERE Name = 'TestAcctBusinessAccount1'];
        acc.OwnerId = user.Id;
        Update acc;

        Test.startTest();
            Sales_RelationShip__c newSalesRel = Sales_RelationShip_TestDataFactory.createSalesRelationship(acc);
            newSalesRel.Sales_Office__c = '4102'; // Sales Office assigned to the user
            newSalesRel.Sales_Org__c = OrganizationCommons.ORG_FLORIDA; // Sales Org assigned to the user
            newSalesRel.Distribution_Channel__c = '60'; // Distribution Channel assigned to the user
            Insert newSalesRel;
        Test.stopTest();
        
        Account accPost = [SELECT Id,OwnerId,Owner.Name FROM Account WHERE Id =: acc.Id];
        System.debug(acc.OwnerId + ' != ' + accPost.OwnerId);
        Assert.areNotEqual(acc.OwnerId, accPost.OwnerId, 'Owner should have been reassigned');
    }
}