force-app/main/default/objects/Account/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Account</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Displays_Marketing_Material__c/Displays_Marketing_Material__c.object-meta.xml
<CustomObject>
    <label>Displays &amp; Marketing Material</label>
    <nameField>
        <label>Displays &amp; Marketing Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Displays &amp; Marketing Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Displays_Marketing_Material__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Displays &amp; Marketing Material</relationshipLabel>
    <relationshipName>Displays_Marketing_Material</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Displays_Marketing_Material__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Settings</fullName>
            </value>
            <value>
                <fullName>Dakkar Panel Stand</fullName>
            </value>
            <value>
                <fullName>Highker Stand</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Krion countertop</fullName>
            </value>
            <value>
                <fullName>Krion tower</fullName>
            </value>
            <value>
                <fullName>Starwood Zone</fullName>
            </value>
            <value>
                <fullName>Xlight tower</fullName>
            </value>
            <value>
                <fullName>Xtone Countertop</fullName>
            </value>
            <value>
                <fullName>Xtone tower</fullName>
            </value>
            <value>
                <fullName>Cuna parker</fullName>
            </value>
            <value>
                <fullName>Table Display Rack XTONE</fullName>
            </value>
            <value>
                <fullName>Boxtone</fullName>
                <label>BOXTONE</label>
            </value>
            <value>
                <fullName>Exp. Tower Xtone 30x60</fullName>
            </value>
            <value>
                <fullName>Ex. Tower Xtone 25x28</fullName>
            </value>
            <value>
                <fullName>Binder</fullName>
            </value>
            <value>
                <fullName>Table Display Rack Altissima</fullName>
            </value>
            <value>
                <fullName>Countertop Altissima</fullName>
            </value>
            <value>
                <fullName>Krion Box</fullName>
            </value>
            <value>
                <fullName>Xtone Setting</fullName>
            </value>
            <value>
                <fullName>Altissima Setting</fullName>
            </value>
            <value>
                <fullName>Xtone Pantonier</fullName>
            </value>
            <value>
                <fullName>Xtone Catalogue</fullName>
            </value>
            <value>
                <fullName>Sample classifier Xtone 10x20</fullName>
            </value>
            <value>
                <fullName>Xtone Packtool</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/InstallationRequest__c.object-meta.xml
<CustomObject>
    <description>Class to store and follow the installation request of our products. This is a service certain showrooms offer through a list of authorised installers.</description>
    <label>Installation Request</label>
    <nameField>
        <label>Installation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationRequest__c/fields/bathrooms__c.field-meta.xml
<CustomField>
    <fullName>bathrooms__c</fullName>
    <description>Number of bathrooms included in the installation</description>
    <label>#Bathrooms</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/InstallerAccount__c.field-meta.xml
<CustomField>
    <fullName>InstallerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installation Requests</relationshipLabel>
    <relationshipName>Installation_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InstallationRequest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Opportunity this installation is for</description>
    <inlineHelpText>Please enter the opportunity this installation is for</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Installation Requests</relationshipLabel>
    <relationshipName>Installation_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Moodboard__c/Moodboard__c.object-meta.xml
<CustomObject>
    <description>Object created to have Moodboard Info</description>
    <label>Moodboard</label>
    <nameField>
        <label>Moodboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moodboards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Moodboard__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Moodboards</relationshipLabel>
    <relationshipName>Moodboards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No contact</fullName>
                <default>true</default>
                <label>No contact</label>
            </value>
            <value>
                <fullName>Scheduled call</fullName>
            </value>
            <value>
                <fullName>Email sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <description>Date of the newest last created/modification date of any related object to an Opportunity</description>
    <label>Last Activity Date (LAD)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OpportunityContactRole/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>CASESAFEID(Contact.AccountId)</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ActivityDateServiceTest.cls
@IsTest
public class ActivityDateServiceTest {
    @TestSetup
    static void makeData(){
        TestUtils.enableTriggers();
        TriggerFlags.tflags.Opportunity_Contact_Role__c = true;
        TriggerFlags.tflags.Contact__c = true;
        List<Account> accs = DataFactoryAccount.createAccounts(5);
        List<Opportunity> opps = DataFactoryOpportunity.createRetailOpportunities(accs, 2);
        DataFactoryContact.createContacts(accs[0].Id, 2);
    }

    @isTest
    public static void testAccounts() {
        List<Account> accsList = [SELECT Id, Last_Activity_Date__c FROM Account];
        
        Test.startTest();

        Displays_Marketing_Material__c display = new Displays_Marketing_Material__c(Account__c = accsList[0].Id, Type__c = 'Settings');
        insert display;
        AccountTeamMember teamMember = new AccountTeamMember(AccountId = accsList[1].Id, UserId = UserInfo.getUserId());
        insert teamMember;
        Task newTask = new Task(TaskSubType = 'Email', WhatId = accsList[0].Id, Subject = 'Test');
        insert newTask;
        
        insert Sales_RelationShip_TestDataFactory.createSalesRelationship(accsList[0]);
        
        Test.stopTest();

        Assert.isTrue(accsList[0].Last_Activity_date__c != null, 'No tiene Last Activity Date');

    }

    @isTest
    public static void testOpportunities() {
        List<Opportunity> oppsList = [SELECT Id, AccountId, Last_Activity_Date__c FROM Opportunity];
        Contact ct = [SELECT Id, AccountId FROM Contact LIMIT 1];
        
        Test.startTest();
        
        Moodboard__c aux = new Moodboard__c(Opportunity__c = oppsList[0].id, Name = 'Test Moodboard');
        insert aux;

        OpportunityTeamMember teamMember = new OpportunityTeamMember(OpportunityId = oppsList[0].Id, UserId = UserInfo.getUserId());
        insert teamMember;
        
        OpportunityContactRole oppActor1 = new OpportunityContactRole(OpportunityId = oppsList[0].Id, ContactId = ct.Id);
        insert oppActor1;
        
        Event ev = new Event(WhatId = ct.AccountId, StartDateTime = System.now(), EndDateTime = System.now().addDays(8), WhoId = ct.Id, Subject = 'Test Event', Description = 'Desc Test');
        insert ev;
        
        ActivityMetric actMetric = new ActivityMetric(BaseId = ct.AccountId, LastEmailDateTime = System.now());
        insert actMetric;
        
        InstallationRequest__c request = new InstallationRequest__c(
													Name= 'Test Retail Opportunity #', 
                                            		bathrooms__c = 1, 
                                                    Description__c = 'Description of the test intallation request',
                                                   	InstallerAccount__c = oppsList[0].AccountId,
                                                    Opportunity__c = oppsList[0].Id);
        Test.stopTest();

        Assert.isTrue(oppsList[0].Last_Activity_date__c != null, 'No tiene Last Activity Date');

    }
    
    @isTest
    static void fillerTest() {
        ActivityDateService aux = new ActivityDateService();
        aux.testFiller();
        Assert.isTrue(1 == 1);
    }
}