force-app/main/default/objects/Account/fields/Professional__c.field-meta.xml
<CustomField>
    <fullName>Professional__c</fullName>
    <label>Professional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Profesional</fullName>
            </value>
            <value>
                <fullName>No Profesional</fullName>
                <default>true</default>
                <label>No Profesional</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Close_Mode__c.field-meta.xml
<CustomField>
    <fullName>Close_Mode__c</fullName>
    <label>Close Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In shop date</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
            <value>
                <fullName>More samples</fullName>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>Not contacted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Project_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Project_Date__c</fullName>
    <label>End Project Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Project_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Project_Date__c</fullName>
    <label>Start Project Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Argumentario_Controller.cls
public class Argumentario_Controller {
    
    @AuraEnabled
    public static Opportunity getOpportunity(String recordId){
        
        return [SELECT Account.Name, Account.PersonEmail, Account.ShippingAddress, Order__c, Close_Mode__c, StageName
                FROM Opportunity
                WHERE Id = :recordId];
        
    }
    
    @AuraEnabled
    public static void saveOpportunity(String recordId, String jsonObject, String jsonAccount){

        Opportunity opp = [SELECT Account.Name, Account.PersonEmail, Order__c, AccountId
                		   FROM Opportunity
                		   WHERE Id = :recordId];
        Account acc = [SELECT Professional__c FROM Account WHERE ID =: opp.AccountId];
        
        Map<String, Object> request = (Map<String, Object>) JSON.deserializeUntyped(jsonObject);
        Map<String, Object> requestAccount = (Map<String, Object>) JSON.deserializeUntyped(jsonAccount);
        
        for(String key: request.keySet()){
            system.debug('Opportunity field: '+ key +' - ' + request.get(key));
            switch on key{
                when 'Start_Project_Date__c', 'End_Project_Date__c' {
                    Date d = Date.valueOf((string) request.get(key));
                    opp.put(key, datetime.newInstance(d.year(), d.month(),d.day()));
                    
                }
                when else {
            		opp.put(key, request.get(key));
                }
            }
        }
        
        for(String key: requestAccount.keySet()){
            system.debug('Account field: '+ key +' - ' + requestAccount.get(key));
            acc.put(key, requestAccount.get(key));
        }
       
        if(!requestAccount.isEmpty()){
        	update acc;    
        }
        if(!request.isEmpty()){
        	update opp;
        }
        
    }

}