force-app/main/default/objects/Account/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SalesOrgs__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <formula>Owner.Sales_Office_Text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Follow__c/Follow__c.object-meta.xml
<CustomObject>
    <description>Objeto que registra la suscripción de un usuario con un Account, Opportunity, etc</description>
    <label>Follow</label>
    <nameField>
        <displayFormat>FW-{00000000}</displayFormat>
        <label>Follow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cuenta a la que se ha suscrito el usuario</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Follows</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>RecordType para Follow de Account</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Order/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <label>SalesOffice</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/SALES_OFFICE__c.object-meta.xml
<CustomObject>
    <description>Entidad custom que contiene el maestro de relaciones para transformar el código de la oficina de ventas por el nombre.</description>
    <label>Sales Office</label>
    <nameField>
        <label>Nombre de SALES_OFFICE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_OFFICE__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <description>Country ISO Code</description>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone</description>
    <label>Phone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>Código de la oficina de ventas</description>
    <externalId>true</externalId>
    <label>SalesOffice</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Org</label>
    <referenceTo>Sales_Org__c</referenceTo>
    <relationshipLabel>Sales Office</relationshipLabel>
    <relationshipName>Sales_Office</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/WaitingList__c.field-meta.xml
<CustomField>
    <fullName>WaitingList__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the Sales Office Waiting List?</description>
    <label>Waiting List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>User accepts in store appointments</description>
    <inlineHelpText>Please tick this box if the user accepts store appointments</inlineHelpText>
    <label>Store Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Sales Office from Sales Org default</description>
    <inlineHelpText>Sales Office from Sales Org default</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Default_Sales_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WaitingList__c/WaitingList__c.object-meta.xml
<CustomObject>
    <description>Manages waiting lists</description>
    <label>Waiting List</label>
    <nameField>
        <displayFormat>WL-{0000000}</displayFormat>
        <label>Waiting List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waiting Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WaitingList__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account is related with the entry</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Waiting Lists</relationshipLabel>
    <relationshipName>Waiting_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has an Appointment?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Waiting Lists</relationshipLabel>
    <relationshipName>Waiting_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>FirstName__c + &quot; &quot; + LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Office</label>
    <referenceTo>SALES_OFFICE__c</referenceTo>
    <relationshipLabel>Waiting Lists</relationshipLabel>
    <relationshipName>Waiting_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Waiting_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ONQUEUE</fullName>
                <default>true</default>
                <label>On queue</label>
            </value>
            <value>
                <fullName>ASSIGNED</fullName>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>INPROGRESS</fullName>
                <label>In progress</label>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>LOST</fullName>
                <label>Lost</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/transformed__c.field-meta.xml
<CustomField>
    <fullName>transformed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transformed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WaitingListComponentController.cls
/**
* @author Ivan Losilla
* @date May 2021
* @group-content ../../ApexDocContent/WAITING LISTS.htm
* @description Manage the component WaitingListComponent sending necessary info
*/
public class WaitingListComponentController {
    /**
    * @description Given a SalesOffice and a date, returns the entries
    * @param salesOffice sap code of the sales office
    * @param dateFilter date
    * @return list of entries that match the params
    */
	@AuraEnabled
    public static List<WaitingList__c> getWaitingPersonsData(String salesOffice, Date dateFilter) {
        List<WaitingList__c> auxWaitingLists = new List<WaitingList__c>();
        List<WaitingList__c> waitingLists = new List<WaitingList__c>();
        Integer dayFiltered = dateFilter.Day();
        Integer monthFiltered = dateFilter.Month();
        Integer yearFiltered = dateFilter.Year();
        
        auxWaitingLists = [SELECT toLabel(Status__c) labelStatus, Name__c, Email__c,FirstName__c,Id,LastName__c,
                        Phone__c,SalesOffice__r.SalesOffice__c,Status__c, Salesperson__r.Name, Salesperson__c,
                        Salesperson__r.FirstName, Salesperson__r.LastName, Transformed__c,Account__c,Account__r.Name,
                        Contact__c,Contact__r.Name,Appointment__c,CreatedDate
                        FROM WaitingList__c 
                        WHERE SalesOffice__r.SalesOffice__c =: salesOffice
                        order By Status__c ASC, CreatedDate ASC];
        
        for (WaitingList__c wList : auxWaitingLists) {
            //DateTime transCreatedDate = SystemUtils.toUserTimezone(wList.CreatedDate);
            Integer dayWList = wList.CreatedDate.Day();
            Integer monthWList = wList.CreatedDate.Month();
            Integer yearWList = wList.CreatedDate.Year();

            if (dayFiltered == dayWList && monthFiltered == monthWList && yearFiltered == yearWList) {
                waitingLists.add(wList);
            }
        }
        return waitingLists;
    } // getWaitingPersonsData

    /**
    * @description Get the data of the sales office the current user can see, and have waiting lists active
    */
    @AuraEnabled 
    public static List<Sales_Office__c> getSalesOffice() {
        List<Sales_Office__c> salesOfficeList = new List<Sales_Office__c>();
        List<User> usr = UserUtils.getData(new Set<Id>{UserInfo.getUserId()});
        if (UserUtils.isAdministrator(usr[0])) {
            salesOfficeList = [SELECT Name,SalesOffice__c,SalesOrg__c, WaitingList__c, CountryCode__c FROM SALES_OFFICE__c where WaitingList__c = true];
        } else {
            Set<Id> listSubordinatesIds = SystemUtils.getRoleSubordinateUsers(usr[0].UserRoleId);
            List<User> listSubordinates = UserUtils.getData(listSubordinatesIds);
            Set<String> listSalesOffice = new Set<String>{usr[0].Sales_Office__c};

            for (User subordinate : listSubordinates) {
                listSalesOffice.add(subordinate.Sales_Office__c);
            }
            salesOfficeList = [SELECT Name,SalesOffice__c,SalesOrg__c, WaitingList__c, CountryCode__c FROM SALES_OFFICE__c where WaitingList__c = true and SalesOffice__c in :listSalesOffice];
        }       
        return salesOfficeList;
    } // getSalesOffice

    @AuraEnabled 
    public static String getUserSalesOffice() {
        List<User> usr = UserUtils.getData(new Set<Id>{UserInfo.getUserId()});
        return usr[0].Sales_Office__c;
    } // getUserSalesOffice

    /**
    * @description Given a sales office, returns the users that have it set on the profile
    * @param salesOffice sap code of a sales office
    * @return List of users who work on a sales office
    */
    @AuraEnabled 
    public static List<User> getUsers(String salesOffice) {
        List<User> usrList = new List<User>();
        usrList = [SELECT Id, Name from User where isActive = true and Sales_Office__c =: salesOffice order by Name ASC];
        return usrList;
    } // getUsers

    @AuraEnabled 
    public static String getPersonAccountRecordType() {
        return Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Private_Customer').getRecordTypeId();
    } // getPersonAccountRecordType

    /**
    * @description Changes the owner of an entry on a Waiting list and changes the status to 'INPROGRESS'
    * @param waitingId the id of the entry that is going to change
    */
    @AuraEnabled 
    public static Boolean assistCustomer(String waitingId) {
        WaitingList wlist = new WaitingList(waitingId);
        wlist.assistCustomer();
        
        if (wlist.getSalesperson() != UserInfo.getUserId()) {
            wlist.sendNotificationsAssigned(wlist.getSalesperson(), true);
        }
        return true;
    }

    /**
    * @description Changes the owner of an entry on a Waiting list and changes the status to 'INPROGRESS'
    * @param waitingId the id of the entry that is going to change
    * @param salespersonId the id of the salesperson
    */
    @AuraEnabled 
    public static Boolean assignSalesperson(String waitingId, String salespersonId) {
        WaitingList wlist = new WaitingList(waitingId);
        String existingSalesperson = wlist.getSalesperson();
        wlist.assignSalesperson(salespersonId);
        wlist = new WaitingList(waitingId);
        if (salespersonId != UserInfo.getUserId() && salespersonId != existingSalesperson) {
            //wlist.sendNotificationsAssigned(salespersonId, false);
            wlist.sendWaitingAssistanceMail();
        }
        return true;
    }
    
    @AuraEnabled 
    public static Boolean assignAndAssistSalesperson(String waitingId, String salespersonId) {
        WaitingList wlist = new WaitingList(waitingId);
        wlist.assignSalesperson(salespersonId);
        wlist.assistCustomer();
        
        if (salespersonId != UserInfo.getUserId()) {
            wlist.sendNotificationsAssigned(salespersonId, true);
            wlist.sendWaitingAssistanceMail();
        }
        return true;
    }

    @AuraEnabled 
    public static Boolean changeStatus(String waitingId, String newStatus) {
        WaitingList wlist = new WaitingList(waitingId);
        wlist.changeStatus(newStatus);
        return true;
    }

    @AuraEnabled 
    public static Boolean createNewWListEntry(WaitingList__c entryData) {
        try {
            insert entryData;
        } catch (ContextException ex) {
            throw new ContextException(ex);
        }
        
        WaitingList wlist = new WaitingList(entryData.Id);
        wlist.sendNotificationNewWLItem();
        return true;
    }

    @AuraEnabled 
    public static Boolean createNewPersonAccount(String waitingId, Account accountData) {
         Savepoint sp = Database.setSavepoint();
        
        try {
            insert accountData;
            
            WaitingList__c waitingPerson = [Select Id, Status__c from WaitingList__c where Id =: waitingId LIMIT 1];
            if (waitingPerson != null) {
                waitingPerson.Status__c = 'COMPLETED';
                waitingPerson.Transformed__c = true;
                waitingPerson.Account__c = accountData.Id;
                update waitingPerson;
            }
            
            return true;
        } catch (ContextException ex) {
            Database.RollBack(sp);
            throw new ContextException(ex);
        }
    } // createNewPersonAccount

    @AuraEnabled
    public static Boolean createNewContact(String waitingId, Contact contactData) {
         Savepoint sp = Database.setSavepoint();
        
        try {
            if (contactData.AccountId == null) {
                throw new ContextException('An account must be selected');
            }
            insert contactData;
            
            WaitingList__c waitingPerson = [Select Id, Status__c from WaitingList__c where Id =: waitingId LIMIT 1];
            if (waitingPerson != null) {
                waitingPerson.Status__c = 'COMPLETED';
                waitingPerson.Transformed__c = true;
                waitingPerson.Contact__c = contactData.Id;
                update waitingPerson;
            }
            
            return true;
        } catch (ContextException ex) {
            Database.RollBack(sp);
            throw new ContextException(ex);
        }
    } // createNewPersonAccount
}