force-app/main/default/objects/Account/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SalesOrgs__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <formula>Owner.Sales_Office_Text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/USA.recordType-meta.xml
<RecordType>
    <fullName>USA</fullName>
    <active>true</active>
    <label>USA</label>
</RecordType>

force-app/main/default/objects/Follow__c/Follow__c.object-meta.xml
<CustomObject>
    <description>Objeto que registra la suscripción de un usuario con un Account, Opportunity, etc</description>
    <label>Follow</label>
    <nameField>
        <displayFormat>FW-{00000000}</displayFormat>
        <label>Follow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cuenta a la que se ha suscrito el usuario</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Follows</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/SALES_OFFICE__c.object-meta.xml
<CustomObject>
    <description>Entidad custom que contiene el maestro de relaciones para transformar el código de la oficina de ventas por el nombre.</description>
    <label>Sales Office</label>
    <nameField>
        <label>Nombre de SALES_OFFICE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_OFFICE__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <description>Country ISO Code</description>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone</description>
    <label>Phone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>Código de la oficina de ventas</description>
    <externalId>true</externalId>
    <label>SalesOffice</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SALES_OFFICE__c/fields/WaitingList__c.field-meta.xml
<CustomField>
    <fullName>WaitingList__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the Sales Office Waiting List?</description>
    <label>Waiting List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>User accepts in store appointments</description>
    <inlineHelpText>Please tick this box if the user accepts store appointments</inlineHelpText>
    <label>Store Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Sales Office from Sales Org default</description>
    <inlineHelpText>Sales Office from Sales Org default</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Default_Sales_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WaitingList__c/WaitingList__c.object-meta.xml
<CustomObject>
    <description>Manages waiting lists</description>
    <label>Waiting List</label>
    <nameField>
        <displayFormat>WL-{0000000}</displayFormat>
        <label>Waiting List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waiting Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WaitingList__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account is related with the entry</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Waiting Lists</relationshipLabel>
    <relationshipName>Waiting_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has an Appointment?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Waiting Lists</relationshipLabel>
    <relationshipName>Waiting_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>FirstName__c + &quot; &quot; + LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Office</label>
    <referenceTo>SALES_OFFICE__c</referenceTo>
    <relationshipLabel>Waiting Lists</relationshipLabel>
    <relationshipName>Waiting_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Waiting_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ONQUEUE</fullName>
                <default>true</default>
                <label>On queue</label>
            </value>
            <value>
                <fullName>ASSIGNED</fullName>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>INPROGRESS</fullName>
                <label>In progress</label>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>LOST</fullName>
                <label>Lost</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WaitingList__c/fields/transformed__c.field-meta.xml
<CustomField>
    <fullName>transformed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transformed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WaitingList.cls
public class WaitingList {
    private WaitingList__c entry;

    public WaitingList(WaitingList__c wlistEntry) {
        this.entry = wlistEntry;
    }

    public WaitingList(Id wlistId) {
        List<WaitingList__c> wlists = getData(new Set<Id>{wlistId});
        if (wlists.size() == 1) {
            this.entry = wlists[0];
        }
    }

    public String getSalesperson() {
        return this.entry == null ? null : this.entry.Salesperson__c; 
    }

    public void assistCustomer() {
        try {
            if (this.entry != null) {
                if (this.entry.Salesperson__c == null) {
                    throw new ContextException(Label.wlist_noSalesperson);
                }
                
                if (this.entry.Status__c != 'ASSIGNED') {
                    throw new ContextException(Label.wlist_alreadyAssigned);
                } else {
                    this.entry.Status__c = 'INPROGRESS';
                    update this.entry;

                    if (this.entry.Phone__c != null) {
                        sendAssistSMS();
                    }
                }
            }
        } catch (ContextException ex) {
            throw new ContextException(ex.getMessage());
        }
    }

    public void assignSalesperson(Id salespersonId) {
        try {
            if (this.entry != null) {
                this.entry.Salesperson__c = salespersonId;
                this.entry.Status__c = 'ASSIGNED';
                update this.entry;
            }
        } catch (ContextException ex) {
            throw new ContextException('Something happened. Try again or contact an Admin');
        }
    }

    public void changeStatus(String newStatus) {
        try {
            if (this.entry != null) {
                this.entry.Status__c = newStatus;
                update this.entry;
            }
        } catch (ContextException ex) {
            throw new ContextException(ex);
        }
    }

    private static List<WaitingList__c> getData(Set<Id> wlistIds) {
        List<WaitingList__c> auxWaitingLists = [SELECT toLabel(Status__c) labelStatus, Name__c, Email__c,FirstName__c,Id,LastName__c,
                        Phone__c,SalesOffice__r.SalesOffice__c,Status__c, SalesOffice__r.CountryCode__c, SalesOffice__r.Name, Salesperson__r.Name, Salesperson__c,
                        Salesperson__r.FirstName, Salesperson__r.LastName, Transformed__c,Account__c,Account__r.Name,
                        Contact__c,Contact__r.Name,Appointment__c,CreatedDate, Owner.Email, Salesperson__r.Email
                        FROM WaitingList__c 
                        WHERE Id IN : wlistIds];
                    
        return auxWaitingLists;
	}

    public void sendNotificationsAssigned(Id userId, Boolean assist) {
        Id typeId = [SELECT Id FROM CUstomNotificationType WHERE DeveloperName = 'ApexNotification'].Id;
        
        try {
            if (typeId != null) {
                Messaging.CustomNotification notification = new Messaging.CustomNotification();
                if (assist == false) {
                    notification.setBody(this.entry.FirstName__c + ' ' + this.entry.LastName__c + ' is waiting for you');
                    notification.setTitle('A Customer is waiting');
                } else {
                    notification.setBody(this.entry.Name__c + ' is waiting for your assistance');
                    notification.setTitle(Label.wlist_customerWaiting);
                }
                notification.setNotificationTypeId(typeId);
                
                notification.setTargetId(this.entry.Id);
                notification.send(new Set<String>{this.entry.Salesperson__c});
            }
        } catch (ContextException e) {
            SystemUtils.debugWarning('WLASSIGNED', 'WAITING LIST ASIGNED MAIL NOT SENT', e);
        }
    }

    public void sendNotificationNewWLItem() {
        try {
            Set<String> userIds = new Set<String>();
            List<User> listUsers = new List<User>();
            if (this.entry != null){
                listUsers = [SELECT Id, Sales_Office__c from User where isActive = true and Sales_Office__c =: this.entry.SalesOffice__r.SalesOffice__c ];
            }
    
            for (user usr : listUsers) {
                userIds.add(usr.Id);
            }
            
            Id typeId = [SELECT Id FROM CUstomNotificationType WHERE DeveloperName = 'ApexNotification'].Id;
            if (typeId != null) {
                Messaging.CustomNotification notification = new Messaging.CustomNotification();
                Set<String> listSendTo = userIds;
    
                if (listSendTo != null && listSendTo.size() > 0) {
                    notification.setBody(Label.wlist_personWaiting.replace(this.entry.FirstName__c + ' ' + this.entry.LastName__c, '#NAME'));
                    notification.setTitle(Label.wlist_newPerson);
                    notification.setNotificationTypeId(typeId);
                    notification.setTargetId(this.entry.Id);
                    notification.send(listSendTo);
                }

                if (this.entry.Phone__c != null) {
                    sendWelcomeSMS();
                }
            }
        } catch (ContextException e) {
            SystemUtils.debugWarning('WLNEWENTRY', 'NEW ENTRY NORIFICATION FAILED', e);
        }
    }

    private void sendWelcomeSMS() {
        String messageSMS = Label.wlist_welcomeSms;
        String firstName = this.entry.FirstName__c == null ? '-' : this.entry.FirstName__c;
        String salesOfficeName = this.entry.SalesOffice__r.Name == null ? '-' : this.entry.SalesOffice__r.Name;
        messageSMS = messageSMS.replace('#FIRSTNAME', firstName);
        messageSMS = messageSMS.replace('#SALESOFFICENAME', salesOfficeName);
        sendSMS(this.entry.Phone__c, messageSMS, this.entry.SalesOffice__r.CountryCode__c);
    }

    private void sendAssistSMS() {
        String messageSMS = Label.wlist_assistSms;
        String firstName = this.entry.FirstName__c == null ? '-' : this.entry.FirstName__c;
        String salesPersonName = this.entry.Salesperson__r.FirstName == null ? '-' : this.entry.Salesperson__r.FirstName;
        messageSMS = messageSMS.replace('#FIRSTNAME', firstName);
        messageSMS = messageSMS.replace('#SALESPERSONNAME', salesPersonName);
        sendSMS(this.entry.Phone__c, messageSMS, this.entry.SalesOffice__r.CountryCode__c);
    }

    @future(callout = true)
    private static void sendSMS(String phone, String body, String country){
        SMS messageSend = new SMS(phone, body, country);
        messageSend.send();
    }

    public void sendWaitingAssistanceMail() {
        try {
            List<Mail> mailsToSend = new List<Mail>();
            Mail auxMail = new Mail();
            auxMail.setHtml(setHtml(this.entry.Salesperson__r.Name, this.entry.Name__c));
            auxMail.setGeneric(); // It will come from a generic email address
            auxMail.setTo(this.entry.Salesperson__c);
            auxMail.setSubject('A CUSTOMER IS WAITING YOUR ASSISTANCE');
            mailsToSend.add(auxMail);
    
            MailUtils.sendBatch(mailsToSend);
        } catch (ContextException e) {
            SystemUtils.debugWarning('WLASSIGNED', 'WAITING LIST ASIGNED MAIL NOT SENT', e);
        }
    }

    private static String setHtml(String ownerName, String personName) {
        String mailBody = '<html><head><style>'
                + 'body { font-family: Helvetica, Tahoma, Sans-serif; color: #666; font-weight: 200; } '
                + 'a { color: #666; } '
                + 'table {border-collapse:collapse;padding:0px;margin:0px;border-spacing:0;mso-table-lspace:0pt;mso-table-rspace:0pt;border:1px solid DimGray;} '
                + 'th,td {border-spacing:0;border-collapse:collapse !important;padding:5px;border:1px solid DimGray;}'
                + '.row-header {background-color: #eff1f3;  font-weight: bold; width: 300px;} '
                + '.error-banner {border-style:none; background-color: #ed676e; color: white;  margin: 20px 0px; } '
                + '.error-banner td {border-style:none; padding: 30px !important;} '
                + '.info-banner {border-style:none; background-color: #DDE9F5; margin: 20px 0px; } '
                + '.info-banner td {border-style:none;; padding: 30px !important;} '
                +  '</style></head><body>#BODY</body></html>';
        String longTextBody = Label.wlist_waitingAssistance;
        longTextBody = longTextBody.replace('#NAMESALESPERSON', ownerName == null ? '' : ownerName);
        longTextBody = longTextBody.replace('#NAMECUSTOMER', personName == null ? '' : personName);
        longTextBody = longTextBody.replace('#TEAMCRM', 'Porcelanosa USA');
        mailBody = mailBody.replace('#BODY',longTextBody);
        
        return mailBody;
    }
}