force-app/main/default/objects/Account/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SalesOrgs__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <externalId>true</externalId>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SAP_Order__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order__c</fullName>
    <description>SAP Order Number</description>
    <label>SAP Order</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <label>SalesOffice</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <description>Sap code of the order is coming from</description>
    <label>Sap Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ECommerceUtilsTest.cls
@isTest public with sharing class ECommerceUtilsTest {

    @testSetup private static void setup() {
        TestUtils.enableTriggers();        
    }

    @isTest private static void findOpportunity() {
        Opportunity opp = DataFactoryOpportunity.createRetailOpportunities(1,1)[0];
        String sapOrder = '0012345678';
        opp.SAP_Order__c = sapOrder;
        update opp;

        Id id = ECommerceUtils.findOpportunity(sapOrder);
        System.assertNotEquals(null, id);

        id = ECommerceUtils.findOpportunity('1111112221');
        System.assertEquals(null, id);

    } // findOpportunity


    private static void createOrder(String sapOrder) {
        Account account = DataFactoryAccount.createPersonAccounts(1)[0];
        Order order = new Order(
            AccountId = account.Id,
            Sap_Id__c = sapOrder,
            SalesOrg__c = OrganizationCommons.ORG_SOUTH_EAST,
            SalesOffice__c = '2554',
            Status = 'Draft',
            EffectiveDate = System.today()
        );
        insert order;
    } // createOrder
} // class