force-app/main/default/objects/Account/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <externalId>true</externalId>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/CollectionDate__c.field-meta.xml
<CustomField>
    <fullName>CollectionDate__c</fullName>
    <description>Date agreed with the customer for the collection of goods</description>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Compensation__c.field-meta.xml
<CustomField>
    <fullName>Compensation__c</fullName>
    <description>Compensation to pay to a customer</description>
    <label>Settlement Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerReturns__c.field-meta.xml
<CustomField>
    <fullName>CustomerReturns__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to true when the customer will return the goods to them warehouse</description>
    <inlineHelpText>Check this if the customer is returning the goods himselt to the warehouse</inlineHelpText>
    <label>Customer will return the goods</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/FactoryInquiryDate__c.field-meta.xml
<CustomField>
    <fullName>FactoryInquiryDate__c</fullName>
    <label>Factory Inquiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/FactoryInquiryResponse__c.field-meta.xml
<CustomField>
    <fullName>FactoryInquiryResponse__c</fullName>
    <label>Factory Response</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/IsClaim__c.field-meta.xml
<CustomField>
    <fullName>IsClaim__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si es un Claim</description>
    <label>Is Claim</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/IsCollection__c.field-meta.xml
<CustomField>
    <fullName>IsCollection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Collection?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G1</fullName>
                <label>Factory Liability.</label>
            </value>
            <value>
                <fullName>G2</fullName>
                <label>Region Liability.</label>
            </value>
            <value>
                <fullName>G3</fullName>
                <label>Customer Liability.</label>
            </value>
            <value>
                <fullName>Company Liability</fullName>
                <isActive>false</isActive>
                <label>Company Liability</label>
            </value>
            <value>
                <fullName>Factory Liability</fullName>
                <isActive>false</isActive>
                <label>Factory Liability</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/RestockFee__c.field-meta.xml
<CustomField>
    <fullName>RestockFee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Apply restocking fee to customer when checked</description>
    <inlineHelpText>Check this box to apply a restocking fee to the customer collection</inlineHelpText>
    <label>Restock Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <description>SAP Sales Organisation</description>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAPCreditNote__c.field-meta.xml
<CustomField>
    <fullName>SAPCreditNote__c</fullName>
    <label>SAP Credit Note</label>
    <length>10</length>
    <referenceTo>Facturas_cabeceraSet__x</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAPDeliveryNumber__c.field-meta.xml
<CustomField>
    <fullName>SAPDeliveryNumber__c</fullName>
    <label>SAP Delivery Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAPGoodsPosted__c.field-meta.xml
<CustomField>
    <fullName>SAPGoodsPosted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SAP Goods Posted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAPInvoice__c.field-meta.xml
<CustomField>
    <fullName>SAPInvoice__c</fullName>
    <description>Invoice Number of the goods to be collected</description>
    <inlineHelpText>Please enter the invoice number of the goods to be collected</inlineHelpText>
    <label>SAP Invoice</label>
    <length>10</length>
    <referenceTo>Facturas_cabeceraSet__x</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAPOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>SAPOrderNumber__c</fullName>
    <description>Stores the SAP Order Number created to manage COLLECTIONS. This is ised in the version 1 that does not creates an ORDER in Salesforce.</description>
    <label>SAP Order Number</label>
    <length>10</length>
    <referenceTo>Pedidos_cabeceraSet__x</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAPWarehouse__c.field-meta.xml
<CustomField>
    <fullName>SAPWarehouse__c</fullName>
    <description>Warehouse selected</description>
    <label>SAP Warehouse</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SupplyReplacement__c.field-meta.xml
<CustomField>
    <fullName>SupplyReplacement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Supply a replacement product or part</description>
    <label>Supply Replacement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Warranty__c.field-meta.xml
<CustomField>
    <fullName>Warranty__c</fullName>
    <label>Product Under Warranty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNoValueSet</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/IsCollection__c.field-meta.xml
<CustomField>
    <fullName>IsCollection__c</fullName>
    <description>The order is a collection</description>
    <formula>BEGINS( TEXT(Type) ,&apos;Z018&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Collection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <description>Sap code of the order is coming from</description>
    <label>Sap Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SAPDeliveryNumber__c.field-meta.xml
<CustomField>
    <fullName>SAPDeliveryNumber__c</fullName>
    <label>SAP Delivery Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SAPGoodsPosted__c.field-meta.xml
<CustomField>
    <fullName>SAPGoodsPosted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SAP Goods Posted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <formula>Product2.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Sap_id__c.field-meta.xml
<CustomField>
    <fullName>Sap_id__c</fullName>
    <label>Sap_id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/ProductListItem__c.object-meta.xml
<CustomObject>
    <description>Custom object to store list of products</description>
    <label>Product List Item</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>ItemId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product List Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductListItem__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAPCasesSettings__c/SAPCasesSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuración Casos SAP</description>
    <label>PORSA SAP Cases</label>
</CustomObject>

force-app/main/default/objects/SAPCasesSettings__c/fields/COL_ReturnsWarehouse__c.field-meta.xml
<CustomField>
    <fullName>COL_ReturnsWarehouse__c</fullName>
    <description>Lista de almacenes seleccionables para devoluciones (separados por ;)</description>
    <label>COL Returns Warehouse</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAPWarehouse__c/SAPWarehouse__c.object-meta.xml
<CustomObject>
    <label>SAP Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/YesNoValueSet.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YES</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <masterLabel>YesNoValueSet</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SAPCasesServiceTest.cls
@isTest(isParallel=false) public class SAPCasesServiceTest {
    @testSetup  public static void testSetup() {
        //DataFactoryProduct.createProducts(null);        
        SAPCasesControllerTest.buildNewCase();    
        DataFactoryCase.autoInsert = false; 
        Case[] cases = DataFactoryCase.createClaims(1);       
        insert cases;   

    }

    @isTest public static void test_createSAPInvoiceCase() {
        SAPCasesControllerTest.testSaveSAPCase();
    }

    @isTest public static void testSEndSolution() {
        //Case c = SAPCASesControllerTest.buildNewCase();
        Case c = [select Id from Case where IsClaim__c = true limit 1];
        c.SupplyReplacement__c = true;
        c.Liability__c = PicklistCommons.getKeysList(Case.Liability__c)[0];
        c.Warranty__c = PicklistCommons.getKeysList(Case.Warranty__c)[0];
        update c;
        SAPCasesService.sendClaimSolutionToCustomer(c.Id, 'dummy@email.cxm');
        Assert.isTrue(true);
    }

    @isTest public static void test_createSAPCollection() {
        insert new SAPCasesSettings__c(
            Name = '502',
            COL_ReturnsWarehouse__c = 'WH1;WH2'
        );

        SAPOrderCreatorTest.SAPProxyMockTest mocker = new SAPOrderCreatorTest.SAPProxyMockTest();
        Test.setMock(HttpCalloutMock.class, mocker);

        Case newCase = [
            SELECT Id, Status, SAPWarehouse__c, CollectionDate__c, RestockFee__c, CustomerReturns__c, AccountId
            FROM Case
            WHERE IsCollection__c = true
            LIMIT 1
        ];

        Account acc = [
            SELECT Id, SAP_Id__c
            FROM Account
            WHERE Id = :newCase.AccountId
            LIMIT 1
        ];
        acc.SAP_Id__c = '1000111';
        update acc;

        newCase.SAPWarehouse__c = 'WH9';
        newCase.CollectionDate__c = System.today().addDays(1);
        newCase.RestockFee__c = true;
        newCase.CustomerReturns__c = true;
        newCase.Status = CasesDomain.STATUS_NEW;
        update newCase;

        Test.startTest();
        SAPCasesService.SAPCollectionDTO dto = SAPCasesService.createSAPCollection(newCase.Id);
        Test.stopTest();

        Case savedCase = [
            SELECT SAPOrderNumber__c, Status
            FROM Case
            WHERE Id = :newCase.Id
        ];

        Assert.areEqual('25', dto.orderNumber, 'El mock debería devolver el pedido 25');
        Assert.areEqual('25', savedCase.SAPOrderNumber__c, 'El Case debe guardar el pedido SAP');
        Assert.areEqual(CasesDomain.STATUS_READY, savedCase.Status, 'El Case debe pasar a Ready');
    }

    @isTest public static void test_createSAPCollection_usesSettingsWarehouse() {
        insert new SAPCasesSettings__c(
            Name = '502',
            COL_ReturnsWarehouse__c = 'WH1;WH2'
        );

        SAPOrderCreatorTest.SAPProxyMockTest mocker = new SAPOrderCreatorTest.SAPProxyMockTest();
        Test.setMock(HttpCalloutMock.class, mocker);

        Case newCase = [
            SELECT Id, Status, SAPWarehouse__c, AccountId
            FROM Case
            WHERE IsCollection__c = true
            LIMIT 1
        ];

        Account acc = [
            SELECT Id, SAP_Id__c
            FROM Account
            WHERE Id = :newCase.AccountId
            LIMIT 1
        ];
        acc.SAP_Id__c = '1000111';
        update acc;

        newCase.SAPWarehouse__c = null;
        newCase.Status = CasesDomain.STATUS_APPROVED;
        update newCase;

        Test.startTest();
        SAPCasesService.SAPCollectionDTO dto = SAPCasesService.createSAPCollection(newCase.Id);
        Test.stopTest();

        Case savedCase = [
            SELECT SAPOrderNumber__c, Status
            FROM Case
            WHERE Id = :newCase.Id
        ];

        Assert.areEqual('25', dto.orderNumber, 'El pedido debe crearse usando el warehouse por defecto');
        Assert.areEqual('25', savedCase.SAPOrderNumber__c);
        Assert.areEqual(CasesDomain.STATUS_READY, savedCase.Status);
    }


    @isTest private static void testCreateClaim() {        
        DataFactoryCase.autoInsert = true;
        //Case[] cases = DataFactoryCase.createClaims(1);
        Case[] cases = [select Id, SAPInvoice__c from Case where IsClaim__c = true limit 1];
        for (Case c : cases) {
            c.Liability__c = PicklistCommons.getKeysList(Case.Liability__c)[0];
            c.Warranty__c = PicklistCommons.getKeysList(Case.Warranty__c)[0];
        }
        update cases;
        Test.startTest();
        SAPCasesService.createSAPInvoiceCase(cases);
        Test.stopTest();
        Case c = [select Id, SalesOrg__c, Status from Case limit 1];
        Assert.isNotNull(c, 'A case should have been created');             
        //Assert.areEqual('502', c.SalesOrg__c, 'The case should have a sales org');    
    }

    @isTest private static void testSaveSAPInvoiceCase() {
        String message = null;
        Case[] cases = [select Id, SAPInvoice__c from Case where IsClaim__c = true limit 1];
        try {
            SAPCasesService.saveSAPInvoiceCase(cases[0]);   
        } catch(Exception ex) {
            message = ex.getMessage();
        }
        Assert.isNotNull(message, 'Message not expected: ' + message);
    }

    @isTest public static void test_RequestApproval() {
        // Case c =  SAPCASesControllerTest.buildNewCase();     
        Case c = [select Id from Case where IsCollection__c = true limit 1];        
        DateTime dt = SAPCasesService.requestApproval(c.Id);        
        Assert.isNotNull(dt, 'A requested approval datetime should have been set');
    }

    @isTest public static void test_approveCase() {
        // Case c = SAPCASesControllerTest.buildNewCase();        
        Case c = [select Id from Case where IsCollection__c = true limit 1];
        SAPCasesService.approveCollection(c.Id, UserInfo.getUserId());
        Case c2 = [select Id, Status from Case where Id = :c.Id limit 1];
        Assert.areEqual(CasesDomain.STATUS_APPROVED, c2.Status);
    }

    @isTest public static void test_updateStatusFromSAP() {
        // Case c = SAPCASesControllerTest.buildNewCase();
        Case c = [select Id from Case where IsCollection__c = true limit 1];
        c.SAPOrderNumber__c = '111111';
        update c;

        SAPCasesService.SAPDeliveryInfoDTO dto = new SAPCasesService.SAPDeliveryInfoDTO();
        dto.orderNumber = '111111';
        dto.deliveryNumber = '999999';
        dto.action = 'CREATE';
        dto.status = 'NA';
        dto.goodsPosted = false;

        SAPCasesService.updateStatusFromSAP(new List<SAPCasesService.SAPDeliveryInfoDTO>{dto});
        Case c2 = [select Id, SAPDeliveryNumber__c from Case where Id = :c.Id limit 1];
        Assert.areEqual('999999', c2.SAPDeliveryNumber__c);

        
        dto.orderNumber = '111111';
        dto.deliveryNumber = '999999';
        dto.action = 'GOODS-POSTED';
        dto.status = 'NA';
        dto.goodsPosted = true;

        ProductListItem__c pri = new ProductListItemsSelector().selectByCase(new Set<Id>{c.Id})[0];
        List<SAPCasesService.SAPDeliveryItemDTO> items = new List<SAPCasesService.SAPDeliveryItemDTO>();
        SAPCasesService.SAPDeliveryItemDTO item = new SAPCasesService.SAPDeliveryItemDTO();
        item.delivery = '6000000';
        item.itemno = 1;
        item.material = pri.ProductCode__c;
        item.quantity = 1;
        item.unit = 'UN';
        /*
        public String batch;
        public Decimal stk_quantity;
        public String stk_unit;        
        public Double stk_factor_num;
        public Double stk_factor_Den;
        public String order;
        public Integer orderitem;  
        */
        items.add(item);
        dto.items = items;
        SAPCasesService.updateStatusFromSAP(new List<SAPCasesService.SAPDeliveryInfoDTO>{dto});
        c2 = [select Id, SAPGoodsPosted__c from Case where Id = :c.Id limit 1];
        Assert.areEqual(true, c2.SAPGoodsPosted__c);

        // UMPOST
        dto.action = 'GOODS-UNPOST';
        dto.status = 'NA';
        dto.goodsPosted = false;
        SAPCasesService.updateStatusFromSAP(new List<SAPCasesService.SAPDeliveryInfoDTO>{dto});
        c2 = [select Id, SAPGoodsPosted__c from Case where Id = :c.Id limit 1];
        Assert.areEqual(false, c2.SAPGoodsPosted__c);        
    }

    @isTest public static void test_setSAPCreditNote() {
        //Case c = SAPCASesControllerTest.buildNewCase();
        Case c = [select Id from Case where IsCollection__c = true limit 1];
        c.SAPOrderNumber__c = '111111';
        update c;

        SAPCasesService.SAPCreditNoteDTO[] dtos = new List<SAPCasesService.SAPCreditNoteDTO>();
        SAPCasesService.SAPCreditNoteDTO dto = new SAPCasesService.SAPCreditNoteDTO();
        dto.invoiceNumber = '8888888';
        dto.orderNumber = '111111';
        dto.isCollection = true;
        dto.isReversal = false;
        dto.isCredit = true;
        dto.action = 'CREATE';
        dtos.add(dto);

        SAPCasesService.setSAPCreditNote(dtos);

        Case c2 = [select Id, SAPCreditNote__c from Case where Id = :c.Id limit 1];
        Assert.areEqual('8888888', c2.SAPCreditNote__c);
    }

    @isTest public static void test_setSAPCreditNote_2() {
        //Case c = SAPCASesControllerTest.buildNewCase();
        Case c = [select Id from Case where IsCollection__c = true limit 1];
        c.SAPCreditNote__c = '8888888';
        c.Status = CasesDomain.STATUS_INVOICED;
        update c;

        SAPCasesService.SAPCreditNoteDTO[] dtos = new List<SAPCasesService.SAPCreditNoteDTO>();
        SAPCasesService.SAPCreditNoteDTO dto = new SAPCasesService.SAPCreditNoteDTO();
        dto.invoiceNumber = '8888888';
        dto.orderNumber = '111111';
        dto.isCollection = true;
        dto.isReversal = false;
        dto.isCredit = true;
        dto.action = 'CLEAR';
        dtos.add(dto);

        SAPCasesService.setSAPCreditNote(dtos);

        Case c2 = [select Id, Status from Case where Id = :c.Id limit 1];
        Assert.areEqual(CasesDomain.STATUS_CLOSED, c2.Status, 'Status should be closed');
    }
  

    @isTest public static void testParseReason() {
        String reason = 'E08';
        Assert.areEqual(reason, SAPCasesService.parseReason(reason));
        reason = 'E08_1';
        Assert.areEqual('E08', SAPCasesService.parseReason(reason));
    }
 
    @isTest private static void testCreateCompensation() {                    
        Test.startTest();  
        // SAPCasesService.createSAPInvoiceCase(cases);        
        Case c = [select Id, SalesOrg__c, Status from Case limit 1];
        Assert.isTrue(true);
        c.Compensation__c = 500;
        Boolean exc = false;
        try {
            SAPCasesService.createCompensationOrder(c.Id);
        } catch (Exception e) {
            exc = (e.getTypeName() == 'ContextException');
        }
        Test.stopTest();
        Assert.isTrue(exc, 'Not important, just trying to reach coverage');
    }

    @isTest private static void testUpdateCaseResponse() {
        Case c = [select Id, FactoryInquiryDate__c from Case where IsClaim__c = true limit 1];
        c.FactoryInquiryDate__c = System.today();
        update c;
        c = new CasesSelector().selectById(new Set<Id>{c.Id})[0];
        Test.startTest();
        SAPCasesService.updateCaseResponse(c, 'XXX');
        Test.stopTest();
        c = new CasesSelector().selectById(new Set<Id>{c.Id})[0];
        Assert.areEqual(c.FactoryInquiryResponse__c, 'XXX', 'Wrong factoryn response ' + c.FactoryInquiryResponse__c);
    }

   
}