force-app/main/default/objects/Account/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <externalId>true</externalId>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Facturas_cabeceraSet__x/Facturas_cabeceraSet__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>Facturas_cabeceraSet</externalName>
    <label>Facturas_cabeceraSet</label>
    <pluralLabel>Facturas_cabeceraSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/Facturas_cabeceraSet__x/fields/Distchannel__c.field-meta.xml
<CustomField>
    <fullName>Distchannel__c</fullName>
    <description>Distchannel</description>
    <externalDeveloperName>Distchannel</externalDeveloperName>
    <label>Distchannel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Facturas_cabeceraSet__x/fields/Dnet__c.field-meta.xml
<CustomField>
    <fullName>Dnet__c</fullName>
    <description>Dnet</description>
    <externalDeveloperName>Dnet</externalDeveloperName>
    <label>Dnet</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Facturas_cabeceraSet__x/fields/Refer__c.field-meta.xml
<CustomField>
    <fullName>Refer__c</fullName>
    <description>Refer</description>
    <externalDeveloperName>Refer</externalDeveloperName>
    <label>Refer</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Facturas_cabeceraSet__x/fields/SALESOFFIC__c.field-meta.xml
<CustomField>
    <fullName>SALESOFFIC__c</fullName>
    <description>SALESOFFIC</description>
    <externalDeveloperName>SALESOFFIC</externalDeveloperName>
    <label>SALESOFFIC</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Facturas_cabeceraSet__x/fields/Sfopportunity__c.field-meta.xml
<CustomField>
    <fullName>Sfopportunity__c</fullName>
    <description>Sfopportunity</description>
    <externalDeveloperName>Sfopportunity</externalDeveloperName>
    <label>Sfopportunity</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ofertas_cabeceraSet__x/Ofertas_cabeceraSet__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>Ofertas_cabeceraSet</externalName>
    <label>Ofertas_cabeceraSet</label>
    <pluralLabel>Ofertas_cabeceraSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/Ofertas_cabeceraSet__x/fields/Gtotal__c.field-meta.xml
<CustomField>
    <fullName>Gtotal__c</fullName>
    <description>Gtotal</description>
    <externalDeveloperName>Gtotal</externalDeveloperName>
    <label>Gtotal</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ofertas_cabeceraSet__x/fields/Orderdate__c.field-meta.xml
<CustomField>
    <fullName>Orderdate__c</fullName>
    <description>Orderdate</description>
    <externalDeveloperName>Orderdate</externalDeveloperName>
    <label>Orderdate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ofertas_cabeceraSet__x/fields/Ordernum__c.field-meta.xml
<CustomField>
    <fullName>Ordernum__c</fullName>
    <description>Ordernum</description>
    <externalDeveloperName>Ordernum</externalDeveloperName>
    <label>Ordernum</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ofertas_cabeceraSet__x/fields/Refer__c.field-meta.xml
<CustomField>
    <fullName>Refer__c</fullName>
    <description>Refer</description>
    <externalDeveloperName>Refer</externalDeveloperName>
    <label>Refer</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ofertas_cabeceraSet__x/fields/Salesorg__c.field-meta.xml
<CustomField>
    <fullName>Salesorg__c</fullName>
    <description>Salesorg</description>
    <externalDeveloperName>Salesorg</externalDeveloperName>
    <label>Salesorg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Default Sales Org of the User who created the Opportunity</description>
    <label>Sales Org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillTo__c.field-meta.xml
<CustomField>
    <fullName>BillTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that will receive the invoice if it is different from the orde&apos;s account</description>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>BillTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ordernum__c.field-meta.xml
<CustomField>
    <fullName>Ordernum__c</fullName>
    <label>XXX Ordernum</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <description>Sap code of the order is coming from</description>
    <label>Sap Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/Pedidos_cabeceraSet__x.object-meta.xml
<CustomObject>
    <externalDataSource>SAP</externalDataSource>
    <externalName>Pedidos_cabeceraSet</externalName>
    <label>Pedidos_cabeceraSet</label>
    <pluralLabel>Pedidos_cabeceraSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/BillTo__c.field-meta.xml
<CustomField>
    <fullName>BillTo__c</fullName>
    <description>BillTo</description>
    <externalDeveloperName>BillTo</externalDeveloperName>
    <label>BillTo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Dcurr__c.field-meta.xml
<CustomField>
    <fullName>Dcurr__c</fullName>
    <description>Dcurr</description>
    <externalDeveloperName>Dcurr</externalDeveloperName>
    <label>Dcurr</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Dtotal__c.field-meta.xml
<CustomField>
    <fullName>Dtotal__c</fullName>
    <description>Dtotal</description>
    <externalDeveloperName>Dtotal</externalDeveloperName>
    <label>Dtotal</label>
    <precision>14</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Gtax__c.field-meta.xml
<CustomField>
    <fullName>Gtax__c</fullName>
    <description>Gtax</description>
    <externalDeveloperName>Gtax</externalDeveloperName>
    <label>Gtax</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/OpenF__c.field-meta.xml
<CustomField>
    <fullName>OpenF__c</fullName>
    <description>OpenF</description>
    <externalDeveloperName>OpenF</externalDeveloperName>
    <label>OpenF</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Paid__c.field-meta.xml
<CustomField>
    <fullName>Paid__c</fullName>
    <description>Paid</description>
    <externalDeveloperName>Paid</externalDeveloperName>
    <label>Paid</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedidos_cabeceraSet__x/fields/Salesoffic__c.field-meta.xml
<CustomField>
    <fullName>Salesoffic__c</fullName>
    <description>Salesoffic</description>
    <externalDeveloperName>Salesoffic</externalDeveloperName>
    <label>Salesoffic</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <description>Code of the Sales Org</description>
    <externalId>true</externalId>
    <label>Sales Org</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <externalId>true</externalId>
    <label>Sap Id</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SAPDocsController.cls
/**
* @author 			Ramón Prades
* @date 			November-2020
* @group 			Accounts
* @group-content 	../../ApexDocContent/Accounts.htm
* @description 	    Apex Controller for SAPDocs component (displays the list of sap docs of an account)
*/
public with sharing class SAPDocsController {

    private static String userSalesOrgs;
    
    @AuraEnabled 
    public static SAPDocsDTO getSAPDocuments(String docType, String accountId, String salesOrg) {        
        Account account = [Select Id, Name, SAP_Id__c from Account where Id = :accountId][0];
        List<sObject> theList = new List<sObject>();
        switch on docType.toUppercase() {
            when 'Q' {
                theList = readQuotes(account.SAP_Id__c, salesOrg);
            }
            when 'O' {
                theList = readOrders(account.SAP_Id__c, salesOrg);
            }
            when 'I' {
                theList = readInvoices(account.SAP_Id__c, salesOrg);
            }
        }
        SAPDocsDTO dto = new SAPDocsDTO();
        dto.variant = 'ACC';
        dto.accountId = accountId;
        dto.breadcrumb1 = account.Name;
        dto.breadcrumb2 = OrganizationUtil.getSalesOrgName(salesOrg);
        dto.sapId = account.SAP_Id__c;
        dto.items = (List<sObject>) theList;
        return dto;            
    } // getSAPDocuments

    @AuraEnabled 
    public static SAPDocsDTO getOPPDocuments(String docType, String opportunityId, String salesOrg) {
        Opportunity opp = [select Id, Name from Opportunity where Id = :opportunityId limit 1];
        SAPDocsDTO dto = new SAPDocsDTO();
        dto.permissionErrors = new List<String>();
        dto.breadcrumb1 = opp.Name;                
        dto.breadcrumb2 = '';
        dto.userSalesOrgs = [select Sales_Org__c from User where Id = :UserInfo.getUserId() limit 1].Sales_Org__c;
        switch on docType.toUppercase() {
            when 'Q' {
               readOppQuotes(opportunityId, dto);
            }
            when 'O' {
                readOppOrders(opportunityId, dto);
            }
            when 'I' {
                readOppInvoices(opportunityId, dto);
            }
        }
        removeDuplicatedErrors(dto);
        return dto;     
    } // getSAPDocuments



    /*************************************************************/

    private static List<Facturas_cabeceraSet__x> readInvoices(String sapId, String salesOrg) {
        List<Facturas_cabeceraSet__x> theList = new List<Facturas_cabeceraSet__x>();
        for (Facturas_cabeceraSet__x hdr :[select
            BillTo__c, Distchannel__c, Ordernum__c, Orderdate__c, Refer__c,
            Dcurr__c, Dnet__c, Dtax__c, Dtotal__c, Gcurr__c, Gnet__c, Gtax__c, Gtotal__c,
            Sfopportunity__c From Facturas_cabeceraSet__x
            where BillTo__c = :sapId and salesOrg__c = :salesOrg and Paid__c = ' ' order by Orderdate__c, Ordernum__c]
        ) {
            theList.add(hdr);
        }
        return theList;
    } // readInvoices

    private static List<Ofertas_cabeceraSet__x> readQuotes(String sapId, String salesOrg) {
        String completed = 'C';
        List<Ofertas_cabeceraSet__x> theList = new List<Ofertas_cabeceraSet__x>();
        for (Ofertas_cabeceraSet__x hdr :[select
                BillTo__c, Distchannel__c, Ordernum__c, Orderdate__c, Refer__c,
                Dcurr__c, Dnet__c, Dtax__c, Dtotal__c, Gcurr__c, Gnet__c, Gtax__c, Gtotal__c,
                Salesoffic__c, Sfopportunity__c 
            From Ofertas_cabeceraSet__x
            where BillTo__c = :sapId and salesOrg__c = :salesOrg and openf__c != :completed 
            order by Orderdate__c, Ordernum__c]
        ) {
            theList.add(hdr);
        }    
        return theList;
    } // readQuotes

    private static List<Pedidos_cabeceraSet__x> readOrders(String sapId, String salesOrg) {
        String completed = 'C';
        List<Pedidos_cabeceraSet__x> theList = new List<Pedidos_cabeceraSet__x>();
        for (Pedidos_cabeceraSet__x hdr :[select
                BillTo__c, Distchannel__c, Ordernum__c, Orderdate__c, Refer__c,
                Dcurr__c, Dnet__c, Dtax__c, Dtotal__c, Gcurr__c, Gnet__c, Gtax__c, Gtotal__c,
                Salesoffic__c, Sfopportunity__c 
            From Pedidos_cabeceraSet__x 
            where BillTo__c = :sapId and salesOrg__c = :salesOrg and openf__c != :completed 
            order by Orderdate__c, Ordernum__c]
        ) {
            theList.add(hdr);
        }
         System.debug('RPR Pues la lista tiene ' + theList.size());
        return theList;
    } // readQuotes

    private static void readOppQuotes(String oppId, SAPDocsDTO dto) {
        String completed = 'C';
        List<Ofertas_cabeceraSet__x> theList = new List<Ofertas_cabeceraSet__x>();
        for (Ofertas_cabeceraSet__x hdr :[select
                BillTo__c, Distchannel__c, Ordernum__c, Orderdate__c, Refer__c,
                Dcurr__c, Dnet__c, Dtax__c, Dtotal__c, Gcurr__c, Gnet__c, Gtax__c, Gtotal__c,
                Salesorg__c, Salesoffic__c, Sfopportunity__c 
            From Ofertas_cabeceraSet__x
            where Sfopportunity__c = :oppId and openf__c != :completed 
            order by Orderdate__c, Ordernum__c]
        ) {
            if (dto.userSalesOrgs.contains(hdr.Salesorg__c)) {
                theList.add(hdr);
            } else {
                dto.permissionErrors.add(hdr.Salesorg__c);
            }
        }    
        dto.items = (List<sObject>) theList;
    } // readOppQuotes

    private static void readOppOrders(String oppId, SAPDocsDTO dto) {
        String completed = 'C';
        List<pedidos_cabeceraSet__x> theList = new List<Pedidos_cabeceraSet__x>();
        for (Pedidos_cabeceraSet__x hdr :[select
                BillTo__c, Distchannel__c, Ordernum__c, Orderdate__c, Refer__c,
                Dcurr__c, Dnet__c, Dtax__c, Dtotal__c, Gcurr__c, Gnet__c, Gtax__c, Gtotal__c,
                Salesorg__c, Salesoffic__c, Sfopportunity__c 
            From Pedidos_cabeceraSet__x
            where Sfopportunity__c = :oppId and openf__c != :completed 
            order by Orderdate__c, Ordernum__c]
        ) {
            if (dto.userSalesOrgs.contains(hdr.Salesorg__c)) {
                theList.add(hdr);
            } else {
                dto.permissionErrors.add(hdr.Salesorg__c);
            }
        }    
        dto.items = (List<sObject>) theList;
    } // readOppOrders

    private static void readOppInvoices(String oppId, SAPDocsDTO dto) {
        String completed = 'C';
        List<Facturas_cabeceraSet__x> theList = new List<Facturas_cabeceraSet__x>();
        for (Facturas_cabeceraSet__x hdr :[select
                BillTo__c, Distchannel__c, Ordernum__c, Orderdate__c, Refer__c,
                Dcurr__c, Dnet__c, Dtax__c, Dtotal__c, Gcurr__c, Gnet__c, Gtax__c, Gtotal__c,
                Salesorg__c, Salesoffic__c, Sfopportunity__c 
            From Facturas_cabeceraSet__x
            where Sfopportunity__c = :oppId 
            order by Orderdate__c, Ordernum__c]
        ) {
            if (dto.userSalesOrgs.contains(hdr.Salesorg__c)) {
                theList.add(hdr);
            } else {
                dto.permissionErrors.add(hdr.Salesorg__c);
            }
        }    
        dto.items = (List<sObject>) theList;
    } // readOppInvoices


    private static void removeDuplicatedErrors(SAPDocsDTO dto) {
        if (dto.permissionErrors.size()>1) {
            Set<String> mySet = new Set<String>();
            mySet.addAll(dto.permissionErrors);
            dto.permissionErrors.clear();
            dto.permissionErrors.addAll(mySet);
        }
    }   

    // Data transfer object for sales documents (all the same)
    public class SAPDocsDTO {
        @AuraEnabled public String variant;        
        @AuraEnabled public String breadcrumb1;
        @AuraEnabled public String breadcrumb2;
        @AuraEnabled public Id accountId;
        @AuraEnabled public String sapId;
        @AuraEnabled public List<sObject> items = new List<sObject>();
        @AuraEnabled public String userSalesOrgs;
        @AuraEnabled public List<String> permissionErrors = new List<String>();
    } // SAPDocDTO

}