force-app/main/default/objects/Account/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <externalId>true</externalId>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContactPointAddress/fields/NB2B_thirdpartyAddress__c.field-meta.xml
<CustomField>
    <fullName>NB2B_thirdpartyAddress__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delivery Charges Apply</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContactPointAddress/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <description>Id of the address in SAP</description>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NB2B_ExternalObjLoadDays__mdt/NB2B_ExternalObjLoadDays__mdt.object-meta.xml
<CustomObject>
    <description>Num of days to filter in the load of externals objects, date.today - n days</description>
    <label>NB2B_ExternalObjLoadDays</label>
    <pluralLabel>NB2B_ExternalObjLoadDays</pluralLabel>
</CustomObject>

force-app/main/default/objects/NB2B_ExternalObjLoadDays__mdt/fields/NB2B_NumDays__c.field-meta.xml
<CustomField>
    <fullName>NB2B_NumDays__c</fullName>
    <label>NB2B_NumDays</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PorcelanosaAddress__c/PorcelanosaAddress__c.object-meta.xml
<CustomObject>
    <label>Porcelanosa Address</label>
    <nameField>
        <label>Porcelanosa Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porcelanosa Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PorcelanosaAddress__c/fields/NBK_Address__c.field-meta.xml
<CustomField>
    <fullName>NBK_Address__c</fullName>
    <label>Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/PorcelanosaAddress__c/fields/NBK_Address_Type__c.field-meta.xml
<CustomField>
    <fullName>NBK_Address_Type__c</fullName>
    <description>ASddresss Type</description>
    <label>Address Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Showroom</fullName>
                <label>Showroom2</label>
            </value>
            <value>
                <fullName>Warehouse</fullName>
                <label>Warehouse2</label>
            </value>
            <value>
                <fullName>Ships Samples</fullName>
                <label>Ships Samples2</label>
            </value>
            <value>
                <fullName>Collection Point</fullName>
                <label>Collection Point2</label>
            </value>
            <value>
                <fullName>B2B-Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PorcelanosaAddress__c/fields/NBK_isActive__c.field-meta.xml
<CustomField>
    <fullName>NBK_isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PorcelanosaAddress__c/fields/NBK_Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>NBK_Sales_Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Org</label>
    <referenceTo>Sales_Org__c</referenceTo>
    <relationshipLabel>Porcelanosa Address</relationshipLabel>
    <relationshipName>Porcelanosa_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <description>Code of the Sales Org</description>
    <externalId>true</externalId>
    <label>Sales Org</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <externalId>true</externalId>
    <label>Sap Id</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/Sales_Relationship__c.object-meta.xml
<CustomObject>
    <label>SAP Accounting Info</label>
    <nameField>
        <label>Nombre Organizaciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Accounting Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Relationship__c/fields/Account_Org__c.field-meta.xml
<CustomField>
    <fullName>Account_Org__c</fullName>
    <label>Account Org</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Organizaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <formula>Account_Org__r.SAP_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NB2B_AccountSelector.cls
public without sharing class NB2B_AccountSelector {
    
    //Get User Roles from object Sales_Relationship__c
    public static List<Sales_Relationship__c> getUserRoles(String recordIdStr){
        return [
            SELECT Id, Name, Account_org__c 
            FROM Sales_Relationship__c 
            WHERE Account_org__c =:recordIdStr
        ];
    }

    //Get User Roles from object Sales_Relationship__c
    public static List<WebCart> getAccountForUserRoles(String webCartId){
        return [
            SELECT  AccountId
            FROM WebCart  
            WHERE Id =:webCartId
        ];
    }
    //Get User Roles from object Sales_Relationship__c
    public static Address getAccountShippingAddress(String accountId){
        System.debug('NB2B_AccountSelector getAccountShippingAddress');
        return [
            SELECT  BillingAddress
            FROM Account  
            WHERE Id =:accountId limit 1
        ].BillingAddress;
    }

    public static List<Contact> selectContactBySapId(List<String> listSapsId){
        return [
            SELECT Id, Account.SAP_Id__c  
            FROM Contact 
            WHERE Account.SAP_Id__c IN : listSapsId
        ];
    }

    public static List<SalesChannel> getSalesChannel(){
        return [
            SELECT Id, ExternalChannelNumber 
            FROM SalesChannel
        ];
    }

    public static Integer getNumDays(String labelName){
        List<NB2B_ExternalObjLoadDays__mdt> mdt =[
            SELECT NB2B_NumDays__c, Label  
            FROM NB2B_ExternalObjLoadDays__mdt 
            WHERE Label =: labelName
        ];
        return Integer.valueOf(mdt[0].NB2B_NumDays__c);
    }

    public static List<ContactPointAddress> selectPointAddressesByAccountId(Id accountId){
        return [
            SELECT Id, Name, IsPrimary, IsDefault, Address, SAPId__c, ParentId, NB2B_thirdpartyAddress__c
            FROM ContactPointAddress
            WHERE ParentId = : accountId
            AND SAPId__c != null
            //AND AddressType = 'Shipping'
            //AND UsageType NOT IN('Inactive', 'Temporary')
        ];
    }

    public static List<PorcelanosaAddress__c> selectPointAddressesByDeliveryGroup(String deliveryGroup){
        return [
            SELECT Id, Name, NBK_Address__c, NBK_Address_Type__c
            FROM PorcelanosaAddress__c
            WHERE NBK_isActive__c = TRUE
            AND NBK_Address_Type__c includes ('Collection Point')
            AND NBK_Sales_Org__r.SalesOrg__c = : deliveryGroup
        ];
    }

}