force-app/main/default/objects/Account/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <externalId>true</externalId>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Execution_Context__mdt/Execution_Context__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata to define the behavior of a user&apos;s execution context. Initially designed to tell which countries are connected to SAP but open for extension in the near future</description>
    <label>Execution Context</label>
    <pluralLabel>Execution Contexts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Execution_Context__mdt/fields/ExtendedOpps__c.field-meta.xml
<CustomField>
    <fullName>ExtendedOpps__c</fullName>
    <description>Extended opportunities types allowed for the context</description>
    <inlineHelpText>semi-colon separated list of these keys: CUSTOMP, KITCHEN, FACADE.</inlineHelpText>
    <label>Extended Opportunities</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Execution_Context__mdt/fields/Has_SAP__c.field-meta.xml
<CustomField>
    <fullName>Has_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this option when the user works in a context connected to SAP</description>
    <inlineHelpText>Check this option if you need to connect to SAP from Salesforce</inlineHelpText>
    <label>Has SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Execution_Context__mdt/fields/OwnerAssignation__c.field-meta.xml
<CustomField>
    <fullName>OwnerAssignation__c</fullName>
    <description>Método sobre el que se buscará el owner para la asignación de un objeto</description>
    <label>Owner Assignation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>STD</fullName>
                <default>true</default>
                <label>Standard (país y cp)</label>
            </value>
            <value>
                <fullName>USA</fullName>
                <label>Extended US (país, cp, profile, etc)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Execution_Context__mdt/fields/PriceRequest__c.field-meta.xml
<CustomField>
    <fullName>PriceRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Price Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ScriptSendOppsToSAP.cls
/**
* @author Ivan Losilla
* @date September 2022
* @group Scripts
* @description Sends to SAP all Opportunities between two dates of the Accounts with SAPID. Send the Opps to SAP 
* as a new ones, or updates the info if the Opp is already on SAP
* if isTest is true, shows only the info about the Opps that are going to be sent to SAP, but doesn't send anything to SAP.
*/
global class ScriptSendOppsToSAP implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
    private Boolean isTest = true;
    private Date startDate;
    private Date endDate;
    private Set<String> contextsWithSAP = new Set<String>();
    
    global ScriptSendOppsToSAP(Date startDateParam, date endDateParam, Boolean isTestParam) {
        isTest = isTestParam;
        startDate = startDateParam;
        endDate = endDateParam;

        if (contextsWithSAP.size() == 0) {
            List<Execution_Context__mdt> contextsWithSAPList = [SELECT DeveloperName,ExtendedOpps__c,Has_SAP__c,Id,MasterLabel,OwnerAssignation__c,PriceRequest__c FROM Execution_Context__mdt WHERE Has_SAP__c = true];
            for (Execution_Context__mdt execution : contextsWithSAPList) {
                contextsWithSAP.add(execution.DeveloperName);
            }
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, createddate FROM Opportunity WHERE createddate >= :startDate and createddate <= :endDate and Account.Owner.Execution_Context__c in :contextsWithSAP and Account.sap_id__c <> null';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Opportunity> scope) {
        System.debug('Opportunities: ' + scope.size());
        Set<Id> oppsIdsSet = new Set<Id>();
        for (Opportunity opp : scope) {
            System.debug(opp);
            oppsIdsSet.add(opp.Id);
        }

        if (isTest == false) {
            System.debug('Sending to SAP');
            SAPSyncOpportunity.syncNow(oppsIdsSet);
        }
        System.debug('Finished');
    }
    
    global void finish(Database.BatchableContext bc){
    }
}