force-app/main/default/objects/Account/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <externalId>true</externalId>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Distribution_Channel__c/Distribution_Channel__c.object-meta.xml
<CustomObject>
    <label>Distribution Channel</label>
    <nameField>
        <label>Distribution Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Channel__c/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <label>Sap Id / Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>DeliveryDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Distribution_channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel__c</fullName>
    <label>Distribution channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/NB2B_Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>NB2B_Delivery_Method__c</fullName>
    <inlineHelpText>Yo must select wharehouse address when you select pick up from Cliente or Comertial</inlineHelpText>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Customer Pick Up</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Sales Rep Pick Up</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Send to Customer</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Showroom Delivery</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/OrderReason__c.field-meta.xml
<CustomField>
    <fullName>OrderReason__c</fullName>
    <label>Order Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E05_1</fullName>
                <label>Damaged Product</label>
            </value>
            <value>
                <fullName>E11</fullName>
                <label>Not Suitable</label>
            </value>
            <value>
                <fullName>E05</fullName>
                <label>Defective Product</label>
            </value>
            <value>
                <fullName>E07</fullName>
                <label>Sales Error</label>
            </value>
            <value>
                <fullName>E04</fullName>
                <label>Picking Error</label>
            </value>
            <value>
                <fullName>E07_1</fullName>
                <label>Admin Error</label>
            </value>
            <value>
                <fullName>E08</fullName>
                <label>Customer Error</label>
            </value>
            <value>
                <fullName>E08_1</fullName>
                <label>Surplus</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ReferredInvoice__c.field-meta.xml
<CustomField>
    <fullName>ReferredInvoice__c</fullName>
    <description>Invoiuce referred by this order (returns, credits, etc)</description>
    <label>Referred Invoice</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <description>Sap code of the order is coming from</description>
    <label>Sap Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderDeliveryGroup/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <description>Delivery address&apos; SAP Id (taken from Contact Point Address or Account)</description>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <formula>Product2.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ProductName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ProductSalesUnit__c.field-meta.xml
<CustomField>
    <fullName>ProductSalesUnit__c</fullName>
    <description>Product default  sales unit</description>
    <formula>Product2.Umv__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Sales Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ReferredLine__c.field-meta.xml
<CustomField>
    <fullName>ReferredLine__c</fullName>
    <description>Invoice line referred (credits, returns, etc)</description>
    <label>Referred Line</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SalesUnit__c.field-meta.xml
<CustomField>
    <fullName>SalesUnit__c</fullName>
    <label>SalesUnit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductUnits</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Sap_id__c.field-meta.xml
<CustomField>
    <fullName>Sap_id__c</fullName>
    <label>Sap_id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/StockKeepingUnit__c.field-meta.xml
<CustomField>
    <fullName>StockKeepingUnit__c</fullName>
    <formula>Product2.StockKeepingUnit</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SKU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WebStore/fields/SAPChannel__c.field-meta.xml
<CustomField>
    <fullName>SAPChannel__c</fullName>
    <description>SAP channel to use when placong orders to SAP</description>
    <label>SAP Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WebStore/fields/SAPSalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SAPSalesOrg__c</fullName>
    <description>SAP Sales Org used when plaicing orders to SAP</description>
    <label>SAP Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ProductUnits.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PZS</fullName>
        <label>PIECE</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>PALLET</label>
    </customValue>
    <customValue>
        <fullName>SAC</fullName>
        <label>BAG</label>
    </customValue>
    <customValue>
        <fullName>MT2</fullName>
        <label>SQUARE METERS</label>
    </customValue>
    <customValue>
        <fullName>BID</fullName>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>CJ</fullName>
        <label>BOX</label>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
        <label>CENTIMETER</label>
    </customValue>
    <customValue>
        <fullName>DM2</fullName>
        <label>SQUARE DECIMETER</label>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
        <label>KILOGRAM</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>LITER</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>METER</label>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
        <label>SQUARE METER</label>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
        <label>MILILITER</label>
    </customValue>
    <customValue>
        <fullName>ROL</fullName>
        <label>ROLE</label>
    </customValue>
    <customValue>
        <fullName>SQF</fullName>
        <label>SQUARE FOOT</label>
    </customValue>
    <customValue>
        <fullName>UN</fullName>
        <label>UNIT</label>
    </customValue>
    <customValue>
        <fullName>CM2</fullName>
        <label>SQUARE CENTIMETER</label>
    </customValue>
    <customValue>
        <fullName>DM</fullName>
        <label>DECIMETER</label>
    </customValue>
    <description>Values for product units</description>
    <masterLabel>Product Units</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SAPSalesOrderMapper.cls
/**
 * @author         Ramón Prades
 * @date           January 2026
 * @group          SAP
 * @description    Mapper responsible for transforming Salesforce Order data
 *                 into SAP Order DTOs. Designed to be reused both by
 *                 real order serialization and order simulation flows.
 *
 *                 This class does not access the database and does not
 *                 perform JSON serialization.
 */
public class SAPSalesOrderMapper {

    public static final String SAP_API_VERSION = '2.1';        

    // ------------------------------------------------------------
    // Input data (provided externally)
    // ------------------------------------------------------------
    private Order order;
    private OrderDeliveryGroup deliveryGroup;
    private List<OrderItem> items;

    // ------------------------------------------------------------
    // Behaviour flags
    // ------------------------------------------------------------
    private Boolean includePrices = true;
    private String emailAddress = '';
    private String requestedBy = null;

    // ------------------------------------------------------------
    // Constructor
    // ------------------------------------------------------------
    public SAPSalesOrderMapper(Order order, OrderDeliveryGroup deliveryGroup, List<OrderItem> items) {
        this.order = order;
        this.deliveryGroup = deliveryGroup;
        this.items = items;
    }

    // ------------------------------------------------------------
    // Configuration (fluent)
    // ------------------------------------------------------------

    /**
     * Excludes all price-related fields from the resulting SAP DTO.
     * Intended for order simulation scenarios.
     */
    public SAPSalesOrderMapper withoutPrices() {
        this.includePrices = false;
        return this;
    }

    /**
     * Defines an email to receive SAP's confirmation
     */
    public SAPSalesOrderMapper withConfirmationEmail(String email) {
        this.emailAddress = email;
        return this;
    }

    /**
     * Defines the SAP Sold-To account id explicitly.
     * Used when the Order has not been loaded from the database.
     */
    public SAPSalesOrderMapper withRequestedBy(String sapId) {
        this.requestedBy = sapId;
        return this;
    }

    // ------------------------------------------------------------
    // Public API
    // ------------------------------------------------------------

    /**
     * Transforms the provided Salesforce Order data into a SAP
     * order header DTO.
     */
    public SAPOrderHeaderDTO transform() {
        
        SAPOrderHeaderDTO header = new SAPOrderHeaderDTO();        

        header.sourceOrderId = this.order.Id;
        header.OperationType = this.mapOrderType(this.order.Type);
        header.Version = SAP_API_VERSION;
        header.m_Date = this.order.EffectiveDate;        
        header.RequestedBy = this.requestedBy != null ? this.requestedBy : this.order.Account?.SAP_Id__c;
        header.Email = this.emailAddress;
        header.Reference = this.order.PONumber;

        header.DeliveryInstructions = this.deliveryGroup?.DeliveryInstructions;
        header.DeliverToAlias = '';
        header.DeliverTo = this.deliveryGroup?.SAPId__c;

        header.SalesOrg = this.fixRenamedOrgs(this.order.SalesOrg__c);
        header.Channel = this.order.Distribution_channel__c;
        header.Index = 0;

        header.DeliveryDate = this.deliveryGroup?.DesiredDeliveryDate;
        if (header.DeliveryDate == null) {
            header.DeliveryDate = this.order.DeliveryDate__c;
        }

        header.ApplyRestockingCharges = false;
        header.m_Currency = this.order.CurrencyIsoCode;
        header.invoice = this.order.ReferredInvoice__c;
        header.OrderReason = this.order.OrderReason__c ?? '';

        if (this.includePrices) {
            header.NetValue = this.order.TotalAmount;
            header.Total = this.order.GrandTotalAmount;
        }

        switch on this.order.NB2B_Delivery_Method__c {
                when '1' {
                    header.storePickup = true;
            }
            when '3' {
                header.shippingCondition = 'N6';
                header.freight = 'Z3';
            } 
            when 'N3' {
                header.shippingCondition = 'N3';
                header.freight = 'Z3';
            }
        }

        /*
        if (header.SalesOrg == null && this.order.SalesStoreId != null) {
            WebStore store = this.storesMap.get(this.order.SalesStoreId);
            header.SalesOrg = store?.SAPSalesOrg__c;
            header.Channel = store?.SAPChannel__c;
        }
        */

        header.Items = this.buildItems();
        return header;    
    }

    // ------------------------------------------------------------
    // Internal helpers
    // ------------------------------------------------------------

    /**
     * Builds the SAP order item DTO list.
     */
    private SAPOrderItemDTO[] buildItems() {

        SAPOrderItemDTO[] itemsDTO = new List<SAPOrderItemDTO>();

        for (OrderItem item: this.items) {
            SAPOrderItemDTO dto = new SAPOrderItemDTO();
            dto.Sequence = item.LineNumber;
            dto.ProductCode = item.StockKeepingUnit__c;
            dto.Unit = item.SalesUnit__c ??item.ProductSalesUnit__c;
            dto.Quantity = item.Quantity;
            dto.ProductName = item.ProductName__c;
            dto.SerialNumber = '';
            //dto.Shade;
            dto.lineRef = Integer.valueOf(item.ReferredLine__c);
            if (this.includePrices) {
                dto.PricePerUnit = item.ListPrice;
                dto.PriceUnit = dto.Unit;
                dto.NetValue = item.TotalLineAmount;
                dto.TaxAmount = item.TotalLineTaxAmount;
            }
            itemsDTO.add(dto);
        }        
        return itemsDTO;
    }


    /**
     * Maps salesforce order types to SAP API types
     */
    private String mapOrderType(String orderType) {
        String result = '';
        switch on orderType {                        
            when 'Z011'     { result = '30'; }      // Samples order
            when 'Z016'     { result = '12'; }      // Credit request
            when 'Z017'     { result = '22'; }      // Service order            
            when 'Z018'     { result = '10'; }      // Customer returns
            when 'Z018_F'   { result = '11'; }      // Free Customer returns
            when 'Z051'     { result = '31'; }      // Replacement order 
            when 'ZW04'     {                     // Material order
                result = this.includePrices ? '21' : '20';
            }
            when else {
                throw new ValidationException('Operation type not supported ' + orderType);
            }
        }
        return result;
    }

    /**
     * Fixes renamed sales orgs
     */
    @SuppressWarnings('PMD.IfStmtsMustUseBraces, PMD.IfElseStmtsMustUseBraces')
    private String fixRenamedOrgs(String org) {
        // Check for null to avoid NullPointerException
        if (org == null) {
            return null;
        }

        // Apply mapping if matches specific values
        if (org == '504') return '514';
        if (org == '505') return '515';
        if (org == '506') return '516';
        if (org == '507') return '517';
        if (org == '508') return '518';

        // Return unchanged for other values
        return org;
    }

    /*
     * This method was intented for sales stores linked to a sales org/channel
     * but finally not used.
     */
    /*
    private void readStores(Set<Id> storeIds) {
        this.storesMap = new Map<Id, WebStore>();        
        for (WebStore store  : [select Id, Name, SAPSalesOrg__c, SAPChannel__c from WebStore where id in :storeIds]) {
            this.storesMap.put(store.Id, store);
        }
    }
    */
}