force-app/main/default/objects/Account/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <externalId>true</externalId>
    <label>SAP Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Distribution_Channel__c/Distribution_Channel__c.object-meta.xml
<CustomObject>
    <label>Distribution Channel</label>
    <nameField>
        <label>Distribution Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Channel__c/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <label>Sap Id / Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Sap_Id__c</fullName>
    <externalId>true</externalId>
    <label>Sap Id</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/Sales_Relationship__c.object-meta.xml
<CustomObject>
    <label>SAP Accounting Info</label>
    <nameField>
        <label>Nombre Organizaciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Accounting Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Relationship__c/fields/Account_Org__c.field-meta.xml
<CustomField>
    <fullName>Account_Org__c</fullName>
    <label>Account Org</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Organizaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>Distribution Channel</description>
    <inlineHelpText>Distribution Channel</inlineHelpText>
    <label>Distribution Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <formula>Account_Org__r.SAP_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_configuration__c/Trigger_configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>For Trigger configuration, to set on/off trigger fire events.</description>
    <label>Trigger Configuration</label>
</CustomObject>

force-app/main/default/objects/Trigger_configuration__c/fields/Sales_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Sales_Relationship__c</fullName>
    <defaultValue>false</defaultValue>
    <description>¿Enable Sales Relationship Triggers?</description>
    <label>Sales Relationship</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/B2B_SapAccountingInfoControllerTest.cls
/*-----------------------------------------------------------------------------------------
     Apex Class:        B2B_SapAccountingInfoControllerTest
     Created Date:      14/03/2022
     Author:            Cristobal Acero Lara
     Mail:              cristobal.acero@nubika.com
     Description:       Test to LWC controller
------------------------------------------------------------------------------------------*/
@isTest
public with sharing class B2B_SapAccountingInfoControllerTest {

    @TestSetup
    static void setupData(){
    	CommerceEntitlementPolicy policy = new CommerceEntitlementPolicy(
        	Name = 'SPAIN'
        );
        insert policy;
    
        WebStore webStore = new WebStore(Name='Spain');
        insert webStore;

		Product2 prod = new Product2(
        	Name = 'test',
            productCode = '1235',
            StockKeepingUnit = '12345'
        );
        insert prod;
        
        Account acc = new Account();
        acc = Account_TestDataFactory.createCustomer();
        acc.SAP_Id__c = '1234';
        insert acc;
    
    	WebCart cart = new WebCart(Name='Cart', WebStoreId=webStore.Id, AccountId=acc.Id,PoNumber='test');
        insert cart;
    
        Trigger_configuration__c triggerConf = new Trigger_configuration__c(Name = 'Porcelanosa', CurrencyIsoCode = 'EUR', Sales_Relationship__c = true);
        insert triggerConf;
        
    	Sales_Relationship__c salesRel = new Sales_Relationship__c( Name = 'Test sales' , Account_org__c = acc.Id, Distribution_Channel__c = '10' , Sales_Org__c = OrganizationCommons.ORG_AZURCERAMIQUE);
    	insert salesRel;
        

    }
    
    @isTest
    public static void NB2B_selectSalesRelJob_Test() {
        List<WebCart> listWC  = [SELECT Id from WebCart];
        WebCart wc = listWC[0];
        Test.startTest();
        List<Sales_Relationship__c> listsales= B2B_SapAccountingInfoController.getUserRoles(wc.Id);
        System.assertEquals(listsales.isEmpty(), false);
        Test.stopTest();
    }
    
}