force-app/main/default/objects/OppKitchen__c/OppKitchen__c.object-meta.xml
<CustomObject>
    <description>Additional information for kitchen opportunities. Originally designed for the US, but can (and will) be extended.</description>
    <label>Opportunity Kitchen</label>
    <nameField>
        <label>Kitchen Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Kitchens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppKitchen__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Kitchens</relationshipLabel>
    <relationshipName>OpportunityKitchens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppKitchen__c/fields/ProductLine2__c.field-meta.xml
<CustomField>
    <fullName>ProductLine2__c</fullName>
    <label>Product Line</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discontinued Lines</fullName>
            </value>
            <value>
                <fullName>Emotion</fullName>
            </value>
            <value>
                <fullName>Emotion Wardrobes</fullName>
            </value>
            <value>
                <fullName>Fusion Wardrobes</fullName>
            </value>
            <value>
                <fullName>New Project</fullName>
            </value>
            <value>
                <fullName>New Residence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppKitchen__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUALIFICATION</fullName>
                <default>true</default>
                <label>QUALIFICATION</label>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>RETAINER-RECEIVED</fullName>
            </value>
            <value>
                <fullName>DESIGN-PROPOSAL</fullName>
            </value>
            <value>
                <fullName>DEPOSIT-RECEIVED</fullName>
            </value>
            <value>
                <fullName>SHOP DRAWINGS</fullName>
            </value>
            <value>
                <fullName>DRAWINGS-SIGNED</fullName>
            </value>
            <value>
                <fullName>IN-PRODUCTION</fullName>
            </value>
            <value>
                <fullName>IN-TRANSIT</fullName>
            </value>
            <value>
                <fullName>ARRIVED</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>INSTALLATION</fullName>
            </value>
            <value>
                <fullName>PUNCH-LIST</fullName>
            </value>
            <value>
                <fullName>LOST</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataFactoryOppKitchen.cls
/**
* @author 		Ramón Prades
* @date 		February 2022
* @group 		Data factories
* @description 	Opp Facade
*/
public class DataFactoryOppKitchen {
    
    public static OppKitchen__c createRecords () {
        if (!Test.isRunningTest()) {
            return null;
        }

        // Opportunity
        testUtils.enableTriggers();
        Opportunity opp = DataFactoryOpportunity.createRetailOpportunities(1, 1)[0];
    
        // Kitchen
        OppKitchen__c k = new OppKitchen__c();
        k.Opportunity__c = opp.Id;
        k.Stage__c = TestUtils.getPicklistOption(OppKitchen__c.Stage__c);
        k.ProductLine2__c = TestUtils.getPicklistOption(OppKitchen__c.ProductLine2__c);
        insert k;

        return k;
    }

}