force-app/main/default/objects/PorcelanosaSetting__c/PorcelanosaSetting__c.object-meta.xml
<CustomObject>
    <description>Object to store configuration values as KEY, SUBKEY and VALUE.

For example, GOOGLE_KEY, UK, 102-343</description>
    <label>Porcelanosa Setting</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Porcelanosa Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Porcelanosa Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PorcelanosaSetting__c/fields/Subkey__c.field-meta.xml
<CustomField>
    <fullName>Subkey__c</fullName>
    <description>Secondary key of the record. Please use capitals.</description>
    <inlineHelpText>Secondary key of the record. Please use capitals.</inlineHelpText>
    <label>SUBKEY</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PorcelanosaSetting__c/fields/Value1__c.field-meta.xml
<CustomField>
    <fullName>Value1__c</fullName>
    <description>Setting value</description>
    <label>Value 1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PorcelanosaSettingTest.cls
/**
* @author 		Ramón Prades
* @date 		November 2022
* @group 		Settings
* @description  Class to handle system global settings
*/
@isTest public class PorcelanosaSettingTest {
    
    @testSetup public static void testSetup() {
        PorcelanosaSetting__c setting = new Porcelanosasetting__c();
        setting.key__c = 'TEST';
        setting.subkey__c = 'UK';
        setting.value1__c = 'HELLO';
        insert setting;
    }

    @isTest private static void test1() {
        PorcelanosaSetting setting = new PorcelanosaSetting('TEST', 'UK');
        System.assertEquals('HELLO', setting.value1, 'value should be hello');
    }

    @isTest private static void test2() {
        Boolean exr = false;
        try {
            PorcelanosaSetting setting = new PorcelanosaSetting('XXXXTEST', 'UK');
            System.assertNotEquals(setting, setting, 'Never should be here');
        } catch (ObjectNotFoundException onf) {
            exr = true;
        }
        System.assertEquals(true, exr, 'A exception should have been raised');
    }


}