force-app/main/default/objects/PorcelanosaSetting__c/PorcelanosaSetting__c.object-meta.xml
<CustomObject>
    <description>Object to store configuration values as KEY, SUBKEY and VALUE.

For example, GOOGLE_KEY, UK, 102-343</description>
    <label>Porcelanosa Setting</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Porcelanosa Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Porcelanosa Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PorcelanosaSetting__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PorcelanosaSetting__c/fields/Subkey__c.field-meta.xml
<CustomField>
    <fullName>Subkey__c</fullName>
    <description>Secondary key of the record. Please use capitals.</description>
    <inlineHelpText>Secondary key of the record. Please use capitals.</inlineHelpText>
    <label>SUBKEY</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PorcelanosaSetting__c/fields/Value1__c.field-meta.xml
<CustomField>
    <fullName>Value1__c</fullName>
    <description>Setting value</description>
    <label>Value 1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PorcelanosaSetting__c/fields/Value2__c.field-meta.xml
<CustomField>
    <fullName>Value2__c</fullName>
    <label>Value 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PorcelanosaSetting__c/fields/Value3__c.field-meta.xml
<CustomField>
    <fullName>Value3__c</fullName>
    <label>Value 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Default_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Organization__c</fullName>
    <description>La organización de ventas por defecto para el comercial</description>
    <inlineHelpText>The default sales organization for sales and distribution</inlineHelpText>
    <label>Default Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Execution_Context__c.field-meta.xml
<CustomField>
    <fullName>Execution_Context__c</fullName>
    <description>User&apos;s execution context</description>
    <label>Execution Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <label>DEUTSCHLAND</label>
            </value>
            <value>
                <fullName>ZA</fullName>
                <label>SOUTH AFRICA</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>DENMARK</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>UNITED STATES</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>FRANCE</label>
            </value>
            <value>
                <fullName>GB</fullName>
                <label>UNITED KINGDOM</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>SPAIN</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>POLAND</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>SWITZERLAND</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>ITALY</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>CANADA</label>
            </value>
            <value>
                <fullName>JP</fullName>
                <label>JAPAN</label>
            </value>
            <value>
                <fullName>VO</fullName>
                <label>VOID</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>BELGIUM</label>
            </value>
            <value>
                <fullName>PEXP</fullName>
                <label>PORCELANOSA EXPORT</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>AUSTRALIA</label>
            </value>
            <value>
                <fullName>SE</fullName>
                <label>SCANDINAVIA</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>ISRAEL</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>CHILE</label>
            </value>
            <value>
                <fullName>RD</fullName>
                <label>REPUBLICA DOMINICANA</label>
            </value>
            <value>
                <fullName>DEFAULT</fullName>
                <isActive>false</isActive>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>FLOWTESTUK</fullName>
                <isActive>false</isActive>
                <label>FLOWTESTUK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScriptWeeklyReportsUploadFiles.cls
/**
* @author Ivan Losilla
* @date April 2025
* @group Scripts
* @description Uploads Event management files
* @test ScriptWeeklyReportsUploadFilesTest
*/
global class ScriptWeeklyReportsUploadFiles implements Schedulable, Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
    public Boolean isTest = false;
    public String mailTest;
    public Date startDate;
    public Date endDate;
    public PorcelanosaSetting__c pSetting;
    public Map<String, String> resultBatch = new Map<String, String>();

    global void setStart(Date dt) {
        this.startDate = dt;
    }

    global void setEnd(Date dt) {
        this.endDate = dt;
    }

    global void setSetting(String pSettingId) {
        this.pSetting = [select id,Description__c, Key__c, IsActive__c,Subkey__c, Value1__c, Value2__c, Value3__c  from PorcelanosaSetting__c where Id =: pSettingId];
        if (this.pSetting.Value2__c != null) {
            this.isTest = true;
            this.mailTest = this.pSetting.Value2__c;
        }
    }

    global ScriptWeeklyReportsUploadFiles(Id pSettingId) {
        this.pSetting = [select id,Description__c, Key__c, IsActive__c,Subkey__c, Value1__c, Value2__c, Value3__c  from PorcelanosaSetting__c where Id =: pSettingId];

        if (this.startDate == null || this.endDate == null) {
            Date today = Date.today();
            Date thisMonday = today.toStartOfWeek();
            this.startDate = thisMonday;
            this.endDate = this.startDate.addDays(6);
        }

        if (this.pSetting.Value2__c != null) {
            this.isTest = true;
            this.mailTest = this.pSetting.Value2__c;
        }
    }

    global void execute(System.SchedulableContext context) {
        if (this.pSetting != null && this.pSetting.IsActive__c) {
            Database.executeBatch(new ScriptWeeklyReportsUploadFiles(pSetting.Id), 1); // UNO por UNO
        }
        
    }

    global void execute(Database.BatchableContext bc, List<User> scope) {
        try {
            Map<String, String> result = ReportsHelper.uploadReports(this.startDate, this.endDate, String.valueOf(scope[0].Id));
            if (result.containsKey('SENT') && result.get('UPLOAD') == 'TRUE') {
                this.resultBatch.put(scope[0].email, 'FILE PATH: ' + result.get('PATH') + ' - ' + result.get('REGISTERS') + ' MANAGED' );
            }
        } catch (Exception ex) {
            //this.hasException = true;
            //this.logger.addError(ex);
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        List<String> salesOrgs = new List<String>();
        if (this.pSetting != null && this.pSetting.IsActive__c == true && this.pSetting.Value1__c != null) {
            if (this.pSetting.Value3__c != null) {
                salesOrgs = this.pSetting.Value3__c.split(';');

                return Database.getQueryLocator([
                    SELECT Id, Email, LanguageLocaleKey,TimeZoneSidKey, profile.name, execution_context__c
                    FROM User 
                    WHERE isactive = true and execution_context__c =: this.pSetting.Value1__c AND Default_Sales_Organization__c IN : salesOrgs AND  profile.Name IN ('Managers', 'Standard Trade')
                ]);
            } 

            // All Sales Orgs
            return Database.getQueryLocator([
                SELECT Id, Email, LanguageLocaleKey,TimeZoneSidKey, profile.name, execution_context__c
                FROM User 
                WHERE isactive = true and execution_context__c =: this.pSetting.Value1__c AND  profile.Name IN ('Managers', 'Standard Trade')
            ]);
        }
        return Database.getQueryLocator([
            SELECT Id, TimeZoneSidKey FROM User 
            WHERE Name = 'PATATINPATATAN'
        ]);
    }
    
    global void finish(Database.BatchableContext bc){
    }

    @testVisible public static String testFiller() {
        String s = 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        s += 'Lorem ipsum';
        return s;
    }
}