force-app/main/default/objects/SystemSettings__c/SystemSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Systemwide settings</description>
    <label>System Settings</label>
</CustomObject>

force-app/main/default/objects/SystemSettings__c/fields/SAPAPI__c.field-meta.xml
<CustomField>
    <fullName>SAPAPI__c</fullName>
    <description>URL del Api Manager (proxy) de SAP CPI</description>
    <label>SAP API</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/SAPCPIAPIKey__c.field-meta.xml
<CustomField>
    <fullName>SAPCPIAPIKey__c</fullName>
    <description>API key to access the salesforce API</description>
    <label>SAP CPI API Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StorageAPIHelperTest.cls
@isTest public class StorageAPIHelperTest {

    @testSetup static void testSetup() {
        SystemSettings__c ss = SystemSettings.getSystemSettings();
        ss.SAPAPI__c = 'https:/dymmy-ai.com/';
        ss.SAPCPIAPIKey__c = '321321321321';
        Database.Upsert(ss);
    }

    @isTest static void testConstructorError() {
        Boolean exc = false;
        try {
            StorageAPIHelper helper = new StorageAPIHelper('dummy');  
            Assert.IsNull(helper, 'No storage api class should have been created');
        } catch(Exception ex) {
            exc = String.isNotBlank(ex.getMessage());
        }
        Assert.isTrue(exc, 'An exception was expected');
    }

    @isTest static void testDir() {
        SAPCPIProxyTest.Mocker mocker = new SAPCPIProxyTest.Mocker();
        mocker.customResponse = '{"folder": "/processed","totalItems": 10,"items": []}';
        Test.setMock(HttpCalloutMock.class, mocker);
        Test.startTest();
        StorageAPIHelper helper = new StorageAPIHelper('mbank');            
        StorageAPIHelper.DirectoryDTO dto = helper.dir('/');
        Assert.isTrue(dto.items.size() == 0, 'No items expected');
    }

    @isTest static void testRead() {
        SAPCPIProxyTest.Mocker mocker = new SAPCPIProxyTest.Mocker();
        mocker.customResponse = '123';
        Test.setMock(HttpCalloutMock.class, mocker);
        Test.startTest();
        StorageAPIHelper helper = new StorageAPIHelper('mbank');            
        String content = helper.readTextFile('inbox/test.txt');
        Assert.isNotNull(content, 'COntent cannot be null');
    }

    @isTest static void testMove() {
        SAPCPIProxyTest.Mocker mocker = new SAPCPIProxyTest.Mocker();
        mocker.customResponse = '123';
        Test.setMock(HttpCalloutMock.class, mocker);
        Test.startTest();
        StorageAPIHelper helper = new StorageAPIHelper('mbank');            
        helper.moveFile('inbox/test.txt', 'dummy/folder');
        Assert.isTrue(true);
    }

}