force-app/main/default/objects/SystemSettings__c/SystemSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Systemwide settings</description>
    <label>System Settings</label>
</CustomObject>

force-app/main/default/objects/SystemSettings__c/fields/AdminProfiles__c.field-meta.xml
<CustomField>
    <fullName>AdminProfiles__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>List of profiles of system administrators (for business rules)</description>
    <label>Administrator Profiles</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/AIModel__c.field-meta.xml
<CustomField>
    <fullName>AIModel__c</fullName>
    <description>Default AI model</description>
    <label>AI Model</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/CPDeletionTime__c.field-meta.xml
<CustomField>
    <fullName>CPDeletionTime__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Time in hours before the system deletes custom projects with no files attached (0=Disabled)</description>
    <inlineHelpText>Time in hours before the system deletes custom projects with no files attached (0=Disabled)</inlineHelpText>
    <label>CP Deletion Time (hours)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/CPNotificationsEnabled__c.field-meta.xml
<CustomField>
    <fullName>CPNotificationsEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Custom Projects email notifications enabled</inlineHelpText>
    <label>CP Enable Notifications</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/DefaultUSAMethodOwner__c.field-meta.xml
<CustomField>
    <fullName>DefaultUSAMethodOwner__c</fullName>
    <description>Default owner for the USA assignation method</description>
    <label>Default USA Assign Owner</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/DevFeatures__c.field-meta.xml
<CustomField>
    <fullName>DevFeatures__c</fullName>
    <description>List of features under development</description>
    <inlineHelpText>List delimited with &quot;;&quot;</inlineHelpText>
    <label>DevFeatures</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/DummyProduct__c.field-meta.xml
<CustomField>
    <fullName>DummyProduct__c</fullName>
    <description>SAP code of the dummy products</description>
    <inlineHelpText>SAP code of the dummy products</inlineHelpText>
    <label>Dummy Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/GenericUsers__c.field-meta.xml
<CustomField>
    <fullName>GenericUsers__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Generic Users Id (Magento user, API user, etc.)</description>
    <label>GenericUsers</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/MaterialBankPricebook__c.field-meta.xml
<CustomField>
    <fullName>MaterialBankPricebook__c</fullName>
    <inlineHelpText>Pricebook to use to convert material bank leads</inlineHelpText>
    <label>Material Bank Pricebook</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/SAPAPI__c.field-meta.xml
<CustomField>
    <fullName>SAPAPI__c</fullName>
    <description>URL del Api Manager (proxy) de SAP CPI</description>
    <label>SAP API</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/SapConnectionDown__c.field-meta.xml
<CustomField>
    <fullName>SapConnectionDown__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, everything related to send info to sap is disabled.</description>
    <label>Sap Connection Down</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/SAPCPI__c.field-meta.xml
<CustomField>
    <fullName>SAPCPI__c</fullName>
    <description>URL de SAP CPI</description>
    <label>SAP CPI</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/SAPCPIAPIKey__c.field-meta.xml
<CustomField>
    <fullName>SAPCPIAPIKey__c</fullName>
    <description>API key to access the salesforce API</description>
    <label>SAP CPI API Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/SAPCPIInstance__c.field-meta.xml
<CustomField>
    <fullName>SAPCPIInstance__c</fullName>
    <description>Name of this instance in SAP CPI</description>
    <label>SAP CPI Instance</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/SAPDispatcherEnabled__c.field-meta.xml
<CustomField>
    <fullName>SAPDispatcherEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enables the SAP Dispatcher to send orders to SAP. Should TRUE unless there&apos;s a good reason</description>
    <label>Enable SAP Request Dispatcher</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/USAppointmentSubtype__c.field-meta.xml
<CustomField>
    <fullName>USAppointmentSubtype__c</fullName>
    <label>US Appointment Subtype</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/USClaimsManager__c.field-meta.xml
<CustomField>
    <fullName>USClaimsManager__c</fullName>
    <description>Email of then US claims manager</description>
    <inlineHelpText>Email of then US claims manager</inlineHelpText>
    <label>USClaimsManager</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/USFacadeManagerMail__c.field-meta.xml
<CustomField>
    <fullName>USFacadeManagerMail__c</fullName>
    <description>E-Mail of the US facade manager. A copy of all new facade projects will be sent to this emial in CC</description>
    <label>US Facade Manager Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/USNotifyWebLeads__c.field-meta.xml
<CustomField>
    <fullName>USNotifyWebLeads__c</fullName>
    <defaultValue>false</defaultValue>
    <label>US Notify Web Leads</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SystemSettings.cls
/**
 * Author           Ramón prades
 * Description      Retrieves system settings (stored in custom setting SystemSettings__c)
 * Date             May 2020
 * History              
 */
public with sharing class SystemSettings {

    // Public properties
    public static Boolean CPNotificationsEnabled { get; set; }
    public static Boolean USNotifyWebLeads { get; set; }
    public static String USClaimsManager { get; set; }
    public static Integer CPDeletionTime { get; set; }
    public static String adminProfiles { get; set; }
    public static String genericUsers { get; set; }    
    public static String DummyProduct { get; set; }    
    public static String materialBankPricebook { get; set; }    
    public static String USDefaultOwner { get; set; }    
    public static Boolean SAPConnectionDown { get; set; }
    public static String USFacadeManagerMail {get; set;}    
    public static String USAppointmentSubtype {get; set;}    
    public static String SAPCPIUrl {get; set;}    
    public static String SAPAPIUrl {get; set;}    
    public static String SAPCPIInstance {get; set;}    
    public static String SAPCPIAPIKey {get; set;}
    public static String AIModel {get; set;}
    public static Boolean SAPDispatcherEnabled {get; set;}

    private static SystemSettings__c systemSettings = null;
    
    /**
     * Class constructor
     */
    static {
        getSystemSettings();
        CPNotificationsEnabled = systemSettings.CPNotificationsEnabled__c;
        CPDeletionTime = (Integer) systemSettings.CPDeletionTime__c;
        USClaimsManager = systemSettings.USClaimsManager__c;
        adminProfiles = systemSettings.AdminProfiles__c;
        genericUsers = systemSettings.GenericUsers__c;
        dummyProduct = systemSettings.DummyProduct__c;
        USNotifyWebLeads = systemSettings.USNotifyWebLeads__c;
        materialBankPricebook = systemSettings.MaterialBankPricebook__c;
        USDefaultOwner = systemSettings.DefaultUSAMethodOwner__c;
        SAPConnectionDown = systemSettings.SapConnectionDown__c;
        USFacadeManagerMail = systemSettings.USFacadeManagerMail__c;
        USAppointmentSubtype = systemSettings.USAppointmentSubtype__c;
        SAPCPIUrl = systemSettings.SAPCPI__c;
        SAPAPIUrl = systemSettings.SAPAPI__c;
        SAPCPIInstance = systemSettings.SAPCPIInstance__c;
        SAPCPIAPIKey = systemSettings.SAPCPIAPIKey__c;
        AIModel = systemSettings.AIModel__c;
        SAPDispatcherEnabled = systemSettings.SAPDispatcherEnabled__c;
    }

    public static String dummyProducts {
        get {
            return getSystemSettings().DummyProduct__c;
        }
    }

    public static Boolean underDevelopment(String feature) {
        SystemSettings__c settings =  getSystemSettings();
        try {
            String devFeatures = settings.DevFeatures__c.toUpperCase();
            return (devFeatures.contains(feature.toUpperCase() + ';'));
        } catch (NullPointerException ex) {
            return false;
        }
    }

    public static Boolean sapConnectionDown() {
        return getSystemSettings().SapConnectionDown__c;
    }

    @testvisible
    private static SystemSettings__c getSystemSettings() {
		if (systemSettings == null) {
            systemSettings = SystemSettings__c.getOrgDefaults();
            if (systemSettings == null || systemSettings.AdminProfiles__c	== null) {
                setDefaultSettings();
            }
        } 
        return systemSettings;
    } // getSystemSettings

    @testvisible    
    private static void setDefaultSettings() {
        // By default sets Neoris configuration
        String value = [SELECT Id FROM Profile WHERE Name =: Label.System_Administrator LIMIT 1].Id;
        String valueGeneric = [SELECT Id FROM User WHERE Name LIKE '%API%' LIMIT 1].Id;
        systemSettings.AdminProfiles__c = value;		        
        systemSettings.GenericUsers__c = valueGeneric;
        systemSettings.SAPDispatcherEnabled__c = true;
        if (Test.isRunningTest()) {
            Pricebook2[] books = [select Id from Pricebook2];
            if (books.size() > 0) {
                systemSettings.materialBankPricebook__c = books[0].Id;
            }
            systemSettings.CPDeletionTime__c = 16;
            systemSettings.DummyProduct__c = '999999999';
        }        
        saveSystemSettings(systemSettings);
    } // setDefaultSettings

    @testVisible
    private static void saveSystemSettings(SystemSettings__c settings) {
        Database.insert(settings);
    } // saveSystemSettings

    
} // Class