force-app/main/default/objects/Moodboard__c/Moodboard__c.object-meta.xml
<CustomObject>
    <description>Object created to have Moodboard Info</description>
    <label>Moodboard</label>
    <nameField>
        <label>Moodboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moodboards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Moodboard__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if it&apos;s a default moodboard, created with the opportunity</description>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Moodboard__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Moodboards</relationshipLabel>
    <relationshipName>Moodboards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Moodboard__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <description>Url to the moodboard website</description>
    <label>Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/MoodboardsSelector.cls
/**
* @author 		Ivan Losilla
* @date 		August 2022
* @group 		Moodboards
* @description 	moodboards selector class
*/
public class MoodboardsSelector extends zflib_SObjectSelector  {
    public Schema.SObjectType getSObjectType(){
        return Moodboard__c.sObjectType;
    }

    public List<Moodboard__c> selectById(Set<Id> recordIds){
        return (List<Moodboard__c>) selectSObjectsById(recordIds);
    }

    public Moodboard__c selectById(Id recordId){
        List<Moodboard__c> listMoodboards = (List<Moodboard__c>) selectSObjectsById(new Set<Id>{recordId});
        if (listMoodboards.size() == 1) {
            return listMoodboards[0];
        }
        return null;
    }
   
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            
            // Main info fields
            Moodboard__c.Id,
            Moodboard__c.CurrencyIsoCode,
            Moodboard__c.Name,

            // Other info fields
            Moodboard__c.IsDefault__c,
            Moodboard__c.Opportunity__c,
            Moodboard__c.Url__c,

            // Admin fields
            Moodboard__c.CreatedById
        };
    }
}