force-app/main/default/objects/Lead/fields/Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Account_Classification__c</fullName>
    <label>Account Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Building company</fullName>
            </value>
            <value>
                <fullName>Architectural firm</fullName>
            </value>
            <value>
                <fullName>Brand/Chain/Franchise</fullName>
                <label>Brand/Franchise</label>
            </value>
            <value>
                <fullName>Construction company</fullName>
            </value>
            <value>
                <fullName>Custom home builder</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
                <label>Developer/investor</label>
            </value>
            <value>
                <fullName>Engineering consultant</fullName>
            </value>
            <value>
                <fullName>Facade consultant</fullName>
            </value>
            <value>
                <fullName>Fit-out company (commercial contract)</fullName>
            </value>
            <value>
                <fullName>Franchisee</fullName>
            </value>
            <value>
                <fullName>Interior design firm</fullName>
            </value>
            <value>
                <fullName>Kitchen instalation company</fullName>
            </value>
            <value>
                <fullName>Plumbing company</fullName>
            </value>
            <value>
                <fullName>Procurement company / Quantity surveyor</fullName>
            </value>
            <value>
                <fullName>Public administration</fullName>
            </value>
            <value>
                <fullName>Tile instalation company</fullName>
            </value>
            <value>
                <fullName>Other (indicate)</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>National House Builders</fullName>
            </value>
            <value>
                <fullName>Private customer</fullName>
            </value>
            <value>
                <fullName>Fabricator</fullName>
                <label>Fabricator/Stonemason</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Lead Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Email__c.field-meta.xml
<CustomField>
    <fullName>Business_Email__c</fullName>
    <label>Business Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>XXX Lead Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>America</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bissau</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>Operation_Type__c</fullName>
    <label>Operation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Refurbishment</fullName>
            </value>
            <value>
                <fullName>New construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Opportunity_Classification__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Classification__c</fullName>
    <label>Opportunity Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Health care</fullName>
            </value>
            <value>
                <fullName>Hotels and other hospitality</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Public building</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Residential (Retail)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Opportunity_Classification_II__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Classification_II__c</fullName>
    <label>Opportunity Classification II</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Opportunity_Classification__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Car dealership</fullName>
            </value>
            <value>
                <fullName>Cinema</fullName>
            </value>
            <value>
                <fullName>Clothing store</fullName>
            </value>
            <value>
                <fullName>Financial institutions</fullName>
            </value>
            <value>
                <fullName>Multi-unit</fullName>
            </value>
            <value>
                <fullName>Other store</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Shopping centre/Mall/Leisure center</fullName>
            </value>
            <value>
                <fullName>Single-family home</fullName>
            </value>
            <value>
                <fullName>Sports center</fullName>
            </value>
            <value>
                <fullName>Supermarket</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Project Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Porcelanosa</businessProcess>
    <label>Lead</label>
</RecordType>

force-app/main/default/classes/Lead_TestDataFactory.cls
@isTest
public class Lead_TestDataFactory {
    public static List<Lead> createLeads(Integer records, Map<String, Object> fieldsToAdd){
        
        List<Lead> leadList = new List<Lead>();
        
        Integer alreadyCreated = [SELECT COUNT() FROM Lead WHERE Company LIKE '%testLead'];
        Integer newIndex;
        
        for(Integer i=0; i<records; i++){
            
            newIndex = i + alreadyCreated;
            
            Lead leadToAdd = new Lead(Company = newIndex+'testLead', Status = 'New', Opportunity_Name__c = 'OppName'+newIndex, 
                                      Operation_Type__c = 'Refurbishment', Close_Date__c = Date.today(),
                                      Opportunity_Classification__c = 'Commercial', Opportunity_Classification_II__c = 'Car dealership',
                                      Country__c = 'United Kingdom', City__c = 'Bristol', Address__c = 'Street Name '+newIndex, Postcode__c = 'BS1 3NZ', 
                                      Account_Classification__c = 'Architectural firm', Business_Email__c = 'mail'+newIndex+'@mail.com',
                                      CountryCode = 'GB', Street = 'Street Name '+newIndex, City = 'Bristol', PostalCode = 'BS1 3NZ',
                                      StateCode = 'AB', LastName = 'Contact Last Name ' + newIndex, FirstName = 'Contact First Name ' + newIndex, Salutation = 'Mr.');
            
            for(String fieldName: fieldsToAdd.keySet()){
                if(fieldName == 'Company'){
                    leadToAdd.put(fieldName, (String) fieldsToAdd.get(fieldName));
                }
            }
            
            leadList.add(leadToAdd);
            
        }        
        
        return leadList;
    }
}