force-app/main/default/objects/Lead/fields/LeadSubtype__c.field-meta.xml
<CustomField>
    <fullName>LeadSubtype__c</fullName>
    <inlineHelpText>Please enter here the origin of the lead (i.e. Sale January 2020)</inlineHelpText>
    <label>Lead Subtype</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact Form</fullName>
            </value>
            <value>
                <fullName>PDF Guide Download</fullName>
            </value>
            <value>
                <fullName>US Material Bank</fullName>
            </value>
            <value>
                <fullName>EU Material Bank</fullName>
            </value>
            <value>
                <fullName>Course Request</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Book an Appointment</fullName>
            </value>
            <value>
                <fullName>Google Ad</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
            <value>
                <fullName>US Register Form</fullName>
            </value>
            <value>
                <fullName>Business Trip</fullName>
            </value>
            <value>
                <fullName>Contact Form;Contact Form</fullName>
                <isActive>false</isActive>
                <label>Contact Form;Contact Form</label>
            </value>
            <value>
                <fullName>Showroom Appointment</fullName>
                <isActive>false</isActive>
                <label>Showroom Appointment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Project Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CountryCode__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>USStates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Porcelanosa</businessProcess>
    <label>Lead</label>
</RecordType>

force-app/main/default/classes/NBK_webAppointmentEmailComercial.cls
/**
 * @description  :
 * @author       : Nubika Team <example@nubika.com>
 * @version      : 1.0.0
 * @date         : 13-11-2023
 * @group        :
 * @see          :
**/
public class NBK_webAppointmentEmailComercial {

	@InvocableMethod(callout=true label='Send Appointment Email Comercial')
	public static void execute(List<LeadInfo> leadInfo){
			try{
					if(!leadInfo.isEmpty()){
							if(leadInfo[0].leadId != null){
									//recuperar Lead con id por parametro
									List<Lead> listLeads = [SELECT Id,Opportunity_Name__c,FirstName,LastName,Title,Company,
																									MobilePhone,Email,Status,LeadSource,Owner.Email,Owner.Name,Owner.Id,Owner.FirstName,LeadType__c,LeadSubtype__c,
																									Postcode__c,City__c,State__c,Description
																							FROM Lead
																									WHERE Id =: leadInfo[0].leadId];

									if(listLeads != null && !listLeads.isEmpty()){
											Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
											EmailTemplate template = new EmailTemplate();
											template = [SELECT Id, Name, Subject, HtmlValue
															FROM EmailTemplate
															WHERE developername = 'NBK_AppointmentComercial' LIMIT 1];

											String HTMLbody = template.HtmlValue;

											//FECHA Y HORA CONVERSION
											DateTime dt = DateTime.valueOf(leadInfo[0].fechaHoraS);
											String fechaConvert = String.valueOf(dt.format('MM/dd/YYYY'));

											String mailBody;
											mailBody = getLeadBody(listLeads[0]);
											String body = '<p>Dear ' + listLeads[0].Owner.FirstName + ', you have a new appointment from our website</p>' +
											+ '<p>Please review the details below and follow the link to go to the CRM.</p>'
											+ '<p>WEB APPOINTMENT scheduled by a new Lead at '+fechaConvert+'</p>'
											+ mailBody +
											+ '<p>Thank you,</p>'
											+ '<p>CRM Team<br/>Porcelanosa USA</p>';

											HTMLbody = HTMLbody.replace('((body))', body);

											list<String> toAdresses = new list<String>();
											toAdresses.add(listLeads[0].Owner.Email);

											email.setSubject('New Web Appointment Scheduled at '+fechaConvert);
											email.setToAddresses(toAdresses);
											email.setHtmlBody(HTMLbody);
											//List<OrgWideEmailAddress> orgs = [SELECT Id FROM OrgWideEmailAddress WHERE DisplayName = 'Appointment'];
											List<OrgWideEmailAddress> orgs = [SELECT Id FROM OrgWideEmailAddress WHERE DisplayName = 'Salesforce CRM'];
											if(!orgs.isEmpty()){
													email.setOrgWideEmailAddressId(orgs[0].Id);
											}
											 email.setTargetObjectId(UserInfo.getUserId());
											email.setTreatTargetObjectAsRecipient(false);
											Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
											System.debug('Send Email end');

									}
							}
					}
			}catch(Exception ex){
					System.debug('ERROR EN SENDEMAIL: '+ex.getMessage());
					Logger.error('[APPOINTMENT_MANAGER_SEND_EMAIL_COMERCIAL]: ' + ex.getMessage());
					Logger.saveLog();
			}

	}

	public static String getLeadBody(Lead lead) {
			String url =  URL.getOrgDomainUrl().toExternalForm() + '/' + lead.Id;

			String description = '';
			if (String.isNotEmpty(lead.Description)) {
					description = lead.Description.replace('\n', '<br/>');
			}
			Map<String, String> m = new Map<String, String>();
			m.put('Lead Name', '<a href="' + url + '">' + lead.Opportunity_Name__c + '</a>');
			m.put('Name', lead.FirstName + ' ' + lead.LastName);
			//m.put('Title', lead.Title);
			//m.put('Company', lead.Company);
			m.put('Phone', lead.MobilePhone);
			m.put('EMail', lead.Email);
			m.put('Status', lead.Status);
			m.put('Source', lead.LeadSource);
			m.put('Owner', lead.owner.Name);
			m.put('Type', lead.LeadType__c);
			m.put('Subtype', lead.LeadSubtype__c);
			m.put('Location', lead.Postcode__c + ' ' + lead.City__c + ' (' + lead.State__c + ')');
			m.put('Description', description);
			String table = MailUtils.mapToTable(m, 'width:700px;,border: 1px solid;');

			return table;
	}

	public class LeadInfo {
			@InvocableVariable
			public Id leadId;
			@InvocableVariable
			public String fechaHoraS;
	}

}