force-app/main/default/objects/Installer__c/Installer__c.object-meta.xml
<CustomObject>
    <description>Define accounts that can act as installers in a sales organisation</description>
    <label>Installer</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Installer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Installer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installers</relationshipLabel>
    <relationshipName>Installers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installer__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/countryCode__c.field-meta.xml
<CustomField>
    <fullName>countryCode__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Default Sales Org of the User who created the Opportunity</description>
    <label>Sales Org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <description>Code of the Sales Org</description>
    <externalId>true</externalId>
    <label>Sales Org</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/InstallationFlowHelperTest.cls
@isTest
private class InstallationFlowHelperTest {
    
     @testSetup static void setup() {
		TestUtils.enableTriggers();
     }
    
    @isTest static void test_getInstallers_B() {   
        DataFactoryAccount.autoInsert = true;    
        
        User user = DataFactoryUser.createUKUsers(1)[0];
        user.Sales_Org__c = OrganizationCommons.ORG_NORTH_WEST;

        List<Account> accounts = DataFactoryAccount.createPersonAccounts(1);
        Opportunity opp  = DataFactoryOpportunity.createRetailOpportunities(accounts, 1)[0];   
		    opp.countryCode__c = 'GB';
        opp.Postcode__c = 'LS9 9EE';
        opp.OwnerId = user.Id;
        update opp;

        List<Installer__c> ins = new List<Installer__c>();
        Account[] accs = DataFactoryAccount.createAccounts(2);
        Account acc1 = accs[0];
        Account acc2 = accs[1];
        ins.add(new Installer__c(SalesOrg__c = OrganizationCommons.ORG_SOUTH_EAST, Account__c = acc1.Id));
        ins.add(new Installer__c(SalesOrg__c = OrganizationCommons.ORG_NORTH_WEST, Account__c = acc1.Id));
        ins.add(new Installer__c(SalesOrg__c = OrganizationCommons.ORG_NORTH_WEST, Account__c = acc2.Id));
        ins.add(new Installer__c(SalesOrg__c = OrganizationCommons.ORG_YORKSHIRE, Account__c = acc2.Id));
        insert ins;
        
        List<String> opps = new List<String>();
        opps.add(opp.id);
        List<FlowListType> results = InstallationFlowHelper.getInstallers(opps);
        System.assertEquals(2, results[0].size, 'One installer should have been found');
    }        

}