force-app/main/default/objects/Opportunity/fields/Company_Date__c.field-meta.xml
<CustomField>
    <fullName>Company_Date__c</fullName>
    <label>Company Date</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>company_list</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Classification__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Classification__c</fullName>
    <label>Opportunity Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
                <isActive>false</isActive>
                <label>Education</label>
            </value>
            <value>
                <fullName>Health care</fullName>
                <label>Healthcare</label>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Institutional</fullName>
            </value>
            <value>
                <fullName>Mixed Use Development</fullName>
                <isActive>false</isActive>
                <label>Mixed Use Development</label>
            </value>
            <value>
                <fullName>Office</fullName>
                <label>Office/Corporate</label>
            </value>
            <value>
                <fullName>Other (indicate)</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>Transport stations</fullName>
                <label>Other Transport stations</label>
            </value>
            <value>
                <fullName>Public building</fullName>
                <isActive>false</isActive>
                <label>Public building</label>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Residential (Retail)</fullName>
            </value>
            <value>
                <fullName>Retail Store</fullName>
            </value>
            <value>
                <fullName>Samples Ecommerce</fullName>
            </value>
            <value>
                <fullName>Senior living</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Classification_II__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Classification_II__c</fullName>
    <label>Opportunity Classification II</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Opportunity_Classification__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Car dealership</fullName>
            </value>
            <value>
                <fullName>Casinos</fullName>
            </value>
            <value>
                <fullName>Cinema</fullName>
            </value>
            <value>
                <fullName>Clothing store</fullName>
            </value>
            <value>
                <fullName>Cruise</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Financial institutions</fullName>
                <label>Financial institutions/Banks</label>
            </value>
            <value>
                <fullName>Fitness Club</fullName>
            </value>
            <value>
                <fullName>Government/ Public Building</fullName>
            </value>
            <value>
                <fullName>Hotels</fullName>
            </value>
            <value>
                <fullName>Multi-unit</fullName>
            </value>
            <value>
                <fullName>Museum</fullName>
            </value>
            <value>
                <fullName>Other store (indicate)</fullName>
                <label>Other store</label>
            </value>
            <value>
                <fullName>Religious Buildings</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Roll Out</fullName>
            </value>
            <value>
                <fullName>Shopping centre/Mall/Leisure center</fullName>
            </value>
            <value>
                <fullName>Single-family home</fullName>
            </value>
            <value>
                <fullName>Single Location</fullName>
            </value>
            <value>
                <fullName>Sports center</fullName>
                <label>Sports Arena</label>
            </value>
            <value>
                <fullName>Supermarket</fullName>
                <label>Supermarket/Grocery Stores</label>
            </value>
            <value>
                <fullName>Theaters/Cinema</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Request_Store_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Request_Store_Appointment__c</fullName>
    <label>Request Store Appointment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Office_Date__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office_Date__c</fullName>
    <label>Sales Office Date</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org_Date__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Date__c</fullName>
    <label>Sales Org Date</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Oportunidad_neoris.recordType-meta.xml
<RecordType>
    <fullName>Oportunidad_neoris</fullName>
    <active>true</active>
    <businessProcess>Proceso Oportunidad Porcelanosa</businessProcess>
    <label>Oportunidad_Neoris</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Project_retail.recordType-meta.xml
<RecordType>
    <fullName>Project_retail</fullName>
    <active>true</active>
    <businessProcess>Sales process retail</businessProcess>
    <label>Project retail</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Project_trade.recordType-meta.xml
<RecordType>
    <fullName>Project_trade</fullName>
    <active>true</active>
    <businessProcess>Sales process trade</businessProcess>
    <label>Project trade</label>
</RecordType>

force-app/main/default/objects/Trigger_configuration__c/Trigger_configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>For Trigger configuration, to set on/off trigger fire events.</description>
    <label>Trigger Configuration</label>
</CustomObject>

force-app/main/default/globalValueSets/company_list.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>207</fullName>
        <label>EUROCERAMIQUE SARL</label>
    </customValue>
    <customValue>
        <fullName>208</fullName>
        <label>PORCELANOSA PARIS IDF</label>
    </customValue>
    <customValue>
        <fullName>210</fullName>
        <label>SOCAMED SARL</label>
    </customValue>
    <customValue>
        <fullName>218</fullName>
        <label>PORCELANOSA OUEST SAS</label>
    </customValue>
    <customValue>
        <fullName>219</fullName>
        <label>PORCELANOSA SUD-OUEST</label>
    </customValue>
    <customValue>
        <fullName>502</fullName>
        <label>PORCELANOSA SOUTHEAST LTD</label>
    </customValue>
    <customValue>
        <fullName>504</fullName>
        <label>PORCELANOSA NORTHWEST LTD</label>
    </customValue>
    <customValue>
        <fullName>505</fullName>
        <label>PORCELANOSA MIDLANDS LTD</label>
    </customValue>
    <customValue>
        <fullName>506</fullName>
        <label>PORCELANOSA SCOTLAND LTD</label>
    </customValue>
    <customValue>
        <fullName>507</fullName>
        <label>PORCELANOSA WESTERN LTD</label>
    </customValue>
    <customValue>
        <fullName>508</fullName>
        <label>PORCELANOSA YORKSHIRE LTD</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <label>PORCELANOSA GRUPO</label>
    </customValue>
    <customValue>
        <fullName>201</fullName>
        <label>PORCELANOSA GROUPE SAS</label>
    </customValue>
    <masterLabel>company_list</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Opportunity_TestDataFactory.cls
@isTest
public class Opportunity_TestDataFactory {
    @testSetup static void setup() {
    
    	// Los triggers usan la custom setting "Trigger_configuration__c" para saber si ejecutar las validaciones.
        // Como desde adentro de un test no se puede ver la instacia de "Trigger_configuration__c" hay que insertar una
        // para activar el trigger.
        insert TriggerConfiguration_TestDataFactory.createCustomSetting_ActivatedTriggers();
    
    }

    public static Opportunity createEcommerce(Account acc) {
        //insert_SalesOrg_DistChannel();
        
        Id RecordTypeIdOpportunity = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Oportunidad_neoris').getRecordTypeId();
        System.debug('RecordTypeIdOpportunity:'+ RecordTypeIdOpportunity);
        //Account a = new Account(Name='For Opportunity ecommerce');
		//insert a;
        
        Opportunity o = new Opportunity(Name= 'Test Opportunity ecommerce 1', RecordTypeId= RecordTypeIdOpportunity, 
                                        AccountId= acc.Id, StageName = 'New', CloseDate= Date.today().addDays(30), Opportunity_Classification__c = 'Airport');
        
        return o;
    }

    public static Opportunity createTrade(Account acc) {
        //insert_SalesOrg_DistChannel();
        
        Id RecordTypeIdOpportunity = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Project_trade').getRecordTypeId();
        //Account a = new Account(Name='For Opportunity trade');
		//insert a;
        
        Opportunity o = new Opportunity(Name= 'Test Opportunity trade', RecordTypeId=RecordTypeIdOpportunity, AccountId= acc.Id, 
                                        StageName = 'New', CloseDate= Date.today().addDays(30), Opportunity_Classification__c = 'Airport');
        return o;
    }
    
    public static Opportunity createRetail() {
        //insert_SalesOrg_DistChannel();
        
        Account account = Account_TestDataFactory.createRetailer();
        //insert account;
        
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true;
		dml.DuplicateRuleHeader.runAsCurrentUser = true;

        Database.SaveResult sr = Database.insert(account, dml);
        Opportunity o;
        
        if (sr.isSuccess()) {
            System.debug('Duplicate account has been inserted in Salesforce!');
            
            Id RecordTypeIdOpportunity = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Project_retail').getRecordTypeId();
            o = new Opportunity(Name= 'Test Opportunity retail', RecordTypeId=RecordTypeIdOpportunity, AccountId= account.Id, 
                                            StageName = 'New', CloseDate= Date.today().addDays(30), Opportunity_Classification__c = 'Residential (Retail)');
        }
        return o;
    }
    
    // to create Opportunities that requested a date yesterday
    public static List<Opportunity> createOppsWithReqDate(Integer numOpps, Date requestedDate) {
        //insert_SalesOrg_DistChannel();
        
        List<Opportunity> opportunityList = new List<Opportunity>();
        
        for(Integer i=0; i<numOpps; i++) {            
            Opportunity opportunity = createRetail();
            opportunity.Company_Date__c = OrganizationCommons.SOC_EUROCERAMIQUE;
            opportunity.Sales_Org_Date__c = OrganizationCommons.ORG_AZURCERAMIQUE;
            opportunity.Sales_Office_Date__c = '3015';
            opportunity.Request_Store_Appointment__c = requestedDate;
            opportunityList.add(opportunity);
        }
        
        
        
        return opportunityList;
        
    }
    
    public static List<Opportunity> createOpportunities(Integer numOpps, Map<String, Object> fieldsToAdd) {
        //insert_SalesOrg_DistChannel();
        
        List<Opportunity> opportunityList = new List<Opportunity>();
        
        for(Integer i=0; i<numOpps; i++) {
            Opportunity opportunity = createRetail();
            opportunity.Company_Date__c = OrganizationCommons.SOC_EUROCERAMIQUE;
            opportunity.Sales_Org_Date__c = OrganizationCommons.ORG_AZURCERAMIQUE;
            opportunity.Sales_Office_Date__c = '3015';
            //opportunity.Opportunity_Classification__c = 'Residential';
            //opportunity.Opportunity_Classification_II__c = 'Single-family home';   
            
            // add any extra fields or replace existing ones
            for(String fieldName : fieldsToAdd.keySet()) {
                opportunity.put(fieldName, fieldsToAdd.get(fieldName));
            }
            
            opportunityList.add(opportunity);
        }
        
        return opportunityList;
        
    }
    
}