force-app/main/default/objects/Opportunity/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <defaultValue>&apos;GBP&apos;</defaultValue>
    <description>IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;203&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;206&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;207&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;208&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;210&quot;), &quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c, &quot;218&quot;),&quot;EUR&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;602&quot;), &quot;USD&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;603&quot;), &quot;USD&quot;,  IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;604&quot;), &quot;USD&quot;, IF(ISPICKVAL($User.Default_Sales_Organization__c,&quot;605&quot;), &quot;USD&quot;, IF(ISPICKVAL($User.Default_Sales_Organization__c,&quot;606&quot;), &quot;USD&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;608&quot;), &quot;USD&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;615&quot;), &quot;USD&quot;, IF( ISPICKVAL($User.Default_Sales_Organization__c,&quot;650&quot;), &quot;CAD&quot;, &quot;GBP&quot;))))))</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>ILS</fullName>
            </value>
            <value>
                <fullName>CLP</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>DOP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distribution Channel</label>
    <referenceTo>Distribution_Channel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Default Sales Org of the User who created the Opportunity</description>
    <label>Sales Org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Automatic_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Automatic_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Automatic opp process</businessProcess>
    <description>Available only for administrators</description>
    <label>Automatic Opportunity</label>
</RecordType>

force-app/main/default/objects/Sales_Relationship__c/Sales_Relationship__c.object-meta.xml
<CustomObject>
    <label>SAP Accounting Info</label>
    <nameField>
        <label>Nombre Organizaciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Accounting Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Relationship__c/fields/Account_Org__c.field-meta.xml
<CustomField>
    <fullName>Account_Org__c</fullName>
    <label>Account Org</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Organizaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Custom_Id__c.field-meta.xml
<CustomField>
    <fullName>Custom_Id__c</fullName>
    <description>id_de_sap del account + org. ventas + canal (revisar)</description>
    <externalId>true</externalId>
    <inlineHelpText>SAP ID, PK of 3 grouped values: Customer Sap ID + Sales Organization + Distribution Channel</inlineHelpText>
    <label>Custom Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>Distribution Channel</description>
    <inlineHelpText>Distribution Channel</inlineHelpText>
    <label>Distribution Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Org__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Tienda</description>
    <inlineHelpText>Sales Office</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Default_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Organization__c</fullName>
    <description>La organización de ventas por defecto para el comercial</description>
    <inlineHelpText>The default sales organization for sales and distribution</inlineHelpText>
    <label>Default Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Distribution_channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel__c</fullName>
    <label>Distribution channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Distribution_channel_default__c.field-meta.xml
<CustomField>
    <fullName>Distribution_channel_default__c</fullName>
    <label>Distribution channel default</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>10 Third Party</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Associates</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>20 Subsidiaries</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 National Builders</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>40 Intercompany</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 Others</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Retail</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>65 eCommerce</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 Trade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>Sales Office from Sales Org default</description>
    <inlineHelpText>Sales Office from Sales Org default</inlineHelpText>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Default_Sales_Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>sales_office2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesRelationshipTriggerHandler.cls
public class SalesRelationshipTriggerHandler extends BaseTriggerHandler {
    public override void beforeInsert(List<SObject> newItems) {
        User triggerUser = [SELECT Id, ProfileId, CountryCode, Default_Sales_Organization__c, Distribution_channel_default__c, Sales_Office__c
                            FROM User WHERE Id =: UserInfo.getUserId()];

        for (Sales_Relationship__c sRel : (List<Sales_Relationship__c>) newItems) {
            sRel.Custom_Id__c = sRel.Account_Org__c + '-' + sRel.Sales_Org__c + '-' + sRel.Distribution_Channel__c;

            sRel.Name = SalesRelationshipUtils.getSalesRelName(sRel, triggerUser.CountryCode);
            if (!String.isBlank(sRel.Currency__c)) {
                sRel.CurrencyIsoCode = sRel.Currency__c;
            }
        }
    }

    public override void beforeUpdate(List<SObject> newItems, Map<Id, SObject> oldItems) {
        Map<Id,Sales_Relationship__c> oldItemsTransformed = (Map<Id,Sales_Relationship__c>) oldItems;
        for (Sales_Relationship__c sRel : (List<Sales_Relationship__c>) newItems) {
            if( sRel.Sap_Status__c != oldItemsTransformed.get(sRel.Id).Sap_Status__c && sRel.Sap_Status__c == 'Success'){
                sRel.Error_Message__c = null;
            }
            if (!String.isBlank(sRel.Currency__c)) {
                sRel.CurrencyIsoCode = sRel.Currency__c;
            }
        }
    }

    public override void afterInsert(List<SObject> newItems) {
        insertAutomaticOpportunities((List<Sales_Relationship__c>) newItems);
        platformEventNew((List<Sales_Relationship__c>) newItems);
       
    }

    
    /******************************** Private Methods ************************************/

    public static void UpdateOwner(List<String> salesRelIds){        
        List<Sales_Relationship__c> sRelsData = [SELECT Id, Account_Org__c, Sales_Office__c,Sales_Org__c,Account_Org__r.Owner.Profile.Name
                                            FROM Sales_Relationship__c
                                            WHERE Id IN : salesRelIds];        
        System.debug(sRelsData);
        Set<String> accIds = new Set<String>();
        Set<String> salesOffices = new Set<String>();
        Set<String> salesOrgs = new Set<String>();       
        for (Sales_Relationship__c sRel : sRelsData) {
            salesOffices.add(sRel.Sales_Office__c);
            accIds.add(sRel.Account_Org__c);
            salesOrgs.add(sRel.Sales_Org__c);            
        }

        List<RegionalSettings__mdt> rlist = [Select reassignOwner__c,SalesOrganization__c From RegionalSettings__mdt Where SalesOrganization__c IN :salesOrgs];
        if (rlist.isEmpty() == false) {
            Map<String, RegionalSettings__mdt> salesOrgsStatus = new Map<String, RegionalSettings__mdt>();

            for (RegionalSettings__mdt r : rlist) {
                salesOrgsStatus.put(r.SalesOrganization__c, r);
            }

            List<User> users = [SELECT Id, Sales_Office__c
                                FROM User
                                WHERE Sales_Office__c IN : salesOffices
                                AND IsActive = true];
            
            Map<String, List<User>> salesOfficeUsers = new Map<String, List<User>>();
            for (User u : users) {
                if (salesOfficeUsers.containsKey(u.Sales_Office__c) == false) {
                    salesOfficeUsers.put(u.Sales_Office__c, new List<User>{u});
                } else {
                    List<User> usersList = salesOfficeUsers.get(u.Sales_Office__c);
                    usersList.add(u);
                    salesOfficeUsers.put(u.Sales_Office__c, usersList);
                }
            }

            Map<String, Account> accsMap = new Map<String, Account>();
            List<Account> accounts = [SELECT Id, OwnerId FROM Account WHERE Id IN : accIds];

            for (Account acc : accounts) {
                accsMap.put(acc.Id, acc);
            }

            for (Sales_Relationship__c sRel : sRelsData) {     
                if(sRel.Account_Org__r.Owner.Profile.Name =='Porcelanosa Administrator' 
                    || sRel.Account_Org__r.Owner.Profile.Name =='System Administrator' 
                    || sRel.Account_Org__r.Owner.Profile.Name =='API Only')
                {
                    if (salesOrgsStatus.containsKey(sRel.Sales_Org__c) && salesOrgsStatus.get(sRel.Sales_Org__c).reassignOwner__c ==true) {
                        List<User> Owners = salesOfficeUsers.get(sRel.Sales_Office__c);
                        if (accsMap.containsKey(sRel.Account_Org__c)) {                   
                            Account acc = accsMap.get(sRel.Account_Org__c);
                            Integer randomIndex = (Integer) Math.floor(Math.random() * Owners.size());
                            User OwnerRandom = Owners[randomIndex];                        
                            acc.OwnerId = OwnerRandom.Id;                        
                            accsMap.put(sRel.Account_Org__c, acc);
                        }
                    }
                }
                
            }
            // Actualizar en Salesforce
            update accsMap.values();
        }
        
        
    }

    private void insertAutomaticOpportunities(List<Sales_Relationship__c> newItems){
        Set<Id> accIds = new Set<Id>();
        Id resellerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Third_party_Retailer_Reseller').getRecordTypeId();
        Id fabricatorRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Fabricator').getRecordTypeId();
        Id tradeRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Trade_and_Specificators').getRecordTypeId();
        Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Automatic_Opportunity').getRecordTypeId();
        List<Opportunity> oppsToInsert = new List<Opportunity>();
        Set<Id> oppsToInsertAccountsId = new Set<Id>();
        Map<Id, Account> mapAccounts = new Map<Id, Account>();
        Map<Id, Opportunity> mapAutomaticOpps = new Map<Id, Opportunity>();

        for(Sales_Relationship__c salesRel : newItems){
            accIds.add(salesRel.Account_Org__c);
        }
        
        // Cuentas de las sales rel
        mapAccounts = new Map<Id,Account>([SELECT Id, Name, RecordTypeId FROM Account WHERE Id IN :accIds AND (RecordTypeId =: resellerRecordTypeId OR RecordTypeId =: fabricatorRecTypeId OR
                                (RecordTypeId =: tradeRecTypeId AND Account_Classification__c = 'National House Builders'))]);
        
        // Busca las Opp automáticas de las cuentas
        for (Opportunity opp : [SELECT Id, AccountId FROM Opportunity WHERE RecordTypeId =: oppRecordTypeId AND AccountId IN :mapAccounts.keySet()] ) {
            mapAutomaticOpps.put(opp.AccountId, opp);
        }
        
        for(Sales_Relationship__c newSalesRel : newItems){
            Boolean alreadyExists = false;
            if (mapAccounts.containsKey(newSalesRel.Account_Org__c)) {
                // The automatic Opp already exist
                if (mapAutomaticOpps.containsKey(newSalesRel.Account_Org__c)) {
                    alreadyExists = true;
                    break;
                }

                // Already added to the Automatic Opps to insert
                if (!alreadyExists && oppsToInsertAccountsId.contains(newSalesRel.Account_Org__c)) {
                    alreadyExists = true;
                    break;
                }

                // The Automatic Opp doesn't exist, so we create it
                if(!alreadyExists){
                    try{
                        Account acc = mapAccounts.get(newSalesRel.Account_Org__c);
                        oppsToInsert.add( SalesRelationshipUtils.createAutomaticOpportunity(acc) );
                        oppsToInsertAccountsId.add(acc.Id);
                    } catch(Exception ex){
                        System.debug('Error creating the opportunity: ' + ex.getMessage());
                    }
                }
            }
        }

        if( !oppsToInsert.isEmpty() ){
            Database.SaveResult[] oppListResults = Database.insert(oppsToInsert, false);
            
            for(Database.SaveResult sr : oppListResults){
                if(!sr.isSuccess()){
                    System.debug('Insert automatic opportunity error: ' + sr.getErrors()[0].getMessage() );
                }
            }
        }
    }

    /**
    * @description Creates Platform Events about the new event
    */
    private void platformEventNew(List<Sales_Relationship__c> salesRels) {
        List<PENewSalesRelationship__e> listPlatformEvents = new List<PENewSalesRelationship__e>();
        for (Sales_Relationship__c salesRel : salesRels) {
            listPlatformEvents.add( new PENewSalesRelationship__e( objectId__c = salesRel.Id ));
        }
        List<Database.SaveResult> results = EventBus.publish(listPlatformEvents);
       
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event "New Sales Relationship".');
            } else {
                for(Database.Error err : sr.getErrors()) {
                    Logger.error('Error returned: ' + err.getStatusCode() + ' - ' + err.getMessage());
                    Logger.saveLog();
                }
            }
        }
    } // platformEventNew


}