force-app/main/default/objects/Opportunity/fields/Dist_Channel__c.field-meta.xml
<CustomField>
    <fullName>Dist_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsGeneric__c.field-meta.xml
<CustomField>
    <fullName>IsGeneric__c</fullName>
    <formula>RecordType.Name = &quot;Automatic Opportunity&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsGeneric</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Default Sales Org of the User who created the Opportunity</description>
    <label>Sales Org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesProgram__c.field-meta.xml
<CustomField>
    <fullName>SalesProgram__c</fullName>
    <description>Picklist para completar de forma automática dependiendo diversas variables de la oportunidad</description>
    <label>Sales Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TANDEM</fullName>
                <label>Tándem</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityContactRole/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>CASESAFEID(Contact.AccountId)</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityContactRole/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Holds tips about what was wrong on the contact role process</description>
    <label>Sap Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityContactRole/fields/SapStatus__c.field-meta.xml
<CustomField>
    <fullName>SapStatus__c</fullName>
    <label>Sap Status</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sap_Errors_Group_Config__mdt/Sap_Errors_Group_Config__mdt.object-meta.xml
<CustomObject>
    <description>For storing configuration for the private group to which the notifications of SAP related errors are sent to.</description>
    <label>Sap Errors Group Config</label>
    <pluralLabel>Sap Errors Group Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sap_Errors_Group_Config__mdt/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <description>Name of the group</description>
    <label>Group Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AutomaticContactRolesSendToSap.cls
/**
* @author Ivan Losilla
* @date January 2022
* @group SAP
* @description Manage send the Contact Roles of Opportunities to SAP
*/
public class AutomaticContactRolesSendToSap {

    public static void manageSendToSap(List<OpportunityContactRole> contactRoles){
        List<Id> contactRoleIdList = new List<Id>();
        for (OpportunityContactRole elem : contactRoles) {
            contactRoleIdList.add(elem.Id);
        }
        if(!contactRoleIdList.isEmpty()){
            sendToSAPFuture(contactRoleIdList);
        }
    }
    
    @future(callout=true)
    public static void sendToSAPFuture(List<Id> contactRoleIdList){
        SendToSAP(contactRoleIdList);
    }
    
    public static void sendToSAP(List<Id> contactRoleIdList){
        List<OpportunityContactRole> contactRoles = [SELECT Id, OpportunityId, Account__c, Contact.Name FROM OpportunityContactRole WHERE Id IN: contactRoleIdList];                                        
        
        if(!contactRoles.isEmpty()){
            Set<Id> oppIds =  new Set<Id>();
            
            for( OpportunityContactRole contactRole : contactRoles ){
                oppIds.add(contactRole.OpportunityId);
            }
            
            Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>([SELECT Id, Name, AccountId, Sales_Org__c,SalesProgram__c, Dist_Channel__c, StageName, IsGeneric__c, CloseDate,
                                                                    (SELECT Id, ContactId,Account__c, Role FROM OpportunityContactRoles)
                                                                    FROM Opportunity
                                                                    WHERE Id IN: oppIds]);
            
            Map<Id, Map<String,Object>> responseMap = new Map<Id, Map<String,Object>>();
            
            for(OpportunityContactRole contactRole : contactRoles){
                responseMap.put(contactRole.Id, SendRequest(oppMap.get(contactRole.OpportunityId)));
            }
            
            String groupName;
            Id chatterGroupId;
            EmailTemplate emailTemplate;
            List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
            List<FeedItem> postToInsert = new List<FeedItem>();
            List<CustomNotification> customNotifList = new List<CustomNotification>();
            
            try{
                groupName = Test.isRunningTest() ? 'test group name' : [SELECT Group_Name__c FROM Sap_Errors_Group_Config__mdt WHERE DeveloperName = 'Porcelanosa_Group'].Group_Name__c;
                emailTemplate = [select Id, Subject, HtmlValue from EmailTemplate where DeveloperName = 'SAP_Error_Message_Template_GB'];
                chatterGroupId = [SELECT Id FROM CollaborationGroup WHERE Name =: groupName].Id;
            } catch(Exception ex){
                System.debug('Error retrieving the Collaborative Group: ' + ex.getMessage());
            }
            
            for(OpportunityContactRole contactRole : contactRoles){
                String status = (String) responseMap.get(contactRole.Id).get('status');
                contactRole.SAPStatus__c = status;
                
                if(status == 'Success'){
                	contactRole.ErrorMessage__c = null;
                } else {
                    String errorMessage = (String) responseMap.get(contactRole.Id).get('errorMessage');
                    contactRole.ErrorMessage__c = errorMessage;
                    AutomatismsNotifications.generateNotifications(chatterGroupId, UserInfo.getUserId(), emailTemplate, contactRole, errorMessage, postToInsert, emailList, customNotifList);
                }
            }

            Database.update(contactRoles, false);
            AutomatismsNotifications.sendCustomNotifications(customNotifList);
            AutomatismsNotifications.insertFeedItems(postToInsert);
            
            if(!emailList.isEmpty()){
                Messaging.sendEmail(emailList, false);
            }
            
        }
        
    }
    
    public static Map<String, Object> sendRequest(Opportunity opp){
        SAPWS_Utility.opportunityWrapper = null;
        Map<String, Object> responseMap = new Map<String, Object>();
        Map<String, Object> oppFieldWrapper = new Map<String, Object>();
        
        oppFieldWrapper.put('Name', opp.Name);
        oppFieldWrapper.put('Id', opp.Id);
        oppFieldWrapper.put('IsClosed', false);
        oppFieldWrapper.put('AccountId', opp.AccountId);
        oppFieldWrapper.put('SalesOrg', opp.Sales_Org__c);
        oppFieldWrapper.put('Channel', opp.Dist_Channel__c);
        oppFieldWrapper.put('StageName', opp.StageName);
        oppFieldWrapper.put('IsGeneric__c', opp.IsGeneric__c);
        oppFieldWrapper.put('CloseDate', opp.CloseDate);
        oppFieldWrapper.put('SalesProgram', opp.SalesProgram__c);
        
        Map<String, Object> opportunityWrapper = new Map<String, Object>();
        opportunityWrapper.put('opportunity', oppFieldWrapper);
        opportunityWrapper.put('opportunityActorsList', opp.OpportunityContactRoles);
        opportunityWrapper.put('language', UserInfo.getLanguage());
        SAPWS_Utility.SapResponse response = OpportunityTransactionHandler.runSAPValidation(JSON.serialize(opportunityWrapper));
        responseMap.put('status', response.success ? 'Success' : 'Error');
        
        if(!response.success){
            String errorMessage = response.message + ':<p></p>';
            if(response.details != null){
                for( SAPWS_Utility.Detail detail : response.details ){
                    errorMessage += detail.message + ' (' + detail.code + ').<p></p>';
                }
            }
            
            responseMap.put('errorMessage', errorMessage);
        }
        
        return responseMap;
        
    }
    
}