force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Default Sales Org of the User who created the Opportunity</description>
    <label>Sales Org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Bzirk__c.field-meta.xml
<CustomField>
    <fullName>Bzirk__c</fullName>
    <description>SAP price list code or multiple SAP price list codes separated by semicolon. Ignored when SAP Customer is informed.</description>
    <label>SAP Price Lists</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/ExecutionContext__c.field-meta.xml
<CustomField>
    <fullName>ExecutionContext__c</fullName>
    <description>Execution Context que puede usar este Pricebook</description>
    <label>Execution Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ExecutionContexts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/IsRetailReferencePricebook__c.field-meta.xml
<CustomField>
    <fullName>IsRetailReferencePricebook__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If check, it&apos;s the Reference Pricebook for the context</description>
    <label>Is Retail Reference Pricebook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/SAPSync__c.field-meta.xml
<CustomField>
    <fullName>SAPSync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SI marcado, significa que se actualizan los entries según SAP</description>
    <label>SAP Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Relationship__c/Sales_Relationship__c.object-meta.xml
<CustomObject>
    <label>SAP Accounting Info</label>
    <nameField>
        <label>Nombre Organizaciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Accounting Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Relationship__c/fields/Account_Org__c.field-meta.xml
<CustomField>
    <fullName>Account_Org__c</fullName>
    <label>Account Org</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Organizaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Bzirk__c.field-meta.xml
<CustomField>
    <fullName>Bzirk__c</fullName>
    <description>Sales area of the customer in SAP (BZIRK). In France is related to the price list applied.</description>
    <label>Sales Area</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Execution_Context__c.field-meta.xml
<CustomField>
    <fullName>Execution_Context__c</fullName>
    <description>User&apos;s execution context</description>
    <label>Execution Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <label>DEUTSCHLAND</label>
            </value>
            <value>
                <fullName>ZA</fullName>
                <label>SOUTH AFRICA</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>DENMARK</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>UNITED STATES</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>FRANCE</label>
            </value>
            <value>
                <fullName>GB</fullName>
                <label>UNITED KINGDOM</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>SPAIN</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>POLAND</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>SWITZERLAND</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>ITALY</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>CANADA</label>
            </value>
            <value>
                <fullName>JP</fullName>
                <label>JAPAN</label>
            </value>
            <value>
                <fullName>VO</fullName>
                <label>VOID</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>BELGIUM</label>
            </value>
            <value>
                <fullName>PEXP</fullName>
                <label>PORCELANOSA EXPORT</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>AUSTRALIA</label>
            </value>
            <value>
                <fullName>SE</fullName>
                <label>SCANDINAVIA</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>ISRAEL</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>CHILE</label>
            </value>
            <value>
                <fullName>RD</fullName>
                <label>REPUBLICA DOMINICANA</label>
            </value>
            <value>
                <fullName>DEFAULT</fullName>
                <isActive>false</isActive>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>FLOWTESTUK</fullName>
                <isActive>false</isActive>
                <label>FLOWTESTUK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Organización de Ventas</description>
    <inlineHelpText>Sales Org</inlineHelpText>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sales_orgs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ExecutionContexts.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <label>GERMANY</label>
    </customValue>
    <customValue>
        <fullName>ZA</fullName>
        <label>SOUTH AFRICA</label>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
        <label>DENMARK</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <label>UNITED STATES</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>FRANCE</label>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
        <label>UNITED KINGDOM</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>SPAIN</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>POLAND</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <label>CANADA</label>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
        <label>SWITZERLAND</label>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
        <label>AUSTRALIA</label>
    </customValue>
    <description>List of available ExecutionContexts</description>
    <masterLabel>Execution Contexts</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PricebookAssignatorTest.cls
@isTest
public class PricebookAssignatorTest {
    @testSetup
    private static void testSetup() {
        TestUtils.enableTriggers();
        User usr = new UsersSelector().selectById(UserInfo.getUserId());
        Pricebook2 spb = new Pricebook2(
            IsActive = true,
            SapSync__c = true,
            Bzirk__c = 'V10001',
            Name = 'Test Pricebook SALES REL',
            ExecutionContext__c = 'FR'
        );
        Pricebook2 spb2 = new Pricebook2(
            IsActive = true,
            SapSync__c = true,
            Bzirk__c = '99999',
            Name = 'Test Pricebook Reference',
            ExecutionContext__c = 'FR',
            IsRetailReferencePricebook__c = true
        );
        Pricebook2 spb3 = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            SapSync__c = false
        );
        insert spb;
        insert spb2;
        update spb3;

        List<Account> accs = DataFactoryAccount.createAccounts(10);
        Opportunity newOpp = Opportunity_TestDataFactory.createTrade(accs[1]);
        insert newOpp;

        DataFactoryAccount.autoInsert = false;
        Sales_Relationship__c salesRel = DataFactoryAccount.createSalesRelation(accs[0],'650','60','4200');
        salesRel.Bzirk__c = 'V10001';
        insert salesRel;
    }

    @isTest
    private static void getPricebookToAssign() {
        User usr = new UsersSelector().selectById(UserInfo.getUserId());
        User usrFR = [select id,Execution_Context__c from user where isactive = true and Execution_Context__c = 'FR' LIMIT 1];
        Pricebook2 pb1 = [SELECT Id, Name FROM Pricebook2 WHERE Name = 'Test Pricebook SALES REL' LIMIT 1];
        Pricebook2 pbReference = [SELECT Id, Name FROM Pricebook2 WHERE Name = 'Test Pricebook Reference' LIMIT 1];
        Sales_Relationship__c salesRel = [SELECT Id, Sales_Org__c, Account_org__c FROM Sales_Relationship__c WHERE Sales_Org__c = '650'  LIMIT 1];
        Account accNoSalesRel = [SELECT Id FROM Account WHERE Id <> : salesRel.Account_Org__c LIMIT 1];
        String contextLabel = [Select Execution_Context__c From User Where  Id = :UserInfo.getUserId()].Execution_Context__c;

        AbstractPricebookAssignator pricebookAssign = PricebookAssignator.getInstance(usrFR.Execution_Context__c);
        pricebookAssign.setUser(usrFR.Id);
        pricebookAssign.setAccount(salesRel.Account_Org__c);
        Pricebook2 pbAssigned = pricebookAssign.getPricebook();
        
        System.assert(pbAssigned != null, 'No se ha encontrado Pricebook entry');
        System.assert(pbAssigned.Id == pb1.Id, 'No se ha encontrado Pricebook de la Sales Relationship');
        
        AbstractPricebookAssignator pricebookAssign2 = PricebookAssignator.getInstance(usrFR.Execution_Context__c);
        pricebookAssign2.setUser(usrFR.Id);
        pricebookAssign2.setAccount(accNoSalesRel.Id);
        Pricebook2 pbAssigned2 = pricebookAssign2.getPricebook();

        System.assert(pbAssigned2 != null, 'No se ha encontrado Pricebook entry');
        System.assert(pbAssigned2.Id == pbReference.Id, 'No se ha encontrado Pricebook de Referencia');
    }
}