force-app/main/default/objects/UserAdditionalInfo__c/UserAdditionalInfo__c.object-meta.xml
<CustomObject>
    <description>La idea es que con este objeto nos permita almacenar datos adicionales acerca de usuarios, para utilizarlos en LWC o APEX</description>
    <label>User Additional Info</label>
    <nameField>
        <displayFormat>UAI-{00000000}</displayFormat>
        <label>User Additional Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Additional Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserAdditionalInfo__c/fields/InfoType__c.field-meta.xml
<CustomField>
    <fullName>InfoType__c</fullName>
    <description>Tipo de datos que va a almacenar el registro</description>
    <label>Info type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POPUPLASTTIME</fullName>
            </value>
            <value>
                <fullName>DVSACCOUNTSMANAGED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UserAdditionalInfo__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Additional_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserAdditionalInfo__c/fields/Value1__c.field-meta.xml
<CustomField>
    <fullName>Value1__c</fullName>
    <description>Valor genérico de almacén de valores</description>
    <label>Value 1</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserAdditionalInfo__c/fields/Value2__c.field-meta.xml
<CustomField>
    <fullName>Value2__c</fullName>
    <description>Valor genérico de almacén de valores</description>
    <label>Value 2</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserAdditionalInfo.cls
/**
* @author Ivan Losilla
* @date November 2024
*
* @group Users 
* @description Class to manage everything about User Additional
*/
public class UserAdditionalInfo {
    public static final String POPUPTIMEOPTION =     'POPUPLASTTIME';
    public static final String DVSMANAGEDACCOUNTS =  'DVSACCOUNTSMANAGED';

    @AuraEnabled
    public static Boolean setLastPopupTime(String userId) {
        try {
            UserAdditionalInfo__c found = getLastPopupTime(userId);

            if (found != null) {
                found.Value1__c = String.valueOf(Datetime.now());
                update found;
            } else {
                UserAdditionalInfo__c aux = new UserAdditionalInfo__c(
                    User__c = userId,
                    infoType__c = POPUPTIMEOPTION,
                    Value1__c = String.valueOf(Datetime.now())
                );
                insert aux;
            }

            return true;
        } catch (Exception ex) {
            return false;
        }
    }

    @AuraEnabled
    public static Boolean setDvsAccountsManaged(String userId, String accountId) {
        try {
            UserAdditionalInfo__c aux = new UserAdditionalInfo__c(
                User__c = userId,
                infoType__c = DVSMANAGEDACCOUNTS,
                Value1__c = accountId,
                Value2__c = String.valueOf(Date.today())
            );
    
            insert aux;
            return true;
        } catch (Exception ex) {
            return false;
        }
    }

    public static UserAdditionalInfo__c getLastPopupTime(String userId) {
        List<Account> result = new List<Account>();
        List<UserAdditionalInfo__c> additionalInfo = [SELECT Id, User__c, InfoType__c, Value1__c, Value2__c 
                                                        FROM UserAdditionalInfo__c
                                                        WHERE User__c =: userId AND InfoType__c =: POPUPTIMEOPTION];
        
        if (additionalInfo.size() > 0) {
            return additionalInfo[0];
        } else {
            return null;
        }
    }

    public static List<Account> getDvsAccountsManaged(String userId, Date dateParameter) {
        List<Account> result = new List<Account>();
        Set<Id> accIds = new Set<Id>();
        List<UserAdditionalInfo__c> additionalInfo = [SELECT Id, User__c, InfoType__c, Value1__c, Value2__c 
                                                        FROM UserAdditionalInfo__c
                                                        WHERE User__c =: userId AND InfoType__c =: DVSMANAGEDACCOUNTS AND Value2__c =: String.valueOf(dateParameter)];
        for (UserAdditionalInfo__c aux : additionalInfo) {
            accIds.add(aux.Value1__c);
        }

        if (accIds.size() > 0 ) {
            result = new AccountsSelector().selectById(accIds);
        }
        
        return result;
    }

    @AuraEnabled
    public static UAIAllInfoDTO getAllInfo(String userId) {
        UAIAllInfoDTO result = new UAIAllInfoDTO();
        result.dvsAccountsManaged = getDvsAccountsManaged(userId, Date.today());
        result.lastPopupTime = getLastPopupTime(userId);
        return result;
    }

    public class UAIAllInfoDTO {
        @AuraEnabled
        public List<Account> dvsAccountsManaged = new List<Account>();
        @AuraEnabled
        public UserAdditionalInfo__c lastPopupTime = null;
    }
}