force-app/main/default/objects/Contact/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Dealer)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive_Contact__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>campo que determina si un contacto esta inactivo o no</description>
    <label>Inactive Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Facades</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Home Builder</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Institutional</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Retail Franchise</fullName>
            </value>
            <value>
                <fullName>Senior Living</fullName>
            </value>
            <value>
                <fullName>Workplace/ Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ToMarketingCloud__c.field-meta.xml
<CustomField>
    <fullName>ToMarketingCloud__c</fullName>
    <formula>IF(AND(
ISBLANK(Email) = false,
OR( TEXT(MailingCountryCode) =&apos;GB&apos;, TEXT(MailingCountryCode) = &apos;FR&apos;),
ISBLANK(EmailBouncedReason) = true,
CONTAINS(Email, &apos;porcelanosa&apos;) = false, 
Inactive_Contact__c = false,
HasOptedOutOfEmail = false,
notValidEmail__c = false
), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>To Marketing Cloud</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContactsSelector.cls
/**
* @author 		Ivan Losilla
* @date 		July 2022
* @group 		Contacts
* @description 	contacts selector class
*/
public class ContactsSelector extends zflib_SObjectSelector  {
    public Schema.SObjectType getSObjectType(){
        return Contact.sObjectType;
    }

    public List<Contact> selectById(Set<Id> recordIds){
        return (List<Contact>) selectSObjectsById(recordIds);
    }

    public Contact selectById(Id recordId){
        List<Contact> listContacts = (List<Contact>) selectSObjectsById(new Set<Id>{recordId});
        if (listContacts.size() == 1) {
            return listContacts[0];
        }
        return null;
    }

    public List<Contact> selectByAccountId(Set<Id> recordIds){
        zflib_QueryFactory query = newQueryFactory();
        query.setCondition('AccountId IN :recordIds');
        return (List<Contact>) Database.query( query.toSOQL() );
    }
   
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            
            // Main info fields
            Contact.Id,
            Contact.OwnerId,
            Contact.CurrencyIsoCode,
            Contact.AccountId,
            Contact.Name,
            Contact.Email,
            Contact.Phone,
            Contact.RecordTypeId,

            //Classification fields
            Contact.Dealer__c,
            Contact.Inactive_Contact__c,
            Contact.Specialization__c,
            Contact.ToMarketingCloud__c,

            // Address fields
            Contact.MailingAddress,
            Contact.MailingCity,
            Contact.MailingCountryCode,
            Contact.MailingPostalCode,
            Contact.MailingStateCode,
            Contact.MailingStreet,

            // Admin fields
            Contact.CreatedById,
            Contact.CreatedDate,
            Contact.LastModifiedById
        };
    }
}