force-app/main/default/objects/Contact/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>External ID that matches the External ID of a Lead Contact</description>
    <label>External ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/USA.recordType-meta.xml
<RecordType>
    <fullName>USA</fullName>
    <active>true</active>
    <label>USA</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Lead Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <label>External ID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadSubtype__c.field-meta.xml
<CustomField>
    <fullName>LeadSubtype__c</fullName>
    <inlineHelpText>Please enter here the origin of the lead (i.e. Sale January 2020)</inlineHelpText>
    <label>Lead Subtype</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact Form</fullName>
            </value>
            <value>
                <fullName>PDF Guide Download</fullName>
            </value>
            <value>
                <fullName>US Material Bank</fullName>
            </value>
            <value>
                <fullName>EU Material Bank</fullName>
            </value>
            <value>
                <fullName>Course Request</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Book an Appointment</fullName>
            </value>
            <value>
                <fullName>Google Ad</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
            <value>
                <fullName>US Register Form</fullName>
            </value>
            <value>
                <fullName>Business Trip</fullName>
            </value>
            <value>
                <fullName>Contact Form;Contact Form</fullName>
                <isActive>false</isActive>
                <label>Contact Form;Contact Form</label>
            </value>
            <value>
                <fullName>Showroom Appointment</fullName>
                <isActive>false</isActive>
                <label>Showroom Appointment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Project Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/OwnerLocked__c.field-meta.xml
<CustomField>
    <fullName>OwnerLocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to true whe no owner assignation has to be executed</description>
    <label>Owner Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>Profile of the person or company contacting us</description>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
                <isActive>false</isActive>
                <label>Distributor</label>
            </value>
            <value>
                <fullName>Fabricator</fullName>
            </value>
            <value>
                <fullName>Facade Consultant</fullName>
            </value>
            <value>
                <fullName>Facade Installer</fullName>
            </value>
            <value>
                <fullName>Kitchen &amp; Bath store</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
            <value>
                <fullName>-None-</fullName>
                <isActive>false</isActive>
                <label>-None-</label>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Private Customer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Realtor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Representative__c.field-meta.xml
<CustomField>
    <fullName>Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Porcelanosa User that has filled the form that generated the lead on behalf of a possible customer. It is used mainly for Material Bank leads (US).</description>
    <label>Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Representative</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source/Origin</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CountryCode__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>USStates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Porcelanosa</businessProcess>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Order/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/ProductListItem__c.object-meta.xml
<CustomObject>
    <description>Custom object to store list of products</description>
    <label>Product List Item</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>ItemId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product List Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductListItem__c/fields/IsSample__c.field-meta.xml
<CustomField>
    <fullName>IsSample__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sample</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Product List Items</relationshipLabel>
    <relationshipName>Product_List_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Product Name</description>
    <label>Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/fields/Shipped__c.field-meta.xml
<CustomField>
    <fullName>Shipped__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The products have already been sipped to the customer</description>
    <label>Shipped?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductListItem__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductUnits</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ProductUnits.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PZS</fullName>
        <label>PIECE</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>PALLET</label>
    </customValue>
    <customValue>
        <fullName>SAC</fullName>
        <label>BAG</label>
    </customValue>
    <customValue>
        <fullName>MT2</fullName>
        <label>SQUARE METERS</label>
    </customValue>
    <customValue>
        <fullName>BID</fullName>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>CJ</fullName>
        <label>BOX</label>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
        <label>CENTIMETER</label>
    </customValue>
    <customValue>
        <fullName>DM2</fullName>
        <label>SQUARE DECIMETER</label>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
        <label>KILOGRAM</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>LITER</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>METER</label>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
        <label>SQUARE METER</label>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
        <label>MILILITER</label>
    </customValue>
    <customValue>
        <fullName>ROL</fullName>
        <label>ROLE</label>
    </customValue>
    <customValue>
        <fullName>SQF</fullName>
        <label>SQUARE FOOT</label>
    </customValue>
    <customValue>
        <fullName>UN</fullName>
        <label>UNIT</label>
    </customValue>
    <customValue>
        <fullName>CM2</fullName>
        <label>SQUARE CENTIMETER</label>
    </customValue>
    <customValue>
        <fullName>DM</fullName>
        <label>DECIMETER</label>
    </customValue>
    <description>Values for product units</description>
    <masterLabel>Product Units</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MaterialBankProject.cls
/**
* @author 		Ramón Prades
* @date 		February 2022
* @group 		Leads
* @description 	Class to create leads from a material bank project (in batch). Creates a lead and 
*               schedules the next to avoid hittin the governor limits.
*/
@SuppressWarnings('PMD.ExcessiveParameterList')
public class MaterialBankProject implements Database.Batchable<SObject>, Database.stateful {     

    List<MaterialBankParser.MBProject> projects;
    Integer index = -1;
    public List<Id> leadIds;
    public List<MaterialBankIssue> issues;
    public String fileName = '';
    public Boolean isEurope = false;    
    private String excludedCountries = '';

    static final String LEAD_SOURCE = 'Samples Request';
    static final String LEAD_TYPE = 'US Material Bank';
    static final String LEAD_TYPE_EU = 'EU Material Bank';
    static final String LEAD_SUBTYPE = 'Material Bank';
    static final String SOURCE = 'MBK';
    SystemLog logger;

    public MaterialBankProject(List<MaterialBankParser.MBProject> projects) {     
        this.logger = new SystemLog('MATERIAL-BANK');
        this.fileName = 'void';
        this.leadIds = new List<Id>();
        this.issues = new List<MaterialBankIssue>();
        this.projects = projects;
        this.index = 0;
    }
    
    public MaterialBankProject(String fileName, List<MaterialBankParser.MBProject> projects) {        
        this(projects);
        this.fileName = fileName;
    }

    public void setEurope(Boolean value) {
        this.excludedCountries = '';
        this.isEurope = value;
        if (this.isEurope) {
            this.excludedCountries = 'ES;PT;';
            this.logger.setTag('EUROPE');
        } else {
            this.logger.setTag('USA');
        }
    }

    public MaterialBankProject(String fileName, List<MaterialBankParser.MBProject> projects, List<Id> leadIds, List<MaterialBankIssue> issues, Integer index, SystemLog logger) {        
        this.fileName = fileName;
        this.leadIds = leadIds;
        this.issues = issues;
        this.projects = projects;
        this.logger = logger;
        this.index = index;
    } // Constructor

    public  Database.QueryLocator start(Database.BatchableContext bc) {  
        return Database.getQueryLocator('select Id from User limit 1');     // Para que se ejecute el execute
    }

    public void execute(Database.BatchableContext context, List<sObject> param) {     
        this.logger.addInfo('-----------------------------------') ;
        this.logger.addInfo('Procesando proyecto de MATERIAL BANK');
        this.logger.addInfo('IS_EUROPE vale ' + this.isEurope);
        this.logger.saveLog();
        MaterialBankParser.MBProject project = this.projects[this.index];        
        this.index++;
        Boolean excluded = this.excludedCountries.containsIgnoreCase(project.customer.COUNTRY + ';');
        if (!excluded && !this.leadExists(project.orderId)) {
            try {
                Lead lead = this.createMBLead(project);        
                this.logger.addInfo('Project ' + project.orderId + ' converted to Lead ' + lead.Id + ' ' + lead.Opportunity_Name__c);
                leadIds.add(lead.Id);
                USLeadMailer mailer = new USLeadMailer(lead.Id);
                mailer.setEurope(this.isEurope);
                mailer.newMaterialBankLead();    
            } catch (DmlException dex) {  
                MaterialBankIssue issue = new MaterialBankIssue();
                issue.projectName = project.projectName;
                issue.customerName = (project.customer.CONTACT1NAME ?? project.customer.SHIPPED1NAME);
                issue.isError = true;
                this.logger.addError('DMLError converting project ' + project.orderId);
                for (Integer i = 0; i < dex.getNumDml(); i++) {
                    issue.comments = '[' + dex.getDmlFieldNames(i) + '] ' + dex.getDmlMessage(i);
                }
                this.issues.add(issue);
                this.logger.addError(dex);
            } catch (Exception ex) {
                this.logger.addError(ex.getTypeName() + ' received converting project ' + project.orderId);
                this.logger.addError(ex);
                MaterialBankIssue issue = new MaterialBankIssue();
                issue.projectName = project.projectName;
                issue.customerName = (project.customer.CONTACT1NAME ?? project.customer.SHIPPED1NAME);
                issue.isError = true;
                issue.comments = ex.getTypeName() + '-' + ex.getMessage();
                this.issues.add(issue);
            }                    
        } else if (excluded){
            this.logger.addWarning('Project ' + project.orderId + ' excluded because of country ' + project.customer.COUNTRY);
            MaterialBankIssue issue = new MaterialBankIssue();
            issue.projectName = project.projectName;
            issue.customerName = (project.customer.CONTACT1NAME ?? project.customer.SHIPPED1NAME);
            issue.isError = false;
            issue.comments = 'Project ' + project.orderId + ' excluded (country is ' + project.customer.COUNTRY + ')';
            this.issues.add(issue);        
        } else {
            this.logger.addWarning('Project ' + project.orderId + ' already loaded');
            MaterialBankIssue issue = new MaterialBankIssue();
            issue.projectName = project.projectName;
            issue.customerName = (project.customer.CONTACT1NAME ?? project.customer.SHIPPED1NAME);
            issue.isError = false;
            issue.comments = 'Project ' + project.orderId + ' already loaded';
            this.issues.add(issue);
        }
        this.logger.saveLog();
    }
    
    public void finish(Database.BatchableContext BC) {
        if (this.index <this.projects.size()) {
            MaterialBankProject newProject = new MaterialBankProject(this.fileName, this.projects, this.leadIds, this.issues, this.index, this.logger);
            newProject.setEurope(this.isEurope);
            Database.executeBatch(newProject);
        } else {
            this.logger.saveLog(true);
            try {
                USLeadMailer.summaryMaterialBank(this.isEurope, this.fileName, this.leadIds, issues);                
            } catch(Exception ex) {
                this.logger.addError('Excepción recibida al enviar el resumen de la carga por email');
                this.logger.addError(ex);
            }
        }            
    }

    /*********************************************************/
    /******************** PRIVATE METHODS ********************/
    /*********************************************************/

    private Boolean leadExists(String externalId) {
        Lead[] leads = [select Id, External_ID__c from Lead where External_Id__c = :externalId];
        return (leads.size() > 0);
    } // leadExists

    @testVisible private Lead createMBLead(MaterialBankParser.MBProject project) {     
        Lead lead = new Lead();
        String oppName = project.projectName;
        if (oppName.length() > 40 ) {
            oppName = oppName.substring(0, 40);
        }
        lead.Opportunity_Name__c = oppName;
        lead.LeadSource = MaterialBankProject.LEAD_SOURCE;
        lead.company = project.customer.company;
        if (String.IsNotEMpty(lead.company)) {
            if (lead.company.containsIgnoreCase('PORCELANOSA')) {
                lead.company = '';
            }
        }
        String customerName = project.customer.CONTACT1NAME;
        if (String.isBlank(customerName)) {
            customerName = project.customer.SHIPPED1NAME;
        }
        if (String.isBlank(customerName)) {
            customerName = project.customer.ORDERED1NAME;
        }
        Map<String, String> words = StringUtils.splitName(customerName);
        lead.FirstName = words.get('firstName');
        lead.LastName = words.get('lastName');
        lead.Title = project.customer.TITLE;
        lead.Email = project.customer.CONTACT1EMAIL;
        lead.Profile__c = LeadHelper.mapProfile(project.customer.TITLE);
        lead.Address__c = project.customer.STREET1;
        lead.Postcode__c = project.customer.ZIP;
        lead.CountryCode__c = project.customer.COUNTRY;

        if (!this.isEurope) {
            if (String.isBlank(lead.CountryCode__c)) {
                lead.CountryCode__c = 'US';
                String zip = lead.Postcode__c;
                if (String.isNotBlank(zip)) {
                    zip = zip.toUpperCase();
                    if (zip.containsAny('ABCDEFGHIJKLMNOPQRSTUVWXYZ')) {
                        lead.CountryCode__c = 'CA';
                    }
                }
            }        
            if (lead.CountryCode__c == 'CA') {
                lead.State__c = GeoUtils.getCAStateCode(project.customer.STATE);
            } else {
                lead.State__c = GeoUtils.getUSStateCode(project.customer.STATE);
            }
        }
        
        lead.City__c = project.customer.CITY;
        lead.MobilePhone = project.customer.CONTACT1PHONE;
        lead.Source__c = MaterialBankProject.SOURCE;
        if (this.isEurope) {
            lead.LeadType__c = MaterialBankProject.LEAD_TYPE_EU;
        } else {
            lead.LeadType__c = MaterialBankProject.LEAD_TYPE;
        }
       lead.LeadSubtype__c = MaterialBankProject.LEAD_SUBTYPE;
        lead.Description = '- Project Type : ' + project.projectType + '\n'
                         + '- Project Phase: ' + project.projectPhase + '\n'
                         + '- Order Id     : ' + project.orderId + '\n'
                         + '- Tracking No  : ' + project.TrackingNo + '\n'
                         + '- Contact Name : ' + project.customer.CONTACT1NAME + '\n'
                         + '- Ordered Name : ' + project.customer.ORDERED1NAME + '\n'
                         + '- Shipped Name : ' + project.customer.SHIPPED1NAME + '\n'
                         + '- Contact Pref.: ' + project.customer.CONTACTPREFERENCE + '\n'
                         + '\n'
                         + project.projectDescription;
        lead.External_ID__c = project.orderId;                        

        if (project.porcelanosaEmail != null) {
            String rep = '';
            try {
                rep = UserUtils.getUserIdFromEmail(project.porcelanosaEmail);            
            } catch (ObjectNotFoundException onf1) {
                rep = null;
            }
            lead.Representative__c = rep;
        }

        LeadHelper helper = new LeadHelper(lead);
        if (this.isEurope) {
            helper.setEUWebRequestFields();
        } else {
            helper.setUSWebRequestFields();
        }
        helper.setAccountAndOwner();
        lead.OwnerLocked__c = true;
        insert lead;

        ProductListItem__c[] products = new List<ProductListItem__c>();
        for (MaterialBankParser.MBItem item : project.items) {
            ProductListItem__c product = this.createProductItem(lead, item);
            products.add(product);
        }   
        if (products.size() > 0) {
            insert products;
        }
        return lead;
    } // createLead

    private ProductListItem__c createProductItem(Lead lead, MaterialBankParser.MBItem item) {
        ProductListItem__c product = new ProductListItem__c();
        product.CurrencyIsoCode = lead.CurrencyIsoCode;
        product.isSample__c = true;
        product.Lead__c = lead.Id;
        product.ProductCode__c = item.SKU;
        product.Name__c = item.NAME;
        if (item.COLOR !=null && item.COLOR.length() > 0) {
            product.Name__c += ' (' + item.COLOR + ')';
        }
        product.Quantity__c = item.QTYORIGINAL;
        product.Unit__c = 'PZS';
        product.Shipped__c = TypeConversionCommons.englishToBoolean(item.MBSHIPPED);
        return product;
    }

    /*********************************************************/
    /******************** INNER CLASSES **********************/
    /*********************************************************/

    public class MaterialBankIssue {
        public String projectName;
        public String customerName;
        public Boolean isError;
        public String comments;
    } // MaterialBankIssue

}