force-app/main/default/objects/NB2B_Settings__c/NB2B_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to manage NB2B Mudule logic</description>
    <label>NB2B_Settings</label>
</CustomObject>

force-app/main/default/objects/NB2B_Settings__c/fields/NB2B_CartToOrderFailEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>NB2B_CartToOrderFailEmailAddress__c</fullName>
    <label>NB2B_CartToOrderFailEmailAddress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NB2B_SettingsManager.cls
/**
 * @description  : 
 * @author       : Nubika Team <example@nubika.com>
 * @version      : 1.0.0
 * @date         : 23-08-2023
 * @group        : 
 * @see          : 
**/
public class NB2B_SettingsManager {

    private static final Boolean isTest = Test.isRunningTest();
    public static final String errorEmailAddressFixed = System.Label.B2B_OrderErrorMailAddress;
    
    public static final NB2B_Settings__c settings {
        get{
            if(settings==null){
                return NB2B_Settings__c.getInstance();
            }
            return settings;
        }set;
    }

    public static final List<String> errorEmailAddresses {
        get{
            if(errorEmailAddresses == null){
                errorEmailAddresses = new List<String>();
                String emailFixed;
                List<String> addressesList = new List<String>();
                if(!isTest && settings.NB2B_CartToOrderFailEmailAddress__c != null){
                    addressesList = settings.NB2B_CartToOrderFailEmailAddress__c.split(',');
                    emailFixed = errorEmailAddressFixed;
                }else{
                    emailFixed = 'test@test.com'; 
                }
                errorEmailAddresses.addAll(addressesList);
                errorEmailAddresses.add(emailFixed);
            }
            return errorEmailAddresses;
        }set;
    }
}