force-app/main/default/objects/OpportunityContactRole/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Holds tips about what was wrong on the contact role process</description>
    <label>Sap Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityContactRole/fields/SapStatus__c.field-meta.xml
<CustomField>
    <fullName>SapStatus__c</fullName>
    <label>Sap Status</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OppContactRolesErrorComponentController.cls
public class OppContactRolesErrorComponentController {
    @AuraEnabled
    public static List<OpportunityContactRole> returnOppContactRolesErrors(String recordId){
        List<OpportunityContactRole> returnList = [SELECT Id, ErrorMessage__c, Contact.Name
                                                  FROM OpportunityContactRole 
                                                  WHERE OpportunityId =: recordId AND SapStatus__c = 'Error'];
        return returnList;
    }
    
    @AuraEnabled
    public static String retry(String recordId){
        String result = '';
        
        try{
            OpportunityContactRole oppContactRole = [SELECT Id, SapStatus__c, OpportunityId FROM OpportunityContactRole WHERE Id =: recordId];
            Update oppContactRole;
        } catch(Exception ex){
            result = ex.getMessage();
        }
        return result;
    }
}