force-app/main/default/objects/Execution_Context__mdt/Execution_Context__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata to define the behavior of a user&apos;s execution context. Initially designed to tell which countries are connected to SAP but open for extension in the near future</description>
    <label>Execution Context</label>
    <pluralLabel>Execution Contexts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Execution_Context__mdt/fields/ExtendedOpps__c.field-meta.xml
<CustomField>
    <fullName>ExtendedOpps__c</fullName>
    <description>Extended opportunities types allowed for the context</description>
    <inlineHelpText>semi-colon separated list of these keys: CUSTOMP, KITCHEN, FACADE.</inlineHelpText>
    <label>Extended Opportunities</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Execution_Context__mdt/fields/Has_SAP__c.field-meta.xml
<CustomField>
    <fullName>Has_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this option when the user works in a context connected to SAP</description>
    <inlineHelpText>Check this option if you need to connect to SAP from Salesforce</inlineHelpText>
    <label>Has SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Execution_Context__mdt/fields/OwnerAssignation__c.field-meta.xml
<CustomField>
    <fullName>OwnerAssignation__c</fullName>
    <description>Método sobre el que se buscará el owner para la asignación de un objeto</description>
    <label>Owner Assignation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>STD</fullName>
                <default>true</default>
                <label>Standard (país y cp)</label>
            </value>
            <value>
                <fullName>USA</fullName>
                <label>Extended US (país, cp, profile, etc)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Execution_Context__mdt/fields/PriceRequest__c.field-meta.xml
<CustomField>
    <fullName>PriceRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Price Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/OppCustomProject__c.object-meta.xml
<CustomObject>
    <description>Object to store opportunity&apos;s additional information on US custom project (Krion and similar products transformed by a fabricator).</description>
    <label>Opportunity Custom Project</label>
    <nameField>
        <label>Custom Project Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Custom Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppCustomProject__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>Delivery Needed By</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Related opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Custom_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/fields/ProductManager__c.field-meta.xml
<CustomField>
    <fullName>ProductManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OppCustomProject__c/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <description>Type of custom project</description>
    <label>Project Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALTISSIMA</fullName>
            </value>
            <value>
                <fullName>KRION</fullName>
            </value>
            <value>
                <fullName>KRION &amp; XTONE</fullName>
            </value>
            <value>
                <fullName>XTONE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppKitchen__c/OppKitchen__c.object-meta.xml
<CustomObject>
    <description>Additional information for kitchen opportunities. Originally designed for the US, but can (and will) be extended.</description>
    <label>Opportunity Kitchen</label>
    <nameField>
        <label>Kitchen Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Kitchens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OppKitchen__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Kitchens</relationshipLabel>
    <relationshipName>OpportunityKitchens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OppKitchen__c/fields/PricingCondition__c.field-meta.xml
<CustomField>
    <fullName>PricingCondition__c</fullName>
    <label>Pricing Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Promotional</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
                <default>true</default>
                <label>Regular</label>
            </value>
            <value>
                <fullName>PR1</fullName>
                <isActive>false</isActive>
                <label>PR1</label>
            </value>
            <value>
                <fullName>PR2</fullName>
                <isActive>false</isActive>
                <label>PR2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppKitchen__c/fields/ProductLine2__c.field-meta.xml
<CustomField>
    <fullName>ProductLine2__c</fullName>
    <label>Product Line</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discontinued Lines</fullName>
            </value>
            <value>
                <fullName>Emotion</fullName>
            </value>
            <value>
                <fullName>Emotion Wardrobes</fullName>
            </value>
            <value>
                <fullName>Fusion Wardrobes</fullName>
            </value>
            <value>
                <fullName>New Project</fullName>
            </value>
            <value>
                <fullName>New Residence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppKitchen__c/fields/ProductQuoted__c.field-meta.xml
<CustomField>
    <fullName>ProductQuoted__c</fullName>
    <description>DEPRECATED</description>
    <inlineHelpText>DEPRECATED</inlineHelpText>
    <label>Product Quoted</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OppKitchen__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kitchen</fullName>
                <default>true</default>
                <label>Kitchen</label>
            </value>
            <value>
                <fullName>Vanity</fullName>
            </value>
            <value>
                <fullName>Closet</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>P1</fullName>
                <isActive>false</isActive>
                <label>P1</label>
            </value>
            <value>
                <fullName>P2</fullName>
                <isActive>false</isActive>
                <label>P2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <label>ProjectType</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/Execution_Context__c.field-meta.xml
<CustomField>
    <fullName>Execution_Context__c</fullName>
    <description>User&apos;s execution context</description>
    <label>Execution Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <label>DEUTSCHLAND</label>
            </value>
            <value>
                <fullName>ZA</fullName>
                <label>SOUTH AFRICA</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>DENMARK</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>UNITED STATES</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>FRANCE</label>
            </value>
            <value>
                <fullName>GB</fullName>
                <label>UNITED KINGDOM</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>SPAIN</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>POLAND</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>SWITZERLAND</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>ITALY</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>CANADA</label>
            </value>
            <value>
                <fullName>JP</fullName>
                <label>JAPAN</label>
            </value>
            <value>
                <fullName>VO</fullName>
                <label>VOID</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>BELGIUM</label>
            </value>
            <value>
                <fullName>PEXP</fullName>
                <label>PORCELANOSA EXPORT</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>AUSTRALIA</label>
            </value>
            <value>
                <fullName>SE</fullName>
                <label>SCANDINAVIA</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>ISRAEL</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>CHILE</label>
            </value>
            <value>
                <fullName>RD</fullName>
                <label>REPUBLICA DOMINICANA</label>
            </value>
            <value>
                <fullName>DEFAULT</fullName>
                <isActive>false</isActive>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>FLOWTESTUK</fullName>
                <isActive>false</isActive>
                <label>FLOWTESTUK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityInfoControllerTest.cls
@isTest
public class OpportunityInfoControllerTest {
    @testSetup
    private static void testSetup() {
        testUtils.enableTriggers();
    }

    @isTest
    private static void testKitchenData() {
        String contextLabel = [Select Execution_Context__c From User Where  Id = :UserInfo.getUserId()].Execution_Context__c;
        Execution_Context__mdt context = [Select MasterLabel, DeveloperName,OwnerAssignation__c, Has_SAP__c, ExtendedOpps__c, PriceRequest__c From Execution_Context__mdt Where DeveloperName = :contextLabel];
        context.ExtendedOpps__c = 'CUSTOMP,KITCHEN,FACADE';

        Opportunity opp = DataFactoryOpportunity.createRetailOpportunities(1, 1)[0];

        // Kitchen
        OppKitchen__c k = new OppKitchen__c();
        k.Opportunity__c = opp.Id;
        k.ProductType__c = TestUtils.getPicklistOption(OppKitchen__c.ProductType__c);
        k.ProductQuoted__c = 'PQ';
        k.ProductLine2__c = 'Emotion';
        k.PricingCondition__c = TestUtils.getPicklistOption(OppKitchen__c.PricingCondition__c);
        insert k;
        
        OpportunityInfoController.InfoDTO aux = OpportunityInfoController.readOpportunityInfo(opp.Id);
        Assert.areEqual(true, aux.isKitchen, 'No tiene un Opportunity Kitchen');

        OpportunityInfoController.deleteKitchen(aux.kitchenId);
        aux = OpportunityInfoController.readOpportunityInfo(opp.Id);
        Assert.areEqual(false, aux.isKitchen, 'No debe de tener una Opportunity Kitchen');
    }

    @isTest
    private static void testCustomProjectData() {
        SystemSettings.CPDeletionTime = 10;

        String contextLabel = [Select Execution_Context__c From User Where  Id = :UserInfo.getUserId()].Execution_Context__c;
        Execution_Context__mdt context = [Select MasterLabel, DeveloperName,OwnerAssignation__c, Has_SAP__c, ExtendedOpps__c, PriceRequest__c From Execution_Context__mdt Where DeveloperName = :contextLabel];
        context.ExtendedOpps__c = 'CUSTOMP,KITCHEN,FACADE';

        Opportunity opp = DataFactoryOpportunity.createRetailOpportunities(1, 1)[0];

        // Kitchen
        OppCustomProject__c cp = new OppCustomProject__c();
        cp.Opportunity__c = opp.Id;
        cp.ProjectType__c = 'KRION';
        cp.ProductManager__c = UserInfo.getUserId();
        cp.DeliveryDate__c = System.today();
        Test.startTest();
        insert cp;
        OpportunityInfoController.InfoDTO aux = OpportunityInfoController.readOpportunityInfo(opp.Id);
        Assert.areEqual(true, aux.isCustomProject, 'No tiene un Opportunity Custom Project');
        Test.stopTest();
        
        //OpportunityInfoController.InfoDTO aux = OpportunityInfoController.readOpportunityInfo(opp.Id);
        //Assert.areEqual(false, aux.isCustomProject, 'Tiene un Opportunity Custom Project');

        OpportunityInfoController.deleteCustomProject(aux.customProjectId);
        aux = OpportunityInfoController.readOpportunityInfo(opp.Id);
        Assert.areEqual(false, aux.isKitchen, 'No debe de tener una Opportunity Custom Project');
    }
}