force-app/main/default/objects/Execution_Context__mdt/Execution_Context__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata to define the behavior of a user&apos;s execution context. Initially designed to tell which countries are connected to SAP but open for extension in the near future</description>
    <label>Execution Context</label>
    <pluralLabel>Execution Contexts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Execution_Context__mdt/fields/ExtendedOpps__c.field-meta.xml
<CustomField>
    <fullName>ExtendedOpps__c</fullName>
    <description>Extended opportunities types allowed for the context</description>
    <inlineHelpText>semi-colon separated list of these keys: CUSTOMP, KITCHEN, FACADE.</inlineHelpText>
    <label>Extended Opportunities</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Execution_Context__mdt/fields/Has_SAP__c.field-meta.xml
<CustomField>
    <fullName>Has_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this option when the user works in a context connected to SAP</description>
    <inlineHelpText>Check this option if you need to connect to SAP from Salesforce</inlineHelpText>
    <label>Has SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Execution_Context__mdt/fields/IFlow_allow_create__c.field-meta.xml
<CustomField>
    <fullName>IFlow_allow_create__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows the creation of accounts and contacts in login flow</description>
    <inlineHelpText>Allows the creation of accounts and contacts in login flow</inlineHelpText>
    <label>Login flow allow create</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Execution_Context__mdt/fields/OwnerAssignation__c.field-meta.xml
<CustomField>
    <fullName>OwnerAssignation__c</fullName>
    <description>Método sobre el que se buscará el owner para la asignación de un objeto</description>
    <label>Owner Assignation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>STD</fullName>
                <default>true</default>
                <label>Standard (país y cp)</label>
            </value>
            <value>
                <fullName>USA</fullName>
                <label>Extended US (país, cp, profile, etc)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Execution_Context__mdt/fields/PriceRequest__c.field-meta.xml
<CustomField>
    <fullName>PriceRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Price Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Execution_Context__c.field-meta.xml
<CustomField>
    <fullName>Execution_Context__c</fullName>
    <description>User&apos;s execution context</description>
    <label>Execution Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <label>DEUTSCHLAND</label>
            </value>
            <value>
                <fullName>ZA</fullName>
                <label>SOUTH AFRICA</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>DENMARK</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>UNITED STATES</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>FRANCE</label>
            </value>
            <value>
                <fullName>GB</fullName>
                <label>UNITED KINGDOM</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>SPAIN</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>POLAND</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>SWITZERLAND</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>ITALY</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>CANADA</label>
            </value>
            <value>
                <fullName>JP</fullName>
                <label>JAPAN</label>
            </value>
            <value>
                <fullName>VO</fullName>
                <label>VOID</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>BELGIUM</label>
            </value>
            <value>
                <fullName>PEXP</fullName>
                <label>PORCELANOSA EXPORT</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>AUSTRALIA</label>
            </value>
            <value>
                <fullName>SE</fullName>
                <label>SCANDINAVIA</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>ISRAEL</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>CHILE</label>
            </value>
            <value>
                <fullName>RD</fullName>
                <label>REPUBLICA DOMINICANA</label>
            </value>
            <value>
                <fullName>DEFAULT</fullName>
                <isActive>false</isActive>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>FLOWTESTUK</fullName>
                <isActive>false</isActive>
                <label>FLOWTESTUK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExecutionContext.cls
public class ExecutionContext {
    
    /* Aura variables */
    @AuraEnabled
    public String MasterLabel{get;set;}	
    @AuraEnabled
    public Boolean useSAP{get;set;}
    @AuraEnabled
    public String ownerAssignation{get;set;}
    @AuraEnabled
    public String extendedOpps{get;set;}
    @AuraEnabled
    public Boolean priceRequest{get;set;} // forzar despliegue de esta pxxx línea
    @AuraEnabled
    public Boolean lFlowAllowCreate{get;set;}
  
    /* Class members */
    private static ExecutionContext context;
    
    public ExecutionContext( String contextLabel ) {
        if (String.isBlank(contextLabel)) {
            contextLabel = 'DEFAULT';
        }
        Execution_Context__mdt context = [Select MasterLabel, DeveloperName,OwnerAssignation__c, Has_SAP__c, ExtendedOpps__c, PriceRequest__c, IFlow_allow_create__c From Execution_Context__mdt Where DeveloperName = :contextLabel];
        this.masterLabel = context.DeveloperName;
        this.useSAP = context.Has_SAP__c;
        this.ownerAssignation = context.OwnerAssignation__c;
        this.priceRequest = context.PriceRequest__c;
        this.extendedOpps = context.ExtendedOpps__c;
        this.lFlowAllowCreate = context.IFlow_allow_create__c;
        if (this.extendedOpps == null) {
          this.extendedOpps = '';
        }
    }
  
    @AuraEnabled(cacheable=true)
    public static ExecutionContext getUserExecutionContext() {
        String contextLabel = [Select Execution_Context__c From User Where  Id = :UserInfo.getUserId()].Execution_Context__c;
        if (ExecutionContext.context == null) {
            ExecutionContext.context =  new ExecutionContext( contextLabel );
        }
        return ExecutionContext.context;
    }
  
  }