force-app/main/default/objects/Sales_Relationship__c/Sales_Relationship__c.object-meta.xml
<CustomObject>
    <label>SAP Accounting Info</label>
    <nameField>
        <label>Nombre Organizaciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Accounting Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Relationship__c/fields/Account_Org__c.field-meta.xml
<CustomField>
    <fullName>Account_Org__c</fullName>
    <label>Account Org</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Organizaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Holds tips about what was wrong on the account process</description>
    <label>Error Message</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Reason_of_creation__c.field-meta.xml
<CustomField>
    <fullName>Reason_of_creation__c</fullName>
    <label>Reason of creation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Change Account Owner</fullName>
            </value>
            <value>
                <fullName>New Account</fullName>
            </value>
            <value>
                <fullName>New Account Team Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Relationship__c/fields/Sap_Status__c.field-meta.xml
<CustomField>
    <fullName>Sap_Status__c</fullName>
    <label>Sap Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Undefined</fullName>
                <default>true</default>
                <label>Undefined</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountSapErrorsController.cls
public without sharing class AccountSapErrorsController {
	@AuraEnabled
    public static List<Sales_Relationship__c> returnAccErrors(String recordId){
        List<Sales_Relationship__c> returnList = [SELECT Id, Name, CreatedDate, Reason_of_Creation__c, Sap_Status__c, Error_Message__c
                                                 FROM Sales_Relationship__c 
                                                  WHERE Account_Org__c =: recordId AND Sap_Status__c != 'Success'];
        
        return returnList;
    }
    
    @AuraEnabled
    public static String retry(String recordId){
        String result = '';
        
        try{
            Automatic_AccountSendToSAP.SendToSAP(new List<Id>{Id.valueOf(recordId)});
        } catch(Exception ex){
            result = ex.getMessage();
        }
        
        return result;
    }
}