force-app/main/default/objects/Sales_Relationship__c/Sales_Relationship__c.object-meta.xml
<CustomObject>
    <label>SAP Accounting Info</label>
    <nameField>
        <label>Nombre Organizaciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Accounting Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Execution_Context__c.field-meta.xml
<CustomField>
    <fullName>Execution_Context__c</fullName>
    <description>User&apos;s execution context</description>
    <label>Execution Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <label>DEUTSCHLAND</label>
            </value>
            <value>
                <fullName>ZA</fullName>
                <label>SOUTH AFRICA</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>DENMARK</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>UNITED STATES</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>FRANCE</label>
            </value>
            <value>
                <fullName>GB</fullName>
                <label>UNITED KINGDOM</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>SPAIN</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>POLAND</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>SWITZERLAND</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>ITALY</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>CANADA</label>
            </value>
            <value>
                <fullName>JP</fullName>
                <label>JAPAN</label>
            </value>
            <value>
                <fullName>VO</fullName>
                <label>VOID</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>BELGIUM</label>
            </value>
            <value>
                <fullName>PEXP</fullName>
                <label>PORCELANOSA EXPORT</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>AUSTRALIA</label>
            </value>
            <value>
                <fullName>SE</fullName>
                <label>SCANDINAVIA</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>ISRAEL</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>CHILE</label>
            </value>
            <value>
                <fullName>RD</fullName>
                <label>REPUBLICA DOMINICANA</label>
            </value>
            <value>
                <fullName>DEFAULT</fullName>
                <isActive>false</isActive>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>FLOWTESTUK</fullName>
                <isActive>false</isActive>
                <label>FLOWTESTUK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScriptSendAccountsToSAPFusionTest.cls
@isTest
public with sharing class ScriptSendAccountsToSAPFusionTest {
    @isTest
    public static void testPart1() {
        List<Account> accountsList = DataFactoryAccount.createPersonAccounts(4);
        User usr = DataFactoryUser.createUKUser();
        usr.Execution_context__c = 'GB';
        update usr;

        for (Account acc : accountsList) {
            acc.OwnerId = usr.Id;
        }
        update accountsList;

        List<Sales_Relationship__c> salesRelsList = [SELECT id FROM Sales_Relationship__c];
        System.assert(salesRelsList.size() == 0, 'Sales Relations have been created');
        
        Test.starttest();
        Date startDate = date.today().addDays(-6);
        Date endDate = date.today().addDays(+1);
        Database.executeBatch(new ScriptSendAccountsToSAPFusionPart1(startDate,endDate,false));
        Test.stoptest();
        
        salesRelsList = [SELECT id FROM Sales_Relationship__c];
        System.assert(salesRelsList.size() > 0, 'There are no Sales Relations created');
    }

    @isTest
    public static void testPart2() {
        User usr = DataFactoryUser.createUKUser();
        usr.Execution_context__c = 'GB';
        update usr;

        System.runAs(usr){
            List<Account> accountsList = DataFactoryAccount.createPersonAccounts(4);
        }

        List<Sales_Relationship__c> salesRelsList = [SELECT id FROM Sales_Relationship__c];
        System.assert(salesRelsList.size() > 0, 'Sales Relations have not been created');
        
        Test.starttest();
            Database.executeBatch(new ScriptSendAccountsToSAPFusionPart2(false),5);
        Test.stoptest();
        
        salesRelsList = [SELECT id FROM Sales_Relationship__c];
        System.assert(salesRelsList.size() > 0, 'There are no Sales Relations created');
    }
}