force-app/main/default/objects/Sales_Relationship__c/Sales_Relationship__c.object-meta.xml
<CustomObject>
    <label>SAP Accounting Info</label>
    <nameField>
        <label>Nombre Organizaciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Accounting Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_configuration__c/Trigger_configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>For Trigger configuration, to set on/off trigger fire events.</description>
    <label>Trigger Configuration</label>
</CustomObject>

force-app/main/default/objects/Trigger_configuration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>¿Enable Account Triggers?</description>
    <label>Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_configuration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_configuration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <defaultValue>false</defaultValue>
    <description>¿Enable Event Triggers?</description>
    <label>Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_configuration__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>¿Enable LeadTriggers?</description>
    <label>Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>¿Enable Opportunity Triggers?</description>
    <label>Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_configuration__c/fields/Opportunity_Split__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Split__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opportunity Split</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_configuration__c/fields/Opportunity_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Team_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opportunity Team Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_configuration__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>false</defaultValue>
    <description>¿Enable Order Triggers?</description>
    <label>Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_configuration__c/fields/Sales_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Sales_Relationship__c</fullName>
    <defaultValue>false</defaultValue>
    <description>¿Enable Sales Relationship Triggers?</description>
    <label>Sales Relationship</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_configuration__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <defaultValue>false</defaultValue>
    <description>¿Enable Task Triggers?</description>
    <label>Task</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_configuration__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <defaultValue>false</defaultValue>
    <description>¿Enable User Triggers?</description>
    <label>User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TriggerConfiguration_TestDataFactory.cls
/*-----------------------------------------------------------------------------------------
Author:         Juan Manuel Martinez
Company:        Neoris
Description:    Crea custom settings para ser usadas en test de clases que implementen TriggerFactory.
                Es necesario insertarla porque los test no pueden ver instancias de esta setting que ya estan insertadas
Date:           26-03-2019
History
<Date>            <Author>              <Change Description>
26-04-2019								Agregado el metodo createSalesOrg
-----------------------------------------------------------------------------------------*/

@isTest
public class TriggerConfiguration_TestDataFactory {
    
    public static Trigger_configuration__c createCustomSetting_ActivatedTriggers() {
        Trigger_configuration__c testCustomSetting = new Trigger_configuration__c();
        
        testCustomSetting.Name = 'Activated Test Setting';
        testCustomSetting.Event__c = true;
        testCustomSetting.Task__c = true;
        testCustomSetting.Sales_Relationship__c = true;
        testCustomSetting.User__c = true;
        testCustomSetting.Opportunity_Split__c = false;
        testCustomSetting.Opportunity_Team_Member__c = false;
        testCustomSetting.Account__c = true;
        testCustomSetting.Opportunity__c = true;
        testCustomSetting.Order__c = true;
        testCustomSetting.Lead__c = true;
        testCustomSetting.Contact__c = true;
        
        return testCustomSetting;
    }
    
    public static Trigger_configuration__c createCustomSetting_DeactivatedTriggers() {
        Trigger_configuration__c testCustomSetting = new Trigger_configuration__c();
        
        testCustomSetting.Name = 'Deactivated Test Setting';
        testCustomSetting.Event__c = false;
        testCustomSetting.Task__c = false;
        testCustomSetting.Sales_Relationship__c = false;
        testCustomSetting.User__c = false;
        testCustomSetting.Opportunity_Split__c = false;
        testCustomSetting.Opportunity_Team_Member__c = false;
        testCustomSetting.Account__c = false;
        testCustomSetting.Opportunity__c = false;
        testCustomSetting.Order__c = false;
        testCustomSetting.Lead__c = false;
        testCustomSetting.Contact__c = false;
        
        return testCustomSetting;
    }
    
}