force-app/main/default/objects/OpportunitySettings__c/OpportunitySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for features related to the Opportunities, by Country</description>
    <label>PORSA Opportunity Settings</label>
</CustomObject>

force-app/main/default/objects/OpportunitySettings__c/fields/novalidcreation_mailto__c.field-meta.xml
<CustomField>
    <fullName>novalidcreation_mailto__c</fullName>
    <description>List of Id, of the Managers that are going to receive the email of OpportunitytMail.alertNotValidCreation</description>
    <label>No Valid Opportunity Creation Mail To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunitySettingsTest.cls
@IsTest
public inherited sharing class OpportunitySettingsTest {
  @testSetup static void setup() {
    TestUtils.enableTriggers();
    OpportunitySettings__c newOppSetting = new OpportunitySettings__c(Name = 'GB', Country__c = 'GB', novalidcreation_mailto__c = 'ivan.losilla@porcelanosagrupo.com');
    insert newOppSetting;
  }

  @isTest
  static void getOpportunitySettings() {
    Map<String, OpportunitySettings__c> mapSettings = OpportunitySettings.getOpportunitySettings();

    System.assert(mapSettings.containsKey('GB'), 'No lee correctamente el Opportunity Settings');
    System.assert(mapSettings.containsKey('ES') == false, 'No lee correctamente el Opportunity Settings');
  }

  @isTest
  static void getCreateValidationMailsTo() {
    Map<String, List<String>> mapSettings = OpportunitySettings.getCreateValidationMailsTo();

    System.assert(mapSettings.containsKey('GB'), 'No lee correctamente el Opportunity Settings');
    List<String> oppSet = mapSettings.get('GB');
    System.assert(oppSet[0] == 'ivan.losilla@porcelanosagrupo.com', 'No lee el valor correcto del Setting');
  }
}