force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/AppointmentManagerFrontProperty__mdt.object-meta.xml
<CustomObject>
    <label>AppointmentManagerFrontProperty</label>
    <pluralLabel>AppointmentManagerFrontProperties</pluralLabel>
</CustomObject>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/CountryAuxi__c.field-meta.xml
<CustomField>
    <fullName>CountryAuxi__c</fullName>
    <label>CountryAuxi</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/DateFormat__c.field-meta.xml
<CustomField>
    <fullName>DateFormat__c</fullName>
    <description>Formato de fecha</description>
    <label>Date Format</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/HasAssociates__c.field-meta.xml
<CustomField>
    <fullName>HasAssociates__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si tiene asociados para mostrar en la web</description>
    <label>Has Associates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/LatitudeInit__c.field-meta.xml
<CustomField>
    <fullName>LatitudeInit__c</fullName>
    <label>LatitudeInit</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/LongitudeInit__c.field-meta.xml
<CustomField>
    <fullName>LongitudeInit__c</fullName>
    <label>LongitudeInit</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/NameShown__c.field-meta.xml
<CustomField>
    <fullName>NameShown__c</fullName>
    <description>Nombre que se muestra del país</description>
    <label>Name Shown</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/PrivacyPolicyUrl__c.field-meta.xml
<CustomField>
    <fullName>PrivacyPolicyUrl__c</fullName>
    <description>Url de la página de politica de privacidad del país</description>
    <label>Privacy Policy Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/ZoomFinder__c.field-meta.xml
<CustomField>
    <fullName>ZoomFinder__c</fullName>
    <label>ZoomFinder</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/ZoomFinderCountry__c.field-meta.xml
<CustomField>
    <fullName>ZoomFinderCountry__c</fullName>
    <label>ZoomFinderCountry</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/ZoomFinderState__c.field-meta.xml
<CustomField>
    <fullName>ZoomFinderState__c</fullName>
    <label>ZoomFinderState</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/ZoomGeneral__c.field-meta.xml
<CustomField>
    <fullName>ZoomGeneral__c</fullName>
    <label>ZoomGeneral</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AppointmentManagerFrontProperty__mdt/fields/ZoomStore__c.field-meta.xml
<CustomField>
    <fullName>ZoomStore__c</fullName>
    <label>ZoomStore</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AppointmentManagerFrontProperty_Selector.cls
public class AppointmentManagerFrontProperty_Selector {

    public static AppointmentManagerFrontProperty__mdt getPropertiesFromCountry(String country){
        return [SELECT Id, ZoomGeneral__c, Country__c, CountryAuxi__c, ZoomFinder__c, ZoomStore__c, LatitudeInit__c, LongitudeInit__c, ZoomFinderState__c,ZoomFinderCountry__c,PrivacyPolicyUrl__c,NameShown__c,HasAssociates__c,DateFormat__c
                    FROM AppointmentManagerFrontProperty__mdt 
                        WHERE Country__c =: country LIMIT 1];
    }

}