force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <label>Sales Org</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <description>Code of the Sales Org</description>
    <externalId>true</externalId>
    <label>Sales Org</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesOrgsSelector.cls
/**
 * @author         Ramón Prades
 * @date           August 2024
 * @layer          Selectors
 * @description    Reads sales organisations data
*/
public with sharing class SalesOrgsSelector extends zflib_SObjectSelector_v2 {
    
    public override String getTypeName() {
        return 'Sales_Org__c';
    }

    public Sales_Org__c[] selectBySAPId(Set<String> sapCodes){
        zflib_QueryFactory query = newQueryFactory();
        query.setCondition('SalesOrg__c in :sapCodes');
        return Database.query( query.toSOQL() );
     }
} // class