force-app/main/default/objects/AccountAdditionalInfo__c/AccountAdditionalInfo__c.object-meta.xml
<CustomObject>
    <label>Account Additional Info</label>
    <nameField>
        <label>Accoutn Additional Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Additional Infos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAdditionalInfo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Additional Infos</relationshipLabel>
    <relationshipName>Account_Additional_Infos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAdditionalInfo__c/fields/InfoType__c.field-meta.xml
<CustomField>
    <fullName>InfoType__c</fullName>
    <label>Info type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>PURCHASE</fullName>
            </value>
            <value>
                <fullName>GOAL</fullName>
            </value>
            <value>
                <fullName>QUOTES</fullName>
            </value>
            <value>
                <fullName>INVOICES</fullName>
            </value>
            <value>
                <fullName>ORDERS</fullName>
            </value>
            <value>
                <fullName>WEEKLYCOMMENT</fullName>
            </value>
            <value>
                <fullName>PEDIDOS</fullName>
                <isActive>false</isActive>
                <label>PEDIDOS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Follow__c/Follow__c.object-meta.xml
<CustomObject>
    <description>Objeto que registra la suscripción de un usuario con un Account, Opportunity, etc</description>
    <label>Follow</label>
    <nameField>
        <displayFormat>FW-{00000000}</displayFormat>
        <label>Follow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cuenta a la que se ha suscrito el usuario</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Follows</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>RecordType para Follow de Account</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Follow__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <description>Recordtype para Follow de Opportunity</description>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/InfoType__c.field-meta.xml
<CustomField>
    <fullName>InfoType__c</fullName>
    <description>Type of record of the additional info related to the opportunity (if any). Can be &apos;CUSTOM PROJECT&apos;, &apos;FACADE&apos; or &apos;KITCHEN&apos; (or blank)</description>
    <label>Opportunity Info Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PROJECT</fullName>
                <label>Custom Project</label>
            </value>
            <value>
                <fullName>KITCHEN</fullName>
                <label>Kitchen</label>
            </value>
            <value>
                <fullName>FACADE</fullName>
                <label>Facade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityAdditionalInfo__c/OpportunityAdditionalInfo__c.object-meta.xml
<CustomObject>
    <label>Opportunity Additional Info</label>
    <nameField>
        <displayFormat>OAI-{00000000}</displayFormat>
        <label>Opportunity Additional Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities Additional Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityAdditionalInfo__c/fields/InfoType__c.field-meta.xml
<CustomField>
    <fullName>InfoType__c</fullName>
    <label>Info Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WEEKLYCOMMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScriptCreateWeeklyCommentsTest.cls
@isTest
public class ScriptCreateWeeklyCommentsTest {

    @isTest
    static void testRunJobOnLastThursday() {
        User u = DatafactoryUser.createUKUser();
        u.Alias = 'ssega';
        update u;

        Account acc = DatafactoryAccount.createAccounts(1)[0];

        // Crear una oportunidad vinculada
        Opportunity opp = new Opportunity(
            Name='Test Opp',
            StageName='Prospecting',
            CloseDate=System.today().addDays(30),
            OwnerId=u.Id,
            LeadSource='Porsamarket',
            AccountId=acc.Id
        );
        insert opp;

        // Crear Follow__c relacionado con la Account
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType='Follow__c' AND Name='Account' LIMIT 1];
        Follow__c fol = new Follow__c(
            Account__c=acc.Id,
            OwnerId=u.Id,
            RecordTypeId=rt.Id
        );
        insert fol;

         // Crear Follow__c relacionado con la Account
         rt = [SELECT Id FROM RecordType WHERE SObjectType='Follow__c' AND Name='Opportunity' LIMIT 1];
         fol = new Follow__c(
             Account__c=acc.Id,
             OwnerId=u.Id,
             RecordTypeId=rt.Id
         );
         insert fol;

        Test.startTest();
        ScriptCreateWeeklyComments.runJob();
        Test.stopTest();

        List<AccountAdditionalInfo__c> accInfos = [SELECT Id, InfoType__c FROM AccountAdditionalInfo__c];
        List<OpportunityAdditionalInfo__c> oppInfos = [SELECT Id, InfoType__c FROM OpportunityAdditionalInfo__c];

        System.assert(accInfos.size() > 0, 'Debe haberse creado al menos un registro AccountAdditionalInfo__c');
        System.assert(oppInfos.size() > 0, 'Debe haberse creado al menos un registro OpportunityAdditionalInfo__c');
        System.assertEquals('WEEKLYCOMMENT', accInfos[0].InfoType__c);
        System.assertEquals('WEEKLYCOMMENT', oppInfos[0].InfoType__c);
    }

    @isTest
    static void testExecuteMethod() {
        Test.startTest();
        ScriptCreateWeeklyComments job = new ScriptCreateWeeklyComments();
        String jobId = System.schedule('Test Job', '0 0 23 ? * THU *', job);
        Test.stopTest();
        System.assertNotEquals(null, jobId);
    }
}