force-app/main/default/objects/PorcelanosaAddress__c/PorcelanosaAddress__c.object-meta.xml
<CustomObject>
    <label>Porcelanosa Address</label>
    <nameField>
        <label>Porcelanosa Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porcelanosa Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PorcelanosaAddress__c/fields/NBK_isActive__c.field-meta.xml
<CustomField>
    <fullName>NBK_isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PorcelanosaAddress__c/fields/NBK_isWarehouse__c.field-meta.xml
<CustomField>
    <fullName>NBK_isWarehouse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isWarehouse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/b2b_customLookupController_Test.cls
@isTest
public class b2b_customLookupController_Test {
	static testMethod void testFetchLookupData() {
        // Insert some test data for the lookup object
		PorcelanosaAddress__c testAccounts = new PorcelanosaAddress__c();
        testAccounts.NBK_Address__CountryCode__s = 'US';
        testAccounts.NBK_isActive__c = true;
        testAccounts.NBK_isWarehouse__c = true;
        insert testAccounts;

        // Call the method to be tested
        List<sObject> result = b2b_customLookupController.fetchLookupData('US', 'PorcelanosaAddress__c');
    }
    
   	static testMethod void testFetchLookupDataEmpty() {
        // Call the method to be tested
        List<sObject> result = b2b_customLookupController.fetchLookupData('US', 'PorcelanosaAddress__c');
    }
}