force-app/main/default/objects/PorcelanosaAddress__c/PorcelanosaAddress__c.object-meta.xml
<CustomObject>
    <label>Porcelanosa Address</label>
    <nameField>
        <label>Porcelanosa Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porcelanosa Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PorcelanosaAddress__c/fields/NBK_Address_Type__c.field-meta.xml
<CustomField>
    <fullName>NBK_Address_Type__c</fullName>
    <description>ASddresss Type</description>
    <label>Address Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Showroom</fullName>
                <label>Showroom2</label>
            </value>
            <value>
                <fullName>Warehouse</fullName>
                <label>Warehouse2</label>
            </value>
            <value>
                <fullName>Ships Samples</fullName>
                <label>Ships Samples2</label>
            </value>
            <value>
                <fullName>Collection Point</fullName>
                <label>Collection Point2</label>
            </value>
            <value>
                <fullName>B2B-Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PorcelanosaAddress__c/fields/NBK_isActive__c.field-meta.xml
<CustomField>
    <fullName>NBK_isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PorcelanosaAddress__c/fields/SAPSalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SAPSalesOrg__c</fullName>
    <label>SAPSalesOrg</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PorcelanosaAddressesSelector.cls
/**
* @author         Ramón Prades
* @date           May 2023
* @group          Product List Items
* @description    Selector class. 
*                 Aprovechamos esta clase y su test como test de zflib_SObejctSelectoir_v2
*/
public class PorcelanosaAddressesSelector extends zflib_SObjectSelector_v2 {

    public override String getTypeName() {
        return 'PorcelanosaAddress__c';
    }

    public List<PorcelanosaAddress__c> selectByCountry(Set<String> countryCodes){
        zflib_QueryFactory query = newQueryFactory();
        query.setCondition('NBK_Address__CountryCode__s IN :countryCodes AND NBK_isActive__c = true');
        return (List<PorcelanosaAddress__c>) Database.query( query.toSOQL() );
    }

    /**
     * Selects addresses in the oassed SAO salkes org codes
     */
    public List<PorcelanosaAddress__c> selectBySalesOrg(Set<String> salesOrgs){
        zflib_QueryFactory query = newQueryFactory();
        query.setCondition('SAPSalesOrg__c IN :salesOrgs AND NBK_isActive__c = true');
        return (List<PorcelanosaAddress__c>) Database.query( query.toSOQL() );
    }

    /**
     * Selects colleciton points in a list of sales orgs
     */
    public List<PorcelanosaAddress__c> selectCollectionPoints(Set<String> salesOrgs){
        String spoint = '(\'Collection Point\')';
        zflib_QueryFactory query = newQueryFactory();
        query.setCondition('SAPSalesOrg__c IN :salesOrgs AND NBK_Address_Type__c includes ' + spoint + ' AND NBK_isActive__c = true ');
        return (List<PorcelanosaAddress__c>) Database.query( query.toSOQL() );
    }



} // class